IF NOT exists (select * from FEATURE where FEATUREID = 71)
begin		
	INSERT INTO FEATURE (FEATUREID, FEATURENAME, CATEGORYID, ISEXTERNAL, ISINTERNAL)
	VALUES (71, N'Financial Reports', 9819, 0, 1)
	END
go

If NOT exists (select * from TASK where TASKID = 210)
BEGIN
	INSERT INTO TASK (TASKID, TASKNAME, DESCRIPTION)
	VALUES (210, N'View Revenue Analysis Report',N'Allow the user to view the Revenue Analysis Financial Report')
END
go

IF NOT exists (select * from FEATURETASK where FEATUREID = 71 AND TASKID = 210)
begin
	INSERT INTO FEATURETASK (FEATUREID, TASKID)
	VALUES (71, 210)
END
go

If NOT exists(SELECT * FROM PERMISSIONS WHERE OBJECTTABLE = 'TASK'
				and OBJECTINTEGERKEY = 210
				and LEVELTABLE is null
				and LEVELKEY is null)
BEGIN
	INSERT	PERMISSIONS (OBJECTTABLE, OBJECTINTEGERKEY, OBJECTSTRINGKEY, LEVELTABLE, LEVELKEY, GRANTPERMISSION, DENYPERMISSION) 
	VALUES ('TASK', 210, NULL, NULL, NULL, 32, 0)
END
go

If NOT exists(SELECT * FROM PERMISSIONS WHERE OBJECTTABLE = 'TASK'
	and OBJECTINTEGERKEY = 210
	and LEVELTABLE = 'ROLE'
	and LEVELKEY = -21)
BEGIN
	INSERT	PERMISSIONS (OBJECTTABLE, OBJECTINTEGERKEY, OBJECTSTRINGKEY, LEVELTABLE, LEVELKEY, GRANTPERMISSION, DENYPERMISSION) 
	VALUES ('TASK', 210, NULL, 'ROLE', -21, 0, 0)
 
END
go

If NOT exists (SELECT * FROM VALIDOBJECT WHERE TYPE = 20
                      and OBJECTDATA = '12  07')
BEGIN
	declare @validObject int
	Select @validObject = (max(OBJECTID) + 1) from VALIDOBJECT
	INSERT INTO VALIDOBJECT (OBJECTID, TYPE, OBJECTDATA)	
	VALUES (@validObject, 20, '12  07')
END
go

If NOT exists (SELECT * FROM VALIDOBJECT WHERE TYPE = 20
                      and OBJECTDATA = '12 003')
BEGIN
	declare @validObject int
    Select @validObject = (max(OBJECTID) + 1) from VALIDOBJECT
    INSERT INTO VALIDOBJECT (OBJECTID, TYPE, OBJECTDATA)
	VALUES (@validObject, 20, '12 003')
END
go



