If NOT exists (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'OPENITEM' AND COLUMN_NAME = 'OPENITEMID')
	BEGIN		 
		ALTER TABLE OPENITEM ADD OPENITEMID int IDENTITY (1,1)  NOT FOR REPLICATION 		 
 	END
GO
exec ipu_UtilGenerateAuditTriggers 'OPENITEM'
GO