If NOT exists (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TABLEATTRIBUTES' AND COLUMN_NAME = 'TABLEATTRIBUTESID')
	BEGIN		 
		ALTER TABLE TABLEATTRIBUTES ADD TABLEATTRIBUTESID int IDENTITY (1,1)  NOT FOR REPLICATION 		 
 	END
GO
exec ipu_UtilGenerateAuditTriggers 'TABLEATTRIBUTES'
GO