ALTER TABLE SEARCHRESULTS ALTER COLUMN TITLE varchar(max)
ALTER TABLE SEARCHRESULTS ALTER COLUMN ABSTRACT varchar(max)
ALTER TABLE SEARCHRESULTS ALTER COLUMN CITATION varchar(max)
ALTER TABLE SEARCHRESULTS ALTER COLUMN INVENTORNAME varchar(max)
