	If NOT exists (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ACTIVITYATTACHMENT' AND COLUMN_NAME = 'ATTACHMENTCONTENTID')
		BEGIN	
		 PRINT '**** RFC27700 Adding column ACTIVITYATTACHMENT.ATTACHMENTCONTENTID.'	 
			ALTER TABLE ACTIVITYATTACHMENT ADD ATTACHMENTCONTENTID int NULL			 
		 PRINT '**** RFC27700 ACTIVITYATTACHMENT.ATTACHMENTCONTENTID column has been added.'
 		END
		 PRINT '**** RFC27700 ACTIVITYATTACHMENT.ATTACHMENTCONTENTID already exists'
		 PRINT ''
	GO
    exec ipu_UtilGenerateAuditTriggers 'ACTIVITYATTACHMENT'
	GO

	If NOT exists (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ATTACHMENTCONTENT')
		BEGIN
			PRINT '**** RFC27700  Adding table ATTACHMENTCONTENT.' 

				CREATE TABLE dbo.ATTACHMENTCONTENT
				 (
 					ID  int  IDENTITY (1,1)  NOT FOR REPLICATION,
 					CONTENT  varbinary(max)  NOT NULL ,
 					CONTENTTYPE  nvarchar(max)  NOT NULL ,
 					FILENAME  nvarchar(max)  NOT NULL ,
 					LOGUSERID  nvarchar(50)  NULL ,
 					LOGIDENTITYID  int  NULL ,
 					LOGTRANSACTIONNO  int  NULL ,
 					LOGDATETIMESTAMP  datetime  NULL ,
 					LOGAPPLICATION  nvarchar(128)  NULL ,
 					LOGOFFICEID  int  NULL 
				 )

			exec sc_AssignTableSecurity 'ATTACHMENTCONTENT'

			PRINT '**** RFC27700 ATTACHMENTCONTENT table has been added.'
			PRINT ''
		END
	ELSE
			PRINT '**** RFC27700 ATTACHMENTCONTENT already exists'
			PRINT ''
	go 
	 
	if exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'ACTIVITYATTACHMENT' and CONSTRAINT_NAME = 'R_81828')
		begin
			PRINT 'Dropping foreign key constraint ACTIVITYATTACHMENT.R_81828...'
			ALTER TABLE ACTIVITYATTACHMENT DROP CONSTRAINT R_81828
		end
	go

	if exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'ATTACHMENTCONTENT' and CONSTRAINT_NAME = 'XPKATTACHMENTCONTENT')
		begin
			PRINT 'Dropping primary key constraint ATTACHMENTCONTENT.XPKATTACHMENTCONTENT...'
			ALTER TABLE ATTACHMENTCONTENT DROP CONSTRAINT XPKATTACHMENTCONTENT
		end
	go

	ALTER TABLE dbo.ATTACHMENTCONTENT
		 WITH NOCHECK ADD CONSTRAINT  XPKATTACHMENTCONTENT PRIMARY KEY   NONCLUSTERED (ID  ASC)
	go

	if exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'ACTIVITYATTACHMENT' and CONSTRAINT_NAME = 'R_81828')
		begin
			PRINT 'Dropping foreign key constraint ACTIVITYATTACHMENT.R_81828...'
			ALTER TABLE ACTIVITYATTACHMENT DROP CONSTRAINT R_81828
		end
	go

	ALTER TABLE dbo.ACTIVITYATTACHMENT
		 WITH NOCHECK ADD CONSTRAINT  R_81828 FOREIGN KEY (ATTACHMENTCONTENTID) REFERENCES dbo.ATTACHMENTCONTENT(ID)
			ON DELETE CASCADE
		 NOT FOR REPLICATION
	go
	
	if NOT exists (select * from AUDITLOGTABLES where TABLENAME = 'ATTACHMENTCONTENT')
		begin
			Insert AUDITLOGTABLES (TABLENAME, LOGFLAG, REPLICATEFLAG)
			Values ('ATTACHMENTCONTENT', 0, 0)
		end
	go