/****************************************************************************/
/*** RFC72198 Adding table CONFIGURATIONITEMCOMPONENTS ***/	
/****************************************************************************/

If NOT exists (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CONFIGURATIONITEMCOMPONENTS')
		BEGIN
		PRINT '**** RFC72198  Adding table CONFIGURATIONITEMCOMPONENTS.'
		CREATE TABLE dbo.CONFIGURATIONITEMCOMPONENTS
	( 
		CONFIGITEMID         int  NOT NULL ,
		COMPONENTID          int  NOT NULL ,
		LOGUSERID            nvarchar(50)  NULL ,
		LOGIDENTITYID        int  NULL ,
		LOGTRANSACTIONNO     int  NULL ,
		LOGDATETIMESTAMP     datetime  NULL ,
		LOGAPPLICATION       nvarchar(128)  NULL ,
		LOGOFFICEID          int  NULL 
	)
 
			exec sc_AssignTableSecurity 'CONFIGURATIONITEMCOMPONENTS'				
			PRINT '**** RFC72198 CONFIGURATIONITEMCOMPONENTS table has been added.'
			PRINT ''
		END
		ELSE
			PRINT '**** RFC72198 Table CONFIGURATIONITEMCOMPONENTS already exists'
			PRINT ''
go 


if not exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'CONFIGURATIONITEMCOMPONENTS' and CONSTRAINT_NAME = 'XPKCONFIGURATIONITEMCOMPONENTS')
	begin
		PRINT 'Adding primary key constraint CONFIGURATIONITEMCOMPONENTS.XPKCONFIGURATIONITEMCOMPONENTS...'
		ALTER TABLE dbo.CONFIGURATIONITEMCOMPONENTS
		WITH NOCHECK ADD CONSTRAINT XPKCONFIGURATIONITEMCOMPONENTS PRIMARY KEY  CLUSTERED (CONFIGITEMID ASC,COMPONENTID ASC)
	end
		exec ipu_UtilGenerateAuditTriggers 'CONFIGURATIONITEMCOMPONENTS'
go



if not exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'CONFIGURATIONITEMCOMPONENTS' and CONSTRAINT_NAME = 'R_81906')
	begin
		PRINT 'Adding foreign key constraint CONFIGURATIONITEMCOMPONENTS.R_81906...'
		ALTER TABLE dbo.CONFIGURATIONITEMCOMPONENTS
		WITH NOCHECK ADD CONSTRAINT R_81906 FOREIGN KEY (CONFIGITEMID) REFERENCES dbo.CONFIGURATIONITEM(CONFIGITEMID)
		NOT FOR REPLICATION
	end
go

if not exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'CONFIGURATIONITEMCOMPONENTS' and CONSTRAINT_NAME = 'R_81907')
	begin
		PRINT 'Adding foreign key constraint CONFIGURATIONITEMCOMPONENTS.R_81907...'
		ALTER TABLE dbo.CONFIGURATIONITEMCOMPONENTS
		WITH NOCHECK ADD CONSTRAINT R_81907 FOREIGN KEY (COMPONENTID) REFERENCES dbo.COMPONENTS(COMPONENTID)
		NOT FOR REPLICATION
	end
go


/***  RFC72198  Add data into AUDITLOGTABLES.TABLENAME = CONFIGURATIONITEMCOMPONENTS		***/   
	
	IF NOT exists (select * from AUDITLOGTABLES where TABLENAME = 'CONFIGURATIONITEMCOMPONENTS')
		begin
			PRINT '**** RFC72198  Inserting data into AUDITLOGTABLE.TABLENAME = CONFIGURATIONITEMCOMPONENTS'
			Insert AUDITLOGTABLES (TABLENAME, LOGFLAG, REPLICATEFLAG)
			Values ('CONFIGURATIONITEMCOMPONENTS', 0, 0)
			PRINT '**** RFC72198  Data has been successfully added to AUDITLOGTABLES table.'
			PRINT ''	
		END
	ELSE
		PRINT '**** RFC72198  AUDITLOGTABLES.CONFIGURATIONITEMCOMPONENTS already exists.'
		PRINT ''
	go	
	
	
	
/****************************************************************************/
/*** RFC72198 Adding table CONFIGURATIONITEMTAGS ***/	
/****************************************************************************/

If NOT exists (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CONFIGURATIONITEMTAGS')
		BEGIN
		PRINT '**** RFC72198  Adding table CONFIGURATIONITEMTAGS.'
		CREATE TABLE dbo.CONFIGURATIONITEMTAGS
	( 
		CONFIGITEMID         int  NOT NULL ,
		TAGID                int  NOT NULL ,
		LOGUSERID            nvarchar(50)  NULL ,
		LOGIDENTITYID        int  NULL ,
		LOGTRANSACTIONNO     int  NULL ,
		LOGDATETIMESTAMP     datetime  NULL ,
		LOGAPPLICATION       nvarchar(128)  NULL ,
		LOGOFFICEID          int  NULL 
	)
 
			exec sc_AssignTableSecurity 'CONFIGURATIONITEMTAGS'				
			PRINT '**** RFC72198 CONFIGURATIONITEMTAGS table has been added.'
			PRINT ''
		END
		ELSE
			PRINT '**** RFC72198 Table CONFIGURATIONITEMTAGS already exists'
			PRINT ''
go 


if not exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'CONFIGURATIONITEMTAGS' and CONSTRAINT_NAME = 'XPKCONFIGURATIONITEMTAGS')
	begin
		PRINT 'Adding primary key constraint CONFIGURATIONITEMTAGS.XPKCONFIGURATIONITEMTAGS...'
		ALTER TABLE dbo.CONFIGURATIONITEMTAGS
		WITH NOCHECK ADD CONSTRAINT XPKCONFIGURATIONITEMTAGS PRIMARY KEY  CLUSTERED (CONFIGITEMID ASC,TAGID ASC)
	end
	exec ipu_UtilGenerateAuditTriggers 'CONFIGURATIONITEMTAGS'
go



if not exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'CONFIGURATIONITEMTAGS' and CONSTRAINT_NAME = 'R_81908')
	begin
		PRINT 'Adding foreign key constraint CONFIGURATIONITEMTAGS.R_81908...'
		ALTER TABLE dbo.CONFIGURATIONITEMTAGS
		WITH NOCHECK ADD CONSTRAINT R_81908 FOREIGN KEY (CONFIGITEMID) REFERENCES dbo.CONFIGURATIONITEM(CONFIGITEMID)
		NOT FOR REPLICATION
	end
GO


if exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'CONFIGURATIONITEMTAGS' and CONSTRAINT_NAME = 'R_81909')
		begin
			PRINT 'Dropping foreign key constraint CONFIGURATIONITEMTAGS.R_81909...'
			ALTER TABLE CONFIGURATIONITEMTAGS DROP CONSTRAINT R_81909
		end

if not exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'CONFIGURATIONITEMTAGS' and CONSTRAINT_NAME = 'R_81909')
	begin
		PRINT 'Adding foreign key constraint CONFIGURATIONITEMTAGS.R_81909...'
		ALTER TABLE dbo.CONFIGURATIONITEMTAGS
		WITH NOCHECK ADD CONSTRAINT R_81909 FOREIGN KEY (TAGID) REFERENCES dbo.TAGS(TAGID)
			ON DELETE CASCADE
			ON UPDATE CASCADE
		NOT FOR REPLICATION
	end
go


/***  RFC72198  Add data into AUDITLOGTABLES.TABLENAME = CONFIGURATIONITEMTAGS		***/   
	
	IF NOT exists (select * from AUDITLOGTABLES where TABLENAME = 'CONFIGURATIONITEMTAGS')
		begin
			PRINT '**** RFC72198  Inserting data into AUDITLOGTABLE.TABLENAME = CONFIGURATIONITEMTAGS'
			Insert AUDITLOGTABLES (TABLENAME, LOGFLAG, REPLICATEFLAG)
			Values ('CONFIGURATIONITEMTAGS', 0, 0)
			PRINT '**** RFC72198  Data has been successfully added to AUDITLOGTABLES table.'
			PRINT ''	
		END
	ELSE
		PRINT '**** RFC72198  AUDITLOGTABLES.CONFIGURATIONITEMTAGS already exists.'
		PRINT ''
	go	
