		/*** RFC46138 Alter column SITECONTROL.CONTROLID ***/	

		If exists (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SITECONTROL' AND COLUMN_NAME = 'CONTROLID' AND CHARACTER_MAXIMUM_LENGTH <> 50)
			BEGIN	
				PRINT '**** RFC46138 Modifying column SITECONTROL.CONTROLID.'	 
				ALTER TABLE SITECONTROL ALTER COLUMN CONTROLID  nvarchar(50) NOT NULL				 
				PRINT '**** RFC46138 SITECONTROL.CONTROLID column has been modified.'
			END
				PRINT '**** RFC46138 SITECONTROL.CONTROLID not found'
				PRINT ''
		GO
        exec ipu_UtilGenerateAuditTriggers 'SITECONTROL'
		GO
