/**********************************************************************************************************/	
/*** RFC51919 Add information for Site Controls where it was missing									***/      
/**********************************************************************************************************/
PRINT '**** RFC51919 Adding site control details like notes, initial value where it was missing'

if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'Case Default Description')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'The format of the Case Default Description.', S.INITIALVALUE = 'CASE_DEFAULT_DESCRIPTION' 
	from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Not Known')  
	where S.CONTROLID = 'Case Default Description'
	
if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'CEF Exclude Old Events')	
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'Specifies whether CEF reports should include CASEEVENT transaction with an event date older than the report From Date. If set to TRUE, CASEEVENT transactions with an event date older than the report From Date will not be included in CEF reports. Type = Boolean. Default value = False', 
	S.INITIALVALUE = 'FALSE' from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Inprotech Inprotech 3.5.1')  
	where S.CONTROLID = 'CEF Exclude Old Events'

if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'Charge Date set to Bill Date')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'Specifies how the transaction date for WIP generated by Charge Generation will be determined. If set to TRUE, WIP transaction dates are the same as the invoice date. If set to FALSE, transaction dates are determined using standard logic. Type = Boolean. Default Value = FALSE.', 
	S.INITIALVALUE = 'FALSE' 
	from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Not Known')  
	where S.CONTROLID = 'Charge Date set to Bill Date'

if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'Client Event Text')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'Determines whether or not Event Text is visible to your firms external users (your clients). If set to TRUE, your clients are able to view Event Text. Type = Boolean. Default Value = False.', 
	S.INITIALVALUE = 'FALSE' from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Not Known')  
	where S.CONTROLID = 'Client Event Text'

if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'CMS Unique Client Alias Type')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'Specifies the Name Alias Type to use when storing the CMS Unique Client ID in NAMEALIAS. Type = Character. Default value = Null'
	from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Not Known')  
	where S.CONTROLID = 'CMS Unique Client Alias Type'

if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'Consolidate by Name Type')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'Determines whether or not Name Type consolidation will occure when consolidating charges on an automatically generated bill. If a Name Type is specified, then Name Type consolidation will occur based on that Name Type. If left blank, Name Type consolidation will not occur. Type= Character. Default value = blank.'
	from SITECONTROL S   left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Not Known')  
	where S.CONTROLID = 'Consolidate by Name Type'

if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'CPA Use NameAddress CPA Client')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'Specifies whether the CPA Client Account Number stored against a Name Address combination for a case is inserted into the batch for the case. By default, the CPA Client Account Number is not inserted into the batch. Type = Boolean. Default value = False', 
	S.INITIALVALUE = 'FALSE' 
	from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Not Known')  
	where S.CONTROLID = 'CPA Use NameAddress CPA Client'

if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'CPA-Use ClientCaseCode')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'Determines whether the IRN is held in the CLIENTCASECODE or the AGENTCASECODE. If set to TRUE, this indeicates that the Inprotech user is know by CPA Global as a Managing Agent, and the IRN is held in CLIENTCASECODE. Type = Boolean. Default value = False.', 
	S.INITIALVALUE = 'FALSE' 
	from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Not Known')  
	where S.CONTROLID = 'CPA-Use ClientCaseCode'

if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'CRM Name Screen Program')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'Specifies which program to use for CRM screen control rules when none have been provided.  Specify the value as the Program Code defined in the Program pick list.  Type = Character. Default Value = NAMECRM'
	from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Not Known')  
	where S.CONTROLID = 'CRM Name Screen Program'

if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'Database Email Login')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'Specifies the windows authentication login to be used to send email via database mail on behalf of a logged in user. If no login is specified, email will be sent as a background task.  Type = Character. Default Value = Blank.'
	from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Not Known')  
	where S.CONTROLID = 'Database Email Login'

if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'DebtorType based on Instructor')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'Determines whether the Debtor type is derived from the Debtor or from the Instructor. If set to TRUE, the Debtor type is dervied from the Instructor during fee calculations. Type = Boolean. Default Value = False',
	S.INITIALVALUE = 'FALSE' 
	from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Not Known')  
	where S.CONTROLID = 'DebtorType based on Instructor'

if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'Division Name Alias')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'Specifies the Alias Type code to be used for determining the External Name code for Divisions. For example, DV. Type = Character. Default value =  Blank'
	from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Inprotech 3.5.1')  
	where S.CONTROLID = 'Division Name Alias'

if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'Division Name Types')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'Specifies one or multiple Case Name types to use when recording Division names. If specifying multiple name type, use a comma separated list, for example, DIV,DVC.  When producing EDE output the External Name Code will be determined from a Name Alias rather than Name Mapping. Type = Character. Default value =  Blank'
	from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Inprotech 3.5.1')  
	where S.CONTROLID = 'Division Name Types'

if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'DocItem Concat Null')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'Determines whether or not CONCAT_NULL_YIELDS_NULL will be ON when running DocItems. Type = Boolean. Default value = false.',
	S.INITIALVALUE = 'FALSE' 
	from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Not Known')  
	where S.CONTROLID = 'DocItem Concat Null'

if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'EDE Ad-hoc Reports')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'Specifies which Document Code to filter the list of available letters by when generating EDE ad-hoc reports for a batch.  For example,  enter ''EDE Ad-hoc'' will list only letters with matching Document Code in the letter pick list. Type= Character. Default value = blank.'
	from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Inprotech 3.5.1')  
	where S.CONTROLID = 'EDE Ad-hoc Reports'

if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'EDE Name Group')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'Specifies the group of applicable case Name types to include in EDE reports. Type = Character. Default value = EDE NAME GROUP.'
	from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Inprotech 3.5.1')  
	where S.CONTROLID = 'EDE Name Group'

if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'Email Reminder Date Style')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'Determines the date style to be used in email reminders. There are four format options to choose from: 1=dd MMM yyyy; 2=MMM dd, yyyy; 3=yyyy/mm/dd; 4=mm/dd/yyyy. Type = Integer.  Default = 1 (dd/mm/yyyy).'
	from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Not Known')  
	where S.CONTROLID = 'Email Reminder Date Style'

if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'EPL Suffix')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'Specifies the suffix characters to be added to the <ReceiverFileName> CPA-XML element to create EPL output file names. Type = Character. Default value =  EPL'
	from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Inprotech 3.5.1')  
	where S.CONTROLID = 'EPL Suffix'

if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'External DocGen in Use')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'If set to TRUE then the External Usage combo box will be visible on the Document Details screen of the Letter Maintenance program. Type = Boolean . Default value = False.'
	from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Inprotech 3.5.1')  
	where S.CONTROLID = 'External DocGen in Use'

if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'Input Amend EDE Action')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'Specifies the Action code to be used for the EDE Input Amend Report. Type = Character. Default value = blank.'
	from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Inprotech 3.5.1')  
	where S.CONTROLID = 'Input Amend EDE Action'

if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'Law Update Save Event -11')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'Specifies the EventNo to save a snapshot of Event -11 against vefore law updates are applied. Type = Integer. Default value = 54'
	from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Not Known')  
	where S.CONTROLID = 'Law Update Save Event -11'

if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'Law Update Valid Tables')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'Specifies which method will be used by Law Updates to handle Valid Combination tables. There are four methods to choose from: 0-Create country rules and backfill from default;  1-Use country if available otherwise add to default;  2-Only add where country already exist;  3-Do NOT add any new rules. Type = Integer. Default value = 1.'
	from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Not Known')  
	where S.CONTROLID = 'Law Update Valid Tables'

if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'Log Time as GMT')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'Determines whether Greenwhich Mean Time will be used on log datetime stamps instead of the datatime stamp specified in the Log Time Offset site control. Type = Boolean |  Default value = false.'
	from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Not Known')  
	where S.CONTROLID = 'Log Time as GMT'

if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'Maximum Concurrent Policing')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'Specifies the maximum number of separate Policing request rows can be processed concurrently. A value of zero (0) indicates that there is no maximum number. This option only impacts on firms that run Policing Continuously with multiple threads. Type = Integer. Default value = 0'
	from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Not Known')  
	where S.CONTROLID = 'Maximum Concurrent Policing'

if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'Name Screen Default Program')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'Specifies the program to be used to locate Name screen control rules when none have been provided. The value should be the Program Code as defined in the Program pick list. Type = character; Default value = NAMENTRY'
	from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Not Known')  
	where S.CONTROLID = 'Name Screen Default Program'

if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'Policing Message Interval')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'Specifies how often (in tenth of a second intervals) policing status messages should be refreshed.  Type = Integer |  Default value = 0'
	from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Not Known')  
	where S.CONTROLID = 'Policing Message Interval'

if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'Policing Update After Seconds')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'Specifies the number of seconds policing will wait before checking the queue again. A value greater than zero forces Policing to apply database updates sequentially for multiple connections. Type = Integer | Default value = 0'
	from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Not Known')  
	where S.CONTROLID = 'Policing Update After Seconds'


if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'Property Type Campaign')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'Specifies the Property Type code used for CRM "Campaign" property type, as held in PROPERTYTYPE.PROPERTYTYPE. Type = Character | Default value = F'
	from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Not Known')  
	where S.CONTROLID = 'Property Type Campaign'

if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'Property Type Marketing Event')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'Specifies the Property Type code used for CRM "Marketing Event" property type, as held in PROPERTYTYPE.PROPERTYTYPE. Type = Character | Default value = E'
	from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Not Known')  
	where S.CONTROLID = 'Property Type Marketing Event'


if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'Property Type Opportunity')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'Specifies the Property Type code used for CRM "Opportunity" property type, as held in PROPERTYTYPE.PROPERTYTYPE. Type = Character | Default value = A'
	from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Not Known')  
	where S.CONTROLID = 'Property Type Opportunity'


if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'Publish Action')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'Specifies an optional action code which restrices events from being displayed for an internal user enquiry via the Internet Enquiry module. Type = Character | Default value  = blank'
	from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Not Known')  
	where S.CONTROLID = 'Publish Action'

if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'Reverse Reconciled')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'Determines whether the reconciled or saved statement transactions can be reversed or not. There are three options:  0 allows the transaction to be reverse; 1 allows reversal with a warning;  2 does not allow reversals. Type = integer | Default value = 0'
	from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Not Known')  
	where S.CONTROLID = 'Reverse Reconciled'


if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'Session Reports')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'Determines whether individuals can see a Session Report when they close the Cases or Names program. By default, Session Reports are not shown. Type = Boolean | Default value = False'
	from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Inprotech 3.5.1')  
	where S.CONTROLID = 'Session Reports'

if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'Suppress Bill To Prompt')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'Determines whether or not a prompt is displayed in Billing allowing an individual to change the bill debtor even when there is a Bill To name set up against it.  Type = Boolean | Default value = False'
	from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Not Known')  
	where S.CONTROLID = 'Suppress Bill To Prompt'

if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'TR External Change')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'This only applies if the Transaction Reason Site Control is set to TRUE. Specifies the Transaction Reason used when a change is made by an external user. For example, when clients issue instructions.  Type = Integer | Default value = blank'
	from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Not Known')  
	where S.CONTROLID = 'TR External Change'

if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'TR Internal Change')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'This only applies if the Transaction Reason Site Control is set to TRUE. Specifies the Transaction Reason used when a change is made by an internal user. For example, when clerical staff enter data. Type = Integer | Default value = blank'
	from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Not Known')  
	where S.CONTROLID = 'TR Internal Change'

if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'TR IP Office Verification')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'This only applies if the Transaction Reason Site Control is set to TRUE. Specifies the Transaction Reason used when a change is made by accepting data from an external source. For example, when updating Inprotech via Case Data Comparison. Type = Integer | Default value = blank'
	from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Not Known')  
	where S.CONTROLID = 'TR IP Office Verification'

if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'WIP Verification No Enforced')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'Type = Integer | Default value = 0'
	from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Not Known')  
	where S.CONTROLID = 'WIP Verification No Enforced'

if exists (select 1 from SITECONTROL where NOTES is null and CONTROLID = 'WorkBench Administrator Email')
	update S  set S.VERSIONID = R.VERSIONID, S.NOTES = 'Specifies a default email address to be used as the default web-based software administration email. This will be used to send automated internal system emails from the web-based software. For example, when an indivudal is locked out of the web-based software. Type = Character | Default value = blank'
	from SITECONTROL S   
	left join RELEASEVERSIONS R on (R.VERSIONNAME = 'Not Known')  
	where S.CONTROLID = 'WorkBench Administrator Email'

PRINT '**** RFC51919 End ****'
PRINT ''