	/*** R60349 Add column NAMERELATION.ETHICALWALL          ***/      

	If NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NAMERELATION' AND COLUMN_NAME = 'ETHICALWALL')
	 BEGIN   
		PRINT '**** R60349 Adding column NAMERELATION.ETHICALWALL.'           
		ALTER TABLE NAMERELATION add ETHICALWALL tinyint NOT NULL DEFAULT  0		 
		PRINT '**** R60349 NAMERELATION.ETHICALWALL column has been added.'
	 END
	 ELSE   
		PRINT '**** R60349 NAMERELATION.ETHICALWALL already exists'
		PRINT ''
	 GO
	 IF dbo.fn_IsAuditSchemaConsistent('NAMERELATION') = 0
	 BEGIN
		EXEC ipu_UtilGenerateAuditTriggers 'NAMERELATION'
	 END
	 GO