If NOT exists (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POLICINGLOG' AND COLUMN_NAME = 'POLICINGLOGID')
	BEGIN		 
		ALTER TABLE POLICINGLOG ADD POLICINGLOGID int IDENTITY (1,1)  NOT FOR REPLICATION 		
 	END
GO
IF dbo.fn_IsAuditSchemaConsistent('POLICINGLOG') = 0
BEGIN
	exec ipu_UtilGenerateAuditTriggers 'POLICINGLOG' 
END
GO