	/****** RFC68457 Adding column EDECASEDETAILS.CASEOFFICE ********/

	If NOT exists (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EDECASEDETAILS' AND COLUMN_NAME = 'CASEOFFICE')
		BEGIN
			PRINT '**** RFC68457 Adding column EDECASEDETAILS.CASEOFFICE.' 
			ALTER TABLE EDECASEDETAILS ADD CASEOFFICE nvarchar(80)  NULL
			PRINT '**** RFC68457 EDECASEDETAILS.CASEOFFICE column has been added.'			
		END
	go

	/****** RFC68457 Adding column EDECASEDETAILS.FAMILY ********/
	If NOT exists (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EDECASEDETAILS' AND COLUMN_NAME = 'FAMILY')
		BEGIN
			PRINT '**** RFC68457 Adding column EDECASEDETAILS.FAMILY.' 
			ALTER TABLE EDECASEDETAILS ADD FAMILY nvarchar(20)  NULL
			PRINT '**** RFC68457 EDECASEDETAILS.FAMILY column has been added.'			
		END
	go

	   IF dbo.fn_IsAuditSchemaConsistent('EDECASEDETAILS') = 0
       BEGIN
		 exec ipu_UtilGenerateAuditTriggers 'EDECASEDETAILS'
       END
	
	GO
