 /*** R60691 Add column NUMBERTYPES.DOCITEMID          ***/      

	If NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'NUMBERTYPES' AND COLUMN_NAME = 'DOCITEMID')
	 BEGIN   
		PRINT '**** R60691 Adding column NUMBERTYPES.DOCITEMID.'           
		ALTER TABLE NUMBERTYPES add  DOCITEMID int  NULL 		
		PRINT '**** R60691 NUMBERTYPES.DOCITEMID column has been added.'
	 END
	 ELSE   
		PRINT '**** R60691 NUMBERTYPES.DOCITEMID already exists'
		PRINT ''
	 GO
	 IF dbo.fn_IsAuditSchemaConsistent('NUMBERTYPES') = 0
	 BEGIN
		EXEC ipu_UtilGenerateAuditTriggers 'NUMBERTYPES' 
	 END
	 GO
     

 /*** R60691 Adding foreign key NUMBERTYPES.DOCITEMID to ITEM.ITEM_ID     ***/   

 if exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'NUMBERTYPES' and CONSTRAINT_NAME = 'R_81884')
	begin
		PRINT 'Dropping foreign key constraint NUMBERTYPES.R_81884...'
		ALTER TABLE NUMBERTYPES DROP CONSTRAINT R_81884
	end
go

 ALTER TABLE dbo.NUMBERTYPES
	 WITH NOCHECK ADD CONSTRAINT R_81884 FOREIGN KEY (DOCITEMID) REFERENCES dbo.ITEM(ITEM_ID)
	 NOT FOR REPLICATION
go