/****************************************************************************/
/*** RFC61776 Adding table EXCHANGEREQUESTQUEUE ***/	
/****************************************************************************/

If NOT exists (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EXCHANGEREQUESTQUEUE')
		BEGIN
		PRINT '**** RFC61776  Adding table EXCHANGEREQUESTQUEUE.'
			CREATE TABLE dbo.EXCHANGEREQUESTQUEUE
		( 
			 	ID                   bigint  NOT NULL  IDENTITY ( 1,1 )  NOT FOR REPLICATION,
				EMPLOYEENO           int  NOT NULL ,
				MESSAGESEQ           datetime  NOT NULL ,
				DATECREATED          datetime  NOT NULL ,
				REQUESTTYPE          smallint  NOT NULL ,
				STATUSID             smallint  NOT NULL 
				DEFAULT  0,
				ERRORMESSAGE         nvarchar(max)  NULL ,
				RETRIES              smallint  NULL ,
				CASEID               int  NULL ,
				REFERENCE            nvarchar(100)  NULL ,
				NAMENO               int  NULL ,
				ALERTNAMENO          int  NULL ,
				EVENTNO              int  NULL ,
				IDENTITYID           int  NULL ,
				LOGUSERID            nvarchar(50)  NULL ,
				LOGIDENTITYID        int  NULL ,
				LOGTRANSACTIONNO     int  NULL ,
				LOGDATETIMESTAMP     datetime  NULL ,
				LOGAPPLICATION       nvarchar(128)  NULL ,
				LOGOFFICEID          int  NULL 
		)
			exec sc_AssignTableSecurity 'EXCHANGEREQUESTQUEUE'			 
			PRINT '**** RFC61776 EXCHANGEREQUESTQUEUE table has been added.'
			PRINT ''
		END
		ELSE
			PRINT '**** RFC61776 EXCHANGEREQUESTQUEUE already exists'
			PRINT ''
go 
 
 
 if not exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'EXCHANGEREQUESTQUEUE' and CONSTRAINT_NAME = 'XPKEXCHANGEREQUESTQUEUE')
	begin
		PRINT 'Adding primary key constraint EXCHANGEREQUESTQUEUE.XPKEXCHANGEREQUESTQUEUE...'
		ALTER TABLE dbo.EXCHANGEREQUESTQUEUE
		WITH NOCHECK ADD CONSTRAINT XPKEXCHANGEREQUESTQUEUE PRIMARY KEY  CLUSTERED (ID ASC)		
	end
	ELSE
			PRINT '**** RFC61776 Primary key constraint EXCHANGEREQUESTQUEUE.XPKEXCHANGEREQUESTQUEUE already exists'
			PRINT ''
GO

IF dbo.fn_IsAuditSchemaConsistent('EXCHANGEREQUESTQUEUE') = 0
BEGIN
   EXEC ipu_UtilGenerateAuditTriggers 'EXCHANGEREQUESTQUEUE'
END
GO
  
 if not exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'EXCHANGEREQUESTQUEUE' and CONSTRAINT_NAME = 'R_81888')
	begin
		PRINT 'Adding foreign key constraint EXCHANGEREQUESTQUEUE.R_81888...'
		ALTER TABLE dbo.EXCHANGEREQUESTQUEUE
		WITH NOCHECK ADD CONSTRAINT R_81888 FOREIGN KEY (EMPLOYEENO) REFERENCES dbo.NAME(NAMENO)
		NOT FOR REPLICATION
	end
	ELSE
			PRINT '**** RFC61776 Foreign key constraint EXCHANGEREQUESTQUEUE.R_81888 already exists'
			PRINT ''
go

if exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'EXCHANGEREQUESTQUEUE' and CONSTRAINT_NAME = 'R_81889')
      begin
            PRINT 'Dropping foreign key constraint EXCHANGEREQUESTQUEUE.R_81889...'
            ALTER TABLE EXCHANGEREQUESTQUEUE DROP CONSTRAINT R_81889
      end
go

 if not exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'EXCHANGEREQUESTQUEUE' and CONSTRAINT_NAME = 'R_81889')
	begin
		PRINT 'Adding foreign key constraint EXCHANGEREQUESTQUEUE.R_81889...'
		ALTER TABLE dbo.EXCHANGEREQUESTQUEUE
		WITH NOCHECK ADD CONSTRAINT R_81889 FOREIGN KEY (CASEID) REFERENCES dbo.CASES(CASEID)
		ON DELETE CASCADE
		NOT FOR REPLICATION
	end
	ELSE
			PRINT '**** RFC61776 Foreign key constraint EXCHANGEREQUESTQUEUE.R_81889 already exists'
			PRINT ''
go


 if not exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'EXCHANGEREQUESTQUEUE' and CONSTRAINT_NAME = 'R_81890')
	begin
		PRINT 'Adding foreign key constraint EXCHANGEREQUESTQUEUE.R_81890...'
		ALTER TABLE dbo.EXCHANGEREQUESTQUEUE
		WITH NOCHECK ADD CONSTRAINT R_81890 FOREIGN KEY (ALERTNAMENO) REFERENCES dbo.NAME(NAMENO)
		NOT FOR REPLICATION
	end
	ELSE
			PRINT '**** RFC61776 Foreign key constraint EXCHANGEREQUESTQUEUE.R_81890 already exists'
			PRINT ''
go

 if not exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'EXCHANGEREQUESTQUEUE' and CONSTRAINT_NAME = 'R_81892')
	begin
		PRINT 'Adding foreign key constraint EXCHANGEREQUESTQUEUE.R_81892...'
		ALTER TABLE dbo.EXCHANGEREQUESTQUEUE
		WITH NOCHECK ADD CONSTRAINT R_81892 FOREIGN KEY (NAMENO) REFERENCES dbo.NAME(NAMENO)
		NOT FOR REPLICATION
	end
	ELSE
			PRINT '**** RFC61776 Foreign key constraint EXCHANGEREQUESTQUEUE.R_81892 already exists'
			PRINT ''
go


 if not exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'EXCHANGEREQUESTQUEUE' and CONSTRAINT_NAME = 'R_81893')
	begin
		PRINT 'Adding foreign key constraint EXCHANGEREQUESTQUEUE.R_81893...'
		ALTER TABLE dbo.EXCHANGEREQUESTQUEUE
		WITH NOCHECK ADD CONSTRAINT R_81893 FOREIGN KEY (EVENTNO) REFERENCES dbo.EVENTS(EVENTNO)
		NOT FOR REPLICATION
	end
	ELSE
			PRINT '**** RFC61776 Foreign key constraint EXCHANGEREQUESTQUEUE.R_81893 already exists'
			PRINT ''
go

if not exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'EXCHANGEREQUESTQUEUE' and CONSTRAINT_NAME = 'R_81899')
	begin
		PRINT 'Adding foreign key constraint EXCHANGEREQUESTQUEUE.R_81899...'
		ALTER TABLE dbo.EXCHANGEREQUESTQUEUE
		WITH NOCHECK ADD CONSTRAINT R_81899 FOREIGN KEY (IDENTITYID) REFERENCES dbo.USERIDENTITY(IDENTITYID)
		NOT FOR REPLICATION
	end
	ELSE
			PRINT '**** RFC61776 Foreign key constraint EXCHANGEREQUESTQUEUE.R_81899 already exists'
			PRINT ''
go

/***  RFC61776  Add data into AUDITLOGTABLES.TABLENAME = EXCHANGEREQUESTQUEUE		***/   

IF NOT exists (select * from AUDITLOGTABLES where TABLENAME = 'EXCHANGEREQUESTQUEUE')
	begin
		PRINT '**** RFC61776  Inserting data into AUDITLOGTABLE.TABLENAME = EXCHANGEREQUESTQUEUE'
		Insert AUDITLOGTABLES (TABLENAME, LOGFLAG, REPLICATEFLAG)
		Values ('EXCHANGEREQUESTQUEUE', 0, 0)
		PRINT '**** RFC61776  Data has been successfully added to AUDITLOGTABLES table.'
		PRINT ''	
	END
ELSE
	PRINT '**** RFC61776  AUDITLOGTABLES.EXCHANGEREQUESTQUEUE already exists.'
	PRINT ''
go