	/*** R71920 Add column EVENTTEXTTYPE.SHARINGALLOWED   ***/      

	If NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EVENTTEXTTYPE' AND COLUMN_NAME = 'SHARINGALLOWED')
	 BEGIN   
		PRINT '**** R71920 Adding column EVENTTEXTTYPE.SHARINGALLOWED.'           
		ALTER TABLE EVENTTEXTTYPE ADD SHARINGALLOWED bit  NULL		
		PRINT '**** R71920 EVENTTEXTTYPE.SHARINGALLOWED column has been added.'
	 END
	 ELSE   
		PRINT '**** R71920 EVENTTEXTTYPE.SHARINGALLOWED already exists'
		PRINT ''
	 GO

IF dbo.fn_IsAuditSchemaConsistent('EVENTTEXTTYPE') = 0
BEGIN
   EXEC ipu_UtilGenerateAuditTriggers 'EVENTTEXTTYPE'
END
GO