/** RFC72426 Add column PROPERTYTYPE.ICONIMAGEID		**/      

If NOT exists (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PROPERTYTYPE' AND COLUMN_NAME = 'ICONIMAGEID')
	BEGIN		
		PRINT '**** RFC72426 Adding column PROPERTYTYPE.ICONIMAGEID' 
		ALTER TABLE PROPERTYTYPE ADD ICONIMAGEID int  NULL 
		PRINT '**** RFC72426 Column PROPERTYTYPE.ICONIMAGEID added' 		
 	END
ELSE
	BEGIN
		PRINT '**** RFC72426 Column PROPERTYTYPE.ICONIMAGEID exists already' 
	END
GO

IF dbo.fn_IsAuditSchemaConsistent('PROPERTYTYPE') = 0
BEGIN
   EXEC ipu_UtilGenerateAuditTriggers 'PROPERTYTYPE'
END
GO

/** RFC72426 Adding foreign key R_81901		**/ 


if exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'PROPERTYTYPE' and CONSTRAINT_NAME = 'R_81901')
	begin
		PRINT 'Dropping foreign key constraint PROPERTYTYPE.R_81901...'
		ALTER TABLE PROPERTYTYPE DROP CONSTRAINT R_81901
	end
go

if not exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'PROPERTYTYPE' and CONSTRAINT_NAME = 'R_81901')
	begin
		PRINT 'Adding foreign key constraint PROPERTYTYPE.R_81901...'
		ALTER TABLE dbo.PROPERTYTYPE
		WITH NOCHECK ADD CONSTRAINT R_81901 FOREIGN KEY (ICONIMAGEID) REFERENCES dbo.IMAGE(IMAGEID)
		NOT FOR REPLICATION
	end	
go

