IF EXISTS (SELECT * FROM SITECONTROL WHERE controlid = 'FILE Integration Event' AND COLINTEGER IS NOT NULL) 
	AND NOT EXISTS(SELECT * FROM FILECASE)
BEGIN
	INSERT FILECASE (IPTYPE, CASEID, COUNTRYCODE, PARENTCASEID)
	SELECT 'PATENT_POST_PCT', RC.RELATEDCASEID, C.COUNTRYCODE, RC.CASEID
	FROM RELATEDCASE RC 
	JOIN SITECONTROL SC ON SC.CONTROLID = 'FILE Integration Event'
	JOIN CASEEVENT CE ON RC.RELATEDCASEID = CE.CASEID AND CE.EVENTNO = SC.COLINTEGER AND CE.CYCLE = 1 AND CE.EVENTDATE IS NOT NULL
    JOIN CASES C ON C.CASEID = RC.RELATEDCASEID
	WHERE RC.RELATIONSHIP = 'DC1'
	
	INSERT FILECASE (IPTYPE, CASEID)
	SELECT 'PATENT_POST_PCT', F.PARENTCASEID 
	FROM CASES C
	JOIN (SELECT DISTINCT(PARENTCASEID) AS PARENTCASEID FROM FILECASE WHERE PARENTCASEID IS NOT NULL) AS F ON C.CASEID = F.PARENTCASEID

END
GO


