If EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'USERIDENTITYACCESSLOG')
		BEGIN
		PRINT '**** Clearing unnecessary log data.'
			UPDATE USERIDENTITYACCESSLOG SET DATA=NULL WHERE LOGOUTTIME IS NOT NULL AND DATA IS NOT NULL
		END
GO