/*** R68324 Add column COUNTRYGROUP.PROPERTYTYPES          ***/      

	If NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'COUNTRYGROUP' AND COLUMN_NAME = 'PROPERTYTYPES')
	 BEGIN   
		PRINT '**** R68324 Adding column COUNTRYGROUP.PROPERTYTYPES.'           
		ALTER TABLE COUNTRYGROUP add PROPERTYTYPES  nvarchar(100) NULL	 
		PRINT '**** R68324 COUNTRYGROUP.PROPERTYTYPES column has been added.'
	 END
	 ELSE   
		PRINT '**** R68324 COUNTRYGROUP.PROPERTYTYPES already exists'
		PRINT ''
	 GO
	 IF dbo.fn_IsAuditSchemaConsistent('COUNTRYGROUP') = 0
	 BEGIN
		EXEC ipu_UtilGenerateAuditTriggers 'COUNTRYGROUP'
	 END
	 GO