--
-- CLAIMS PRIORITY FROM PROVISIONAL APPLICATION
-- 
insert MAPPING (STRUCTUREID, DATASOURCEID, INPUTDESCRIPTION, INPUTCODEID, OUTPUTCODEID, OUTPUTVALUE, ISNOTAPPLICABLE)
select M.STRUCTUREID, M.DATASOURCEID, 'CLAIMS PRIORITY FROM PROVISIONAL APPLICATION', M.INPUTCODEID, M.OUTPUTCODEID, M.OUTPUTVALUE, M.ISNOTAPPLICABLE
from MAPPING M
left join MAPPING M1 on (	M1.DATASOURCEID = M.DATASOURCEID 
					and		M1.STRUCTUREID = M.STRUCTUREID 
					and		M1.INPUTDESCRIPTION = 'CLAIMS PRIORITY FROM PROVISIONAL APPLICATION')
where M.STRUCTUREID = 3 and M.DATASOURCEID = -1
and M.INPUTDESCRIPTION = 'WHICH CLAIMS PRIORITY FROM PROVISIONAL APPLICATION'
and M1.ENTRYID is null

--
-- THIS APPLICATION CLAIMS PRIORITY FROM PROVISIONAL APPLICATION
-- 
insert MAPPING (STRUCTUREID, DATASOURCEID, INPUTDESCRIPTION, INPUTCODEID, OUTPUTCODEID, OUTPUTVALUE, ISNOTAPPLICABLE)
select M.STRUCTUREID, M.DATASOURCEID, 'THIS APPLICATION CLAIMS PRIORITY FROM PROVISIONAL APPLICATION', M.INPUTCODEID, M.OUTPUTCODEID, M.OUTPUTVALUE, M.ISNOTAPPLICABLE
from MAPPING M
left join MAPPING M1 on (	M1.DATASOURCEID = M.DATASOURCEID 
					and		M1.STRUCTUREID = M.STRUCTUREID
					and		M1.INPUTDESCRIPTION = 'THIS APPLICATION CLAIMS PRIORITY FROM PROVISIONAL APPLICATION' )
where M.STRUCTUREID = 3 and M.DATASOURCEID = -1
and M.INPUTDESCRIPTION = 'WHICH CLAIMS PRIORITY FROM PROVISIONAL APPLICATION'
and M1.ENTRYID is null

--
-- IS A CONTINUATION-IN-PART-OF
-- 
insert MAPPING (STRUCTUREID, DATASOURCEID, INPUTDESCRIPTION, INPUTCODEID, OUTPUTCODEID, OUTPUTVALUE, ISNOTAPPLICABLE)
select M.STRUCTUREID, M.DATASOURCEID, 'IS A CONTINUATION-IN-PART-OF', M.INPUTCODEID, M.OUTPUTCODEID, M.OUTPUTVALUE, M.ISNOTAPPLICABLE
from MAPPING M
left join MAPPING M1 on (	M1.DATASOURCEID = M.DATASOURCEID 
					and		M1.STRUCTUREID = M.STRUCTUREID
					and		M1.INPUTDESCRIPTION = 'IS A CONTINUATION-IN-PART-OF')
where M.STRUCTUREID = 3 and M.DATASOURCEID = -1
and M.INPUTDESCRIPTION = 'WHICH IS A CONTINUATION IN PART OF'
and M1.ENTRYID is null

--
-- THIS APPLICATION IS A CONTINUATION IN PART OF
-- 
insert MAPPING (STRUCTUREID, DATASOURCEID, INPUTDESCRIPTION, INPUTCODEID, OUTPUTCODEID, OUTPUTVALUE, ISNOTAPPLICABLE)
select M.STRUCTUREID, M.DATASOURCEID, 'THIS APPLICATION IS A CONTINUATION IN PART OF', M.INPUTCODEID, M.OUTPUTCODEID, M.OUTPUTVALUE, M.ISNOTAPPLICABLE
from MAPPING M
left join MAPPING M1 on (	M1.DATASOURCEID = M.DATASOURCEID 
						and M1.STRUCTUREID = M.STRUCTUREID
						and M1.INPUTDESCRIPTION = 'THIS APPLICATION IS A CONTINUATION IN PART OF')
where M.STRUCTUREID = 3 and M.DATASOURCEID = -1
and M.INPUTDESCRIPTION = 'WHICH IS A CONTINUATION IN PART OF'
and M1.ENTRYID is null

--
-- IS A CONTINUATION OF
-- 
insert MAPPING (STRUCTUREID, DATASOURCEID, INPUTDESCRIPTION, INPUTCODEID, OUTPUTCODEID, OUTPUTVALUE, ISNOTAPPLICABLE)
select M.STRUCTUREID, M.DATASOURCEID, 'IS A CONTINUATION OF', M.INPUTCODEID, M.OUTPUTCODEID, M.OUTPUTVALUE, M.ISNOTAPPLICABLE
from MAPPING M
left join MAPPING M1 on (	M1.DATASOURCEID = M.DATASOURCEID 
						and M1.STRUCTUREID = M.STRUCTUREID
						and M1.INPUTDESCRIPTION = 'IS A CONTINUATION OF')
where M.STRUCTUREID = 3 and M.DATASOURCEID = -1
and M.INPUTDESCRIPTION = 'WHICH IS A CONTINUATION OF'
and M1.ENTRYID is null

--
-- THIS APPLICATION IS A CONTINUATION OF
-- 
insert MAPPING (STRUCTUREID, DATASOURCEID, INPUTDESCRIPTION, INPUTCODEID, OUTPUTCODEID, OUTPUTVALUE, ISNOTAPPLICABLE)
select M.STRUCTUREID, M.DATASOURCEID, 'THIS APPLICATION IS A CONTINUATION OF', M.INPUTCODEID, M.OUTPUTCODEID, M.OUTPUTVALUE, M.ISNOTAPPLICABLE
from MAPPING M
left join MAPPING M1 on (	M1.DATASOURCEID = M.DATASOURCEID 
						and M1.STRUCTUREID = M.STRUCTUREID
						and M1.INPUTDESCRIPTION = 'THIS APPLICATION IS A CONTINUATION OF')
where M.STRUCTUREID = 3 and M.DATASOURCEID = -1
and M.INPUTDESCRIPTION = 'WHICH IS A CONTINUATION OF'
and M1.ENTRYID is null

--
-- IS A DIVISION OF
-- 
insert MAPPING (STRUCTUREID, DATASOURCEID, INPUTDESCRIPTION, INPUTCODEID, OUTPUTCODEID, OUTPUTVALUE, ISNOTAPPLICABLE)
select M.STRUCTUREID, M.DATASOURCEID, 'IS A DIVISION OF', M.INPUTCODEID, M.OUTPUTCODEID, M.OUTPUTVALUE, M.ISNOTAPPLICABLE
from MAPPING M
left join MAPPING M1 on (	M1.DATASOURCEID = M.DATASOURCEID 
						and M1.STRUCTUREID = M.STRUCTUREID
						and M1.INPUTDESCRIPTION = 'IS A DIVISION OF')
where M.STRUCTUREID = 3 and M.DATASOURCEID = -1
and M.INPUTDESCRIPTION = 'THIS APPLICATION IS A DIVISION OF'
and M1.ENTRYID is null

--
-- IS A RE-EXAMINATION OF
-- 
insert MAPPING (STRUCTUREID, DATASOURCEID, INPUTDESCRIPTION, INPUTCODEID, OUTPUTCODEID, OUTPUTVALUE, ISNOTAPPLICABLE)
select M.STRUCTUREID, M.DATASOURCEID, 'IS A RE-EXAMINATION OF', M.INPUTCODEID, M.OUTPUTCODEID, M.OUTPUTVALUE, M.ISNOTAPPLICABLE
from MAPPING M
left join MAPPING M1 on (	M1.DATASOURCEID = M.DATASOURCEID 
						and M1.STRUCTUREID = M.STRUCTUREID
						and M1.INPUTDESCRIPTION = 'IS A RE-EXAMINATION OF')
where M.STRUCTUREID = 3 and M.DATASOURCEID = -1
and M.INPUTDESCRIPTION = 'PARENT CONTINUITY - REEXAM'
and M1.ENTRYID is null

--
-- THIS APPLICATION IS A RE-EXAMINATION OF
-- 
insert MAPPING (STRUCTUREID, DATASOURCEID, INPUTDESCRIPTION, INPUTCODEID, OUTPUTCODEID, OUTPUTVALUE, ISNOTAPPLICABLE)
select M.STRUCTUREID, M.DATASOURCEID, 'THIS APPLICATION IS A RE-EXAMINATION OF', M.INPUTCODEID, M.OUTPUTCODEID, M.OUTPUTVALUE, M.ISNOTAPPLICABLE
from MAPPING M
left join MAPPING M1 on (	M1.DATASOURCEID = M.DATASOURCEID 
						and M1.STRUCTUREID = M.STRUCTUREID
						and M1.INPUTDESCRIPTION = 'THIS APPLICATION IS A RE-EXAMINATION OF')
where M.STRUCTUREID = 3 and M.DATASOURCEID = -1
and M.INPUTDESCRIPTION = 'PARENT CONTINUITY - REEXAM'
and M1.ENTRYID is null

--
-- IS A NATIONAL STAGE ENTRY OF
-- 
insert MAPPING (STRUCTUREID, DATASOURCEID, INPUTDESCRIPTION, INPUTCODEID, OUTPUTCODEID, OUTPUTVALUE, ISNOTAPPLICABLE)
select EV.STRUCTUREID, -1, 'IS A NATIONAL STAGE ENTRY OF', NULL, EV.CODEID, NULL, 0
from ENCODEDVALUE EV 
left join MAPPING M1 on (	M1.STRUCTUREID = EV.STRUCTUREID 
					and		M1.DATASOURCEID = -1
					and		M1.INPUTDESCRIPTION = 'IS A NATIONAL STAGE ENTRY OF')
WHERE EV.SCHEMEID = -1 
and EV.[DESCRIPTION] = 'PCT PARENT APPLICATION' 
and M1.ENTRYID is null

--
-- THIS APPLICATION IS A NATIONAL STAGE ENTRY OF
-- 
insert MAPPING (STRUCTUREID, DATASOURCEID, INPUTDESCRIPTION, INPUTCODEID, OUTPUTCODEID, OUTPUTVALUE, ISNOTAPPLICABLE)
select EV.STRUCTUREID, -1, 'THIS APPLICATION IS A NATIONAL STAGE ENTRY OF', NULL, EV.CODEID, NULL, 0
from ENCODEDVALUE EV 
left join MAPPING M1 on (	M1.STRUCTUREID = EV.STRUCTUREID
					and		M1.DATASOURCEID = -1
					and M1.INPUTDESCRIPTION = 'THIS APPLICATION IS A NATIONAL STAGE ENTRY OF')
WHERE EV.SCHEMEID = -1 
and EV.[DESCRIPTION] = 'PCT PARENT APPLICATION' 
and M1.ENTRYID is null
