/** DR-46993 Adding column NAMETYPE.NATIONALITYFLAG	**/

If NOT exists (SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'NAMETYPE'AND COLUMN_NAME = 'NATIONALITYFLAG')
	BEGIN
	PRINT '**** DR-46993 Adding column NAMETYPE.NATIONALITYFLAG'
	ALTER TABLE NAMETYPE ADD NATIONALITYFLAG bit NOT NULL DEFAULT 0
	PRINT '**** DR-46993 Column NAMETYPE.NATIONALITYFLAG added'	
END
ELSE
	BEGIN
	PRINT '**** DR-46993 Column NAMETYPE.NATIONALITYFLAG exists already'
END
GO

IF dbo.fn_IsAuditSchemaConsistent('NAMETYPE') = 0
BEGIN
   EXEC ipu_UtilGenerateAuditTriggers 'NAMETYPE'
END
GO