/** DR-48752 Adding column USERIDENTITY.PASSWORDHISTORY	**/

If NOT exists (SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'USERIDENTITY'AND COLUMN_NAME = 'PASSWORDHISTORY')
	BEGIN
	PRINT '**** DR-48752 Adding column USERIDENTITY.PASSWORDHISTORY'
	ALTER TABLE USERIDENTITY ADD PASSWORDHISTORY nvarchar(max) NULL
	PRINT '**** DR-48752 Column USERIDENTITY.PASSWORDHISTORY added'
END
ELSE
	BEGIN
	PRINT '**** DR-48752 Column USERIDENTITY.PASSWORDHISTORY exists already'
END
GO


/** DR-48752 Adding column USERIDENTITY.PASSWORDUPDATEDDATE	**/

If NOT exists (SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'USERIDENTITY'AND COLUMN_NAME = 'PASSWORDUPDATEDDATE')
	BEGIN
	PRINT '**** DR-48752 Adding column USERIDENTITY.PASSWORDUPDATEDDATE'
	ALTER TABLE USERIDENTITY ADD PASSWORDUPDATEDDATE datetime NULL
	PRINT '**** DR-48752 Column USERIDENTITY.PASSWORDUPDATEDDATE added'
END
ELSE
	BEGIN
	PRINT '**** DR-48752 Column USERIDENTITY.PASSWORDUPDATEDDATE exists already'
END
GO

IF dbo.fn_IsAuditSchemaConsistent('USERIDENTITY') = 0
BEGIN
EXEC ipu_UtilGenerateAuditTriggers 'USERIDENTITY'
END
GO