/*** DR-58188 Add column CASES.BUDGETSTARTDATE   ***/      

If NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CASES' AND COLUMN_NAME = 'BUDGETSTARTDATE')
	BEGIN   
	PRINT '**** DR-58188 Adding column CASES.BUDGETSTARTDATE.'           
	ALTER TABLE CASES ADD BUDGETSTARTDATE datetime  NULL		
	PRINT '**** DR-58188 CASES.BUDGETSTARTDATE column has been added.'
	END
	ELSE   
	PRINT '**** DR-58188 CASES.BUDGETSTARTDATE already exists'
	PRINT ''
	go
	 
/*** DR-58188 Add column CASES.BUDGETENDDATE   ***/      

If NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CASES' AND COLUMN_NAME = 'BUDGETENDDATE')
	BEGIN   
	PRINT '**** DR-58188 Adding column CASES.BUDGETENDDATE.'           
	ALTER TABLE CASES ADD BUDGETENDDATE datetime  NULL		
	PRINT '**** DR-58188 CASES.BUDGETENDDATE column has been added.'
	END
	ELSE   
	PRINT '**** DR-58188 CASES.BUDGETENDDATE already exists'
	PRINT ''
	go		
IF dbo.fn_IsAuditSchemaConsistent('CASES') = 0
BEGIN
	EXEC ipu_UtilGenerateAuditTriggers 'CASES'
END
GO		