/*** DR-56993 Add column DESIGNELEMENT.STOPRENEWDATE          ***/      

	If NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'DESIGNELEMENT' AND COLUMN_NAME = 'STOPRENEWDATE')
	 BEGIN   
		PRINT '**** DR-56993 Adding column DESIGNELEMENT.STOPRENEWDATE.'           
		ALTER TABLE DESIGNELEMENT ADD STOPRENEWDATE DATETIME NULL	 
		PRINT '**** DR-56993 DESIGNELEMENT.STOPRENEWDATE column has been added.'
	 END
	 ELSE   
		PRINT '**** DR-56993 DESIGNELEMENT.STOPRENEWDATE already exists'
		PRINT ''
	 GO

	 If EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'DESIGNELEMENT' AND COLUMN_NAME = 'CLIENTELEMENTID' AND CHARACTER_MAXIMUM_LENGTH <> 254)
			BEGIN	
				PRINT '**** DR-56993 Modifying column DESIGNELEMENT.CLIENTELEMENTID.'	 
				ALTER TABLE DESIGNELEMENT ALTER COLUMN CLIENTELEMENTID  NVARCHAR(254) NULL				 
				PRINT '**** DR-56993 DESIGNELEMENT.CLIENTELEMENTID column has been modified.'
			END
				PRINT '**** DR-56993 DESIGNELEMENT.CLIENTELEMENTID not found'
				PRINT ''
		GO

	If EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'DESIGNELEMENT' AND COLUMN_NAME = 'RENEWFLAG' AND DATA_TYPE <> 'BIT')
			BEGIN	
				PRINT '**** DR-56993 Modifying column DESIGNELEMENT.RENEWFLAG.'	 
				ALTER TABLE DESIGNELEMENT ALTER COLUMN RENEWFLAG  BIT NULL				 
				PRINT '**** DR-56993 DESIGNELEMENT.RENEWFLAG column has been modified.'
			END
				PRINT '**** DR-56993 DESIGNELEMENT.RENEWFLAG not found'
				PRINT ''
		GO

		If EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'DESIGNELEMENT' AND COLUMN_NAME = 'TYPEFACE' AND IS_NULLABLE = 'NO')
			BEGIN	
				PRINT '**** DR-56993 Modifying column DESIGNELEMENT.TYPEFACE.'	 
				ALTER TABLE DESIGNELEMENT ALTER COLUMN TYPEFACE  INT NULL				 
				PRINT '**** DR-56993 DESIGNELEMENT.TYPEFACE column has been modified.'
			END
				PRINT '**** DR-56993 DESIGNELEMENT.TYPEFACE not found'
				PRINT ''
		GO

		IF dbo.fn_IsAuditSchemaConsistent('DESIGNELEMENT') = 0
		BEGIN
         exec ipu_UtilGenerateAuditTriggers 'DESIGNELEMENT'
		END
		GO