/** DR-59545 Adding column REPORTCONTENTRESULT.STATUS	**/

If NOT exists (SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'REPORTCONTENTRESULT'AND COLUMN_NAME = 'STATUS')
	BEGIN
	PRINT '**** DR-59545 Adding column REPORTCONTENTRESULT.STATUS'
	ALTER TABLE REPORTCONTENTRESULT ADD STATUS int  NULL
	PRINT '**** DR-59545 Column REPORTCONTENTRESULT.STATUS added'
END
ELSE
	BEGIN
	PRINT '**** DR-59545 Column REPORTCONTENTRESULT.STATUS exists already'
END
GO


/** DR-59545 Adding column REPORTCONTENTRESULT.STARTED	**/

If NOT exists (SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'REPORTCONTENTRESULT'AND COLUMN_NAME = 'STARTED')
	BEGIN
	PRINT '**** DR-59545 Adding column REPORTCONTENTRESULT.STARTED'
	ALTER TABLE REPORTCONTENTRESULT ADD STARTED datetime  NULL
	PRINT '**** DR-59545 Column REPORTCONTENTRESULT.STARTED added'
END
ELSE
	BEGIN
	PRINT '**** DR-59545 Column REPORTCONTENTRESULT.STARTED exists already'
END
GO


/** DR-59545 Adding column REPORTCONTENTRESULT.FINISHED	**/

If NOT exists (SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'REPORTCONTENTRESULT'AND COLUMN_NAME = 'FINISHED')
	BEGIN
	PRINT '**** DR-59545 Adding column REPORTCONTENTRESULT.FINISHED'
	ALTER TABLE REPORTCONTENTRESULT ADD FINISHED datetime  NULL
	PRINT '**** DR-59545 Column REPORTCONTENTRESULT.FINISHED added'
END
ELSE
	BEGIN
	PRINT '**** DR-59545 Column REPORTCONTENTRESULT.FINISHED exists already'
END
GO


/** DR-59545 Adding column REPORTCONTENTRESULT.ERROR	**/

If NOT exists (SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'REPORTCONTENTRESULT'AND COLUMN_NAME = 'ERROR')
	BEGIN
	PRINT '**** DR-59545 Adding column REPORTCONTENTRESULT.ERROR'
	ALTER TABLE REPORTCONTENTRESULT ADD ERROR nvarchar(max) NULL
	PRINT '**** DR-59545 Column REPORTCONTENTRESULT.ERROR added'
END
ELSE
	BEGIN
	PRINT '**** DR-59545 Column REPORTCONTENTRESULT.ERROR exists already'
END
GO


/** DR-59545 Adding column REPORTCONTENTRESULT.CONNECTIONID	**/

If NOT exists (SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'REPORTCONTENTRESULT'AND COLUMN_NAME = 'CONNECTIONID')
	BEGIN
	PRINT '**** DR-59545 Adding column REPORTCONTENTRESULT.CONNECTIONID'
	ALTER TABLE REPORTCONTENTRESULT ADD CONNECTIONID nvarchar(max) NULL
	PRINT '**** DR-59545 Column REPORTCONTENTRESULT.CONNECTIONID added'
END
ELSE
	BEGIN
	PRINT '**** DR-59545 Column REPORTCONTENTRESULT.CONNECTIONID exists already'
END
GO


/** DR-59545 Adding column REPORTCONTENTRESULT.IDENTITYID	**/

If NOT exists (SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'REPORTCONTENTRESULT'AND COLUMN_NAME = 'IDENTITYID')
	BEGIN
	PRINT '**** DR-59545 Adding column REPORTCONTENTRESULT.IDENTITYID'
	ALTER TABLE REPORTCONTENTRESULT ADD IDENTITYID int  NULL
	PRINT '**** DR-59545 Column REPORTCONTENTRESULT.IDENTITYID added'
END
ELSE
	BEGIN
	PRINT '**** DR-59545 Column REPORTCONTENTRESULT.IDENTITYID exists already'
END
GO


/** DR-59545 Alter column REPORTCONTENTRESULT.PROCESSID	**/

If EXISTS (SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'REPORTCONTENTRESULT' AND COLUMN_NAME = 'PROCESSID' AND IS_NULLABLE = 'NO')
			BEGIN
	PRINT '**** DR-59545 Modifying column REPORTCONTENTRESULT.PROCESSID.'
	ALTER TABLE REPORTCONTENTRESULT ALTER COLUMN PROCESSID int  NULL
	PRINT '**** DR-59545 REPORTCONTENTRESULT.PROCESSID column has been modified.'
END		
GO


/** DR-59545 Alter column REPORTCONTENTRESULT.CONTENT	**/

If EXISTS (SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'REPORTCONTENTRESULT' AND COLUMN_NAME = 'CONTENT' AND IS_NULLABLE = 'NO')
			BEGIN
	PRINT '**** DR-59545 Modifying column REPORTCONTENTRESULT.CONTENT.'
	ALTER TABLE REPORTCONTENTRESULT ALTER COLUMN CONTENT varbinary(max)  NULL
	PRINT '**** DR-59545 REPORTCONTENTRESULT.CONTENT column has been modified.'
END		
GO


/** DR-59545 Alter column REPORTCONTENTRESULT.CONTENTTYPE	**/

If EXISTS (SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'REPORTCONTENTRESULT' AND COLUMN_NAME = 'CONTENTTYPE' AND (IS_NULLABLE = 'NO' OR CHARACTER_MAXIMUM_LENGTH <> '100'))
			BEGIN
	PRINT '**** DR-59545 Modifying column REPORTCONTENTRESULT.CONTENTTYPE.'
	ALTER TABLE REPORTCONTENTRESULT ALTER COLUMN CONTENTTYPE nvarchar(100)  NULL
	PRINT '**** DR-59545 REPORTCONTENTRESULT.CONTENTTYPE column has been modified.'
END		
GO


/** DR-59545 Alter column REPORTCONTENTRESULT.FILENAME	**/

If EXISTS (SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'REPORTCONTENTRESULT' AND COLUMN_NAME = 'FILENAME' AND (IS_NULLABLE = 'NO' OR CHARACTER_MAXIMUM_LENGTH <> '508'))
			BEGIN
	PRINT '**** DR-59545 Modifying column REPORTCONTENTRESULT.FILENAME.'
	ALTER TABLE REPORTCONTENTRESULT ALTER COLUMN FILENAME nvarchar(508) NULL
	PRINT '**** DR-59545 REPORTCONTENTRESULT.FILENAME column has been modified.'
END		
GO

/** DR-59545 Removing unique index REPORTCONTENTRESULT.XAK1REPORTCONTENTRESULT	**/

if exists (select *
from sysindexes
where name = 'XAK1REPORTCONTENTRESULT')
begin
	PRINT 'Dropping index REPORTCONTENTRESULT.XAK1REPORTCONTENTRESULT ...'
	DROP INDEX XAK1REPORTCONTENTRESULT ON REPORTCONTENTRESULT
end
go


/** DR-59545 Adding non-unique index REPORTCONTENTRESULT.XIE1REPORTCONTENTRESULT	**/

if not exists (select *
from sysindexes
where name = 'XIE1REPORTCONTENTRESULT')
begin
	PRINT 'Adding index REPORTCONTENTRESULT.XIE1REPORTCONTENTRESULT ...'
	CREATE NONCLUSTERED INDEX XIE1REPORTCONTENTRESULT ON REPORTCONTENTRESULT
( 
	PROCESSID ASC
)
end
go

IF dbo.fn_IsAuditSchemaConsistent('REPORTCONTENTRESULT') = 0
BEGIN
EXEC ipu_UtilGenerateAuditTriggers 'REPORTCONTENTRESULT'
END
GO