/** DR-59461 Adding column BACKGROUNDPROCESS.PROCESSSUBTYPE	**/

If NOT exists (SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'BACKGROUNDPROCESS'AND COLUMN_NAME = 'PROCESSSUBTYPE')
	BEGIN
	PRINT '**** DR-59461 Adding column BACKGROUNDPROCESS.PROCESSSUBTYPE'
	ALTER TABLE BACKGROUNDPROCESS ADD PROCESSSUBTYPE nvarchar(30)  NULL
	PRINT '**** DR-59461 Column BACKGROUNDPROCESS.PROCESSSUBTYPE added'
END
ELSE
	BEGIN
	PRINT '**** DR-59461 Column BACKGROUNDPROCESS.PROCESSSUBTYPE exists already'
END
GO
IF dbo.fn_IsAuditSchemaConsistent('BACKGROUNDPROCESS') = 0
BEGIN
EXEC ipu_UtilGenerateAuditTriggers 'BACKGROUNDPROCESS'
END
GO