If exists (SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'TMCLASS' AND COLUMN_NAME = 'CLASSHEADING' and UPPER(DATA_TYPE) = 'NTEXT')
Begin
	ALTER TABLE TMCLASS DISABLE TRIGGER ALL
	PRINT '*** RFC53705 Altering COLUMN TMCLASS.CLASSHEADING (DR-15430)	***'
	ALTER TABLE TMCLASS ALTER COLUMN CLASSHEADING nvarchar(max) NULL
	PRINT '*** RFC53705 TMCLASS.CLASSHEADING column has been altered (DR-15430)	***'

	-- Move data (<4000 bytes) from LOB onto the table to improve performance
	UPDATE TMCLASS SET CLASSHEADING = CLASSHEADING
		WHERE CLASSHEADING IS NOT NULL
	PRINT ''

	ALTER TABLE TMCLASS ENABLE TRIGGER ALL

End
Else
Begin
	PRINT '*** RFC53705 TMCLASS.CLASSHEADING already converted to nvarchar(max) (DR-15430)	***'
End
GO

If exists (SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'TMCLASS' AND COLUMN_NAME = 'CLASSNOTES' and UPPER(DATA_TYPE) = 'NTEXT')
Begin
	ALTER TABLE TMCLASS DISABLE TRIGGER ALL
	PRINT '*** RFC53705 Altering COLUMN TMCLASS.CLASSNOTES (DR-15430)	***'
	ALTER TABLE TMCLASS ALTER COLUMN CLASSNOTES nvarchar(max) NULL
	PRINT '*** RFC53705 TMCLASS.CLASSNOTES column has been altered (DR-15430)	***'

	-- Move data (<4000 bytes) from LOB onto the table to improve performance
	UPDATE TMCLASS SET CLASSNOTES = CLASSNOTES
		WHERE CLASSNOTES IS NOT NULL
	PRINT ''

	ALTER TABLE TMCLASS ENABLE TRIGGER ALL

End
Else
Begin
	PRINT '*** RFC53705 TMCLASS.CLASSNOTES already converted to nvarchar(max) (DR-15430)	***'
End
GO

-- Regenerate audit trigger on TMCLASS table
IF dbo.fn_IsAuditSchemaConsistent('TMCLASS') = 0
BEGIN
   EXEC ipu_UtilGenerateAuditTriggers 'TMCLASS'
END
GO