/** DR-53426 Adding column POLICINGLOG.SPID **/

If NOT exists (SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'POLICINGLOG'AND COLUMN_NAME = 'SPID')
BEGIN
	PRINT '**** DR-53426 Adding column POLICINGLOG.SPID'
	ALTER TABLE POLICINGLOG ADD SPID smallint NULL
	PRINT '**** DR-53426 Column POLICINGLOG.SPID added'
END
ELSE
BEGIN
	PRINT '**** DR-53426 Column POLICINGLOG.SPID exists already'
END
GO

/** DR-53426 Adding column POLICINGLOG.SPIDSTART **/

If NOT exists (SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'POLICINGLOG'AND COLUMN_NAME = 'SPIDSTART')
BEGIN
	PRINT '**** DR-53426 Adding column POLICINGLOG.SPIDSTART'
	ALTER TABLE POLICINGLOG ADD SPIDSTART datetime NULL
	PRINT '**** DR-53426 Column POLICINGLOG.SPIDSTART added'
END
ELSE
BEGIN
	PRINT '**** DR-53426 Column POLICINGLOG.SPIDSTART exists already'
END
GO

IF dbo.fn_IsAuditSchemaConsistent('POLICINGLOG') = 0
BEGIN
EXEC ipu_UtilGenerateAuditTriggers 'POLICINGLOG'
END
GO