/****************************************************************************/
/*** DR-63866 Database changes for KOT ***/
/****************************************************************************/

/*** DR-63866 Adding table KOTCASETYPE ***/

If NOT exists (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KOTCASETYPE')
BEGIN
PRINT '**** DR-63866 Adding table KOTCASETYPE.'
CREATE TABLE dbo.KOTCASETYPE
(
	KOTID int NOT NULL ,
	CASETYPE nchar(1) NOT NULL ,
	LOGUSERID nvarchar(50) NULL ,
	LOGIDENTITYID int NULL ,
	LOGTRANSACTIONNO int NULL ,
	LOGDATETIMESTAMP datetime NULL ,
	LOGAPPLICATION nvarchar(128) NULL ,
	LOGOFFICEID int NULL
)
exec sc_AssignTableSecurity 'KOTCASETYPE'
PRINT '**** DR-63866 KOTCASETYPE table has been added.'
PRINT ''
END
ELSE
PRINT '**** DR-63866 Table KOTCASETYPE already exists'
PRINT ''
go

/*** DR-63866 Adding table KOTNAMETYPE ***/

If NOT exists (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KOTNAMETYPE')
BEGIN
PRINT '**** DR-63866 Adding table KOTNAMETYPE.'
CREATE TABLE dbo.KOTNAMETYPE
(
	KOTID int NOT NULL ,
	NAMETYPE nvarchar(3) NOT NULL ,
	LOGUSERID nvarchar(50) NULL ,
	LOGIDENTITYID int NULL ,
	LOGTRANSACTIONNO int NULL ,
	LOGDATETIMESTAMP datetime NULL ,
	LOGAPPLICATION nvarchar(128) NULL ,
	LOGOFFICEID int NULL
)
exec sc_AssignTableSecurity 'KOTNAMETYPE'
PRINT '**** DR-63866 KOTNAMETYPE table has been added.'
PRINT ''
END
ELSE
PRINT '**** DR-63866 Table KOTNAMETYPE already exists'
PRINT ''
go

/*** DR-63866 Adding table KOTROLE ***/

If NOT exists (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KOTROLE')
BEGIN
PRINT '**** DR-63866 Adding table KOTROLE.'
CREATE TABLE dbo.KOTROLE
(
	KOTID int NOT NULL ,
	ROLEID int NOT NULL ,
	LOGUSERID nvarchar(50) NULL ,
	LOGIDENTITYID int NULL ,
	LOGTRANSACTIONNO int NULL ,
	LOGDATETIMESTAMP datetime NULL ,
	LOGAPPLICATION nvarchar(128) NULL ,
	LOGOFFICEID int NULL
)
exec sc_AssignTableSecurity 'KOTROLE'
PRINT '**** DR-63866 KOTROLE table has been added.'
PRINT ''
END
ELSE
PRINT '**** DR-63866 Table KOTROLE already exists'
PRINT ''
go

/*** DR-63866 Adding table KOTTEXTTYPE ***/

If NOT exists (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'KOTTEXTTYPE')
BEGIN
PRINT '**** DR-63866 Adding table KOTTEXTTYPE.'
CREATE TABLE dbo.KOTTEXTTYPE
(
	ID int IDENTITY NOT FOR REPLICATION NOT NULL ,
	TEXTTYPE nvarchar(2) NOT NULL ,
	TYPE char(1) NOT NULL ,
	BACKGROUNDCOLOR nvarchar(7) NULL ,
	LOGUSERID nvarchar(50) NULL ,
	LOGIDENTITYID int NULL ,
	LOGTRANSACTIONNO int NULL ,
	LOGDATETIMESTAMP datetime NULL ,
	LOGAPPLICATION nvarchar(128) NULL ,
	LOGOFFICEID int NULL ,
	CASEPROGRAM bit NOT NULL DEFAULT 0,
	NAMEPROGRAM bit NOT NULL DEFAULT 0,
	TIMEPROGRAM bit NOT NULL DEFAULT 0,
	BILLINGPROGRAM bit NOT NULL DEFAULT 0,
	TASKPLANNERPROGRAM bit NOT NULL DEFAULT 0,
	PENDING bit NOT NULL DEFAULT 0,
	REGISTERED bit NOT NULL DEFAULT 0,
	DEAD bit NOT NULL DEFAULT 0
)
exec sc_AssignTableSecurity 'KOTTEXTTYPE'
PRINT '**** DR-63866 KOTTEXTTYPE table has been added.'
PRINT ''
END
ELSE
PRINT '**** DR-63866 Table KOTTEXTTYPE already exists'
PRINT ''
go

If exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'KOTTEXTTYPE' and CONSTRAINT_NAME = 'FK_dbo.KotTextType_TextType_dbo.TextType')
begin
	PRINT 'Dropping foreign key constraint FK_dbo.KotTextType_TextType_dbo.TextType...'
	ALTER TABLE dbo.KOTTEXTTYPE DROP CONSTRAINT [FK_dbo.KotTextType_TextType_dbo.TextType]
end
go

If exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'KOTCASETYPE' and CONSTRAINT_NAME = 'FK_dbo.KOTCASETYPE_KOTTEXTTYPE_dbo.KOTTEXTTYPE')
begin
	PRINT 'Dropping foreign key constraint [FK_dbo.KOTCASETYPE_KOTTEXTTYPE_dbo.KOTTEXTTYPE]...'
	ALTER TABLE dbo.KOTCASETYPE DROP CONSTRAINT [FK_dbo.KOTCASETYPE_KOTTEXTTYPE_dbo.KOTTEXTTYPE]
end
go

If exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'KOTCASETYPE' and CONSTRAINT_NAME = 'FK_dbo.KOTCASETYPE_CASETYPE_dbo.CASETYPE')
begin
	PRINT 'Dropping foreign key constraint [FK_dbo.KOTCASETYPE_CASETYPE_dbo.CASETYPE]...'
	ALTER TABLE dbo.KOTCASETYPE DROP CONSTRAINT [FK_dbo.KOTCASETYPE_CASETYPE_dbo.CASETYPE]
end
go

If exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'KOTNAMETYPE' and CONSTRAINT_NAME = 'FK_dbo.KOTNAMETYPE_KOTTEXTTYPE_dbo.KOTTEXTTYPE')
begin
	PRINT 'Dropping foreign key constraint FK_dbo.KOTNAMETYPE_KOTTEXTTYPE_dbo.KOTTEXTTYPE...'
	ALTER TABLE dbo.KOTNAMETYPE DROP CONSTRAINT [FK_dbo.KOTNAMETYPE_KOTTEXTTYPE_dbo.KOTTEXTTYPE]
end
go

If exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'KOTNAMETYPE' and CONSTRAINT_NAME = 'FK_dbo.KotNameType_NameType_dbo.NameType')
begin
	PRINT 'Dropping foreign key constraint FK_dbo.KotNameType_NameType_dbo.NameType...'
	ALTER TABLE dbo.KotNameType DROP CONSTRAINT [FK_dbo.KotNameType_NameType_dbo.NameType]
end
go

If exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'KOTROLE' and CONSTRAINT_NAME = 'FK_dbo.KotRole_KotTextType_dbo.KotTextType')
begin
	PRINT 'Dropping foreign key constraint FK_dbo.KotRole_KotTextType_dbo.KotTextType...'
	ALTER TABLE dbo.KOTROLE DROP CONSTRAINT [FK_dbo.KotRole_KotTextType_dbo.KotTextType]
end
go

If exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'KOTROLE' and CONSTRAINT_NAME = 'FK_dbo.KotRole_Role_dbo.Role')
begin
	PRINT 'Dropping foreign key constraint FK_dbo.KotRole_Role_dbo.Role...'
	ALTER TABLE dbo.KOTROLE DROP CONSTRAINT [FK_dbo.KotRole_Role_dbo.Role]
end
go

if not exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'KOTCASETYPE' and CONSTRAINT_NAME = 'XPKKOTCASETYPE')
begin
	PRINT 'Adding primary key constraint KOTCASETYPE.XPKKOTCASETYPE...'
	ALTER TABLE dbo.KOTCASETYPE
	WITH NOCHECK ADD CONSTRAINT XPKKOTCASETYPE PRIMARY KEY CLUSTERED (KOTID ASC,CASETYPE ASC)
end
go

if not exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'KOTNAMETYPE' and CONSTRAINT_NAME = 'XPKKOTNAMETYPE')
begin
	PRINT 'Adding primary key constraint KOTNAMETYPE.XPKKOTNAMETYPE...'
	ALTER TABLE dbo.KOTNAMETYPE
	WITH NOCHECK ADD CONSTRAINT XPKKOTNAMETYPE PRIMARY KEY CLUSTERED (KOTID ASC,NAMETYPE ASC)
end
go

if not exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'KOTROLE' and CONSTRAINT_NAME = 'XPKKOTROLE')
begin
	PRINT 'Adding primary key constraint KOTROLE.XPKKOTROLE...'
	ALTER TABLE dbo.KOTROLE
	WITH NOCHECK ADD CONSTRAINT XPKKOTROLE PRIMARY KEY CLUSTERED (KOTID ASC,ROLEID ASC)
end
go

if not exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'KOTTEXTTYPE' and CONSTRAINT_NAME = 'XPKKOTTEXTTYPE')
begin
	PRINT 'Adding primary key constraint KOTTEXTTYPE.XPKKOTTEXTTYPE...'
	ALTER TABLE dbo.KOTTEXTTYPE
	WITH NOCHECK ADD CONSTRAINT XPKKOTTEXTTYPE PRIMARY KEY CLUSTERED (ID ASC)
end
go

if not exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'KOTCASETYPE' and CONSTRAINT_NAME = 'R_81933')
begin
	PRINT 'Adding foreign key constraint KOTCASETYPE.R_81933...'
	ALTER TABLE dbo.KOTCASETYPE
	WITH NOCHECK ADD CONSTRAINT R_81933 FOREIGN KEY (KOTID) REFERENCES dbo.KOTTEXTTYPE(ID)
	ON DELETE CASCADE
	NOT FOR REPLICATION
end
go

if not exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'KOTCASETYPE' and CONSTRAINT_NAME = 'R_81934')
begin
	PRINT 'Adding foreign key constraint KOTCASETYPE.R_81934...'
	ALTER TABLE dbo.KOTCASETYPE
	WITH NOCHECK ADD CONSTRAINT R_81934 FOREIGN KEY (CASETYPE) REFERENCES dbo.CASETYPE(CASETYPE)
	NOT FOR REPLICATION
end
go

if not exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'KOTNAMETYPE' and CONSTRAINT_NAME = 'R_81935')
begin
	PRINT 'Adding foreign key constraint KOTNAMETYPE.R_81935...'
	ALTER TABLE dbo.KOTNAMETYPE
	WITH NOCHECK ADD CONSTRAINT R_81935 FOREIGN KEY (KOTID) REFERENCES dbo.KOTTEXTTYPE(ID)
	ON DELETE CASCADE
	NOT FOR REPLICATION
end
go

if not exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'KOTNAMETYPE' and CONSTRAINT_NAME = 'R_81936')
begin
	PRINT 'Adding foreign key constraint KOTNAMETYPE.R_81936...'
	ALTER TABLE dbo.KOTNAMETYPE
	WITH NOCHECK ADD CONSTRAINT R_81936 FOREIGN KEY (NAMETYPE) REFERENCES dbo.NAMETYPE(NAMETYPE)
	NOT FOR REPLICATION
end
go

if not exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'KOTROLE' and CONSTRAINT_NAME = 'R_81937')
begin
	PRINT 'Adding foreign key constraint KOTROLE.R_81937...'
	ALTER TABLE dbo.KOTROLE
	WITH NOCHECK ADD CONSTRAINT R_81937 FOREIGN KEY (KOTID) REFERENCES dbo.KOTTEXTTYPE(ID)
	ON DELETE CASCADE
	NOT FOR REPLICATION
end
go

if not exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'KOTROLE' and CONSTRAINT_NAME = 'R_81938')
begin
	PRINT 'Adding foreign key constraint KOTROLE.R_81938...'
	ALTER TABLE dbo.KOTROLE
	WITH NOCHECK ADD CONSTRAINT R_81938 FOREIGN KEY (ROLEID) REFERENCES dbo.ROLE(ROLEID)
	NOT FOR REPLICATION
end
go

if not exists (select * from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE where TABLE_NAME = 'KOTTEXTTYPE' and CONSTRAINT_NAME = 'R_81932')
begin
	PRINT 'Adding foreign key constraint KOTTEXTTYPE.R_81932...'
	ALTER TABLE dbo.KOTTEXTTYPE
	WITH NOCHECK ADD CONSTRAINT R_81932 FOREIGN KEY (TEXTTYPE) REFERENCES dbo.TEXTTYPE(TEXTTYPE)
	NOT FOR REPLICATION
end
go

/*** DR-63866 Genarating audit triggers ***/

IF dbo.fn_IsAuditSchemaConsistent('KOTCASETYPE') = 0
BEGIN
   EXEC ipu_UtilGenerateAuditTriggers 'KOTCASETYPE'
END
GO

IF dbo.fn_IsAuditSchemaConsistent('KOTNAMETYPE') = 0
BEGIN
   EXEC ipu_UtilGenerateAuditTriggers 'KOTNAMETYPE'
END
GO

IF dbo.fn_IsAuditSchemaConsistent('KOTROLE') = 0
BEGIN
   EXEC ipu_UtilGenerateAuditTriggers 'KOTROLE'
END
GO

IF dbo.fn_IsAuditSchemaConsistent('KOTTEXTTYPE') = 0
BEGIN
   EXEC ipu_UtilGenerateAuditTriggers 'KOTTEXTTYPE'
END
GO
