IF NOT EXISTS (SELECT * FROM CONFIGURATIONITEM WHERE TASKID = 227 AND GENERICPARAM='TSDR')
BEGIN
	INSERT INTO CONFIGURATIONITEM(TASKID, TITLE, DESCRIPTION, GENERICPARAM, URL) VALUES
	(227,
	N'TSDR Integration Settings',
	N'Configure required settings for TSDR integration and data download.', 'TSDR', '/apps/#/pto-settings/uspto-tsdr')
END
GO

insert CONFIGURATIONITEMCOMPONENTS (CONFIGITEMID, COMPONENTID)
select CI.CONFIGITEMID, CO.COMPONENTID
from CONFIGURATIONITEM CI
join COMPONENTS CO on CO.COMPONENTNAME in ('Case Comparison', 'Integration')
where CI.TITLE = 'TSDR Integration Settings'
and not exists (
	select * 
	from CONFIGURATIONITEMCOMPONENTS CIC
	where CIC.COMPONENTID = CO.COMPONENTID and  CIC.CONFIGITEMID = CI.CONFIGITEMID)

go