IF EXISTS (SELECT * FROM CONFIGURATIONITEM WHERE TASKID = 227 AND GENERICPARAM='TSDR')
BEGIN
	UPDATE CONFIGURATIONITEM Set Title = N'USPTO TSDR Integration settings' WHERE TASKID = 227 AND GENERICPARAM = 'TSDR'
END
GO
