/****************************************************************************/
/*** DR-69021 Adding table EXCHANGERESOURCETRACKER ***/
/****************************************************************************/

If NOT exists (SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'EXCHANGERESOURCETRACKER')
		BEGIN
	PRINT '**** DR-69021  Adding table EXCHANGERESOURCETRACKER.'
	CREATE TABLE dbo.EXCHANGERESOURCETRACKER
	(
		ID bigint IDENTITY ( 1,1 ) NOT FOR REPLICATION NOT NULL ,
		EMPLOYEENO int NOT NULL ,
		MESSAGESEQ datetime NOT NULL ,
		RESOURCEID nvarchar(4000) NOT NULL ,
		RESOURCETYPE smallint NOT NULL ,
		LOGUSERID nvarchar(50) NULL ,
		LOGIDENTITYID int NULL ,
		LOGTRANSACTIONNO int NULL ,
		LOGDATETIMESTAMP datetime NULL ,
		LOGAPPLICATION nvarchar(128) NULL ,
		LOGOFFICEID int NULL
	)
	exec sc_AssignTableSecurity 'EXCHANGERESOURCETRACKER'
	PRINT '**** DR-69021 EXCHANGERESOURCETRACKER table has been added.'
	PRINT ''
END
		else
			PRINT '**** DR-69021 Table EXCHANGERESOURCETRACKER already exists'
PRINT ''
go


if not exists (select *
from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE
where TABLE_NAME = 'EXCHANGERESOURCETRACKER' and CONSTRAINT_NAME = 'XPKEXCHANGERESOURCETRACKER')
	begin
	PRINT 'Adding primary key constraint EXCHANGERESOURCETRACKER.XPKEXCHANGERESOURCETRACKER...'
	ALTER TABLE dbo.EXCHANGERESOURCETRACKER
	 WITH NOCHECK ADD CONSTRAINT XPKEXCHANGERESOURCETRACKER PRIMARY KEY  CLUSTERED (ID ASC)
	PRINT 'Primary key constraint EXCHANGERESOURCETRACKER.XPKEXCHANGERESOURCETRACKER has been added...'
end
	else
	PRINT 'Primary key constraint EXCHANGERESOURCETRACKER.XPKEXCHANGERESOURCETRACKER already exists...'
go


if not exists (select *
from INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE
where TABLE_NAME = 'EXCHANGERESOURCETRACKER' and CONSTRAINT_NAME = 'R_81941')
	begin
	PRINT 'Adding foreign key constraint EXCHANGERESOURCETRACKER.R_81941...'
	ALTER TABLE dbo.EXCHANGERESOURCETRACKER
	 WITH NOCHECK ADD CONSTRAINT R_81941 FOREIGN KEY (EMPLOYEENO) REFERENCES dbo.NAME(NAMENO)
		ON DELETE CASCADE
	 NOT FOR REPLICATION
	PRINT 'Foreign key constraint EXCHANGERESOURCETRACKER.R_81941 has been added...'
end
	else
	PRINT 'Foreign key constraint EXCHANGERESOURCETRACKER.R_81941 already exists...'
go



if not exists (select *
from sysindexes
where name = 'XAK1EXCHANGERESOURCETRACKER')
begin
	PRINT 'Adding index EXCHANGERESOURCETRACKER.XAK1EXCHANGERESOURCETRACKER ...'
	CREATE UNIQUE NONCLUSTERED INDEX XAK1EXCHANGERESOURCETRACKER ON EXCHANGERESOURCETRACKER
( 
	EMPLOYEENO ASC,
	MESSAGESEQ ASC
)
	PRINT 'Index EXCHANGERESOURCETRACKER.XAK1EXCHANGERESOURCETRACKER has been added...'
end
else 
PRINT 'Index EXCHANGERESOURCETRACKER.XAK1EXCHANGERESOURCETRACKER already exists...'
go

/*** DR-69021 Genarating audit triggers ***/

IF dbo.fn_IsAuditSchemaConsistent('EXCHANGERESOURCETRACKER') = 0
BEGIN
   EXEC ipu_UtilGenerateAuditTriggers 'EXCHANGERESOURCETRACKER'
END
GO

/**********************************************************************************************************/
/*** DR-69021 Add data into AUDITLOGTABLES.TABLENAME = EXCHANGERESOURCETRACKER ***/
/**********************************************************************************************************/

IF NOT exists (select *
from AUDITLOGTABLES
where TABLENAME = 'EXCHANGERESOURCETRACKER')
		begin
	PRINT '**** DR-69021  Inserting data into AUDITLOGTABLE.TABLENAME = EXCHANGERESOURCETRACKER'
	Insert AUDITLOGTABLES
		(TABLENAME, LOGFLAG, REPLICATEFLAG)
	Values
		('EXCHANGERESOURCETRACKER', 0, 0)
	PRINT '**** DR-69021  Data has been successfully added to AUDITLOGTABLES table.'
	PRINT ''
END
	ELSE
		PRINT '**** DR-69021  AUDITLOGTABLES.EXCHANGERESOURCETRACKER already exists.'
PRINT ''
	go	