/*** DR-70200 Add column RECORDALAFFECTEDCASE.RECORDALSTEPS		***/
If NOT exists (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RECORDALAFFECTEDCASE' AND COLUMN_NAME = 'RECORDALSTEPSEQ')
BEGIN
	
    PRINT '**** DR-70200 Adding column RECORDALAFFECTEDCASE.RECORDALSTEPSEQ'
    ALTER TABLE RECORDALAFFECTEDCASE ADD RECORDALSTEPSEQ int  NULL
    PRINT '**** DR-70200 Column RECORDALAFFECTEDCASE.RECORDALSTEPSEQ added'	  

END
ELSE
    BEGIN
    PRINT '**** DR-70200 Column RECORDALAFFECTEDCASE.RECORDALSTEPSEQ exists already'
END
GO

IF dbo.fn_IsAuditSchemaConsistent('RECORDALAFFECTEDCASE') = 0
BEGIN
   EXEC ipu_UtilGenerateAuditTriggers 'RECORDALAFFECTEDCASE'
END
GO

IF exists (Select 1 from RECORDALAFFECTEDCASE where RECORDALSTEPSEQ is null and CASEID is not null)
Begin
	PRINT '**** DR-70200 Updating RECORDALAFFECTEDCASE.RECORDALSTEPSEQ'
	UPDATE R
	SET RECORDALSTEPSEQ = RS.RECORDALSTEPSEQ
	FROM RECORDALAFFECTEDCASE R
	JOIN RECORDALSTEP RS on (R.CASEID = RS.CASEID and R.RECORDALTYPENO = RS.RECORDALTYPENO)
	WHERE R.RECORDALSTEPSEQ is null
	PRINT '**** DR-70200 RECORDALAFFECTEDCASE.RECORDALSTEPSEQ updated'
End
ELSE 
BEGIN
	PRINT '**** DR-70200 RECORDALAFFECTEDCASE.RECORDALSTEPSEQ already exists'
END
GO

