/***************** DR-72639  Add Doc items 'EMAIL_TASKPLANNER_SUBJECT' and 'EMAIL_TASKPLANNER_BODY' *************************/
IF NOT EXISTS(SELECT 1 FROM ITEM WHERE ITEM_NAME = 'EMAIL_TASKPLANNER_SUBJECT')
BEGIN
	PRINT 'Adding ITEM_NAME = ''EMAIL_TASKPLANNER_SUBJECT'''
	    Declare @nItemId int
		Select @nItemId = (Min(ITEM_ID)-1) from ITEM
		INSERT INTO ITEM (ITEM_ID,ITEM_NAME, SQL_QUERY, ITEM_DESCRIPTION, DATE_CREATED, DATE_UPDATED, ITEM_TYPE, ENTRY_POINT_USAGE, SQL_DESCRIBE, SQL_INTO)
		VALUES (@nItemId, 'EMAIL_TASKPLANNER_SUBJECT', 'ipw_EmailTaskPlannerSubject', 'Task Planner Email Subject', CONVERT(date, getdate()), CONVERT(date, getdate()), 1, 1,1, ':s[0]')
	PRINT 'Added ITEM_NAME = ''EMAIL_TASKPLANNER_SUBJECT'''
END
GO

IF NOT EXISTS(SELECT 1 FROM ITEM WHERE ITEM_NAME = 'EMAIL_TASKPLANNER_BODY')
BEGIN
	PRINT 'Adding ITEM_NAME = ''EMAIL_TASKPLANNER_BODY'''
	Declare @nItemId int
	Select @nItemId = (Min(ITEM_ID)-1) from ITEM
	INSERT INTO ITEM (ITEM_ID, ITEM_NAME, SQL_QUERY, ITEM_DESCRIPTION, DATE_CREATED, DATE_UPDATED, ITEM_TYPE, ENTRY_POINT_USAGE, SQL_DESCRIBE, SQL_INTO)
	VALUES (@nItemId, 'EMAIL_TASKPLANNER_BODY', 'ipw_EmailTaskPlannerBody', 'Task Planner Email Body', CONVERT(date, getdate()), CONVERT(date, getdate()), 1, 1,1, ':s[0]')
	PRINT 'Added ITEM_NAME = ''EMAIL_TASKPLANNER_BODY'''
END
GO