/***	DR-73634 Add column EXTERNALSETTINGS.ISDISABLED   ***/ 

	If NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EXTERNALSETTINGS' AND COLUMN_NAME = 'ISDISABLED')
	 BEGIN   
		PRINT '**** DR-73634 Add column EXTERNALSETTINGS.ISDISABLED'           
		ALTER TABLE EXTERNALSETTINGS add ISDISABLED BIT NOT NULL DEFAULT 0 
		PRINT '**** DR-73634 Add column EXTERNALSETTINGS.ISDISABLED column has been added.'
	 END
	 ELSE   
		PRINT '**** DR-73634 column EXTERNALSETTINGS.ISDISABLED already exists'
		PRINT ''
	 GO

	 IF dbo.fn_IsAuditSchemaConsistent('EXTERNALSETTINGS') = 0
BEGIN
   EXEC ipu_UtilGenerateAuditTriggers 'EXTERNALSETTINGS'
END
	GO	