IF NOT EXISTS (SELECT * FROM MAPSCENARIO WHERE SYSTEMID = -5 AND STRUCTUREID = 12)
Begin
	print '**** DR-75136 Adding Type of Mark Map Scenario.'
	INSERT INTO MAPSCENARIO (SYSTEMID, STRUCTUREID, SCHEMEID, IGNOREUNMAPPED)
	VALUES (-5, 12, -3, 0)
	print '**** DR-75136 Adding Type of Mark Map Scenario.'
	print ''
End
Else
Begin
	print '****DR-75136 Type of Mark Map Scenario already exists.'
	print ''
End
go

insert MAPPING (STRUCTUREID, DATASOURCEID, INPUTCODE, INPUTDESCRIPTION, INPUTCODEID, OUTPUTCODEID, OUTPUTVALUE, ISNOTAPPLICABLE)
select EV.STRUCTUREID, -5, NULL, 'SOUND ONLY', NULL, EV.CODEID, NULL, 0 
from ENCODEDVALUE EV
where EV.SCHEMEID = -1 and EV.STRUCTUREID = 12
and EV.CODE = 5103
and not exists(
	select * 
	from MAPPING M 
	where M.DATASOURCEID = -5
	and M.STRUCTUREID = EV.STRUCTUREID 
	and M.OUTPUTCODEID = EV.CODEID
	and M.INPUTDESCRIPTION = N'SOUND ONLY'
)
go

insert MAPPING (STRUCTUREID, DATASOURCEID, INPUTCODE, INPUTDESCRIPTION, INPUTCODEID, OUTPUTCODEID, OUTPUTVALUE, ISNOTAPPLICABLE)
select EV.STRUCTUREID, -5, NULL, 'THREE-DIMENSIONAL TRADEMARK', NULL, EV.CODEID, NULL, 0 
from ENCODEDVALUE EV
where EV.SCHEMEID = -1 and EV.STRUCTUREID = 12
and EV.CODE = 5105
and not exists(
	select * 
	from MAPPING M 
	where M.DATASOURCEID = -5
	and M.STRUCTUREID = EV.STRUCTUREID 
	and M.OUTPUTCODEID = EV.CODEID
	and M.INPUTDESCRIPTION = N'THREE-DIMENSIONAL TRADEMARK'
)
go

insert MAPPING (STRUCTUREID, DATASOURCEID, INPUTCODE, INPUTDESCRIPTION, INPUTCODEID, OUTPUTCODEID, OUTPUTVALUE, ISNOTAPPLICABLE)
select EV.STRUCTUREID, -5, NULL, 'WORD MARK', NULL, EV.CODEID, NULL, 0 
from ENCODEDVALUE EV
where EV.SCHEMEID = -1 and EV.STRUCTUREID = 12
and EV.CODE = 5102
and not exists(
	select * 
	from MAPPING M 
	where M.DATASOURCEID = -5
	and M.STRUCTUREID = EV.STRUCTUREID 
	and M.OUTPUTCODEID = EV.CODEID 
	and M.INPUTDESCRIPTION = N'WORD MARK'
)
go

insert MAPPING (STRUCTUREID, DATASOURCEID, INPUTCODE, INPUTDESCRIPTION, INPUTCODEID, OUTPUTCODEID, OUTPUTVALUE, ISNOTAPPLICABLE)
select EV.STRUCTUREID, -5, NULL, 'WORD ONLY', NULL, EV.CODEID, NULL, 0 
from ENCODEDVALUE EV
where EV.SCHEMEID = -1 and EV.STRUCTUREID = 12
and EV.CODE = 5102
and not exists(
	select * 
	from MAPPING M 
	where M.DATASOURCEID = -5
	and M.STRUCTUREID = EV.STRUCTUREID 
	and M.OUTPUTCODEID = EV.CODEID 
	and M.INPUTDESCRIPTION = N'WORD ONLY'
)
go

insert MAPPING (STRUCTUREID, DATASOURCEID, INPUTCODE, INPUTDESCRIPTION, INPUTCODEID, OUTPUTCODEID, OUTPUTVALUE, ISNOTAPPLICABLE)
select EV.STRUCTUREID, -5, NULL, 'BLOCK LETTERS', NULL, EV.CODEID, NULL, 0 
from ENCODEDVALUE EV
where EV.SCHEMEID = -1 and EV.STRUCTUREID = 12
and EV.CODE = 5102
and not exists(
	select * 
	from MAPPING M 
	where M.DATASOURCEID = -5
	and M.STRUCTUREID = EV.STRUCTUREID 
	and M.OUTPUTCODEID = EV.CODEID 
	and M.INPUTDESCRIPTION = N'BLOCK LETTERS'
)
go

insert MAPPING (STRUCTUREID, DATASOURCEID, INPUTCODE, INPUTDESCRIPTION, INPUTCODEID, OUTPUTCODEID, OUTPUTVALUE, ISNOTAPPLICABLE)
select EV.STRUCTUREID, -5, NULL, 'DESIGN AND COLOR', NULL, EV.CODEID, NULL, 0 
from ENCODEDVALUE EV
where EV.SCHEMEID = -1 and EV.STRUCTUREID = 12
and EV.CODE = 5111
and not exists(
	select * 
	from MAPPING M 
	where M.DATASOURCEID = -5
	and M.STRUCTUREID = EV.STRUCTUREID 
	and M.OUTPUTCODEID = EV.CODEID 
	and M.INPUTDESCRIPTION = N'DESIGN AND COLOR'
)
go

insert MAPPING (STRUCTUREID, DATASOURCEID, INPUTCODE, INPUTDESCRIPTION, INPUTCODEID, OUTPUTCODEID, OUTPUTVALUE, ISNOTAPPLICABLE)
select EV.STRUCTUREID, -5, NULL, 'DESIGN MARK', NULL, EV.CODEID, NULL, 0 
from ENCODEDVALUE EV
where EV.SCHEMEID = -1 and EV.STRUCTUREID = 12
and EV.CODE = 5101
and not exists(
	select * 
	from MAPPING M 
	where M.DATASOURCEID = -5
	and M.STRUCTUREID = EV.STRUCTUREID 
	and M.OUTPUTCODEID = EV.CODEID 
	and M.INPUTDESCRIPTION = N'DESIGN MARK'
)
go

insert MAPPING (STRUCTUREID, DATASOURCEID, INPUTCODE, INPUTDESCRIPTION, INPUTCODEID, OUTPUTCODEID, OUTPUTVALUE, ISNOTAPPLICABLE)
select EV.STRUCTUREID, -5, NULL, 'DESIGN ONLY', NULL, EV.CODEID, NULL, 0 
from ENCODEDVALUE EV
where EV.SCHEMEID = -1 and EV.STRUCTUREID = 12
and EV.CODE = 5101
and not exists(
	select * 
	from MAPPING M 
	where M.DATASOURCEID = -5
	and M.STRUCTUREID = EV.STRUCTUREID 
	and M.OUTPUTCODEID = EV.CODEID 
	and M.INPUTDESCRIPTION = N'DESIGN ONLY'
)
go

insert MAPPING (STRUCTUREID, DATASOURCEID, INPUTCODE, INPUTDESCRIPTION, INPUTCODEID, OUTPUTCODEID, OUTPUTVALUE, ISNOTAPPLICABLE)
select EV.STRUCTUREID, -5, NULL, 'SOUND ONLY', NULL, EV.CODEID, NULL, 0 
from ENCODEDVALUE EV
where EV.SCHEMEID = -1 and EV.STRUCTUREID = 12
and EV.CODE = 5103
and not exists(
	select * 
	from MAPPING M 
	where M.DATASOURCEID = -5
	and M.STRUCTUREID = EV.STRUCTUREID 
	and M.OUTPUTCODEID = EV.CODEID 
	and M.INPUTDESCRIPTION = N'SOUND ONLY'
)
go

insert MAPPING (STRUCTUREID, DATASOURCEID, INPUTCODE, INPUTDESCRIPTION, INPUTCODEID, OUTPUTCODEID, OUTPUTVALUE, ISNOTAPPLICABLE)
select EV.STRUCTUREID, -5, NULL, 'STYLIZED LETTERS', NULL, EV.CODEID, NULL, 0 
from ENCODEDVALUE EV
where EV.SCHEMEID = -1 and EV.STRUCTUREID = 12
and EV.CODE = 5108
and not exists(
	select * 
	from MAPPING M 
	where M.DATASOURCEID = -5
	and M.STRUCTUREID = EV.STRUCTUREID 
	and M.OUTPUTCODEID = EV.CODEID 
	and M.INPUTDESCRIPTION = N'STYLIZED LETTERS'
)
go

insert MAPPING (STRUCTUREID, DATASOURCEID, INPUTCODE, INPUTDESCRIPTION, INPUTCODEID, OUTPUTCODEID, OUTPUTVALUE, ISNOTAPPLICABLE)
select EV.STRUCTUREID, -5, NULL, 'WORD AND DESIGN', NULL, EV.CODEID, NULL, 0 
from ENCODEDVALUE EV
where EV.SCHEMEID = -1 and EV.STRUCTUREID = 12
and EV.CODE = 5107
and not exists(
	select * 
	from MAPPING M 
	where M.DATASOURCEID = -5
	and M.STRUCTUREID = EV.STRUCTUREID 
	and M.OUTPUTCODEID = EV.CODEID 
	and M.INPUTDESCRIPTION = N'WORD AND DESIGN'
)
go