IF EXISTS(SELECT 1 FROM TASKPLANNERTAB T WHERE T.IDENTITYID IS NULL)
BEGIN
	PRINT 'Deleting rows with null identityId....'
		DELETE FROM TASKPLANNERTAB WHERE IDENTITYID IS NULL
	PRINT 'Deleted rows with null identityId ....'
END
Go