-----------------------------------------------------------------------------------------------------------------------------
-- Creation of csw_ListCopyProfileData
-----------------------------------------------------------------------------------------------------------------------------
If exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[csw_ListCopyProfileData]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
Begin
	Print '**** Drop Stored Procedure dbo.csw_ListCopyProfileData.'
	Drop procedure [dbo].[csw_ListCopyProfileData]
	Print '**** Creating Stored Procedure dbo.csw_ListCopyProfileData...'
	Print ''
End
go

SET QUOTED_IDENTIFIER off
go

CREATE procedure dbo.csw_ListCopyProfileData
	@pnUserIdentityId		int,			-- Mandatory
	@psCulture			nvarchar(10)    = null, -- the language in which output is to be expressed
	@pnCaseKey			int             = null,
	@psProfileKey		        nvarchar(50)    = null,	
	@pbIsSubTypeKeyAdded		bit		= 0,
	@pbIsTitleOrMarkAdded		bit		= 0,	
	@pbIsCaseFamilyAdded		bit		= 0,
	@pbIsBasisAdded			bit		= 0,	
	@pbIsCaseCategoryAdded		bit		= 0,
	@pbIsCaseOfficeAdded		bit		= 0,
	@pbIsNationalPhaseModified	bit		= 0,	-- no longer used
	@pbIsCountrySpecified		bit		= 0,
	@pbIsPropertyTypeSpecified	bit		= 0,
	@pbCalledFromCentura            bit		= 0

-- PROCEDURE :	csw_ListCopyProfileData
-- VERSION :	26
-- DESCRIPTION:	Returns the details of the selected Copy Profile.
-- SCOPE:	Clerical WorkBench

-- MODIFICTIONS :
-- Date		Who	Change	Version	Description
-- ------------	-------	------	-------	----------------------------------------------- 
-- 16 Nov 2007	5704	LP	1	Procedure created
-- 03 Jul 2008  6754	LP      2	Fix PROTECTCOPY logic
-- 29 Jan 2009  6373	LP      3	Return all applicable attributes if no Profile specified
-- 19 Mar 2009  6373	LP      4	Implement translation for descriptions
-- 10 Mar 2010  7946	DV	5	Added Numeric Key column
-- 06 May 2010	9236	DV	6	Modified SP to return all profile attributes to match it with C/S logic
-- 27 Aug 2010	9625	LP	7	Fix issue of Case Type being returned in Case Category field.
-- 27 Jan 2011  10027	LP	8	Fix localisation label for copy profile attributes.
-- 26 May 2011  10640	DV	9	Pass the ProfileKey as null if the attribute does not exists in the ProfileName
-- 07 Jun 2011	10786	LP	10	Fix issue of OfficialNumber attributes being returned twice.
-- 14 Jun 2011  100548	DV	11	Fix localisation label for copy profile attributes.
-- 07 Jul 2011	10830	DL	12	Specify database collation default to temp table columns of type varchar, nvarchar and char
-- 26 Jul 2011	100361	MF	13	Case Attributes are lost in copy case for Designated Countries Cases
-- 24 Aug 2011	11121	LP	14	Fix issue of Case Event rows not being displayed as options to be copied.
--					Set Case Type to be selected by default regardless of PROTECTCOPY flag
--					Only display Country and Property Type if not already specified (from New Case)
-- 17 Aug 2011  10296   DV      14      Return Replacement Data for all valid Attributes if Profile name is selected
-- 19 Oct 2011	R10425	LP	15	Return CaseEvents against Copy Profile even if ImportanceLevel is not 9
-- 10 Nov 2011	R11462	LP	16	Display copy attribute regardless of the parent case, as long as it has Replacement Data
--					This only applies if Copy Profile has been selected.
-- 07 Dec 2011	R11462	LP	17	Allow copying of SERVPERFORMEDIN
-- 30 Dec 2011	R11746	LP	18	Use specified copy profile regardless of @pbIsNationalPhaseModified flag.
-- 13 Feb 2012	R11772	LP	19	Leave SEQUENCENO as NULL instead of defaulting to 1.
--					This was previously causing duplicate relationships being created.
-- 30 Jul 2014	R37850	JD	20	DR-6054 A default copy profile for Maketing events to be provided
-- 20 Oct 2015	R43744	DV	21	Added logic to listed for being copied.
-- 02 Nov 2015	R53910	vql	22	Adjust formatted names logic (DR-15543).
-- 20 Jan 2016	R55493	MF	23	Cater for PROFITECENTRECODE column to be copied for CASES.
-- 26 Jul 2016	R64247	vql	24	Copy profile displays fewer fields after upgrade (DR-23064).
-- 24 Aug 2016	62043	MF	25	Table Attribute is not being returned even though it is in the Copy Profile.
-- 04 Sep 2019	DR-47583 BS	26	Optimized the procedure by implementing changes suggested in DR-47583.
--                              Function fn_FormatFullName directly used instead of calling it through fn_FormatNameUsingNameNo
--                              Instead of UNION, stored the results directly in temp table and made DISTINCT at the end.
--                              Created temp tables for the most frequently used tables 
as


CREATE TABLE #COPYPROFILE_TEMP ( 
	SELECTED		decimal(1,0), 
	FA_DESCRIPTION		nvarchar(254)	collate database_default, 
	FUNCTIONAREA		nvarchar(254)	collate database_default, 
	CA_DESCRIPTION		nvarchar(254)	collate database_default NULL, 
	COPYAREA		nvarchar(254)	collate database_default NULL, 
	REPLACEMENTDATAKEY	nvarchar(254)	collate database_default NULL, 
	REPLACEMENTDATA		nvarchar(254)	collate database_default NULL, 
	PROTECTCOPY		decimal(1,0)	NULL , 
	SEQUENCENO		nvarchar(3)	collate database_default NULL,
	NUMERICKEY		int		NULL,
	PROFILENAME		nvarchar(50)	collate database_default NULL)

SELECT * INTO #CASES_TMP FROM CASES WHERE CASEID = @pnCaseKey
SELECT * INTO #PROPERTY_TMP FROM PROPERTY WHERE CASEID = @pnCaseKey
SELECT * INTO #MARKETING_TMP FROM MARKETING WHERE CASEID = @pnCaseKey


-- Declarations
Declare	@nErrorCode		int
Declare @sSQLString		nvarchar(4000)
Declare @sLookupCulture		nvarchar(10)

Set @nErrorCode=0
Set @sLookupCulture = dbo.fn_GetLookupCulture(@psCulture, null, 0)

-- CA_DESCRIPTION should contain WB Resource Ids corresponding to the CASE table column

If @psProfileKey is not null
and @psProfileKey <> ''
and @nErrorCode=0
Begin
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        -- Case Information
        SELECT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Case Information', 'CopyArea_CASES', 'Case_CaseCategory', 'CASECATEGORY', 
        CC.CASECATEGORY, dbo.fn_GetTranslation(CC.CASECATEGORYDESC, null, CC.CASECATEGORYDESC_TID, @sLookupCulture), ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
        FROM	#CASES_TMP  C
        left join COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'CASES' and P.CHARACTERKEY = 'CASECATEGORY')
        left join CASECATEGORY CC on (CC.CASECATEGORY = P.REPLACEMENTDATA
				  and CC.CASETYPE     = C.CASETYPE)
        WHERE @pbIsCaseCategoryAdded = 0
        and (C.CASECATEGORY IS NOT NULL OR P.REPLACEMENTDATA IS NOT NULL)
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 0

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT 1, 'Case Information', 'CopyArea_CASES', 'Case_CaseType', 'CASETYPE', 
        CT.CASETYPE, dbo.fn_GetTranslation(CT.CASETYPEDESC, null, CT.CASETYPEDESC_TID, @sLookupCulture), ISNULL(P.PROTECTCOPY,0),P.SEQUENCENO, NULL, P.PROFILENAME
        FROM	#CASES_TMP  C
        left join COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'CASES' and P.CHARACTERKEY = 'CASETYPE')
        left join CASETYPE CT on (CT.CASETYPE= P.REPLACEMENTDATA)
        WHERE	 
        (C.CASETYPE IS NOT NULL OR P.REPLACEMENTDATA IS NOT NULL)
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 0

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Case Information', 'CopyArea_CASES', 'Case_IntClasses', 'INTCLASSES', NULL, 
		P.REPLACEMENTDATA, ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
        FROM	#CASES_TMP  C
        left join	COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'CASES' and P.CHARACTERKEY = 'INTCLASSES')
        WHERE	
        (C.INTCLASSES IS NOT NULL OR P.REPLACEMENTDATA IS NOT NULL)
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 0

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Case Information', 'CopyArea_CASES', 'Case_LocalClasses', 'LOCALCLASSES', NULL, 
		P.REPLACEMENTDATA, ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
        FROM	#CASES_TMP  C
        left join	COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'CASES' and P.CHARACTERKEY = 'LOCALCLASSES')
        WHERE	
        (C.LOCALCLASSES IS NOT NULL OR P.REPLACEMENTDATA IS NOT NULL)
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 0

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Case Information', 'CopyArea_CASES', 'Case_LocalClientFlag', 'LOCALCLIENTFLAG', NULL, 
		P.REPLACEMENTDATA, ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
        FROM	#CASES_TMP  C
        left join	COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'CASES' and P.CHARACTERKEY = 'LOCALCLIENTFLAG')
        WHERE	
        (C.LOCALCLIENTFLAG IS NOT NULL OR P.REPLACEMENTDATA IS NOT NULL) 
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 0

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Case Information', 'CopyArea_CASES', 'Case_NumberOfClasses', 'NOOFCLASSES', NULL, P.REPLACEMENTDATA, 
		ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
        FROM	#CASES_TMP  C
        left join	COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'CASES' and P.CHARACTERKEY = 'NOOFCLASSES')
        WHERE	
        (C.NOOFCLASSES IS NOT NULL OR P.REPLACEMENTDATA IS NOT NULL) 
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 0

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
	SELECT DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Case Information', 'CopyArea_CASES', 'Case_ShortTitle', 'TITLE', NULL, 
	        P.REPLACEMENTDATA, ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
	FROM	#CASES_TMP  C
	left join	COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'CASES' and P.CHARACTERKEY = 'TITLE')
	WHERE	@pbIsTitleOrMarkAdded = 0
	and (C.TITLE IS NOT NULL OR P.REPLACEMENTDATA IS NOT NULL) 
	and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 0
				

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Case Information', 'CopyArea_CASES', 'Case_TypeOfMark', 'TYPEOFMARK', 
                P.REPLACEMENTDATA,dbo.fn_GetTranslation(T.DESCRIPTION, null, T.DESCRIPTION_TID, @sLookupCulture), ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
        FROM	#CASES_TMP  C
        left join	COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'CASES' and P.CHARACTERKEY = 'TYPEOFMARK')
        left join       TABLECODES T on (T.TABLETYPE = 51 and T.TABLECODE = P.REPLACEMENTDATA)
        WHERE	
        (C.TYPEOFMARK IS NOT NULL OR P.REPLACEMENTDATA IS NOT NULL) 
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 0
		
		
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
	SELECT DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Case Information', 'CopyArea_CASES', 'Case_SubType', 'SUBTYPE', 
	        P.REPLACEMENTDATA, dbo.fn_GetTranslation(S.SUBTYPEDESC, null, S.SUBTYPEDESC_TID, @sLookupCulture), ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
	FROM	#CASES_TMP  C
	left join	COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'CASES' and P.CHARACTERKEY = 'SUBTYPE')
	left join       SUBTYPE S on (S.SUBTYPE = P.REPLACEMENTDATA)
	WHERE	@pbIsSubTypeKeyAdded = 0
	and (C.SUBTYPE IS NOT NULL OR P.REPLACEMENTDATA IS NOT NULL) 
	and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 0
		

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        -- always checked by default
        SELECT DISTINCT 1, 'Case Information', 'CopyArea_CASES', 'Case_PropertyType', 'PROPERTYTYPE', 
                P.REPLACEMENTDATA, dbo.fn_GetTranslation(PT.PROPERTYNAME, null, PT.PROPERTYNAME_TID, @sLookupCulture), ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
        FROM #CASES_TMP C
        left join COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'CASES' and P.CHARACTERKEY = 'PROPERTYTYPE')
        left join PROPERTYTYPE PT on (PT.PROPERTYTYPE = P.REPLACEMENTDATA)
        WHERE @pbIsPropertyTypeSpecified = 0 
        and (C.PROPERTYTYPE IS NOT NULL OR P.REPLACEMENTDATA IS NOT NULL) 
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 0

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Case Information', 'CopyArea_CASES', 'Case_FamilyReference', 'FAMILY',  
	        P.REPLACEMENTDATA,dbo.fn_GetTranslation(CF.FAMILYTITLE, null, CF.FAMILYTITLE_TID, @sLookupCulture), ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
        FROM	#CASES_TMP  C
        left join	COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'CASES' and P.CHARACTERKEY = 'FAMILY')
        left join       CASEFAMILY CF on (CF.FAMILY = P.REPLACEMENTDATA)
        WHERE @pbIsCaseFamilyAdded = 0
        and (C.FAMILY IS NOT NULL OR P.REPLACEMENTDATA IS NOT NULL) 
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)		
		and isnull(P.CRMONLY,0) = 0

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        -- always checked by default
        SELECT DISTINCT 1, 'Case Information', 'CopyArea_CASES', 'Case_Country', 'COUNTRYCODE',  
	        P.REPLACEMENTDATA, CT.COUNTRY, ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
        FROM	#CASES_TMP  C
        left join	COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'CASES' and P.CHARACTERKEY = 'COUNTRYCODE')
        left join       COUNTRY CT on (CT.COUNTRYCODE = P.REPLACEMENTDATA)
        WHERE @pbIsCountrySpecified = 0
        and (C.COUNTRYCODE IS NOT NULL OR P.REPLACEMENTDATA IS NOT NULL) 
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 0

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Case Information', 'CopyArea_CASES', 'Case_Status', 'STATUSCODE', P.REPLACEMENTDATA, 
        dbo.fn_GetTranslation(S.INTERNALDESC, null, S.INTERNALDESC_TID, @sLookupCulture), ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
        FROM #CASES_TMP C
        left join COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'CASES' and P.CHARACTERKEY = 'STATUSCODE')
        left join STATUS S on (S.STATUSCODE = P.REPLACEMENTDATA)
        WHERE	
        (C.STATUSCODE IS NOT NULL OR P.REPLACEMENTDATA IS NOT NULL) 
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 0

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Case Information', 'CopyArea_CASES', 'Case_Stem', 'STEM', NULL, 
		P.REPLACEMENTDATA, ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
        FROM	#CASES_TMP  C
        left join	COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'CASES' and P.CHARACTERKEY = 'STEM')
        WHERE	
        (C.STEM IS NOT NULL OR P.REPLACEMENTDATA IS NOT NULL) 
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 0

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Case Information', 'CopyArea_CASES', 'Case_TaxCode', 'TAXCODE', NULL, 
		P.REPLACEMENTDATA, ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
        FROM	#CASES_TMP  C
        left join	COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'CASES' and P.CHARACTERKEY = 'TAXCODE')
        WHERE	
        C.TAXCODE IS NOT NULL 
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 0

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Case Information', 'CopyArea_CASES', 'Case_StateTaxCode', 'STATETAXCODE', 
	        P.REPLACEMENTDATA, dbo.fn_GetTranslation(TR.DESCRIPTION, null, TR.DESCRIPTION_TID, @sLookupCulture), ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
        FROM	#CASES_TMP  C
        left join	COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'CASES' and P.CHARACTERKEY = 'STATETAXCODE')
        left join       TAXRATES TR on (TR.TAXCODE = P.REPLACEMENTDATA)
        WHERE	
        (C.STATETAXCODE IS NOT NULL OR P.REPLACEMENTDATA IS NOT NULL) 
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 0

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Case Information', 'CopyArea_CASES', 'Case_Office', 'OFFICEID',  
	        P.REPLACEMENTDATA, dbo.fn_GetTranslation(O.DESCRIPTION, null, O.DESCRIPTION_TID, @sLookupCulture), ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
        FROM	#CASES_TMP  C
        left join	COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'CASES' and P.CHARACTERKEY = 'OFFICEID')
        left join       OFFICE O on (O.OFFICEID = P.REPLACEMENTDATA)
        WHERE @pbIsCaseOfficeAdded = 0 
        and (C.OFFICEID IS NOT NULL OR P.REPLACEMENTDATA IS NOT NULL) 
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 0

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Case Information', 'CopyArea_CASES', 'Case_Predecessor', 'PREDECESSORID', NULL, 
		P.REPLACEMENTDATA, ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
        FROM	#CASES_TMP  C
        left join	COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'CASES' and P.CHARACTERKEY = 'PREDECESSORID')
        WHERE	
        (C.PREDECESSORID IS NOT NULL OR P.REPLACEMENTDATA IS NOT NULL) 
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 0

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Case Information', 'CopyArea_CASES', 'Case_EntitySize', 'ENTITYSIZE',  
	        P.REPLACEMENTDATA,dbo.fn_GetTranslation(T.DESCRIPTION, null, T.DESCRIPTION_TID, @sLookupCulture), ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
        FROM	#CASES_TMP  C
        left join	COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'CASES' and P.CHARACTERKEY = 'ENTITYSIZE')
        left join       TABLECODES T on (T.TABLETYPE = 26 and T.TABLECODE = P.REPLACEMENTDATA)
        WHERE	
        (C.ENTITYSIZE IS NOT NULL OR P.REPLACEMENTDATA IS NOT NULL) 
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 0

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Case Information', 'CopyArea_CASES', 'Case_PurchaseOrderNo', 'PURCHASEORDERNO', NULL, 
		P.REPLACEMENTDATA, ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
        FROM	#CASES_TMP  C
        left join	COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'CASES' and P.CHARACTERKEY = 'PURCHASEORDERNO')
        WHERE	
        (C.PURCHASEORDERNO IS NOT NULL OR P.REPLACEMENTDATA IS NOT NULL) 
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 0

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Case Information', 'CopyArea_CASES', 'Case_NoInSeries', 'NOINSERIES', NULL, 
		P.REPLACEMENTDATA, ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
        FROM	#CASES_TMP  C
        left join	COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'CASES' and P.CHARACTERKEY = 'NOINSERIES')
        WHERE	
         (C.NOINSERIES IS NOT NULL OR P.REPLACEMENTDATA IS NOT NULL) 
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 0

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Case Information', 'CopyArea_CASES', 'Case_FileCover', 'FILECOVER', NULL, 
		P.REPLACEMENTDATA, ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
        FROM	#CASES_TMP  C
        left join	COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'CASES' and P.CHARACTERKEY = 'FILECOVER')
        WHERE	
         (C.FILECOVER IS NOT NULL OR P.REPLACEMENTDATA IS NOT NULL) 
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
 		and isnull(P.CRMONLY,0) = 0

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Case Information', 'CopyArea_CASES', 'Case_ProfitCentreCode', 'PROFITCENTRECODE', NULL, 
		P.REPLACEMENTDATA, ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
        FROM	#CASES_TMP  C
        left join	COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'CASES' and P.CHARACTERKEY = 'PROFITCENTRECODE')
        WHERE	
         (C.PROFITCENTRECODE IS NOT NULL OR P.REPLACEMENTDATA IS NOT NULL) 
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
 		and isnull(P.CRMONLY,0) = 0
       
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Case Information', 'CopyArea_CASES', 'Name_ServPerforemedIn', 'SERVPERFORMEDIN', NULL, 
		P.REPLACEMENTDATA, ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
        FROM	#CASES_TMP  C
        left join	COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'CASES' and P.CHARACTERKEY = 'SERVPERFORMEDIN')
        WHERE	
         (C.SERVPERFORMEDIN IS NOT NULL OR P.REPLACEMENTDATA IS NOT NULL) 
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 0

         -- CASE TEXT
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT	DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Texttype', 'CopyArea_CASETEXT',
        dbo.fn_GetTranslation(T.TEXTDESCRIPTION, null, T.TEXTDESCRIPTION_TID, @sLookupCulture),
        T.TEXTTYPE, NULL, NULL, ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME        
        FROM	CASETEXT CT,  	TEXTTYPE T  
        left join	COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'CASETEXT' and T.TEXTTYPE = P.CHARACTERKEY)
        WHERE	CT.CASEID =  @pnCaseKey  
        and CT.TEXTTYPE = T.TEXTTYPE    
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 0

        -- OFFICIAL NUMBERS
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT	DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Official Number', 'CopyArea_OFFICIALNUMBERS', 
        dbo.fn_GetTranslation(N.DESCRIPTION, null, N.DESCRIPTION_TID, @sLookupCulture), 
        N.NUMBERTYPE, NULL, NULL, ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME        
        FROM	NUMBERTYPES N,  	OFFICIALNUMBERS OFFNUM  
        left join	COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'OFFICIALNUMBERS' and P.CHARACTERKEY = OFFNUM.NUMBERTYPE)
        WHERE	OFFNUM.CASEID = @pnCaseKey  
        AND OFFNUM.NUMBERTYPE = N.NUMBERTYPE  
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 0

        -- KEYWORDS
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Keywords', 'CopyArea_CASEWORDS', NULL, NULL, NULL, NULL, ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME    
        FROM	CASEWORDS C 
        left join	COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'CASEWORDS')
        WHERE	C.CASEID =  @pnCaseKey 
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 0

        -- CASE LOCATION
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT 	DISTINCT  CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Case Location', 'CopyArea_CASELOCATION', 'Case_FileLocation', NULL, NULL, NULL, ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME    
        FROM	CASELOCATION C 
        left join	COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'CASELOCATION')
        WHERE	C.CASEID =  @pnCaseKey
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 0

	-- CASE IMAGE
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Case Image', 'CopyArea_CASEIMAGE', NULL, NULL, NULL, 
		P.REPLACEMENTDATA, ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
        FROM	CASEIMAGE CI
        left join	COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'CASEIMAGE')
        WHERE	CASEID = @pnCaseKey 
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 0

        -- CASE NAME
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
    SELECT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Nametype', 'CopyArea_CASENAME', 
        dbo.fn_GetTranslation(N.DESCRIPTION, null, N.DESCRIPTION_TID, @sLookupCulture), 
        N.NAMETYPE, P.REPLACEMENTDATA,  dbo.fn_FormatFullName(NA.NAME, NA.FIRSTNAME, NA.MIDDLENAME, NA.SUFFIX, NA.TITLE, null),
        ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME       
        FROM	CASENAME CN
        join NAMETYPE N on(N.NAMETYPE=CN.NAMETYPE)
	left join COPYPROFILE P on (P.PROFILENAME = @psProfileKey and P.COPYAREA = 'CASENAME' and N.NAMETYPE = P.CHARACTERKEY)
	left join NAME NA on (NA.NAMENO = P.REPLACEMENTDATA)
        WHERE	(CN.CASEID =  @pnCaseKey)		
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 0
	
    INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
    SELECT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Nametype', 'CopyArea_CASENAME', 
        dbo.fn_GetTranslation(N.DESCRIPTION, null, N.DESCRIPTION_TID, @sLookupCulture), 
        N.NAMETYPE, P.REPLACEMENTDATA,  dbo.fn_FormatFullName(NA.NAME, NA.FIRSTNAME, NA.MIDDLENAME, NA.SUFFIX, NA.TITLE, null),
        ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME       
      FROM COPYPROFILE P 
        join NAME NA on (NA.NAMENO = P.REPLACEMENTDATA)
        join NAMETYPE N on N.NAMETYPE = P.CHARACTERKEY
        WHERE	P.REPLACEMENTDATA IS NOT NULL
           and (P.PROFILENAME = @psProfileKey and P.COPYAREA = 'CASENAME')
           and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		    and isnull(P.CRMONLY,0) = 0

        -- RELATIONSHIP
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT	DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Relationship', 'CopyArea_RELATEDCASE', 
        dbo.fn_GetTranslation(CR.RELATIONSHIPDESC, null, CR.RELATIONSHIPDESC_TID, @sLookupCulture), 
        CR.RELATIONSHIP, NULL, NULL,ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME       
        FROM CASERELATION CR
        join RELATEDCASE RC	on (RC.RELATIONSHIP = CR.RELATIONSHIP
				and RC.CASEID =  @pnCaseKey)
	left join COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'RELATEDCASE' and RC.RELATIONSHIP = P.CHARACTERKEY)
        WHERE	CR.SHOWFLAG = 1 
        AND	CR.RELATIONSHIP NOT LIKE 'DC%' 
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 0

        -- ACTION
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT 	1, 'Create Action', 'CopyArea_ACTIONS',
        dbo.fn_GetTranslation(A.ACTIONNAME, null, A.ACTIONNAME_TID, @sLookupCulture),  	
        A.ACTION,  	NULL,  	NULL,  	0, P.SEQUENCENO, NULL, P.PROFILENAME    
        FROM	ACTIONS A  
        left join	COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'ACTIONS')
        WHERE	A.ACTION =  P.CHARACTERKEY
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 0

         -- TABLE ATTRIBUTES
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT	DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Table Attributes', 'CopyArea_TABLEATTRIBUTES',
        dbo.fn_GetTranslation(T.TABLENAME, null, T.TABLENAME_TID, @sLookupCulture),
        cast(T.TABLETYPE as nvarchar), NULL, NULL, ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME        
        FROM TABLEATTRIBUTES TA
        join TABLETYPE T  on (T.TABLETYPE=TA.TABLETYPE)
        left join COPYPROFILE P on (P.PROFILENAME = @psProfileKey   
				and P.COPYAREA = 'TABLEATTRIBUTES' 
				and isnull(P.NUMERICKEY,TA.TABLETYPE)=TA.TABLETYPE)
        WHERE	TA.GENERICKEY = cast(@pnCaseKey as nvarchar)
        and	TA.PARENTTABLE='CASES'   
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 0

        -- PROPERTY INFORMATION
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        Select DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Property Information', 'CopyArea_PROPERTY', 'Case_ApplicationBasis', 'BASIS', 
                P.REPLACEMENTDATA, dbo.fn_GetTranslation(B.BASISDESCRIPTION, null, B.BASISDESCRIPTION_TID, @sLookupCulture), ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
        From #PROPERTY_TMP PR
        left join COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'PROPERTY' and P.CHARACTERKEY = 'BASIS')
        left join APPLICATIONBASIS B on (B.BASIS= P.REPLACEMENTDATA)
        Where @pbIsBasisAdded = 0
        and (PR.BASIS IS NOT NULL OR P.REPLACEMENTDATA IS NOT NULL)
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null) 
		and isnull(P.CRMONLY,0) = 0

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        Select DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Property Information', 'CopyArea_PROPERTY', 'Case_NoOfClaims', 'NOOFCLAIMS', NULL, P.REPLACEMENTDATA, ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
        From #PROPERTY_TMP PR
        left join COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'PROPERTY' and P.CHARACTERKEY = 'NOOFCLAIMS')
        Where 
        (PR.NOOFCLAIMS IS NOT NULL OR P.REPLACEMENTDATA IS NOT NULL)
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 0

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        Select DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Property Information', 'CopyArea_PROPERTY', 'CaseRenewals_RenewalNotes', 'RENEWALNOTES', NULL, P.REPLACEMENTDATA, ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
        From #PROPERTY_TMP PR
        left join COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'PROPERTY' and P.CHARACTERKEY = 'RENEWALNOTES')
        Where 
        (PR.RENEWALNOTES IS NOT NULL OR P.REPLACEMENTDATA IS NOT NULL)
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 0

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        Select DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Property Information', 'CopyArea_PROPERTY', 'Case_PlaceFirstUsed', 'PLACEFIRSTUSED', NULL, P.REPLACEMENTDATA, ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
        From #PROPERTY_TMP PR
        left join COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'PROPERTY' and P.CHARACTERKEY = 'PLACEFIRSTUSED')
        Where 
        (PR.PLACEFIRSTUSED IS NOT NULL OR P.REPLACEMENTDATA IS NOT NULL)
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 0

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        Select DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Property Information', 'CopyArea_PROPERTY', 'Case_ProposedUse', 'PROPOSEDUSE', NULL, P.REPLACEMENTDATA, ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
        From #PROPERTY_TMP PR
        left join COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'PROPERTY' and P.CHARACTERKEY = 'PROPOSEDUSE')
        Where 
        (PR.PROPOSEDUSE IS NOT NULL OR P.REPLACEMENTDATA IS NOT NULL)
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 0

        -- CASE EVENT
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Event', 'CopyArea_CASEEVENT', 
        dbo.fn_GetTranslation(E.EVENTDESCRIPTION, null, E.EVENTDESCRIPTION_TID, @sLookupCulture), 
        convert(nvarchar(11),E.EVENTNO), NULL, NULL, ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, P.NUMERICKEY, P.PROFILENAME       
        FROM CASEEVENT CE  
        join EVENTS E	on (E.EVENTNO=CE.EVENTNO
			and E.IMPORTANCELEVEL='9'
			and E.EVENTNO NOT IN ( -13,-16,-14 ) )
        left join COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'CASEEVENT' and P.NUMERICKEY = CE.EVENTNO)
        WHERE CE.CASEID = @pnCaseKey       
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
 		and isnull(P.CRMONLY,0) = 0
       
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Event', 'CopyArea_CASEEVENT', 
        dbo.fn_GetTranslation(E.EVENTDESCRIPTION, null, E.EVENTDESCRIPTION_TID, @sLookupCulture), 
        convert(nvarchar(11),E.EVENTNO), NULL, NULL, ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, P.NUMERICKEY, P.PROFILENAME       
        FROM CASEEVENT CE  
        join EVENTS E	on (E.EVENTNO=CE.EVENTNO
			and E.IMPORTANCELEVEL<>'9'
			and E.EVENTNO NOT IN ( -13,-16,-14 ) )
        join COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'CASEEVENT' and P.NUMERICKEY = CE.EVENTNO)
        WHERE CE.CASEID = @pnCaseKey       
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
 		and isnull(P.CRMONLY,0) = 0
       
        -- CHECKLIST
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        Select DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Checklist', 'CopyArea_CASECHECKLIST', 
        dbo.fn_GetTranslation(C.CHECKLISTDESC, null, C.CHECKLISTDESC_TID, @sLookupCulture), 
        convert(nvarchar(6),CC.CHECKLISTTYPE), NULL, NULL, ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, P.NUMERICKEY, P.PROFILENAME
        From CASECHECKLIST CC
        join CHECKLISTS C on (C.CHECKLISTTYPE=CC.CHECKLISTTYPE)
        left join COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'CASECHECKLIST' and CC.CHECKLISTTYPE = P.NUMERICKEY)
        Where CC.CASEID = @pnCaseKey 
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 0
		
	 -- INSTRUCTIONS
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        Select DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Instructions', 'CopyArea_INSTRUCTIONS', 
        dbo.fn_GetTranslation(IT.INSTRTYPEDESC, null, IT.INSTRTYPEDESC_TID, @sLookupCulture), 
        I.INSTRUCTIONTYPE, NULL, NULL, ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, P.NUMERICKEY, P.PROFILENAME
        From NAMEINSTRUCTIONS NI
        join INSTRUCTIONS I on (I.INSTRUCTIONCODE=NI.INSTRUCTIONCODE)
        join INSTRUCTIONTYPE IT on (IT.INSTRUCTIONTYPE = I.INSTRUCTIONTYPE)
        left join COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'INSTRUCTIONS' and IT.INSTRUCTIONTYPE = P.CHARACTERKEY)
        Where NI.CASEID = @pnCaseKey 
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 0
        
		-- CRM

		-- MARKETING

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
		SELECT DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Marketing Activity Information', 'CopyArea_MARKETING', 'MarketingActivity_ActualCost', 'ACTUALCOST', NULL, 
		P.REPLACEMENTDATA, ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
        FROM	#MARKETING_TMP  M
        left join	COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'MARKETING' and P.CHARACTERKEY = 'ACTUALCOST')
        WHERE	
        (M.ACTUALCOST IS NOT NULL OR P.REPLACEMENTDATA IS NOT NULL)
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 1

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
		SELECT DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Marketing Activity Information', 'CopyArea_MARKETING', 'MarketingActivity_ActualCostCurrency', 'ACTUALCOSTCURRENCY', NULL, 
		P.REPLACEMENTDATA, ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
        FROM	#MARKETING_TMP  M
        left join	COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'MARKETING' and P.CHARACTERKEY = 'ACTUALCOSTCURRENCY')
        WHERE	
        (M.ACTUALCOSTCURRENCY IS NOT NULL OR P.REPLACEMENTDATA IS NOT NULL)
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 1

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
		SELECT DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Marketing Activity Information', 'CopyArea_MARKETING', 'MarketingActivity_NumberContacted', 'NUMBERCONTACTED', NULL, 
		P.REPLACEMENTDATA, ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
        FROM	#MARKETING_TMP  M
        left join	COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'MARKETING' and P.CHARACTERKEY = 'NUMBERCONTACTED')
        WHERE	
        (M.NUMBERCONTACTED IS NOT NULL OR P.REPLACEMENTDATA IS NOT NULL)
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 1

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
		SELECT DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Marketing Activity Information', 'CopyArea_MARKETING', 'MarketingActivity_NumberOfResponses', 'NUMBEROFRESPONSES', NULL, 
		P.REPLACEMENTDATA, ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
        FROM	#MARKETING_TMP  M
        left join	COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'MARKETING' and P.CHARACTERKEY = 'NUMBEROFRESPONSES')
        WHERE	
        (M.NUMBEROFRESPONSES IS NOT NULL OR P.REPLACEMENTDATA IS NOT NULL)
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 1

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
		SELECT DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Marketing Activity Information', 'CopyArea_MARKETING', 'MarketingActivity_ActualCostLocal', 'ACTUALCOSTLOCAL', NULL, 
		P.REPLACEMENTDATA, ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
        FROM	#MARKETING_TMP  M
        left join	COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'MARKETING' and P.CHARACTERKEY = 'ACTUALCOSTLOCAL')
        WHERE	
        (M.ACTUALCOSTLOCAL IS NOT NULL OR P.REPLACEMENTDATA IS NOT NULL)
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 1

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
		SELECT DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Marketing Activity Information', 'CopyArea_MARKETING', 'MarketingActivity_ExpectedResponses', 'EXPECTEDRESPONSES', NULL, 
		P.REPLACEMENTDATA, ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
        FROM	#MARKETING_TMP  M
        left join	COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'MARKETING' and P.CHARACTERKEY = 'EXPECTEDRESPONSES')
        WHERE	
        (M.EXPECTEDRESPONSES IS NOT NULL OR P.REPLACEMENTDATA IS NOT NULL)
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 1

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
		SELECT DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Marketing Activity Information', 'CopyArea_MARKETING', 'MarketingActivity_StaffAttended', 'STAFFATTENDED', NULL, 
		P.REPLACEMENTDATA, ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
        FROM	#MARKETING_TMP  M
        left join	COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'MARKETING' and P.CHARACTERKEY = 'STAFFATTENDED')
        WHERE	
        (M.STAFFATTENDED IS NOT NULL OR P.REPLACEMENTDATA IS NOT NULL)
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 1

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
		SELECT DISTINCT CASE WHEN P.PROTECTCOPY IS NOT NULL THEN 1 ELSE 0 END, 'Marketing Activity Information', 'CopyArea_MARKETING', 'MarketingActivity_ContactsAttended', 'CONTACTSATTENDED', NULL, 
		P.REPLACEMENTDATA, ISNULL(P.PROTECTCOPY,0), P.SEQUENCENO, NULL, P.PROFILENAME
        FROM	#MARKETING_TMP  M
        left join	COPYPROFILE P on (P.PROFILENAME = @psProfileKey   and P.COPYAREA = 'MARKETING' and P.CHARACTERKEY = 'CONTACTSATTENDED')
        WHERE	
        (M.CONTACTSATTENDED IS NOT NULL OR P.REPLACEMENTDATA IS NOT NULL)
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)
		and isnull(P.CRMONLY,0) = 1

	Set @nErrorCode=@@Error
End
Else If @nErrorCode=0
Begin
        INSERT INTO #COPYPROFILE_TEMP (SELECTED, FA_DESCRIPTION, FUNCTIONAREA, CA_DESCRIPTION, COPYAREA, REPLACEMENTDATAKEY, REPLACEMENTDATA, PROTECTCOPY, SEQUENCENO, NUMERICKEY, PROFILENAME)  
        -- Case Information
        SELECT DISTINCT 0, 'Case Information', 'CopyArea_CASES', 'Case_CaseCategory', 'CASECATEGORY', CC.CASECATEGORY, 
        dbo.fn_GetTranslation(CC.CASECATEGORYDESC, null, CC.CASECATEGORYDESC_TID, @sLookupCulture), 0, 1, null, NULL
        FROM #CASES_TMP C
        join CASECATEGORY CC	on (CC.CASECATEGORY = C.CASECATEGORY
				and CC.CASETYPE     = C.CASETYPE)
        WHERE @pbIsCaseCategoryAdded = 0
        and C.CASECATEGORY IS NOT NULL       

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT 1, 'Case Information', 'CopyArea_CASES', 'Case_CaseType', 'CASETYPE', CT.CASETYPE, 
        dbo.fn_GetTranslation(CT.CASETYPEDESC, null, CT.CASETYPEDESC_TID, @sLookupCulture), 1, 1, null, NULL
        FROM	#CASES_TMP  C
        left join CASETYPE CT on (CT.CASETYPE= C.CASETYPE)
        WHERE	
        C.CASETYPE IS NOT NULL 
        and CT.CASETYPE = C.CASETYPE
       
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        -- always checked by default
        SELECT DISTINCT 1, 'Case Information', 'CopyArea_CASES', 'Case_PropertyType', 'PROPERTYTYPE', NULL, NULL, 1, 1, NULL, NULL
        FROM #CASES_TMP C
        WHERE	@pbIsPropertyTypeSpecified = 0 
        and C.PROPERTYTYPE IS NOT NULL
        
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT 0, 'Case Information', 'CopyArea_CASES', 'Case_IntClasses', 'INTCLASSES', NULL, NULL, 0, 1, NULL, NULL
        FROM	#CASES_TMP  C
        WHERE	
        C.INTCLASSES IS NOT NULL 

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT 0, 'Case Information', 'CopyArea_CASES', 'Case_LocalClasses', 'LOCALCLASSES', NULL, NULL, 0, 1, NULL, NULL
        FROM	#CASES_TMP  C
        WHERE	
        C.LOCALCLASSES IS NOT NULL 

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT 0, 'Case Information', 'CopyArea_CASES', 'Case_LocalClientFlag', 'LOCALCLIENTFLAG', NULL, NULL, 0, 1, NULL, NULL
        FROM	#CASES_TMP  C
        WHERE	
        C.LOCALCLIENTFLAG IS NOT NULL 

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT 0, 'Case Information', 'CopyArea_CASES', 'Case_NumberOfClasses', 'NOOFCLASSES', NULL, NULL, 0, 1, NULL, NULL
        FROM	#CASES_TMP  C
        WHERE	
        C.NOOFCLASSES IS NOT NULL 
        
		
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
	SELECT DISTINCT 0, 'Case Information', 'CopyArea_CASES', 'Case_ShortTitle', 'TITLE', NULL, NULL, 0, 1, NULL, NULL
	FROM	#CASES_TMP  C
	WHERE 	@pbIsTitleOrMarkAdded = 0
	and C.TITLE IS NOT NULL 
	

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT 0, 'Case Information', 'CopyArea_CASES', 'Case_TypeOfMark', 'TYPEOFMARK', NULL, NULL, 0, 1, NULL, NULL
        FROM	#CASES_TMP  C
        WHERE	
        C.TYPEOFMARK IS NOT NULL 

		
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
	SELECT DISTINCT 0, 'Case Information', 'CopyArea_CASES', 'Case_SubType', 'SUBTYPE', NULL, NULL, 0, 1, NULL, NULL
	FROM	#CASES_TMP  C
	WHERE	@pbIsSubTypeKeyAdded = 0
	and C.SUBTYPE IS NOT NULL 
		

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT 0, 'Case Information', 'CopyArea_CASES', 'Case_FamilyReference', 'FAMILY', NULL, NULL, 0, 1, NULL, NULL
        FROM	#CASES_TMP  C
        WHERE	@pbIsCaseFamilyAdded = 0
        and C.FAMILY IS NOT NULL 		 

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        -- always checked by default
        SELECT DISTINCT 1, 'Case Information', 'CopyArea_CASES', 'Case_Country', 'COUNTRYCODE', NULL, NULL, 1, 1, NULL, NULL
        FROM	#CASES_TMP  C
        WHERE @pbIsCountrySpecified = 0 
        and C.COUNTRYCODE IS NOT NULL 

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT 0, 'Case Information', 'CopyArea_CASES', 'Case_Status', 'STATUSCODE', NULL, 
        dbo.fn_GetTranslation(S.INTERNALDESC, null, S.INTERNALDESC_TID, @sLookupCulture), 0, 1, NULL, NULL
        FROM #CASES_TMP C
        left join STATUS S on (S.STATUSCODE = C.STATUSCODE)
        WHERE	
        C.STATUSCODE IS NOT NULL 
        and S.STATUSCODE = C.STATUSCODE

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT 0, 'Case Information', 'CopyArea_CASES', 'Case_Stem', 'STEM', NULL, NULL, 0, 1, NULL, NULL
        FROM	#CASES_TMP  C
        WHERE	
        C.STEM IS NOT NULL 

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT 0, 'Case Information', 'CopyArea_CASES', 'Case_TaxCode', 'TAXCODE', NULL, NULL, 0, 1, NULL, NULL
        FROM	#CASES_TMP  C
        WHERE	
        C.TAXCODE IS NOT NULL 

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT 0, 'Case Information', 'CopyArea_CASES', 'Case_StateTaxCode', 'STATETAXCODE', NULL, NULL, 0, 1, NULL, NULL
        FROM	#CASES_TMP  C
        WHERE	
        C.STATETAXCODE IS NOT NULL 

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT 0, 'Case Information', 'CopyArea_CASES', 'Case_Office', 'OFFICEID', NULL, NULL, 0, 1, NULL, NULL
        FROM	#CASES_TMP  C
        WHERE	@pbIsCaseOfficeAdded = 0
        and C.OFFICEID IS NOT NULL 

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT 0, 'Case Information', 'CopyArea_CASES', 'Case_Predecessor', 'PREDECESSORID', NULL, NULL, 0, 1, NULL, NULL
        FROM	#CASES_TMP  C
        WHERE	
        C.PREDECESSORID IS NOT NULL 

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT 0, 'Case Information', 'CopyArea_CASES', 'Case_EntitySize', 'ENTITYSIZE', NULL, NULL, 0, 1, NULL, NULL
        FROM	#CASES_TMP  C
        WHERE	
        C.ENTITYSIZE IS NOT NULL 

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT 0, 'Case Information', 'CopyArea_CASES', 'Case_PurchaseOrderNo', 'PURCHASEORDERNO', NULL, NULL, 0, 1, NULL, NULL
        FROM	#CASES_TMP  C
        WHERE	
        C.PURCHASEORDERNO IS NOT NULL 

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT 0, 'Case Information', 'CopyArea_CASES', 'Case_NoInSeries', 'NOINSERIES', NULL, NULL, 0, 1, NULL, NULL
        FROM	#CASES_TMP  C
        WHERE	
        C.NOINSERIES IS NOT NULL 

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT 0, 'Case Information', 'CopyArea_CASES', 'Case_FileCover', 'FILECOVER', NULL, NULL, 0, 1, NULL, NULL
        FROM	#CASES_TMP  C
        WHERE	
        C.FILECOVER IS NOT NULL

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT 0, 'Case Information', 'CopyArea_CASES', 'Case_ProfitCentreCode', 'PROFITCENTRECODE', NULL, NULL, 0, 1, NULL, NULL
        FROM	#CASES_TMP  C
        WHERE	
        C.PROFITCENTRECODE IS NOT NULL 
        
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT 0, 'Case Information', 'CopyArea_CASES', 'Name_ServPerforemedIn', 'SERVPERFORMEDIN', NULL, NULL, 0, 1, NULL, NULL
        FROM	#CASES_TMP  C
        WHERE	
        C.SERVPERFORMEDIN IS NOT NULL 

         -- CASE TEXT
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT	DISTINCT 0, 'Texttype', 'CopyArea_CASETEXT', 
        dbo.fn_GetTranslation(T.TEXTDESCRIPTION, null, T.TEXTDESCRIPTION_TID, @sLookupCulture), 
        T.TEXTTYPE, NULL, NULL, 0, 1, NULL, NULL    
        FROM	CASETEXT CT,  	TEXTTYPE T
        WHERE	CT.CASEID =  @pnCaseKey  
        and	CT.TEXTTYPE = T.TEXTTYPE    
       
        -- OFFICIAL NUMBERS
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT	0, 'Official Number', 'CopyArea_OFFICIALNUMBERS', 
        dbo.fn_GetTranslation(N.DESCRIPTION, null, N.DESCRIPTION_TID, @sLookupCulture), 
        N.NUMBERTYPE, NULL, NULL, 0, 1, NULL, NULL        
        FROM	NUMBERTYPES N,  OFFICIALNUMBERS OFFNUM  
        WHERE	OFFNUM.CASEID = @pnCaseKey  
        AND OFFNUM.NUMBERTYPE = N.NUMBERTYPE

        -- KEYWORDS
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT 0, 'Keywords', 'CopyArea_CASEWORDS', NULL, NULL, NULL, NULL, 0, 1, NULL, NULL   
        FROM	CASEWORDS C
        WHERE	C.CASEID =  @pnCaseKey

        -- CASE LOCATION
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT 	DISTINCT 0, 'Case Location', 'CopyArea_CASELOCATION', 'Case_FileLocation', NULL, NULL, NULL, 0, 1, NULL, NULL   
        FROM	CASELOCATION C
        WHERE	C.CASEID =  @pnCaseKey

        -- CASE NAME
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT	DISTINCT 0, 'Nametype', 'CopyArea_CASENAME', 
        dbo.fn_GetTranslation(N.DESCRIPTION, null, N.DESCRIPTION_TID, @sLookupCulture), 
        N.NAMETYPE, NULL, NULL, 0, 1, NULL, NULL      
        FROM	CASENAME CN,  	NAMETYPE N 
        WHERE	CN.CASEID =  @pnCaseKey  
        AND	CN.NAMETYPE = N.NAMETYPE 
        
        -- RELATIONSHIP
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT	DISTINCT 0, 'Relationship', 'CopyArea_RELATEDCASE',
        dbo.fn_GetTranslation(CR.RELATIONSHIPDESC, null, CR.RELATIONSHIPDESC_TID, @sLookupCulture) , 
        CR.RELATIONSHIP, NULL, NULL,0, 1, NULL, NULL      
        FROM	CASERELATION CR,  	RELATEDCASE RC  
        WHERE	RC.CASEID =  @pnCaseKey  
        AND	RC.RELATIONSHIP = CR.RELATIONSHIP  
        AND	CR.SHOWFLAG = 1 
        AND	RC.RELATIONSHIP NOT LIKE 'DC%' 
        
        -- ACTION
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT 	DISTINCT 0, 'Create Action',  	'CopyArea_ACTIONS',  	
        dbo.fn_GetTranslation(A.ACTIONNAME, null, A.ACTIONNAME_TID, @sLookupCulture),  	
        A.ACTION,  	NULL,  	NULL,  	ISNULL(P.PROTECTCOPY,0), 1, P.NUMERICKEY, NULL    
        FROM	ACTIONS A, COPYPROFILE P  
        WHERE	(A.ACTION =  '' or A.ACTION is null)
        and P.COPYAREA = 'ACTIONS'
        and P.REPLACEMENTDATA IS NULL
        and (P.STOPCOPY = 0 or  P.STOPCOPY is null)

         -- TABLE ATTRIBUTE
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT	DISTINCT 0, 'Table Attributes', 'CopyArea_TABLEATTRIBUTES', 
        dbo.fn_GetTranslation(T.TABLENAME, null, T.TABLENAME_TID, @sLookupCulture), 
        cast(T.TABLETYPE as nvarchar), NULL, NULL, 0, 1, NULL, NULL    
        FROM TABLEATTRIBUTES TA
	join TABLETYPE T  on (T.TABLETYPE=TA.TABLETYPE)
        WHERE	TA.GENERICKEY = cast(@pnCaseKey as nvarchar)
	and	TA.PARENTTABLE='CASES'    

        -- PROPERTY INFORMATION
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        Select DISTINCT 0, 'Property Information', 'CopyArea_PROPERTY', 'Case_ApplicationBasis', 'BASIS', NULL, NULL, 0, 1, NULL, NULL
        From #PROPERTY_TMP PR
        Where @pbIsBasisAdded = 0
        and PR.BASIS IS NOT NULL 

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        Select DISTINCT 0, 'Property Information', 'CopyArea_PROPERTY', 'Case_NoOfClaims', 'NOOFCLAIMS', NULL, NULL, 0, 1, NULL, NULL
        From #PROPERTY_TMP PR
        Where 
        PR.NOOFCLAIMS IS NOT NULL

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        Select DISTINCT 0, 'Property Information', 'CopyArea_PROPERTY', 'CaseRenewals_RenewalNotes', 'RENEWALNOTES', NULL, NULL, 0, 1, NULL, NULL
        From #PROPERTY_TMP PR
        Where 
        PR.RENEWALNOTES IS NOT NULL

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        Select DISTINCT 0, 'Property Information', 'CopyArea_PROPERTY', 'Case_PlaceFirstUsed', 'PLACEFIRSTUSED', NULL, NULL, 0, 1, NULL, NULL
        From #PROPERTY_TMP PR
        Where 
        PR.PLACEFIRSTUSED IS NOT NULL

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        Select DISTINCT 0, 'Property Information', 'CopyArea_PROPERTY', 'Case_ProposedUse', 'PROPOSEDUSE', NULL, NULL, 0, 1, NULL, NULL
        From #PROPERTY_TMP PR, COPYPROFILE P
        Where 
        PR.PROPOSEDUSE IS NOT NULL
        
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        Select DISTINCT 0, 'Case Image', 'CopyArea_CASEIMAGE', NULL, NULL, NULL, NULL, 0, 1, NULL, NULL
        From CASEIMAGE CI
        Where CI.CASEID = @pnCaseKey
        and CI.IMAGEID IS NOT NULL

        -- CASE EVENT
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT 0, 'Event', 'CopyArea_CASEEVENT', 
        dbo.fn_GetTranslation(E.EVENTDESCRIPTION, null, E.EVENTDESCRIPTION_TID, @sLookupCulture), 
        convert(nvarchar(11),E.EVENTNO), NULL, NULL, 0, 1, E.EVENTNO, NULL      
        FROM EVENTS E, CASEEVENT CE, COPYPROFILE P  
        WHERE CE.CASEID = @pnCaseKey  
        AND	E.EVENTNO = CE.EVENTNO  
        AND	E.IMPORTANCELEVEL = '9'  
        AND	E.EVENTNO NOT IN ( -13,-16,-14 )
        
        -- CHECKLIST
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        Select DISTINCT 0, 'Checklist', 'CopyArea_CASECHECKLIST', 
        dbo.fn_GetTranslation(C.CHECKLISTDESC, null, C.CHECKLISTDESC_TID, @sLookupCulture), 
        convert(nvarchar(6),CC.CHECKLISTTYPE), NULL, NULL, 0, 1, CC.CHECKLISTTYPE, NULL
        From CHECKLISTS C, CASECHECKLIST CC
        Where CC.CASEID = @pnCaseKey
        and CC.CHECKLISTTYPE = C.CHECKLISTTYPE
        
        -- INSTRUCTIONS
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        Select DISTINCT 0, 'Instructions', 'CopyArea_INSTRUCTIONS', 
        dbo.fn_GetTranslation(IT.INSTRTYPEDESC, null, IT.INSTRTYPEDESC_TID, @sLookupCulture), 
        IT.INSTRUCTIONTYPE, NULL, NULL, 0, 1, NULL, NULL
        From NAMEINSTRUCTIONS NI, INSTRUCTIONS I
        join INSTRUCTIONTYPE IT on (IT.INSTRUCTIONTYPE = I.INSTRUCTIONTYPE)
        Where NI.CASEID = @pnCaseKey        
        and NI.INSTRUCTIONCODE = I.INSTRUCTIONCODE

		-- CRM

		-- MARKETING

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT 0, 'Marketing Activity Information', 'CopyArea_MARKETING', 'MarketingActivity_ActualCost', 'ACTUALCOST', NULL, NULL, 0, 1, NULL, NULL
        FROM	#MARKETING_TMP  M
        WHERE	
        M.ACTUALCOST IS NOT NULL 

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT 0, 'Marketing Activity Information', 'CopyArea_MARKETING', 'MarketingActivity_ActualCostCurrency', 'ACTUALCOSTCURRENCY', NULL, NULL, 0, 1, NULL, NULL
        FROM	#MARKETING_TMP  M
        WHERE	
        M.ACTUALCOSTCURRENCY IS NOT NULL 

	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT 0, 'Marketing Activity Information', 'CopyArea_MARKETING', 'MarketingActivity_NumberContacted', 'NUMBERCONTACTED', NULL, NULL, 0, 1, NULL, NULL
        FROM	#MARKETING_TMP  M
        WHERE	
        M.NUMBERCONTACTED IS NOT NULL 
		
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT 0, 'Marketing Activity Information', 'CopyArea_MARKETING', 'MarketingActivity_NumberOfResponses', 'NUMBEROFRESPONSES', NULL, NULL, 0, 1, NULL, NULL
        FROM	#MARKETING_TMP  M
        WHERE	
        M.NUMBEROFRESPONSES IS NOT NULL 
		
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT 0, 'Marketing Activity Information', 'CopyArea_MARKETING', 'MarketingActivity_ActualCostLocal', 'ACTUALCOSTLOCAL', NULL, NULL, 0, 1, NULL, NULL
        FROM	#MARKETING_TMP  M
        WHERE	
        M.ACTUALCOSTLOCAL IS NOT NULL 
		
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT 0, 'Marketing Activity Information', 'CopyArea_MARKETING', 'MarketingActivity_ExpectedResponses', 'EXPECTEDRESPONSES', NULL, NULL, 0, 1, NULL, NULL
        FROM	#MARKETING_TMP  M
        WHERE	
        M.EXPECTEDRESPONSES IS NOT NULL 
		
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT 0, 'Marketing Activity Information', 'CopyArea_MARKETING', 'MarketingActivity_StaffAttended', 'STAFFATTENDED', NULL, NULL, 0, 1, NULL, NULL
        FROM	#MARKETING_TMP  M
        WHERE	
        M.STAFFATTENDED IS NOT NULL 
		
	INSERT INTO #COPYPROFILE_TEMP (SELECTED,  FA_DESCRIPTION,  FUNCTIONAREA,  CA_DESCRIPTION,  COPYAREA,  REPLACEMENTDATAKEY,  REPLACEMENTDATA,  
        PROTECTCOPY, SEQUENCENO, NUMERICKEY,PROFILENAME)  
        SELECT DISTINCT 0, 'Marketing Activity Information', 'CopyArea_MARKETING', 'MarketingActivity_ContactsAttended', 'CONTACTSATTENDED', NULL, NULL, 0, 1, NULL, NULL
        FROM	#MARKETING_TMP  M
        WHERE	
        M.CONTACTSATTENDED IS NOT NULL 

	Set @nErrorCode=@@Error
End

If @nErrorCode=0
Begin
	select DISTINCT
		dbo.fn_StripNonAlphaNumerics(@psProfileKey)+'^'+ dbo.fn_StripNonAlphaNumerics(ISNULL(CA_DESCRIPTION,'')) +'^'+ ISNULL(SEQUENCENO,'')+'^'+ ISNULL(FUNCTIONAREA,'') as RowKey,
		PROFILENAME as ProfileKey,
		ISNULL(SELECTED,0) as IsSelected,
		FUNCTIONAREA as FunctionArea,
		CA_DESCRIPTION as CopyAreaDescription,
		COPYAREA as CopyAreaKey,
		REPLACEMENTDATAKEY as ReplacementDataKey,
		REPLACEMENTDATA as ReplacementData,
		ISNULL(PROTECTCOPY,0) as IsProtected,
		FA_DESCRIPTION as FunctionAreaDescription,
		NUMERICKEY as NumericKey
	 from #COPYPROFILE_TEMP   
	 ORDER BY FA_DESCRIPTION

	Set @nErrorCode=@@Error

	DROP TABLE #COPYPROFILE_TEMP
End

RETURN @nErrorCode
GO

SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

grant execute on dbo.csw_ListCopyProfileData to public
go