//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InprotechKaizen.Model.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CaseResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CaseResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InprotechKaizen.Model.Properties.CaseResources", typeof(CaseResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string ClassesClass {
            get {
                return ResourceManager.GetString("ClassesClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Use.
        /// </summary>
        public static string ClassesFirstUse {
            get {
                return ResourceManager.GetString("ClassesFirstUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Use In Commerce.
        /// </summary>
        public static string ClassesFirstUseInCommerce {
            get {
                return ResourceManager.GetString("ClassesFirstUseInCommerce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International Classes.
        /// </summary>
        public static string ClassesInternationalClass {
            get {
                return ResourceManager.GetString("ClassesInternationalClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-Classes.
        /// </summary>
        public static string ClassesSubClass {
            get {
                return ResourceManager.GetString("ClassesSubClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string ClassesText {
            get {
                return ResourceManager.GetString("ClassesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        public static string ClassesTitle {
            get {
                return ResourceManager.GetString("ClassesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string EventsDate {
            get {
                return ResourceManager.GetString("EventsDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due.
        /// </summary>
        public static string EventsDue {
            get {
                return ResourceManager.GetString("EventsDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurred.
        /// </summary>
        public static string EventsOccurred {
            get {
                return ResourceManager.GetString("EventsOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string EventsTitle {
            get {
                return ResourceManager.GetString("EventsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string NamesAttention {
            get {
                return ResourceManager.GetString("NamesAttention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NamesName {
            get {
                return ResourceManager.GetString("NamesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        public static string NamesReference {
            get {
                return ResourceManager.GetString("NamesReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names.
        /// </summary>
        public static string NamesTitle {
            get {
                return ResourceManager.GetString("NamesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string NamesType {
            get {
                return ResourceManager.GetString("NamesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Variant.
        /// </summary>
        public static string NamesVariant {
            get {
                return ResourceManager.GetString("NamesVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date In Force.
        /// </summary>
        public static string OfficialNumbersDateInForce {
            get {
                return ResourceManager.GetString("OfficialNumbersDateInForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Number.
        /// </summary>
        public static string OfficialNumbersIsCurrent {
            get {
                return ResourceManager.GetString("OfficialNumbersIsCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official No..
        /// </summary>
        public static string OfficialNumbersNo {
            get {
                return ResourceManager.GetString("OfficialNumbersNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official Numbers.
        /// </summary>
        public static string OfficialNumbersTitle {
            get {
                return ResourceManager.GetString("OfficialNumbersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string OfficialNumbersType {
            get {
                return ResourceManager.GetString("OfficialNumbersType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Ref..
        /// </summary>
        public static string RelatedCasesCaseRef {
            get {
                return ResourceManager.GetString("RelatedCasesCaseRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string RelatedCasesCountry {
            get {
                return ResourceManager.GetString("RelatedCasesCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle.
        /// </summary>
        public static string RelatedCasesCycle {
            get {
                return ResourceManager.GetString("RelatedCasesCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string RelatedCasesDate {
            get {
                return ResourceManager.GetString("RelatedCasesDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official No..
        /// </summary>
        public static string RelatedCasesOfficialNo {
            get {
                return ResourceManager.GetString("RelatedCasesOfficialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship.
        /// </summary>
        public static string RelatedCasesRelationship {
            get {
                return ResourceManager.GetString("RelatedCasesRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Cases.
        /// </summary>
        public static string RelatedCasesTitle {
            get {
                return ResourceManager.GetString("RelatedCasesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Preview.
        /// </summary>
        public static string RelatedCasesTitlePreview {
            get {
                return ResourceManager.GetString("RelatedCasesTitlePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaulted From.
        /// </summary>
        public static string StandingInstructionsDefaultedFrom {
            get {
                return ResourceManager.GetString("StandingInstructionsDefaultedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction.
        /// </summary>
        public static string StandingInstructionsInstruction {
            get {
                return ResourceManager.GetString("StandingInstructionsInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction Type.
        /// </summary>
        public static string StandingInstructionsInstructionType {
            get {
                return ResourceManager.GetString("StandingInstructionsInstructionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period 1.
        /// </summary>
        public static string StandingInstructionsPeriod1 {
            get {
                return ResourceManager.GetString("StandingInstructionsPeriod1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period 2.
        /// </summary>
        public static string StandingInstructionsPeriod2 {
            get {
                return ResourceManager.GetString("StandingInstructionsPeriod2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period 3.
        /// </summary>
        public static string StandingInstructionsPeriod3 {
            get {
                return ResourceManager.GetString("StandingInstructionsPeriod3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standing Instructions.
        /// </summary>
        public static string StandingInstructionsTitle {
            get {
                return ResourceManager.GetString("StandingInstructionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string TextLanguage {
            get {
                return ResourceManager.GetString("TextLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string TextText {
            get {
                return ResourceManager.GetString("TextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string TextTitle {
            get {
                return ResourceManager.GetString("TextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TextType {
            get {
                return ResourceManager.GetString("TextType", resourceCulture);
            }
        }
    }
}
