//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InprotechKaizen.Model.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InprotechKaizen.Model.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atlease one option is required.
        /// </summary>
        internal static string AtleastOneOptionRequired {
            get {
                return ResourceManager.GetString("AtleastOneOptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can change your password any time by using the Change Password option in Inprotech..
        /// </summary>
        internal static string CanChangePassword {
            get {
                return ResourceManager.GetString("CanChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basis.
        /// </summary>
        internal static string CaseHeaderBasis {
            get {
                return ResourceManager.GetString("CaseHeaderBasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Category.
        /// </summary>
        internal static string CaseHeaderCaseCategory {
            get {
                return ResourceManager.GetString("CaseHeaderCaseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Reference.
        /// </summary>
        internal static string CaseHeaderCaseReference {
            get {
                return ResourceManager.GetString("CaseHeaderCaseReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Status.
        /// </summary>
        internal static string CaseHeaderCaseStatus {
            get {
                return ResourceManager.GetString("CaseHeaderCaseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Type.
        /// </summary>
        internal static string CaseHeaderCaseType {
            get {
                return ResourceManager.GetString("CaseHeaderCaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        internal static string CaseHeaderClasses {
            get {
                return ResourceManager.GetString("CaseHeaderClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name.
        /// </summary>
        internal static string CaseHeaderClientName {
            get {
                return ResourceManager.GetString("CaseHeaderClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string CaseHeaderCountry {
            get {
                return ResourceManager.GetString("CaseHeaderCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountryAdjective.
        /// </summary>
        internal static string CaseHeaderCountryAdjective {
            get {
                return ResourceManager.GetString("CaseHeaderCountryAdjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentOfficialNumber.
        /// </summary>
        internal static string CaseHeaderCurrentOfficialNumber {
            get {
                return ResourceManager.GetString("CaseHeaderCurrentOfficialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentOfficialNumberType.
        /// </summary>
        internal static string CaseHeaderCurrentOfficialNumberType {
            get {
                return ResourceManager.GetString("CaseHeaderCurrentOfficialNumberType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Size.
        /// </summary>
        internal static string CaseHeaderEntitySize {
            get {
                return ResourceManager.GetString("CaseHeaderEntitySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        internal static string CaseHeaderFamily {
            get {
                return ResourceManager.GetString("CaseHeaderFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Location.
        /// </summary>
        internal static string CaseHeaderFileLocation {
            get {
                return ResourceManager.GetString("CaseHeaderFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Applicant.
        /// </summary>
        internal static string CaseHeaderFirstApplicant {
            get {
                return ResourceManager.GetString("CaseHeaderFirstApplicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Client.
        /// </summary>
        internal static string CaseHeaderLocalClient {
            get {
                return ResourceManager.GetString("CaseHeaderLocalClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string CaseHeaderLocalClientNo {
            get {
                return ResourceManager.GetString("CaseHeaderLocalClientNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string CaseHeaderLocalClientYes {
            get {
                return ResourceManager.GetString("CaseHeaderLocalClientYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No In Series.
        /// </summary>
        internal static string CaseHeaderNoInSeries {
            get {
                return ResourceManager.GetString("CaseHeaderNoInSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Office.
        /// </summary>
        internal static string CaseHeaderOffice {
            get {
                return ResourceManager.GetString("CaseHeaderOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official Numbers.
        /// </summary>
        internal static string CaseHeaderOfficialNumbers {
            get {
                return ResourceManager.GetString("CaseHeaderOfficialNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit Centre.
        /// </summary>
        internal static string CaseHeaderProfitCentre {
            get {
                return ResourceManager.GetString("CaseHeaderProfitCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Type.
        /// </summary>
        internal static string CaseHeaderPropertyType {
            get {
                return ResourceManager.GetString("CaseHeaderPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewal Status.
        /// </summary>
        internal static string CaseHeaderRenewalStatus {
            get {
                return ResourceManager.GetString("CaseHeaderRenewalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string CaseHeaderStatus {
            get {
                return ResourceManager.GetString("CaseHeaderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Type.
        /// </summary>
        internal static string CaseHeaderSubType {
            get {
                return ResourceManager.GetString("CaseHeaderSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string CaseHeaderTitle {
            get {
                return ResourceManager.GetString("CaseHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Mark.
        /// </summary>
        internal static string CaseHeaderTypeOfMark {
            get {
                return ResourceManager.GetString("CaseHeaderTypeOfMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Attorney.
        /// </summary>
        internal static string CaseHeaderWorkingAttorney {
            get {
                return ResourceManager.GetString("CaseHeaderWorkingAttorney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have sufficient privileges to perform this action..
        /// </summary>
        internal static string ErrorSecurityTaskAccessCheckFailure {
            get {
                return ResourceManager.GetString("ErrorSecurityTaskAccessCheckFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State doesn&apos;t exist in the selected Country..
        /// </summary>
        internal static string ErrorStateNotInCountry {
            get {
                return ResourceManager.GetString("ErrorStateNotInCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Access.
        /// </summary>
        internal static string EthicalWallAllowAccess {
            get {
                return ResourceManager.GetString("EthicalWallAllowAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny Access.
        /// </summary>
        internal static string EthicalWallDenyAccess {
            get {
                return ResourceManager.GetString("EthicalWallDenyAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Applicable.
        /// </summary>
        internal static string EthicalWallNotApplicable {
            get {
                return ResourceManager.GetString("EthicalWallNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}.
        /// </summary>
        internal static string ExpiringPasswordGreet {
            get {
                return ResourceManager.GetString("ExpiringPasswordGreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email has been automatically generated. If you require any assistance, contact your system administrator..
        /// </summary>
        internal static string FurtherAssistance {
            get {
                return ResourceManager.GetString("FurtherAssistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Inprotech Team.
        /// </summary>
        internal static string Inprotech {
            get {
                return ResourceManager.GetString("Inprotech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Inprotech password has expired. You will be prompted to change and confirm your password the next time you sign in to Inprotech..
        /// </summary>
        internal static string PasswordExpired {
            get {
                return ResourceManager.GetString("PasswordExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Inprotech password will expire in {0} days..
        /// </summary>
        internal static string PasswordExpiresInDays {
            get {
                return ResourceManager.GetString("PasswordExpiresInDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Inprotech password will expire in {0} day..
        /// </summary>
        internal static string PasswordExpiresInOneDay {
            get {
                return ResourceManager.GetString("PasswordExpiresInOneDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Inprotech password will expire today..
        /// </summary>
        internal static string PasswordExpiresToday {
            get {
                return ResourceManager.GetString("PasswordExpiresToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error querying this data source..
        /// </summary>
        internal static string PriorArtEvidenceFinderError {
            get {
                return ResourceManager.GetString("PriorArtEvidenceFinderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search has taken longer than expected. Please retry..
        /// </summary>
        internal static string PriorArtEvidenceFinderTimedOut {
            get {
                return ResourceManager.GetString("PriorArtEvidenceFinderTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you.
        /// </summary>
        internal static string Regards {
            get {
                return ResourceManager.GetString("Regards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email has been automatically generated. If you require any assistance, contact your system administrator..
        /// </summary>
        internal static string RequireAssistance {
            get {
                return ResourceManager.GetString("RequireAssistance", resourceCulture);
            }
        }
    }
}
