DELETE FROM MODULECONFIGURATION WHERE MODULEID IN (-21)
DELETE FROM PORTALSETTING WHERE MODULEID IN (-21)
DELETE FROM FEATUREMODULE WHERE MODULEID IN (-21)
DELETE FROM MODULE WHERE MODULEID IN (-21)

DELETE FROM FEATURETASK WHERE TASKID IN (32,33)
DELETE FROM TASK WHERE TASKID IN (32,33)