---------------------------------------------------------------------------------------------------------------------------------
-- This script resets the LASTINTERNALCODE table to ensure it accurately reflects the highest code for each table referenced.
---------------------------------------------------------------------------------------------------------------------------------
delete from LASTINTERNALCODE where INTERNALSEQUENCE is null
go

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'ADDRESS')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 	'ADDRESS', isnull(max(ADDRESSCODE),1)
	from 	ADDRESS
else
	Update 	LASTINTERNALCODE 
	set 	INTERNALSEQUENCE= (select max( ADDRESSCODE) from ADDRESS)
	where 	TABLENAME='ADDRESS'
go  
                     
if not exists (select * from LASTINTERNALCODE where TABLENAME = 'CASES')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'CASES', isnull(max(CASEID),1)
	from 	CASES
else
	Update 	LASTINTERNALCODE 
	set 	INTERNALSEQUENCE= (select isnull(max(CASEID),1) from CASES)
	where 	TABLENAME='CASES'
go 

-- sqa20447 - ensure next caseno is > 0 if all existing caseno are negative  or 0
IF (SELECT [INTERNALSEQUENCE] FROM [dbo].[LASTINTERNALCODE] WHERE [TABLENAME] = N'CASES') < 1 
UPDATE [dbo].[LASTINTERNALCODE] 
SET [INTERNALSEQUENCE] = 1 
WHERE 
[TABLENAME] = N'CASES'
GO

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'CHECKLISTS')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'CHECKLISTS', isnull(max(CHECKLISTTYPE),1)
	from 	CHECKLISTS
else
	Update 	LASTINTERNALCODE 
	set 	INTERNALSEQUENCE= (select max( CHECKLISTTYPE ) from CHECKLISTS)
	where 	TABLENAME='CHECKLISTS'
go       
          
if not exists (select * from LASTINTERNALCODE where TABLENAME = 'CORRESPONDTO')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'CORRESPONDTO', isnull(max(CORRESPONDTYPE),600)
	from 	CORRESPONDTO
else
	Update 	LASTINTERNALCODE 
	set 	INTERNALSEQUENCE= (select ISNULL(max( CORRESPONDTYPE ),600) from CORRESPONDTO)
	where 	TABLENAME='CORRESPONDTO'
go      

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'CRITERIA')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	(select 'CRITERIA',	CASE	WHEN max( CRITERIANO ) is null THEN 500
					WHEN max( CRITERIANO ) < 0     THEN 500
		                        ELSE max( CRITERIANO )
				END
	from CRITERIA )
else      
	Update 	LASTINTERNALCODE
	set 	INTERNALSEQUENCE= (select CASE 	WHEN max( CRITERIANO ) is null THEN 500
                                           	WHEN max( CRITERIANO ) < 0     THEN 500
		                                ELSE max( CRITERIANO )
	                              	   END 
				   from CRITERIA)
	where TABLENAME='CRITERIA'
go                     
 
if not exists (select * from LASTINTERNALCODE where TABLENAME = 'DEBTORSTATUS')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 	'DEBTORSTATUS', isnull(max(BADDEBTOR),500)
	from 	DEBTORSTATUS
else 
	Update 	LASTINTERNALCODE
	set 	INTERNALSEQUENCE= (select ISNULL(max( BADDEBTOR ),500) from DEBTORSTATUS)
	where 	TABLENAME='DEBTORSTATUS'
go      

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'DELIVERYMETHOD')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'DELIVERYMETHOD', isnull(max(DELIVERYID),500)
	from DELIVERYMETHOD
else       
	Update 	LASTINTERNALCODE
	set 	INTERNALSEQUENCE= (select ISNULL(max( DELIVERYID ),500) from DELIVERYMETHOD)
	where 	TABLENAME='DELIVERYMETHOD'
go      

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'DOCUMENT')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 	'DOCUMENT', isnull(max(DOCUMENTNO),500)
	from 	DOCUMENT
else     
	Update 	LASTINTERNALCODE
	set 	INTERNALSEQUENCE= (select ISNULL(max( DOCUMENTNO ),500) from DOCUMENT)
	where 	TABLENAME='DOCUMENT'
go        

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'EVENTCATEGORY')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'EVENTCATEGORY', isnull(max(CATEGORYID),500)
	from 	EVENTCATEGORY
else                  
	Update 	LASTINTERNALCODE
	set 	INTERNALSEQUENCE= (select ISNULL(max( CATEGORYID ),500) from EVENTCATEGORY)
	where 	TABLENAME='EVENTCATEGORY'
go      

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'EVENTS')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'EVENTS', isnull(max(EVENTNO),500)
	from 	EVENTS
else                  
	Update 	LASTINTERNALCODE
	set 	INTERNALSEQUENCE= (select ISNULL(max( EVENTNO ),500) from EVENTS)
	where 	TABLENAME='EVENTS'
go      

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'FEELIST')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'FEELIST', isnull(max(FEELISTNO),500)
	from	FEELIST
else
	Update 	LASTINTERNALCODE
	set 	INTERNALSEQUENCE= (select ISNULL(max( FEELISTNO ),500) from FEELIST)
	where 	TABLENAME='FEELIST'
go      

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'IMAGE')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'IMAGE', isnull(max(IMAGEID),500)
	FROM	IMAGE
else
	Update 	LASTINTERNALCODE
	set 	INTERNALSEQUENCE= (select ISNULL(max( IMAGEID ),500) from IMAGE)
	where 	TABLENAME='IMAGE'
go      

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'INSTRUCTIONS')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'INSTRUCTIONS', isnull(max( INSTRUCTIONCODE ),500)
	FROM	INSTRUCTIONS
else                     
	Update 	LASTINTERNALCODE
	set 	INTERNALSEQUENCE= (select ISNULL(max( INSTRUCTIONCODE ),500) from INSTRUCTIONS)
	where 	TABLENAME='INSTRUCTIONS'
go      


if not exists (select * from LASTINTERNALCODE where TABLENAME = 'INTERNALREFSTEM')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'INTERNALREFSTEM', isnull(max( STEMUNIQUENO ),500)
	FROM	INTERNALREFSTEM
else   
	Update LASTINTERNALCODE
	set INTERNALSEQUENCE= (select ISNULL(max( STEMUNIQUENO ),500) from INTERNALREFSTEM)
	where TABLENAME='INTERNALREFSTEM'
go       

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'ITEM')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'ITEM', isnull(max( ITEM_ID ),1)
	FROM	ITEM
else
	Update LASTINTERNALCODE set INTERNALSEQUENCE= (select max( ITEM_ID) from ITEM)
	where TABLENAME='ITEM'
go  

           
if not exists (select * from LASTINTERNALCODE where TABLENAME = 'KEYWORDS')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'KEYWORDS', isnull(max( KEYWORDNO ),500)
	FROM 	KEYWORDS
else  
	Update LASTINTERNALCODE
	set INTERNALSEQUENCE= (select ISNULL(max( KEYWORDNO ),500) from KEYWORDS)
	where TABLENAME='KEYWORDS'
go      
               
if not exists (select * from LASTINTERNALCODE where TABLENAME = 'LANGUAGE')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'LANGUAGE', isnull(max( LANGUAGE_CODE ),500)
	FROM	LANGUAGE
else  
	Update LASTINTERNALCODE
	set INTERNALSEQUENCE= (select ISNULL(max( LANGUAGE_CODE ),500) from LANGUAGE)
	where TABLENAME='LANGUAGE'
go      

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'LETTER')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'LETTER', isnull(max( LETTERNO ),500)
	FROM 	LETTER
else               
	Update LASTINTERNALCODE
	set INTERNALSEQUENCE= (select ISNULL(max( LETTERNO),500) from LETTER)
	where TABLENAME='LETTER'
go      
                   
if not exists (select * from LASTINTERNALCODE where TABLENAME = 'NAME')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'NAME', isnull(max( NAMENO ),500)
	FROM 	NAME
else 
	Update LASTINTERNALCODE
	set INTERNALSEQUENCE= (select ISNULL(max( NAMENO ),500) from NAME)
	where TABLENAME='NAME'
go      

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'NAMEFAMILY')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'NAMEFAMILY', isnull(max( FAMILYNO ),500)
	FROM	NAMEFAMILY
else                  
	Update LASTINTERNALCODE
	set INTERNALSEQUENCE= (select ISNULL(max( FAMILYNO ),500) from NAMEFAMILY)
	where TABLENAME='NAMEFAMILY'
go      

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'NAMEGROUPS')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'NAMEGROUPS', isnull(max( NAMEGROUP ),500)
	FROM 	NAMEGROUPS
else               
	Update LASTINTERNALCODE
	set INTERNALSEQUENCE= (select ISNULL(max( NAMEGROUP ),500) from NAMEGROUPS)
	where TABLENAME='NAMEGROUPS'
go      

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'NARRATIVE')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'NARRATIVE', isnull(max( NARRATIVENO ),500)
	FROM	NARRATIVE
else   
	Update LASTINTERNALCODE
	set INTERNALSEQUENCE= (select ISNULL(max( NARRATIVENO ),500) from NARRATIVE)
	where TABLENAME='NARRATIVE'
go    

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'NARRATIVERULE')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'NARRATIVERULE', isnull(max( NARRATIVERULENO ),500)
	FROM	NARRATIVERULE
else   
	Update LASTINTERNALCODE
	set INTERNALSEQUENCE= (select ISNULL(max( NARRATIVERULENO ),500) from NARRATIVERULE)
	where TABLENAME='NARRATIVERULE'
go      


if not exists (select * from LASTINTERNALCODE where TABLENAME = 'POLICING')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'POLICING', isnull(max( POLICINGSEQNO ),500)
	FROM	POLICING
else               
	Update LASTINTERNALCODE
	set INTERNALSEQUENCE= (select ISNULL(max( POLICINGSEQNO ),500) from POLICING)
	where TABLENAME='POLICING'
go 

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'QUESTION')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'QUESTION', isnull(max( QUESTIONNO ),500)
	FROM 	QUESTION
else  
	Update LASTINTERNALCODE
	set INTERNALSEQUENCE= (select ISNULL(max( QUESTIONNO),500) from QUESTION)
	where TABLENAME='QUESTION'
go     

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'RATES')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'RATES', isnull(max( RATENO ),500)
	FROM	RATES
else                 
	Update LASTINTERNALCODE
	set INTERNALSEQUENCE= (select ISNULL(max( RATENO ),500) from RATES)
	where TABLENAME='RATES'
go 

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'STATUS')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'STATUS', isnull(max( STATUSCODE ),500)
	FROM	STATUS
else                           
	Update LASTINTERNALCODE
	set INTERNALSEQUENCE= (select ISNULL(max( STATUSCODE ),500) from STATUS)
	where TABLENAME='STATUS'
go      

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'TABLECODES')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'TABLECODES', isnull(max( TABLECODE ),500)
	FROM	TABLECODES
else                
	Update LASTINTERNALCODE
	set INTERNALSEQUENCE= (select ISNULL(max( TABLECODE ),500) from TABLECODES)
	where TABLENAME='TABLECODES'
go    

begin
	declare @refno int
	select @refno = (select max( TABLETYPE ) from TABLETYPE)
	if (@refno = NULL or @refno < 5000)
		select @refno = 5000
	if not exists (select * from LASTINTERNALCODE where TABLENAME = 'TABLETYPE')
		INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
		values ('TABLETYPE', @refno )
	else               
	Update LASTINTERNALCODE
	set INTERNALSEQUENCE= @refno where TABLENAME='TABLETYPE'
end
go   

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'TELECOMMUNICATION')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'TELECOMMUNICATION', isnull(max( TELECODE ),500)
	from TELECOMMUNICATION
else              
	Update LASTINTERNALCODE
	set INTERNALSEQUENCE= (select ISNULL(max( TELECODE ),500) from TELECOMMUNICATION)
	where TABLENAME='TELECOMMUNICATION'
go   

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'TIMECOSTING')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'TIMECOSTING', isnull(max( COSTINGSEQNO ),500)
	from	TIMECOSTING
else 
	Update LASTINTERNALCODE
	set INTERNALSEQUENCE= (select ISNULL(max( COSTINGSEQNO ),500) from TIMECOSTING)
	where TABLENAME='TIMECOSTING'
go   

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'TRANSACTIONHEADER')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'TRANSACTIONHEADER', isnull(max( ABS(TRANSNO) ),500)
	FROM	TRANSACTIONHEADER
else             
	Update LASTINTERNALCODE
	set INTERNALSEQUENCE= (select ISNULL(max( ABS(TRANSNO) ),500) from TRANSACTIONHEADER)
	where TABLENAME='TRANSACTIONHEADER'
go  

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'USERQUERY')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'USERQUERY', isnull(max( REFERENCENO ),500)
	FROM 	USERQUERY
else 
	Update LASTINTERNALCODE
	set INTERNALSEQUENCE= (select ISNULL(max( REFERENCENO ),500) from USERQUERY)
	where TABLENAME='USERQUERY'
go 

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'BILLRULE')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'BILLRULE', isnull(max( RULESEQNO ),1)
	from BILLRULE 
else
	Update LASTINTERNALCODE set INTERNALSEQUENCE= (select ISNULL(max(RULESEQNO),500) from BILLRULE)
	where TABLENAME='BILLRULE'
go

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'IMPORTBATCH')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'IMPORTBATCH', isnull(max( IMPORTBATCHNO ),1)
	from 	IMPORTBATCH
else
	Update LASTINTERNALCODE set INTERNALSEQUENCE= (select ISNULL(max(IMPORTBATCHNO),500) from IMPORTBATCH)
	where TABLENAME='IMPORTBATCH'
go                           

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'ACTIVITY')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'ACTIVITY', isnull(max( ACTIVITYNO ),1)
	from 	ACTIVITY
else
	Update LASTINTERNALCODE set INTERNALSEQUENCE= (select ISNULL(max(ACTIVITYNO),500) from ACTIVITY)
	where TABLENAME='ACTIVITY'
go                          

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'NAMEADDRESSSNAP')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'NAMEADDRESSSNAP', isnull(max( NAMESNAPNO ),1)
	from 	NAMEADDRESSSNAP
else
	Update LASTINTERNALCODE set INTERNALSEQUENCE= (select ISNULL(max(NAMESNAPNO),500) from NAMEADDRESSSNAP)
	where TABLENAME='NAMEADDRESSSNAP'
go  

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'AUDITLOCATION')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'AUDITLOCATION', isnull(max( AUDITNUMBER ),1)
	from 	AUDITLOCATION
else
	Update LASTINTERNALCODE set INTERNALSEQUENCE= (select ISNULL(max(AUDITNUMBER),500) from AUDITLOCATION)
	where TABLENAME='AUDITLOCATION'
go

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'BILLFORMAT')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'BILLFORMAT', isnull(max( BILLFORMATID ),1)
	from 	BILLFORMAT 
else
	Update LASTINTERNALCODE set INTERNALSEQUENCE= (select ISNULL(max(BILLFORMATID),500) from BILLFORMAT)
	where TABLENAME='BILLFORMAT'
go

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'COSTTRACK')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'COSTTRACK', isnull(max( COSTID ),1)
	from 	COSTTRACK 
else
	Update LASTINTERNALCODE set INTERNALSEQUENCE= (select ISNULL(max(COSTID),500) from COSTTRACK)
	where TABLENAME='COSTTRACK'
go

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'CPADATA')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'CPADATA', isnull(max( BATCHNO ),1)
	from 	CPADATA 
else
	Update LASTINTERNALCODE set INTERNALSEQUENCE= (select ISNULL(max(BATCHNO),500) from CPADATA)
	where TABLENAME='CPADATA'
go

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'CRITERIA_ITEMS')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'CRITERIA_ITEMS', isnull(max( CRITERIA_ID ),1)
	from 	CRITERIA_ITEMS 
else
	Update LASTINTERNALCODE set INTERNALSEQUENCE= (select ISNULL(max(CRITERIA_ID),500) from CRITERIA_ITEMS)
	where TABLENAME='CRITERIA_ITEMS'
go

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'CRITERIA_MAXIM')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'CRITERIA_MAXIM', isnull(min( CRITERIANO ),1)
	from 	CRITERIA 
else
	Update LASTINTERNALCODE set INTERNALSEQUENCE= (select ISNULL(min(CRITERIANO),500) from CRITERIA)
	where TABLENAME='CRITERIA_MAXIM'
go

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'DEBITNOTEDETAILS')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'DEBITNOTEDETAILS', isnull(max( DEBITNOTENUMBER ),1)
	from 	DEBITNOTEDETAILS 
else
	Update LASTINTERNALCODE set INTERNALSEQUENCE= (select ISNULL(max(DEBITNOTENUMBER),500) from DEBITNOTEDETAILS)
	where TABLENAME='DEBITNOTEDETAILS'
go

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'DOCUMENT_CRITERIA')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'DOCUMENT_CRITERIA', isnull(max( CRITERIA_ID ),1)
	from 	DOCUMENT_CRITERIA 
else
	Update LASTINTERNALCODE set INTERNALSEQUENCE= (select ISNULL(max(CRITERIA_ID),500) from DOCUMENT_CRITERIA)
	where TABLENAME='DOCUMENT_CRITERIA'
go

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'DOCUMENTSUMMARY')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'DOCUMENTSUMMARY', isnull(max( DOCUMENT_ID ),1)
	from 	DOCUMENTSUMMARY 
else
	Update LASTINTERNALCODE set INTERNALSEQUENCE= (select ISNULL(max(DOCUMENT_ID),500) from DOCUMENTSUMMARY)
	where TABLENAME='DOCUMENTSUMMARY'
go

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'GROUPS')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'GROUPS', isnull(max( GROUP_CODE ),1)
	from 	GROUPS
else
	Update LASTINTERNALCODE set INTERNALSEQUENCE= (select ISNULL(max(GROUP_CODE),500) from GROUPS)
	where TABLENAME='GROUPS'
go

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'IMPORTJOURNAL')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'IMPORTJOURNAL', isnull(max( IMPORTBATCHNO ),1)
	from 	IMPORTJOURNAL
else
	Update LASTINTERNALCODE set INTERNALSEQUENCE= (select ISNULL(max(IMPORTBATCHNO),500) from IMPORTJOURNAL)
	where TABLENAME='IMPORTJOURNAL'
go

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'INSTRUCTIONLABEL')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'INSTRUCTIONLABEL', isnull(max( FLAGNUMBER ),1)
	from 	INSTRUCTIONLABEL
else
	Update LASTINTERNALCODE set INTERNALSEQUENCE= (select ISNULL(max(FLAGNUMBER),500) from INSTRUCTIONLABEL)
	where TABLENAME='INSTRUCTIONLABEL'
go

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'GLACCOUNTTYPE')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'GLACCOUNTTYPE', isnull(max( ACCOUNTTYPE ),1)
	from 	GLACCOUNTTYPE 
else
	Update LASTINTERNALCODE set INTERNALSEQUENCE= (select ISNULL(max(ACCOUNTTYPE),500) from GLACCOUNTTYPE)
	where TABLENAME='GLACCOUNTTYPE'
go

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'GLACCOUNTMAPPING')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'GLACCOUNTMAPPING', isnull(max( RULESEQNO ),1)
	from 	GLACCOUNTMAPPING
else
	Update LASTINTERNALCODE set INTERNALSEQUENCE= (select ISNULL(max(RULESEQNO),500) from GLACCOUNTMAPPING)
	where TABLENAME='GLACCOUNTMAPPING'
go

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'LABEL')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'LABEL', isnull(max( LABELID ),1)
	from 	LABEL 
else
	Update LASTINTERNALCODE set INTERNALSEQUENCE= (select ISNULL(max(LABELID),500) from LABEL)
	where TABLENAME='LABEL'
go

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'GLJOURNALLINEFIELD')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'GLJOURNALLINEFIELD', isnull(max( FIELDNO ),1)
	from 	GLJOURNALLINEFIELD
else
	Update LASTINTERNALCODE set INTERNALSEQUENCE= (select ISNULL(max(FIELDNO),500) from GLJOURNALLINEFIELD)
	where TABLENAME='GLJOURNALLINEFIELD'
go

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'MARGIN')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 	'MARGIN', isnull(max(MARGINNO),1)
	from 	MARGIN
else
	Update 	LASTINTERNALCODE set INTERNALSEQUENCE= (select ISNULL(max(MARGINNO),500) from MARGIN)
	where 	TABLENAME='MARGIN'
go  

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'IMPORTMETHOD')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 	'IMPORTMETHOD', isnull(max(IMPORTMETHODNO),1)
	from 	IMPORTMETHOD
else
	Update 	LASTINTERNALCODE set INTERNALSEQUENCE= (select ISNULL(max(IMPORTMETHODNO),500) from IMPORTMETHOD)
	where 	TABLENAME='IMPORTMETHOD'
go  

if not exists (select * from LASTINTERNALCODE where TABLENAME = 'NAMEVARIANT')
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE)
	select 'NAMEVARIANT', isnull(max( NAMEVARIANTNO ),500)
	from	NAMEVARIANT
else 
	Update LASTINTERNALCODE
	set INTERNALSEQUENCE= (select ISNULL(max( NAMEVARIANTNO ),500) from NAMEVARIANT)
	where TABLENAME='NAMEVARIANT'
go   


if not exists (select * from LASTINTERNALCODE where TABLENAME = 'CPASEND') 
	INSERT INTO LASTINTERNALCODE (TABLENAME, INTERNALSEQUENCE) 
	select 'CPASEND', isnull(max( BATCHNO ),0) 
	from CPASEND 
else 
	Update LASTINTERNALCODE 
	set INTERNALSEQUENCE= (select ISNULL(max(BATCHNO),0) from CPASEND) 
	where TABLENAME='CPASEND' 
go 


