using System.Collections.Generic;

namespace Inprotech.Tests.E2e.Integration.Fake.Innography.Uspto
{
    internal static class Documents
    {
        public static readonly string[] PriorArts =
        {
            "1449",
            "371P",
            "892",
            "FOR",
            "IDS",
            "N417",
            "NPL",
            "REF.OTHER"
        };

        public static readonly Dictionary<string, string> IFWs
            = new Dictionary<string, string>
            {
                {"APE2", "2nd or Subsequent Examiner's Answer to Appeal Brief"},
                {"371.RES.DEF", "371 Defective Response - Form M916"},
                {"371.RQ.M922", "371 Requirements for Sequence Disclosure Notice Form M922"},
                {"371.FEE.M923", "371 Supplemental Fees Missing - Form M923"},
                {"OA.POSTCARD", "A courtesy postcard sent by USPTO to users who opt-in for e-Office Action"},
                {"ABN", "Abandonment"},
                {"ABST", "Abstract"},
                {"PD.AUTH.G", "Acceptance of Permission to Access Application"},
                {"SREXR.G", "Acceptance of Permission to Access Search Results"},
                {"R48.REQ.G", "Acceptance of Request under Rule 48 to correct inventorship or name"},
                {"CTAV", "Advisory Action (PTOL-303)"},
                {"AF/D.OTHER", "Affidavit-not covered under specific rule"},
                {"AF/D.131", "Affidavit-Rule 131-pre-AIA (FTI) ONLY"},
                {"AF/D", "Affidavit-submitted prior to Mar 15, 2013"},
                {"AF/D.132", "Affidavit-traversing rejectns or objectns rule 132"},
                {"A.NE.AFCP.D", "After Final Consideration Program Decision"},
                {"A.NE.AFCP", "After Final Consideration Program Request"},
                {"ANE.I", "Amendment After Final or under 37CFR 1.312, initialed by the examiner."},
                {"A.NA", "Amendment after Notice of Allowance (Rule 312)"},
                {"AMSB", "Amendment Submitted/Entered with Filing of CPA/RCE"},
                {"BD.A", "Amendment/Argument after Patent Board Decision"},
                {"A...", "Amendment/Req. Reconsideration-After Non-Final Reject"},
                {"L_R OUT", "Any document coming from L and R"},
                {"L_R IN", "Any request going to L and R"},
                {"AP.B", "Appeal Brief Filed"},
                {"AP_DK_M", "Appeal Docketing Notice"},
                {"APPG", "Appeal Hearing Postponement Granted"},
                {"REM", "Applicant Arguments/Remarks Made in an Amendment"},
                {"INTV.SUM.APP", "Applicant Initiated Interview Summary (PTOL-413)"},
                {"PEFR", "Applicant Response to Pre-Exam Formalities Notice"},
                {"INTRVIEW.APP", "Applicant summary of interview with examiner"},
                {"ADS", "Application Data Sheet"},
                {"ADS.CORR", "Application Data Sheet to update/correct info"},
                {"R3.73", "Assignee showing of ownership per 37 CFR 3.73"},
                {"PD.TO.AUTH", "Auth or Resc of Auth to Access Appl by DAS/PDX Office"},
                {"136A", "Authorization for Extension of Time all replies"},
                {"BIB", "Bibliographic Data Sheet"},
                {"COCOUT", "Certificate of Correction - Post Issue Communication"},
                {"MES.IHEB", "Certification of Micro Entity (Education Basis)"},
                {"FRPR", "Certified Copy of Foreign Priority Application"},
                {"C.AD", "Change of Address"},
                {"P2.436", "CHII - Notification of Transmittal of Demand to the IB or the Competent IPEA"},
                {"CLM.NE", "Claim-Amendment Not Entered"},
                {"CLM", "Claims"},
                {"WCLM", "Claims Worksheet (PTO-2022)"},
                {"N570", "Communication - Re:  Power of Attorney (PTOL-308)"},
                {"CRFD", "Computer Readable Form (CRF) for Sequence Listing - Defective"},
                {"3P.RELEVANCE", "Concise Description of Relevance"},
                {"ACPA", "Continued Prosecution Application - Continuation (ACPA)"},
                {"PATENT.GRANT", "Copy of a Patent Grant"},
                {"CRFE", "CRF entered - partial listing printed by STIC"},
                {"CRFS", "CRF Statement Paper and CRF are the same"},
                {"APDS", "Dismissal of Appeal"},
                {"371P", "Documents submitted with 371 Applications"},
                {"DRW", "Drawings-only black and white line drawings"},
                {"DRW.NONBW", "Drawings-other than black and white line drawings"},
                {"N417", "EFS Acknowledgment Receipt"},
                {"N417.CORR", "EFS Acknowledgment Receipt (Corrected)"},
                {"M865E", "Electronic Request for Interview with Examiner"},
                {"OA.EMAIL", "Email Notification"},
                {"CTEQ", "Ex Parte Quayle Action"},
                {"INTV.SUM.EX", "Examiner initiated interview summary (PTOL-413B)"},
                {"EXIN", "Examiner Interview Summary Record (PTOL - 413)"},
                {"EX.A", "Examiner's Amendment Communication"},
                {"APEA", "Examiner's Answer to Appeal Brief"},
                {"XI.APXDT", "Examiner's Determination on Patent Owner Response/Requester Comments after Board Decision"},
                {"SRNT", "Examiner's search strategy and results"},
                {"XT/", "Extension of Time"},
                {"WFEE", "Fee Worksheet (SB06)"},
                {"APP.FILE.REC", "Filing Receipt"},
                {"CTFR", "Final Rejection"},
                {"FAI.REQ", "First Action Interview - Enrollment Request"},
                {"OA.FAI", "First action interview - office action"},
                {"OA.FAI.OPT.O", "First action without interview"},
                {"FOR", "Foreign Reference"},
                {"P.306", "IB/306 - Notification of the Recording of a Change"},
                {"P.373", "IB/373 - Intl Prelim Report on Patentability Chapter 1"},
                {"P.409.IN", "Incoming IPEA/409 - Int'l Prelim Report on Patentability"},
                {"P.210.IN", "Incoming ISR, 237 and References from IB"},
                {"P.237.IN", "Incoming Written Opinion of the ISA"},
                {"FWCLM", "Index of Claims"},
                {"IDS", "Information Disclosure Statement (IDS) Form (SB08)"},
                {"TERM.PTO.LT1", "Initial letter Re:  PTE Application to regulating agency"},
                {"P2.402", "IPEA/402 - Notification of Receipt of Demand by Competent IPEA (removed from use 2/2007)"},
                {"P2.404", "IPEA/404 - Invitation to Correct Defects in the Demand"},
                {"P2.409", "IPEA/409 - International Preliminary Report on Patentability"},
                {"P2.416", "IPEA/416 - Notification of Transmittal of International Preliminary Report on Patentability"},
                {"P.203", "ISA/203 - Declaration of Non-Establishment DO NOT USE"},
                {"P.205", "ISA/205 - Notification of Change in Abstract as Previously Established by ISA"},
                {"P.206", "ISA/206 - Invitation to Pay Additional Fees"},
                {"P.217.OUT", "ISA/217 - Notification of Decision Concerning Request for Rectification"},
                {"P.220", "ISA/220 - Notification of Transmittal or Search Report and Written Opinion of the ISA, or the Declaration"},
                {"P.225.OUT", "ISA/225 - Invitation to Furnish Nucleotide and/or Amino Acid Sequence Listing and/or Related Tables"},
                {"IFEE", "Issue Fee Payment (PTO-85B)"},
                {"IIFW", "Issue Information including classification, examiner, name, claim, renumbering, etc."},
                {"ISSUE.NTF", "Issue Notification"},
                {"M865", "Letter Requesting Interview with Examiner"},
                {"NRES", "Letter Restarting Period for Response (i.e. Letter re: References)"},
                {"NT.WD.NONCPL", "Letter Withdrawing a Notice of Non-Compliant Amendment"},
                {"W/AC", "Letter Withdrawing/Vacating Office Action"},
                {"1449", "List of References cited by applicant and considered by examiner"},
                {"892", "List of references cited by examiner"},
                {"P.LET", "Misc. incoming letter from Applicant - IA"},
                {"CTMS", "Miscellaneous Action with SSP"},
                {"M327", "Miscellaneous Communication to Applicant - No Action Count"},
                {"LET.", "Miscellaneous Incoming Letter"},
                {"IMIS", "Miscellaneous Internal Document"},
                {"XI.AP.DR", "New Board of Appeals Decision after Board Decision With New Ground of Rejection:  Examiner Reversed"},
                {"NPL", "Non Patent Literature"},
                {"CTNF", "Non-Final Rejection"},
                {"APBD", "Notice - Defective Appeal Brief"},
                {"NOA", "Notice of Allowance and Fees Due (PTOL-85)"},
                {"N/AP", "Notice of Appeal Filed"},
                {"RXNREQAU", "Notice of Assignment of Reexamination Request"},
                {"EBCC.AD", "Notice of Change of Address placed in File Wrapper due to EBC Customer Number update"},
                {"M903", "Notice of DO/EO Acceptance Mailed"},
                {"M905", "Notice of DO/EO Missing Requirements Mailed"},
                {"NFDR", "Notice of Formal Drawings Required"},
                {"NTC.RCE.DEF", "Notice of Improper Request for Continued Examination (RCE) - PTO-2051 Rev 7/2003"},
                {"NT.INC.REPLY", "Notice of Incomplete Reply"},
                {"CPA-AMD", "Notice of Informal or Non-Responsive CPA Amendment"},
                {"RXNIRC", "Notice of Intent to Issue a Reexam Certificate"},
                {"NTC.PUB.DATE", "Notice of New or Revised Publication Date"},
                {"NTC.OMIT.APP", "Notice of Omitted Items Application"},
                {"NTC.PUB", "Notice of Publication"},
                {"RXNREQFD", "Notice of reexamination request filing date"},
                {"ISSUE.WD.NTC", "Notice of withdrawal from issue"},
                {"N416", "Notice of Withdrawal from Issue Branch (PTOL-67)"},
                {"PD.AUTH.NTC", "Notice that authorization for participating IP Offices to access US application was improper"},
                {"NT.CR.APP.PA", "Notice to File Corrected Application Papers"},
                {"NTC.MISS.PRT", "Notice to File Missing Parts"},
                {"NTC.A.NONCPL", "Notice to the applicant regarding a non-compliant or non-responsive amendment"},
                {"AP.PRE.DEF", "Notice-Defective Pre-Brief Appeal"},
                {"APNH", "Notification of Appeal Hearing"},
                {"P.159", "Notification of Decision on Request to Restore Right of Priority"},
                {"RXNDEFCT", "Notification of Defective Paper in a Reexam"},
                {"OATH", "Oath or Declaration filed"},
                {"OA.APPENDIX", "Office Action Appendix"},
                {"PET.OP.DEC", "Office of Petitions Decision (PTO-90)"},
                {"REF.OTHER", "Other Reference-Patent/App/Search documents"},
                {"P.210.OUT", "Outgoing - ISA/210 - International Search Report"},
                {"P.202.OUT", "Outgoing ISA/202 - Notification of Receipt of Search Copy"},
                {"P.118.OUT", "Outgoing RO/118 - Notification Concerngin Documents Transmitted"},
                {"P.123.OUT", "Outgoing RO/123 - Notification Concerning Representation"},
                {"P.237.OUT", "Outgoing Written Opinion of the ISA"},
                {"P.132.OUT", "Outoing RO/132 - Communication in Cases for Which No Other Form Is Applicable"},
                {"APDA", "Patent Board Decision - Examiner Affirmed"},
                {"APDP", "Patent Board Decision - Examiner Affirmed in Part"},
                {"APDR", "Patent Board Decision - Examiner Reversed"},
                {"APDN", "Patent Board Decision 196(b)"},
                {"PPH.DECISION", "Patent Prosecution Highway decision on request/petition to make special"},
                {"P.SRNT.IN", "PCT Search Strategy and results"},
                {"PET.DEC.AUTO", "Petition auto-grant letter from EFS"},
                {"PET.AUTO", "Petition automatically granted by EFS"},
                {"PETDEC", "Petition Decision"},
                {"PET.DEC.COCI", "Petition Decision routed to Certificate of Correction"},
                {"PET.DEC.PUBS", "Petition decision routed to the Office of Publications to act on the decision or continue prosecution."},
                {"PET.DEC.OIPE", "Petition decision routed to the OIPE to act on the decision or continue prosecution."},
                {"PET.DEC.TC", "Petition decision routed to the Technology Center to act on the decision or continue prosecution"},
                {"PGEA.D", "Petition for PreGrant Publication Express Abandonment - Dismissed"},
                {"PGEA.G", "Petition for PreGrant Publication Express Abandonment - Granted"},
                {"PET.OP", "Petition for review by the Office of Petitions"},
                {"PPH.PET.652", "Petition to make special under Patent Prosecution Hwy"},
                {"SCORE", "Placeholder sheet indicating presence of supplemental content in SCORE"},
                {"N427", "Post Allowance Communication - Incoming"},
                {"CDEN", "Post Issue Communication - Request for Certificate of Correction Denied"},
                {"PA..", "Power of Attorney"},
                {"AP.PRE.DEC", "Pre-Brief Appeal Conference decision"},
                {"AP.PRE.REQ", "Pre-Brief Conference request"},
                {"PEFN", "Pre-Exam Formalities Notice"},
                {"OA.FAI.PRELM", "Preinterview first office action"},
                {"A.PE", "Preliminary Amendment"},
                {"PD.FILED.E", "Priority Documents electronically retrieved by USPTO from a participating IP Office"},
                {"IRFND", "Processed Request for Refund"},
                {"A.NE.PCP.D", "Prosecution Conference Pilot Decision Form"},
                {"A.NE.PCP", "Prosecution Conference Pilot Request"},
                {"QPIDS.REQ", "Quick Path Information Disclosure Statement"},
                {"RCE.NE", "RCE Not Entered"},
                {"RXMISC", "Reexam - Miscellaneous Action"},
                {"RXPTDE", "Reexam Petition Decision - Denied"},
                {"RXPTGR", "Reexam Petition Decision - Granted"},
                {"RXCERT", "Reexamination Certificate Issued"},
                {"RFND", "Refund Denied"},
                {"RFN.REQ", "Refund Request"},
                {"SREXR.NTC", "Rejection of Permission to Access Search Results"},
                {"R48.REQ.DIS", "Rejection of Request under Rule 48 to correct inventorship or name"},
                {"Q.DEC.REOPEN", "Reopen prosecution after QPIDS request after Notice of Allowance"},
                {"APRB", "Reply Brief Filed"},
                {"COCIN", "Request for Certificate of Correction"},
                {"RCEX", "Request for Continued Examination (RCE)"},
                {"CFILE", "Request for Corrected Filing Receipt"},
                {"TRIAL.REQ.GP", "Request for Trial  Granted in Part"},
                {"TRIAL.REQ.D", "Request for Trial Denied"},
                {"TRIAL.RQ.DIS", "Request for Trial Dismissed"},
                {"TRIAL.REQ.G", "Request for Trial Granted"},
                {"PD.REQ.RETR", "Request for USPTO to retrieve priority docs"},
                {"R46C.REQ", "Request to correct/update applicant name until payment of issue fee"},
                {"R48.REQ", "Request under Rule 48 correcting inventorship"},
                {"CTRS", "Requirement for Restriction/Election"},
                {"SEQ.REQ.DISC", "Requirements for Sequence Disclosure Notice"},
                {"RESC", "Rescind Nonpublication Request for Pre Grant Pub"},
                {"N572", "Response - Re:  Informal Power of Attorney (PTOL-308)"},
                {"A.QU", "Response after Ex Parte Quayle Action"},
                {"A.NE", "Response After Final Action"},
                {"N271", "Response to Amendment under Rule 312"},
                {"ELC.", "Response to Election / Restriction Filed"},
                {"P.RESP.206", "Response to Form PCT/ISA/206 Unity of Invention"},
                {"PEFRSEQ", "Response to Pre-Exam Sequence Notice"},
                {"P.N.101.ANX", "RO/101 - Annex (fee calculation sheet)"},
                {"P.N.101.CONV", "RO/101 - Request form for new IA - Conventional"},
                {"P.N.101.SAFE", "RO/101 - Request form for new IA - PCT EASY Format"},
                {"P.102", "RO/102 - Notification Concerning Payment of Prescribed Fees and Annex"},
                {"P.105", "RO/105 - Notification of the IA Number and of the International Filing Date"},
                {"P.106", "RO/106 - with Annex A, B and/or C - Invitation to Correct Defects in the IA"},
                {"P.107", "RO/107 - Invitation relating to certain parts of the IA (missing)"},
                {"P.110", "RO/110 - with Annex - Invitation to Correct Priority Claim"},
                {"P.111", "RO/111 - Notification Relating to Priority Claim"},
                {"P.113", "RO/113 - Request for the Recording of a Change"},
                {"P.114", "RO/114 - Notification on Decision of Confirmation of Incorporation by Ref. Of Missing Element/Part"},
                {"P.117", "RO/117 - Notification that IA Considered to be Withdrawn"},
                {"P.124", "RO/124 - Notification of Defective Power of Attorney or Defective Revocation of Power of Attorney"},
                {"P.133", "RO/133 with Annex - Invitation to Pay Prescribed Fees Together with Late Payment Fees"},
                {"P.146", "RO/146 - with Attachments - Notification Regarding Certain Corrections Made Ex Officio"},
                {"P.151", "RO/151 - Notification of Transmittal of IA to the IB as Receiving Office and Invitation to Pay Fee"},
                {"SRFW", "Search information including classification, databases and other search related notes"},
                {"SRFW.KIPO", "Search Information including classification, databases, and other search related notes, may include examination results of claim"},
                {"TERM.PTO.LT2", "Second letter to regulating agency to determine regulartory review period"},
                {"SEQLIST", "Sequence Listing"},
                {"SEQ.TXT", "Sequence Listing (Text File)"},
                {"COCX", "SPE Response - Certificate of Correction under 1.323/1.324"},
                {"SPEC", "Specification"},
                {"SPECNO", "Specification - Not in English"},
                {"SPEC.NE", "Specification-Amendment Not Entered"},
                {"P.SUB.SH.DRW", "Substitute Drawings"},
                {"SA..", "Supplemental Response or Supplemental Amendment"},
                {"DIST", "Terminal Disclaimer Filed"},
                {"DISQ", "Terminal Disclaimer review decision"},
                {"DIST.E.FILE", "Terminal Disclaimer-Filed (Electronic)"},
                {"IDS.3P", "Third-Party Submission Under 37 CFR 1.290"},
                {"TRACK1.REQ", "TrackOne Request"},
                {"TRACK1.GRANT", "TrackOne Request Granted"},
                {"FR TRANS", "Translation of Foreign Priority Documents"},
                {"TRAN.LET", "Transmittal Letter"},
                {"TRNA", "Transmittal of New Application"},
                {"TRIAL.CERT.M", "Trial Certificate Mailed"},
                {"TRIAL.TRMFWD", "Trial Termination or Final Written Decision"},
                {"P.PAMPHLET", "WIPO Publication - Non-English version"}
            };
    }
}