using System;
using System.Linq;

namespace Inprotech.Tests.E2e.Integration.Fake.Innography.Uspto
{
    internal static class ForeignPriorityCountries
    {
        static readonly Random R = new Random();

        internal static string Next()
        {
            return Country.ElementAt(R.Next(0, Country.Length - 1));
        }

        static string[] Country =
        {
            "ANDORRA",
            "UNITED ARAB EMIRATES",
            "AFGHANISTAN",
            "ANTIGUA & BARBUDA",
            "ANGUILA",
            "ALBANIA",
            "ARMENIA",
            "NETHERLANDS ANTILLES",
            "ANGOLA",
            "ARGENTINA",
            "AMERICAN SAMOA",
            "AUSTRIA",
            "AUSTRALIA",
            "ARUBA",
            "AZERBAIJAN",
            "BOSNIA & HERZEGOVINA",
            "BARBADOS",
            "BANGLADESH",
            "BELGIUM",
            "BURKINA FASO",
            "BULGARIA",
            "BAHRAIN",
            "BURUNDI",
            "BENIN",
            "BERMUDA",
            "BRUNEI DARUSSALAM",
            "BOLIVIA",
            "BOPHUTHATSWANA",
            "BRAZIL",
            "BAHAMAS",
            "BHUTAN",
            "BOUVET ISLAND",
            "BOTSWANA",
            "BELARUS",
            "BELIZE",
            "CANADA",
            "CENTRAL AFRICAN REPUBLIC",
            "CONGO",
            "SWITZERLAND",
            "CÔTE D'IVOIRE",
            "COOK ISLANDS",
            "CHILE",
            "CAMEROON",
            "CHINA",
            "COLOMBIA",
            "COSTA RICA",
            "CUBA",
            "CAPE VERDE",
            "CYPRUS",
            "CZECH REPUBLIC",
            "GERMANY",
            "DJIBOUTI",
            "DENMARK",
            "DOMINICA",
            "DOMINICAN REPUBLIC",
            "ALGERIA",
            "ECUADOR",
            "ESTONIA",
            "EGYPT",
            "WEST SAHARA",
            "ERITREA",
            "SPAIN",
            "ETHIOPIA",
            "FINLAND",
            "FIJI",
            "FALKLAND ISLANDS",
            "MICRONESIA (FEDERATED STATES OF)",
            "FAROE ISLANDS",
            "FRANCE",
            "GABON",
            "UNITED KINGDOM",
            "GRENADA",
            "GEORGIA",
            "FRENCH GUIANA",
            "GHANA",
            "GIBRALTA",
            "GREENLAND",
            "GAMBIA",
            "GUINEA",
            "EQUATORIAL GUINEA",
            "GREECE",
            "SOUTH GEORGIA & THE SOUTH SANDWICH ISLANDS",
            "GUATEMALA",
            "GUAM",
            "GUINEA-BISSAU",
            "GUYANA",
            "HONG KONG",
            "HONDURAS",
            "CROATIA",
            "HAITI",
            "HUNGARY",
            "INDONESIA",
            "IRELAND",
            "ISRAEL",
            "INDIA",
            "IRAQ",
            "IRAN",
            "ICELAND",
            "ITALY",
            "JAMAICA",
            "JORDAN",
            "JAPAN",
            "KENYA",
            "KYRGYZSTAN",
            "CAMBODIA",
            "KIRIBATI",
            "COMOROS",
            "SAINT KITTS & NEVIS",
            "DEMOCRATIC PEOPLE'S REPUBLIC OF KOREA",
            "REPUBLIC OF KOREA",
            "KUWAIT",
            "CAYMAN ISLANDS",
            "KAZAKSTAN",
            "LAOS",
            "LEBANON",
            "SAINT LUCIA",
            "LIECHTENSTEIN",
            "SRI LANKA",
            "LIBERIA",
            "LESOTHO",
            "LITHUANIA",
            "LUXEMBOURG",
            "LATVIA",
            "LIBYA",
            "MOROCCO",
            "MONACO",
            "MOLDOVA",
            "MADAGASCAR",
            "MARSHALL ISLANDS",
            "MACEDONIA (F.Y.R.O.M)",
            "MALI",
            "MYANMAR",
            "MONGOLIA",
            "MACAU",
            "NORTHERN MARIANA ISLANDS",
            "MAURITANIA",
            "MONSERRAT",
            "MALTA",
            "MAURITIUS",
            "MALDIVES",
            "MALAWI",
            "MEXICO",
            "MALAYSIA",
            "MOZAMBIQUE",
            "NAMIBIA",
            "NEW CALEDONIA",
            "NIGER",
            "NIGERIA",
            "NICARAGUA",
            "NETHERLANDS",
            "NORWAY",
            "NEPAL",
            "NAURU",
            "NIUE ISLANDS",
            "NEW ZEALAND",
            "OMAN",
            "PANAMA",
            "PERU",
            "FRENCH POLYNESIA",
            "PAPUA NEW GUINEA",
            "PHILIPPINES",
            "PAKISTAN",
            "POLAND",
            "PUERTO RICO",
            "PORTUGAL",
            "PALAU",
            "PARAGUAY",
            "QATAR",
            "ROMANIA",
            "RUSSIAN FEDERATION",
            "RWANDA",
            "SAUDI ARABIA",
            "SOLOMON ISLANDS",
            "SEYCHELLES",
            "SUDAN",
            "SWEDEN",
            "SINGAPORE",
            "SAINT HELENA",
            "SLOVENIA",
            "SLOVAKIA",
            "SIERRA LEONE",
            "SAN MARINO",
            "SENEGAL",
            "SOMALIA",
            "SURINAME",
            "SABAH",
            "SAO TOME & PRINCIPE",
            "EL SALVADOR",
            "SYRIA",
            "SWAZILAND",
            "TAHITI",
            "TURKS & CAICOS ISLANDS",
            "CHAD",
            "TOGO",
            "THAILAND",
            "TRANSKEI",
            "TAJIKISTAN",
            "TOKELAOU",
            "TURKMENISTAN",
            "TUNISIA",
            "TONGA",
            "TIMOR LESTE",
            "TURKEY",
            "TRINIDAD & TOBAGO",
            "TUVALU",
            "TAIWAN",
            "TANZANIA",
            "UKRAINE",
            "UGANDA",
            "UNITED STATES OF AMERICA",
            "URUGUAY",
            "UZBEKISTAN",
            "HOLY SEE",
            "SAINT VINCENT & THE GRENADINES",
            "VENDA",
            "VENEZUELA",
            "VIRGIN ISLANDS (BRITISH)",
            "VIRGIN ISLANDS (U.S.)",
            "VIETNAM",
            "VANUATU",
            "WEST BANK",
            "MALAYA",
            "WESTERN SAMOA",
            "YEMEN (SOUTH)",
            "YEMEN",
            "SERBIA & MONTENEGRO",
            "SOUTH AFRICA",
            "ZAMBIA",
            "ZIMBABWE"
        };
    }
}