namespace Inprotech.Infrastructure.Security.Licensing
{
    public enum LicensedModule : int
    {
        CasesAndNames = 2,
        Timesheet = 6,
        Billing = 7,
        Quotations = 8,
        AccountsReceivable = 9,
        GeneralLedger = 10,
        AccountsPayable = 11,
        FinancialInterface = 12,
        ContactManagement = 13,
        FileTracking = 14,
        CostTracking = 15,
        WebAccessModule = 16,
        ClientWorkBench = 17,
        ProfessionalWorkBench = 18,
        ManagersWorkBench = 19,
        MarketingWorkBench = 20,
        ClericalWorkBench = 21,
        EFiling = 22,
        Ede = 23,
        LawUpdate = 24,
        CrmWorkBench = 25,
        TrustAccounting = 26,
        AdministratorWorkBench = 27,
        CaseNamesClericalWorkBench = 28,
        IpMatterManagementModule = 29,
        TimeandBillingModule = 30,
        FinancialManagementModule = 31,
        MarketingModule = 32,
        ClientAccessModule = 33,
        IntegrationEFilingModule = 34,
        IntegrationAccountingModule = 35,
        IntegrationDmsModule = 36,
        IntegrationExchangeModule = 37,
        EdeModule = 38
    }
}
