exec ip_ListCountry @pnRowCount = 0, 
	@pnUserIdentityId = 1,
	@psColumnIds = 'CountryKey^CountryName^CountryAbbreviation^IsCountryCurrent^DateCeased^DateCommenced',
	@psPublishColumnNames = 'Code^C Name^Abb^Is Alive^Died^Born',
--	@psCountryKey = 'B',
--	@pnCountryKeyOperator = 2,
--	@psPickListSearch = 'AD',
	@pbIsCurrent = 1,
--	@pbIsGroup = 1
--	@psCountryName = 'United',
--	@pnCountryNameOperator = 2
--	@psCountryAdjective = 'Angolan'
--	@psAlternateCode = 'PAR'
-- 	@psGroupCountryKey = 'B',
--	@pnGroupCountryKeyOperator = 2
--	@pdtCeasedToDate = '1990',
--	@pnCeasedDateOperator = 7,
	@pnAttributeTypeKey1 = 50,
	@pnAttributeKey1 = 5001,
	@pnAttributeKey1Operator = 0