exec dbo.csw_UpdateCase
	@pnUserIdentityId = 5, @psCulture = default, @pbCalledFromCentura = default,
	@pnCaseKey = -487,
	
	@psCaseReference = N'1234/A',
	@psCaseFamilyReference = default,
	@pnCaseStatusKey = -221,
	@psCaseTypeCode = N'A',
	@psPropertyTypeCode = N'T',
	@psCountryCode = N'AU',
	@psCaseCategoryCode = N'N',
	@psSubTypeCode = N'N',
	@psApplicationBasisCode = N'Y',
	@psTitle = N'RONDON and shoe device',
	@pbIsLocalClient = 1,
	@pnEntitySizeKey = NULL,
	@pnPredecessorCaseKey = NULL,
	@pbFileCoverCaseKey = NULL,
	@psPurchaseOrderNo = default,
	@psCurrentOfficialNumber = N'777777',
	@psTaxRateCode = default,
	@pnCaseOfficeKey = NULL,
	@pnNoOfClaims = NULL,
	@pnIPOfficeDelay = 1,
	@pnApplicantDelay = 1,
	@pnIPOfficeAdjustment = 1,
	
	@psOldCaseReference = N'1234/A',
	@psOldCaseFamilyReference = default,
	@pnOldCaseStatusKey = -225,
	@psOldCaseTypeCode = N'A',
	@psOldPropertyTypeCode = N'T',
	@psOldCountryCode = N'AU',
@psOldCaseCategoryCode = N'N',
@psOldSubTypeCode = N'N',
@psOldApplicationBasisCode = N'Y',
@psOldTitle = N'RONDON and shoe device',
@pbOldIsLocalClient = 1,
@pnOldEntitySizeKey = NULL,
@pnOldPredecessorCaseKey = NULL,
@pbOldFileCoverCaseKey = NULL,
@psOldPurchaseOrderNo = default,
@psOldCurrentOfficialNumber = N'777777',
@psOldTaxRateCode = default,
@pnOldCaseOfficeKey = NULL,
@pnOldNoOfClaims = NULL,
@pnOldIPOfficeDelay = NULL,
@pnOldApplicantDelay = NULL,
@pnOldIPOfficeAdjustment = NULL,

@pbIsCaseReferenceInUse = 1,
@pbIsCaseFamilyReferenceInUse = 1,
@pbIsCaseStatusKeyInUse = 1,
@pbIsCaseTypeCodeInUse = 1,
@pbIsPropertyTypeCodeInUse = 1,
@pbIsCountryCodeInUse = 1,
@pbIsCaseCategoryCodeInUse = 1,
@pbIsSubTypeCodeInUse = 1,
@pbIsApplicationBasisCodeInUse = 1,
@pbIsTitleInUse = 1,
@pbIsLocalClientInUse = 1,
@pbIsEntitySizeKeyInUse = 1,
@pbIsPredecessorCaseKeyInUse = 1,
@pbIsFileCoverCaseKeyInUse = 1,
@pbIsPurchaseOrderNoInUse = 1,
@pbIsCurrentOfficialNumberInUse = 1,
@pbIsTaxRateCodeInUse = 1,
@pbIsCaseOfficeKeyInUse = 1,
@pbIsNoOfClaimsInUse = 1,
@pbIsIPOfficeDelayInUse = 1,
@pbIsApplicantDelayInUse = 1,
@pbIsIPOfficeAdjustmentInUse = 1

exec dbo.csw_FetchCase @pnUserIdentityId = 5, @psCulture = default, @pbCalledFromCentura = default, @pnCaseKey = -487, @psCaseTypeCode = default, @pbNewRow = default

exec dbo.csw_UpdateCase
	@pnUserIdentityId = 5, @psCulture = default, @pbCalledFromCentura = default,
	@pnCaseKey = -487,
	
	@psCaseReference = N'1234/A',
	@psCaseFamilyReference = default,
	@pnCaseStatusKey = -225,
	@psCaseTypeCode = N'A',
	@psPropertyTypeCode = N'T',
	@psCountryCode = N'AU',
	@psCaseCategoryCode = N'N',
	@psSubTypeCode = N'N',
	@psApplicationBasisCode = N'Y',
	@psTitle = N'RONDON and shoe device',
	@pbIsLocalClient = 1,
	@pnEntitySizeKey = NULL,
	@pnPredecessorCaseKey = NULL,
	@pbFileCoverCaseKey = NULL,
	@psPurchaseOrderNo = default,
	@psCurrentOfficialNumber = N'777777',
	@psTaxRateCode = default,
	@pnCaseOfficeKey = NULL,
	@pnNoOfClaims = NULL,
	@pnIPOfficeDelay = NULL,
	@pnApplicantDelay = NULL,
	@pnIPOfficeAdjustment = NULL,

	@psOldCaseReference = N'1234/A',
	@psOldCaseFamilyReference = default,
	@pnOldCaseStatusKey = -221,
	@psOldCaseTypeCode = N'A',
	@psOldPropertyTypeCode = N'T',
	@psOldCountryCode = N'AU',
@psOldCaseCategoryCode = N'N',
@psOldSubTypeCode = N'N',
@psOldApplicationBasisCode = N'Y',
@psOldTitle = N'RONDON and shoe device',
@pbOldIsLocalClient = 1,
@pnOldEntitySizeKey = NULL,
@pnOldPredecessorCaseKey = NULL,
@pbOldFileCoverCaseKey = NULL,
@psOldPurchaseOrderNo = default,
@psOldCurrentOfficialNumber = N'777777',
@psOldTaxRateCode = default,
@pnOldCaseOfficeKey = NULL,
@pnOldNoOfClaims = NULL,
@pnOldIPOfficeDelay = 1,
@pnOldApplicantDelay = 1,
@pnOldIPOfficeAdjustment = 1,

@pbIsCaseReferenceInUse = 1,
@pbIsCaseFamilyReferenceInUse = 1,
@pbIsCaseStatusKeyInUse = 1,
@pbIsCaseTypeCodeInUse = 1,
@pbIsPropertyTypeCodeInUse = 1,
@pbIsCountryCodeInUse = 1,
@pbIsCaseCategoryCodeInUse = 1,
@pbIsSubTypeCodeInUse = 1,
@pbIsApplicationBasisCodeInUse = 1,
@pbIsTitleInUse = 1,
@pbIsLocalClientInUse = 1,
@pbIsEntitySizeKeyInUse = 1,
@pbIsPredecessorCaseKeyInUse = 1,
@pbIsFileCoverCaseKeyInUse = 1,
@pbIsPurchaseOrderNoInUse = 1,
@pbIsCurrentOfficialNumberInUse = 1,
@pbIsTaxRateCodeInUse = 1,
@pbIsCaseOfficeKeyInUse = 1,
@pbIsNoOfClaimsInUse = 1,
@pbIsIPOfficeDelayInUse = 1,
@pbIsApplicantDelayInUse = 1,
@pbIsIPOfficeAdjustmentInUse = 1

exec dbo.csw_FetchCase @pnUserIdentityId = 5, @psCulture = default, @pbCalledFromCentura = default, @pnCaseKey = -487, @psCaseTypeCode = default, @pbNewRow = default