declare @P1 int
exec dbo.csw_InsertCase
	@pnUserIdentityId = 5,
	@psCulture = N'en',
	@pbCalledFromCentura = default,
	@pnCaseKey = @P1 output,

	@psCaseReference = N'Test2006427172316',
	@psCaseFamilyReference = N'E001',
	@pnCaseStatusKey = NULL,
	@psCaseTypeCode = N'A',
	@psPropertyTypeCode = N'P',
	@psCountryCode = N'AU',
	@psCaseCategoryCode = N'N',
	@psSubTypeCode = N'N',
	@psApplicationBasisCode = N'Y',
	@psTitle = N'Insert Case Test Case',
	@pbIsLocalClient = 0,
	@pnEntitySizeKey = NULL,
	@pnPredecessorCaseKey = NULL,
	@pnFileCoverCaseKey = NULL,
	@psPurchaseOrderNo = default,
	@psCurrentOfficialNumber = default,
	@psTaxRateCode = default,
	@pnCaseOfficeKey = 10175,
	@pnNoOfClaims = NULL,
	@pdtInstructionsReceivedDate = 'Dec 20 2005 12:00:00:000AM',
	@pnIPOfficeDelay = 1,
	@pnApplicantDelay = 1,
	@pnIPOfficeAdjustment = 1,
	
	@pbIsCaseReferenceInUse = 1,
	@pbIsCaseFamilyReferenceInUse = 1,
	@pbIsCaseStatusKeyInUse = 1,
	@pbIsCaseTypeCodeInUse = 1,
	@pbIsPropertyTypeCodeInUse = 1,
	@pbIsCountryCodeInUse = 1,
	@pbIsCaseCategoryCodeInUse = 1,
	@pbIsSubTypeCodeInUse = 1,
	@pbIsApplicationBasisCodeInUse = 1,
	@pbIsTitleInUse = 1,
	@pbIsLocalClientInUse = 1,
	@pbIsEntitySizeKeyInUse = 1,
	@pbIsPredecessorCaseKeyInUse = 1,
	@pbIsFileCoverCaseKeyInUse = 1,
	@pbIsPurchaseOrderNoInUse = 1,
	@pbIsCurrentOfficialNumberInUse = 1,
	@pbIsTaxRateCodeInUse = 1,
	@pbIsCaseOfficeKeyInUse = 1,
	@pbIsNoOfClaimsInUse = 1,
	@pbIsInstructionsReceivedDateInUse = 1,
	@pbIsIPOfficeDelayInUse = 1,
	@pbIsApplicantDelayInUse = 1,
	@pbIsIPOfficeAdjustmentInUse = 1


exec dbo.csw_FetchCase @pnUserIdentityId = 5, @psCulture = N'en', @pbCalledFromCentura = default, @pnCaseKey = @P1, @psCaseTypeCode = default, @pbNewRow = 0


exec dbo.csw_DeleteCase
	@pnUserIdentityId		= 5,		-- Mandatory
	@psCulture			= N'en',	
	@pbCalledFromCentura		= default,
	@pnCaseKey			= @P1,		-- Mandatory

	@psOldCaseReference		= N'Test2006427172316',
	@psOldFamilyCode		= N'E001',
	@psOldStem			= NULL,
	@pnOldStatusKey			= NULL,
	@psOldCaseTypeCode		= N'A',		
	@psOldPropertyTypeCode		= N'P',
	@psOldCountryCode		= N'AU',
	@psOldCaseCategoryCode		= N'N',
	@psOldSubTypeCode		= N'N',
	@pnOldTypeOfMarkKey		= NULL, --
	@psOldTitle			= N'Insert Case Test Case',
	@pnOldNoInSeries		= NULL, --
	@pnOldNoOfClasses		= NULL, --
	@psOldLocalClasses		= NULL, --
	@psOldIntClasses		= NULL, --
	@pbOldLocalClientFlag		= 0,
	@pnOldEntitySizeKey		= NULL,
	@pnOldPredecessorKey		= NULL,
	@pnOldFileCover			= NULL,
	@psOldPurchaseOrderNo		= NULL,
	@pbOldReportToThirdParty	= NULL,
	@psOldCurrentOfficialNo		= NULL,
	@psOldTaxCode			= NULL,
	@psOldStopPayReason		= NULL,
	@pnOldExtendedRenewals		= NULL,
	@pnOldBudgetAmount		= NULL,
	@pnOldIpoDelay			= 1,
	@pnOldApplicantDelay		= 1,
	@pnOldIpoPta			= 1,
	@pnOldOfficeKey			= 10175,
	@pnOldBudgetRevisedAmt		= NULL,
	
	@pbIsCaseReferenceInUse		= 1,
	@pbIsFamilyCodeInUse		= 1,
	@pbIsStemInUse			= 1,
	@pbIsStatusKeyInUse		= 1,
	@pbIsCaseTypeCodeInUse		= 1,		
	@pbIsPropertyTypeCodeInUse	= 1,
	@pbIsCountryCodeInUse		= 1,
	@pbIsCaseCategoryCodeInUse	= 1,
	@pbIsSubTypeCodeInUse		= 1,
	@pbIsTypeOfMarkKeyInUse		= 1,
	@pbIsTitleInUse			= 1,
	@pbIsNoInSeriesInUse		= 1,
	@pbIsNoOfClassesInUse		= 1,
	@pbIsLocalClassesInUse		= 1,
	@pbIsIntClassesInUse		= 1,
	@pbIsLocalClientFlagInUse	= 1,
	@pbIsEntitySizeKeyInUse		= 1,
	@pbIsPredecessorKeyInUse	= 1,
	@pbIsFileCoverInUse		= 1,
	@pbIsPurchaseOrderNoInUse	= 1,
	@pbIsReportToThirdPartyInUse	= 1,	
	@pbIsCurrentOfficialNoInUse	= 1,
	@pbIsTaxCodeInUse		= 1,
	@pbIsStopPayReasonInUse		= 1,
	@pbIsExtendedRenewalsInUse	= 1,
	@pbIsBudgetAmountInUse		= 1,
	@pbIsIpoDelayInUse		= 1,
	@pbIsApplicantDelayInUse	= 1,
	@pbIsIpoPtaInUse		= 1,
	@pbIsOfficeKeyInUse		= 1,
	@pbIsBudgetRevisedAmtInUse	= 1


exec dbo.csw_FetchCase @pnUserIdentityId = 5, @psCulture = N'en', @pbCalledFromCentura = default, @pnCaseKey = @P1, @psCaseTypeCode = default, @pbNewRow = 0