-----------------------------------------------------------------------------------------------------------------------------
-- Creation of fn_ccnEVENTCONTROL
-----------------------------------------------------------------------------------------------------------------------------
if exists (select * from sysobjects where id = object_id(N'[dbo].[fn_ccnEVENTCONTROL]') and xtype='IF')
begin
	print '**** Drop function dbo.fn_ccnEVENTCONTROL.'
	drop function dbo.fn_ccnEVENTCONTROL
	print '**** Creating function dbo.fn_ccnEVENTCONTROL...'
	print ''
end
go

SET NOCOUNT ON
go

-- Table must exist at time of function creation.
if not exists (select * from sysobjects where id = object_id(N'[CCImport_EVENTCONTROL]') and xtype='U')
begin
	select * 
	into CCImport_EVENTCONTROL 
	from EVENTCONTROL
	where 1=0
end
go


SET QUOTED_IDENTIFIER OFF 
go


CREATE FUNCTION dbo.fn_ccnEVENTCONTROL
(
@psUserName			nvarchar(40)	= 'dbo' -- the current user name which will have created the 'CCImport_' tables dbo used as default for security error instead of crash
)
RETURNS TABLE

-- FUNCTION :	fn_ccnEVENTCONTROL
-- VERSION :	2
-- DESCRIPTION:	The SELECT to display of imported data for the EVENTCONTROL table
-- CALLED BY :	xml_CopyConfigImport
-- MODIFICATIONS
-- Date		Who	Number	Version	Description
-- ----         ---	------	-------	-----------------------------------------------------------
-- 20 Feb 2013	System		1	Function generated
-- 01 May 2017	MF	71205	2	Add new column RENEWALSTATUS
--
As 
Return
select	5 as TRIPNO, 'EVENTCONTROL' as TABLENAME, count(*) as 'MISSING', 0 as 'NEW', 0 as 'CHANGE', 0 as 'MATCH'
from CCImport_EVENTCONTROL I 
	right join EVENTCONTROL C on( C.CRITERIANO=I.CRITERIANO
and  C.EVENTNO=I.EVENTNO)
where I.CRITERIANO is null
UNION ALL 
select	5, 'EVENTCONTROL', 0, count(*), 0, 0
from CCImport_EVENTCONTROL I 
	left join EVENTCONTROL C on( C.CRITERIANO=I.CRITERIANO
and  C.EVENTNO=I.EVENTNO)
where C.CRITERIANO is null
UNION ALL 
 select	5, 'EVENTCONTROL', 0, 0, count(*), 0
from CCImport_EVENTCONTROL I 
	join EVENTCONTROL C	on ( C.CRITERIANO=I.CRITERIANO
	and C.EVENTNO=I.EVENTNO)
where 	( I.EVENTNO <>  C.EVENTNO)
	OR 	( I.EVENTDESCRIPTION <>  C.EVENTDESCRIPTION OR (I.EVENTDESCRIPTION is null and C.EVENTDESCRIPTION is not null) 
OR (I.EVENTDESCRIPTION is not null and C.EVENTDESCRIPTION is null))
	OR 	( I.PARENTCRITERIANO <>  C.PARENTCRITERIANO OR (I.PARENTCRITERIANO is null and C.PARENTCRITERIANO is not null) 
OR (I.PARENTCRITERIANO is not null and C.PARENTCRITERIANO is null))
	OR 	( I.PARENTEVENTNO <>  C.PARENTEVENTNO OR (I.PARENTEVENTNO is null and C.PARENTEVENTNO is not null) 
OR (I.PARENTEVENTNO is not null and C.PARENTEVENTNO is null))
	OR 	( I.NUMCYCLESALLOWED <>  C.NUMCYCLESALLOWED OR (I.NUMCYCLESALLOWED is null and C.NUMCYCLESALLOWED is not null) 
OR (I.NUMCYCLESALLOWED is not null and C.NUMCYCLESALLOWED is null))
	OR 	( I.IMPORTANCELEVEL <>  C.IMPORTANCELEVEL OR (I.IMPORTANCELEVEL is null and C.IMPORTANCELEVEL is not null) 
OR (I.IMPORTANCELEVEL is not null and C.IMPORTANCELEVEL is null))
	OR 	( I.WHICHDUEDATE <>  C.WHICHDUEDATE OR (I.WHICHDUEDATE is null and C.WHICHDUEDATE is not null) 
OR (I.WHICHDUEDATE is not null and C.WHICHDUEDATE is null))
	OR 	( I.COMPAREBOOLEAN <>  C.COMPAREBOOLEAN OR (I.COMPAREBOOLEAN is null and C.COMPAREBOOLEAN is not null) 
OR (I.COMPAREBOOLEAN is not null and C.COMPAREBOOLEAN is null))
	OR 	( I.CHECKCOUNTRYFLAG <>  C.CHECKCOUNTRYFLAG OR (I.CHECKCOUNTRYFLAG is null and C.CHECKCOUNTRYFLAG is not null) 
OR (I.CHECKCOUNTRYFLAG is not null and C.CHECKCOUNTRYFLAG is null))
	OR 	( I.SAVEDUEDATE <>  C.SAVEDUEDATE OR (I.SAVEDUEDATE is null and C.SAVEDUEDATE is not null) 
OR (I.SAVEDUEDATE is not null and C.SAVEDUEDATE is null))
	OR 	( I.STATUSCODE <>  C.STATUSCODE OR (I.STATUSCODE is null and C.STATUSCODE is not null) 
OR (I.STATUSCODE is not null and C.STATUSCODE is null))
	OR 	( I.SPECIALFUNCTION <>  C.SPECIALFUNCTION OR (I.SPECIALFUNCTION is null and C.SPECIALFUNCTION is not null) 
OR (I.SPECIALFUNCTION is not null and C.SPECIALFUNCTION is null))
	OR 	( I.INITIALFEE <>  C.INITIALFEE OR (I.INITIALFEE is null and C.INITIALFEE is not null) 
OR (I.INITIALFEE is not null and C.INITIALFEE is null))
	OR 	( I.PAYFEECODE <>  C.PAYFEECODE OR (I.PAYFEECODE is null and C.PAYFEECODE is not null) 
OR (I.PAYFEECODE is not null and C.PAYFEECODE is null))
	OR 	( I.CREATEACTION <>  C.CREATEACTION OR (I.CREATEACTION is null and C.CREATEACTION is not null) 
OR (I.CREATEACTION is not null and C.CREATEACTION is null))
	OR 	( I.STATUSDESC <>  C.STATUSDESC OR (I.STATUSDESC is null and C.STATUSDESC is not null) 
OR (I.STATUSDESC is not null and C.STATUSDESC is null))
	OR 	( I.CLOSEACTION <>  C.CLOSEACTION OR (I.CLOSEACTION is null and C.CLOSEACTION is not null) 
OR (I.CLOSEACTION is not null and C.CLOSEACTION is null))
	OR 	( I.UPDATEFROMEVENT <>  C.UPDATEFROMEVENT OR (I.UPDATEFROMEVENT is null and C.UPDATEFROMEVENT is not null) 
OR (I.UPDATEFROMEVENT is not null and C.UPDATEFROMEVENT is null))
	OR 	( I.FROMRELATIONSHIP <>  C.FROMRELATIONSHIP OR (I.FROMRELATIONSHIP is null and C.FROMRELATIONSHIP is not null) 
OR (I.FROMRELATIONSHIP is not null and C.FROMRELATIONSHIP is null))
	OR 	( I.FROMANCESTOR <>  C.FROMANCESTOR OR (I.FROMANCESTOR is null and C.FROMANCESTOR is not null) 
OR (I.FROMANCESTOR is not null and C.FROMANCESTOR is null))
	OR 	( I.UPDATEMANUALLY <>  C.UPDATEMANUALLY OR (I.UPDATEMANUALLY is null and C.UPDATEMANUALLY is not null) 
OR (I.UPDATEMANUALLY is not null and C.UPDATEMANUALLY is null))
	OR 	( I.ADJUSTMENT <>  C.ADJUSTMENT OR (I.ADJUSTMENT is null and C.ADJUSTMENT is not null) 
OR (I.ADJUSTMENT is not null and C.ADJUSTMENT is null))
	OR 	( I.DOCUMENTNO <>  C.DOCUMENTNO OR (I.DOCUMENTNO is null and C.DOCUMENTNO is not null) 
OR (I.DOCUMENTNO is not null and C.DOCUMENTNO is null))
	OR 	( I.NOOFDOCS <>  C.NOOFDOCS OR (I.NOOFDOCS is null and C.NOOFDOCS is not null) 
OR (I.NOOFDOCS is not null and C.NOOFDOCS is null))
	OR 	( I.MANDATORYDOCS <>  C.MANDATORYDOCS OR (I.MANDATORYDOCS is null and C.MANDATORYDOCS is not null) 
OR (I.MANDATORYDOCS is not null and C.MANDATORYDOCS is null))
	OR 	( replace(CAST(I.NOTES as NVARCHAR(MAX)),char(10),char(13)+char(10)) <>  CAST(C.NOTES as NVARCHAR(MAX)) OR (I.NOTES is null and C.NOTES is not null) 
OR (I.NOTES is not null and C.NOTES is null))
	OR 	( I.INHERITED <>  C.INHERITED OR (I.INHERITED is null and C.INHERITED is not null) 
OR (I.INHERITED is not null and C.INHERITED is null))
	OR 	( I.INSTRUCTIONTYPE <>  C.INSTRUCTIONTYPE OR (I.INSTRUCTIONTYPE is null and C.INSTRUCTIONTYPE is not null) 
OR (I.INSTRUCTIONTYPE is not null and C.INSTRUCTIONTYPE is null))
	OR 	( I.FLAGNUMBER <>  C.FLAGNUMBER OR (I.FLAGNUMBER is null and C.FLAGNUMBER is not null) 
OR (I.FLAGNUMBER is not null and C.FLAGNUMBER is null))
	OR 	( I.SETTHIRDPARTYON <>  C.SETTHIRDPARTYON OR (I.SETTHIRDPARTYON is null and C.SETTHIRDPARTYON is not null) 
OR (I.SETTHIRDPARTYON is not null and C.SETTHIRDPARTYON is null))
	OR 	( I.RELATIVECYCLE <>  C.RELATIVECYCLE OR (I.RELATIVECYCLE is null and C.RELATIVECYCLE is not null) 
OR (I.RELATIVECYCLE is not null and C.RELATIVECYCLE is null))
	OR 	( I.CREATECYCLE <>  C.CREATECYCLE OR (I.CREATECYCLE is null and C.CREATECYCLE is not null) 
OR (I.CREATECYCLE is not null and C.CREATECYCLE is null))
	OR 	( I.ESTIMATEFLAG <>  C.ESTIMATEFLAG OR (I.ESTIMATEFLAG is null and C.ESTIMATEFLAG is not null) 
OR (I.ESTIMATEFLAG is not null and C.ESTIMATEFLAG is null))
	OR 	( I.EXTENDPERIOD <>  C.EXTENDPERIOD OR (I.EXTENDPERIOD is null and C.EXTENDPERIOD is not null) 
OR (I.EXTENDPERIOD is not null and C.EXTENDPERIOD is null))
	OR 	( I.EXTENDPERIODTYPE <>  C.EXTENDPERIODTYPE OR (I.EXTENDPERIODTYPE is null and C.EXTENDPERIODTYPE is not null) 
OR (I.EXTENDPERIODTYPE is not null and C.EXTENDPERIODTYPE is null))
	OR 	( I.INITIALFEE2 <>  C.INITIALFEE2 OR (I.INITIALFEE2 is null and C.INITIALFEE2 is not null) 
OR (I.INITIALFEE2 is not null and C.INITIALFEE2 is null))
	OR 	( I.PAYFEECODE2 <>  C.PAYFEECODE2 OR (I.PAYFEECODE2 is null and C.PAYFEECODE2 is not null) 
OR (I.PAYFEECODE2 is not null and C.PAYFEECODE2 is null))
	OR 	( I.ESTIMATEFLAG2 <>  C.ESTIMATEFLAG2 OR (I.ESTIMATEFLAG2 is null and C.ESTIMATEFLAG2 is not null) 
OR (I.ESTIMATEFLAG2 is not null and C.ESTIMATEFLAG2 is null))
	OR 	( I.PTADELAY <>  C.PTADELAY OR (I.PTADELAY is null and C.PTADELAY is not null) 
OR (I.PTADELAY is not null and C.PTADELAY is null))
	OR 	( I.SETTHIRDPARTYOFF <>  C.SETTHIRDPARTYOFF OR (I.SETTHIRDPARTYOFF is null and C.SETTHIRDPARTYOFF is not null) 
OR (I.SETTHIRDPARTYOFF is not null and C.SETTHIRDPARTYOFF is null))
	OR 	( I.RECEIVINGCYCLEFLAG <>  C.RECEIVINGCYCLEFLAG OR (I.RECEIVINGCYCLEFLAG is null and C.RECEIVINGCYCLEFLAG is not null) 
OR (I.RECEIVINGCYCLEFLAG is not null and C.RECEIVINGCYCLEFLAG is null))
	OR 	( I.RECALCEVENTDATE <>  C.RECALCEVENTDATE OR (I.RECALCEVENTDATE is null and C.RECALCEVENTDATE is not null) 
OR (I.RECALCEVENTDATE is not null and C.RECALCEVENTDATE is null))
	OR 	( I.CHANGENAMETYPE <>  C.CHANGENAMETYPE OR (I.CHANGENAMETYPE is null and C.CHANGENAMETYPE is not null) 
OR (I.CHANGENAMETYPE is not null and C.CHANGENAMETYPE is null))
	OR 	( I.COPYFROMNAMETYPE <>  C.COPYFROMNAMETYPE OR (I.COPYFROMNAMETYPE is null and C.COPYFROMNAMETYPE is not null) 
OR (I.COPYFROMNAMETYPE is not null and C.COPYFROMNAMETYPE is null))
	OR 	( I.COPYTONAMETYPE <>  C.COPYTONAMETYPE OR (I.COPYTONAMETYPE is null and C.COPYTONAMETYPE is not null) 
OR (I.COPYTONAMETYPE is not null and C.COPYTONAMETYPE is null))
	OR 	( I.DELCOPYFROMNAME <>  C.DELCOPYFROMNAME OR (I.DELCOPYFROMNAME is null and C.DELCOPYFROMNAME is not null) 
OR (I.DELCOPYFROMNAME is not null and C.DELCOPYFROMNAME is null))
	OR 	( I.CASETYPE <>  C.CASETYPE OR (I.CASETYPE is null and C.CASETYPE is not null) 
OR (I.CASETYPE is not null and C.CASETYPE is null))
	OR 	( I.COUNTRYCODE <>  C.COUNTRYCODE OR (I.COUNTRYCODE is null and C.COUNTRYCODE is not null) 
OR (I.COUNTRYCODE is not null and C.COUNTRYCODE is null))
	OR 	( I.COUNTRYCODEISTHISCASE <>  C.COUNTRYCODEISTHISCASE OR (I.COUNTRYCODEISTHISCASE is null and C.COUNTRYCODEISTHISCASE is not null) 
OR (I.COUNTRYCODEISTHISCASE is not null and C.COUNTRYCODEISTHISCASE is null))
	OR 	( I.PROPERTYTYPE <>  C.PROPERTYTYPE OR (I.PROPERTYTYPE is null and C.PROPERTYTYPE is not null) 
OR (I.PROPERTYTYPE is not null and C.PROPERTYTYPE is null))
	OR 	( I.PROPERTYTYPEISTHISCASE <>  C.PROPERTYTYPEISTHISCASE OR (I.PROPERTYTYPEISTHISCASE is null and C.PROPERTYTYPEISTHISCASE is not null) 
OR (I.PROPERTYTYPEISTHISCASE is not null and C.PROPERTYTYPEISTHISCASE is null))
	OR 	( I.CASECATEGORY <>  C.CASECATEGORY OR (I.CASECATEGORY is null and C.CASECATEGORY is not null) 
OR (I.CASECATEGORY is not null and C.CASECATEGORY is null))
	OR 	( I.CATEGORYISTHISCASE <>  C.CATEGORYISTHISCASE OR (I.CATEGORYISTHISCASE is null and C.CATEGORYISTHISCASE is not null) 
OR (I.CATEGORYISTHISCASE is not null and C.CATEGORYISTHISCASE is null))
	OR 	( I.SUBTYPE <>  C.SUBTYPE OR (I.SUBTYPE is null and C.SUBTYPE is not null) 
OR (I.SUBTYPE is not null and C.SUBTYPE is null))
	OR 	( I.SUBTYPEISTHISCASE <>  C.SUBTYPEISTHISCASE OR (I.SUBTYPEISTHISCASE is null and C.SUBTYPEISTHISCASE is not null) 
OR (I.SUBTYPEISTHISCASE is not null and C.SUBTYPEISTHISCASE is null))
	OR 	( I.BASIS <>  C.BASIS OR (I.BASIS is null and C.BASIS is not null) 
OR (I.BASIS is not null and C.BASIS is null))
	OR 	( I.BASISISTHISCASE <>  C.BASISISTHISCASE OR (I.BASISISTHISCASE is null and C.BASISISTHISCASE is not null) 
OR (I.BASISISTHISCASE is not null and C.BASISISTHISCASE is null))
	OR 	( I.DIRECTPAYFLAG <>  C.DIRECTPAYFLAG OR (I.DIRECTPAYFLAG is null and C.DIRECTPAYFLAG is not null) 
OR (I.DIRECTPAYFLAG is not null and C.DIRECTPAYFLAG is null))
	OR 	( I.DIRECTPAYFLAG2 <>  C.DIRECTPAYFLAG2 OR (I.DIRECTPAYFLAG2 is null and C.DIRECTPAYFLAG2 is not null) 
OR (I.DIRECTPAYFLAG2 is not null and C.DIRECTPAYFLAG2 is null))
	OR 	( I.OFFICEID <>  C.OFFICEID OR (I.OFFICEID is null and C.OFFICEID is not null) 
OR (I.OFFICEID is not null and C.OFFICEID is null))
	OR 	( I.OFFICEIDISTHISCASE <>  C.OFFICEIDISTHISCASE OR (I.OFFICEIDISTHISCASE is null and C.OFFICEIDISTHISCASE is not null) 
OR (I.OFFICEIDISTHISCASE is not null and C.OFFICEIDISTHISCASE is null))
	OR 	( I.DUEDATERESPNAMETYPE <>  C.DUEDATERESPNAMETYPE OR (I.DUEDATERESPNAMETYPE is null and C.DUEDATERESPNAMETYPE is not null) 
OR (I.DUEDATERESPNAMETYPE is not null and C.DUEDATERESPNAMETYPE is null))
	OR 	( I.DUEDATERESPNAMENO <>  C.DUEDATERESPNAMENO OR (I.DUEDATERESPNAMENO is null and C.DUEDATERESPNAMENO is not null) 
OR (I.DUEDATERESPNAMENO is not null and C.DUEDATERESPNAMENO is null))
	OR 	( I.LOADNUMBERTYPE <>  C.LOADNUMBERTYPE OR (I.LOADNUMBERTYPE is null and C.LOADNUMBERTYPE is not null) 
OR (I.LOADNUMBERTYPE is not null and C.LOADNUMBERTYPE is null))
	OR 	( I.SUPPRESSCALCULATION <>  C.SUPPRESSCALCULATION OR (I.SUPPRESSCALCULATION is null and C.SUPPRESSCALCULATION is not null) 
OR (I.SUPPRESSCALCULATION is not null and C.SUPPRESSCALCULATION is null))
	OR 	( I.RENEWALSTATUS <>  C.RENEWALSTATUS OR (I.RENEWALSTATUS is null and C.RENEWALSTATUS is not null) 
OR (I.RENEWALSTATUS is not null and C.RENEWALSTATUS is null))
/* DISPLAYSEQUENCE : column intentionally excluded from comparison display but will be updated if different. */
UNION ALL 
 select	5, 'EVENTCONTROL', 0, 0, 0, count(*)
from CCImport_EVENTCONTROL I 
join EVENTCONTROL C	on( C.CRITERIANO=I.CRITERIANO
and C.EVENTNO=I.EVENTNO)
where ( I.EVENTNO =  C.EVENTNO)
and ( I.EVENTDESCRIPTION =  C.EVENTDESCRIPTION OR (I.EVENTDESCRIPTION is null and C.EVENTDESCRIPTION is null))
and ( I.PARENTCRITERIANO =  C.PARENTCRITERIANO OR (I.PARENTCRITERIANO is null and C.PARENTCRITERIANO is null))
and ( I.PARENTEVENTNO =  C.PARENTEVENTNO OR (I.PARENTEVENTNO is null and C.PARENTEVENTNO is null))
and ( I.NUMCYCLESALLOWED =  C.NUMCYCLESALLOWED OR (I.NUMCYCLESALLOWED is null and C.NUMCYCLESALLOWED is null))
and ( I.IMPORTANCELEVEL =  C.IMPORTANCELEVEL OR (I.IMPORTANCELEVEL is null and C.IMPORTANCELEVEL is null))
and ( I.WHICHDUEDATE =  C.WHICHDUEDATE OR (I.WHICHDUEDATE is null and C.WHICHDUEDATE is null))
and ( I.COMPAREBOOLEAN =  C.COMPAREBOOLEAN OR (I.COMPAREBOOLEAN is null and C.COMPAREBOOLEAN is null))
and ( I.CHECKCOUNTRYFLAG =  C.CHECKCOUNTRYFLAG OR (I.CHECKCOUNTRYFLAG is null and C.CHECKCOUNTRYFLAG is null))
and ( I.SAVEDUEDATE =  C.SAVEDUEDATE OR (I.SAVEDUEDATE is null and C.SAVEDUEDATE is null))
and ( I.STATUSCODE =  C.STATUSCODE OR (I.STATUSCODE is null and C.STATUSCODE is null))
and ( I.SPECIALFUNCTION =  C.SPECIALFUNCTION OR (I.SPECIALFUNCTION is null and C.SPECIALFUNCTION is null))
and ( I.INITIALFEE =  C.INITIALFEE OR (I.INITIALFEE is null and C.INITIALFEE is null))
and ( I.PAYFEECODE =  C.PAYFEECODE OR (I.PAYFEECODE is null and C.PAYFEECODE is null))
and ( I.CREATEACTION =  C.CREATEACTION OR (I.CREATEACTION is null and C.CREATEACTION is null))
and ( I.STATUSDESC =  C.STATUSDESC OR (I.STATUSDESC is null and C.STATUSDESC is null))
and ( I.CLOSEACTION =  C.CLOSEACTION OR (I.CLOSEACTION is null and C.CLOSEACTION is null))
and ( I.UPDATEFROMEVENT =  C.UPDATEFROMEVENT OR (I.UPDATEFROMEVENT is null and C.UPDATEFROMEVENT is null))
and ( I.FROMRELATIONSHIP =  C.FROMRELATIONSHIP OR (I.FROMRELATIONSHIP is null and C.FROMRELATIONSHIP is null))
and ( I.FROMANCESTOR =  C.FROMANCESTOR OR (I.FROMANCESTOR is null and C.FROMANCESTOR is null))
and ( I.UPDATEMANUALLY =  C.UPDATEMANUALLY OR (I.UPDATEMANUALLY is null and C.UPDATEMANUALLY is null))
and ( I.ADJUSTMENT =  C.ADJUSTMENT OR (I.ADJUSTMENT is null and C.ADJUSTMENT is null))
and ( I.DOCUMENTNO =  C.DOCUMENTNO OR (I.DOCUMENTNO is null and C.DOCUMENTNO is null))
and ( I.NOOFDOCS =  C.NOOFDOCS OR (I.NOOFDOCS is null and C.NOOFDOCS is null))
and ( I.MANDATORYDOCS =  C.MANDATORYDOCS OR (I.MANDATORYDOCS is null and C.MANDATORYDOCS is null))
and ( replace(CAST(I.NOTES as NVARCHAR(MAX)),char(10),char(13)+char(10)) =  CAST(C.NOTES as NVARCHAR(MAX)) OR (I.NOTES is null and C.NOTES is null))
and ( I.INHERITED =  C.INHERITED OR (I.INHERITED is null and C.INHERITED is null))
and ( I.INSTRUCTIONTYPE =  C.INSTRUCTIONTYPE OR (I.INSTRUCTIONTYPE is null and C.INSTRUCTIONTYPE is null))
and ( I.FLAGNUMBER =  C.FLAGNUMBER OR (I.FLAGNUMBER is null and C.FLAGNUMBER is null))
and ( I.SETTHIRDPARTYON =  C.SETTHIRDPARTYON OR (I.SETTHIRDPARTYON is null and C.SETTHIRDPARTYON is null))
and ( I.RELATIVECYCLE =  C.RELATIVECYCLE OR (I.RELATIVECYCLE is null and C.RELATIVECYCLE is null))
and ( I.CREATECYCLE =  C.CREATECYCLE OR (I.CREATECYCLE is null and C.CREATECYCLE is null))
and ( I.ESTIMATEFLAG =  C.ESTIMATEFLAG OR (I.ESTIMATEFLAG is null and C.ESTIMATEFLAG is null))
and ( I.EXTENDPERIOD =  C.EXTENDPERIOD OR (I.EXTENDPERIOD is null and C.EXTENDPERIOD is null))
and ( I.EXTENDPERIODTYPE =  C.EXTENDPERIODTYPE OR (I.EXTENDPERIODTYPE is null and C.EXTENDPERIODTYPE is null))
and ( I.INITIALFEE2 =  C.INITIALFEE2 OR (I.INITIALFEE2 is null and C.INITIALFEE2 is null))
and ( I.PAYFEECODE2 =  C.PAYFEECODE2 OR (I.PAYFEECODE2 is null and C.PAYFEECODE2 is null))
and ( I.ESTIMATEFLAG2 =  C.ESTIMATEFLAG2 OR (I.ESTIMATEFLAG2 is null and C.ESTIMATEFLAG2 is null))
and ( I.PTADELAY =  C.PTADELAY OR (I.PTADELAY is null and C.PTADELAY is null))
and ( I.SETTHIRDPARTYOFF =  C.SETTHIRDPARTYOFF OR (I.SETTHIRDPARTYOFF is null and C.SETTHIRDPARTYOFF is null))
and ( I.RECEIVINGCYCLEFLAG =  C.RECEIVINGCYCLEFLAG OR (I.RECEIVINGCYCLEFLAG is null and C.RECEIVINGCYCLEFLAG is null))
and ( I.RECALCEVENTDATE =  C.RECALCEVENTDATE OR (I.RECALCEVENTDATE is null and C.RECALCEVENTDATE is null))
and ( I.CHANGENAMETYPE =  C.CHANGENAMETYPE OR (I.CHANGENAMETYPE is null and C.CHANGENAMETYPE is null))
and ( I.COPYFROMNAMETYPE =  C.COPYFROMNAMETYPE OR (I.COPYFROMNAMETYPE is null and C.COPYFROMNAMETYPE is null))
and ( I.COPYTONAMETYPE =  C.COPYTONAMETYPE OR (I.COPYTONAMETYPE is null and C.COPYTONAMETYPE is null))
and ( I.DELCOPYFROMNAME =  C.DELCOPYFROMNAME OR (I.DELCOPYFROMNAME is null and C.DELCOPYFROMNAME is null))
and ( I.CASETYPE =  C.CASETYPE OR (I.CASETYPE is null and C.CASETYPE is null))
and ( I.COUNTRYCODE =  C.COUNTRYCODE OR (I.COUNTRYCODE is null and C.COUNTRYCODE is null))
and ( I.COUNTRYCODEISTHISCASE =  C.COUNTRYCODEISTHISCASE OR (I.COUNTRYCODEISTHISCASE is null and C.COUNTRYCODEISTHISCASE is null))
and ( I.PROPERTYTYPE =  C.PROPERTYTYPE OR (I.PROPERTYTYPE is null and C.PROPERTYTYPE is null))
and ( I.PROPERTYTYPEISTHISCASE =  C.PROPERTYTYPEISTHISCASE OR (I.PROPERTYTYPEISTHISCASE is null and C.PROPERTYTYPEISTHISCASE is null))
and ( I.CASECATEGORY =  C.CASECATEGORY OR (I.CASECATEGORY is null and C.CASECATEGORY is null))
and ( I.CATEGORYISTHISCASE =  C.CATEGORYISTHISCASE OR (I.CATEGORYISTHISCASE is null and C.CATEGORYISTHISCASE is null))
and ( I.SUBTYPE =  C.SUBTYPE OR (I.SUBTYPE is null and C.SUBTYPE is null))
and ( I.SUBTYPEISTHISCASE =  C.SUBTYPEISTHISCASE OR (I.SUBTYPEISTHISCASE is null and C.SUBTYPEISTHISCASE is null))
and ( I.BASIS =  C.BASIS OR (I.BASIS is null and C.BASIS is null))
and ( I.BASISISTHISCASE =  C.BASISISTHISCASE OR (I.BASISISTHISCASE is null and C.BASISISTHISCASE is null))
and ( I.DIRECTPAYFLAG =  C.DIRECTPAYFLAG OR (I.DIRECTPAYFLAG is null and C.DIRECTPAYFLAG is null))
and ( I.DIRECTPAYFLAG2 =  C.DIRECTPAYFLAG2 OR (I.DIRECTPAYFLAG2 is null and C.DIRECTPAYFLAG2 is null))
and ( I.OFFICEID =  C.OFFICEID OR (I.OFFICEID is null and C.OFFICEID is null))
and ( I.OFFICEIDISTHISCASE =  C.OFFICEIDISTHISCASE OR (I.OFFICEIDISTHISCASE is null and C.OFFICEIDISTHISCASE is null))
and ( I.DUEDATERESPNAMETYPE =  C.DUEDATERESPNAMETYPE OR (I.DUEDATERESPNAMETYPE is null and C.DUEDATERESPNAMETYPE is null))
and ( I.DUEDATERESPNAMENO =  C.DUEDATERESPNAMENO OR (I.DUEDATERESPNAMENO is null and C.DUEDATERESPNAMENO is null))
and ( I.LOADNUMBERTYPE =  C.LOADNUMBERTYPE OR (I.LOADNUMBERTYPE is null and C.LOADNUMBERTYPE is null))
and ( I.SUPPRESSCALCULATION =  C.SUPPRESSCALCULATION OR (I.SUPPRESSCALCULATION is null and C.SUPPRESSCALCULATION is null))
and ( I.RENEWALSTATUS =  C.RENEWALSTATUS OR (I.RENEWALSTATUS is null and C.RENEWALSTATUS is null))
/* DISPLAYSEQUENCE : column intentionally excluded from comparison display but will be updated if different. */

go

-- Remove table now that function is created.
if  exists (select * from sysobjects where id = object_id(N'[CCImport_EVENTCONTROL]') and xtype='U')
begin
	drop table CCImport_EVENTCONTROL 
end
go
grant DELETE, INSERT, REFERENCES, SELECT, UPDATE on dbo.fn_ccnEVENTCONTROL  to public
go
