-----------------------------------------------------------------------------------------------------------------------------
-- Creation of fn_GetCriteriaRowsForControl
-----------------------------------------------------------------------------------------------------------------------------
if exists (select * from sysobjects where id = object_id('dbo.fn_GetCriteriaRowsForControl') and xtype='TF')
begin
	print '**** Drop function dbo.fn_GetCriteriaRowsForControl.'
	drop function dbo.fn_GetCriteriaRowsForControl
end
print '**** Creating function dbo.fn_GetCriteriaRowsForControl...'
print ''
go

set QUOTED_IDENTIFIER off
go

Create Function dbo.fn_GetCriteriaRowsForControl
			(
			@psPurposeCode		nchar(1),
 	 		@pnCaseOfficeID		int,
			@psCaseType		nchar(1),
			@psAction		nvarchar(2),
			@pnCheckListType	smallint,
			@psProgramID		nvarchar(8),
			@pnRateNo		int,
			@psPropertyType		nchar(1),
			@psCountryCode		nvarchar(3),
			@psCaseCategory		nvarchar(2),
			@psSubType		nvarchar(2),
			@psBasis		nvarchar(2),
			@psRegisteredUsers	nchar(1),
			@pnTypeOfMark		int,
			@pnLocalClientFlag	decimal(1,0),
			@pnTableCode		int,
			@pdtDateOfAct		datetime,
			@pnRuleInUse		decimal(1,0),
			@pnPropertyUnknown	decimal(1,0),
			@pnCountryUnknown	decimal(1,0),
			@pnCategoryUnknown	decimal(1,0),
			@pnSubTypeUnknown	decimal(1,0),
			@psNewCaseType		nchar(1),
			@psNewPropertyType	nchar(1),
			@psNewCountryCode	nvarchar(3),
			@psNewCaseCategory	nvarchar(2),
			@pnRuleType		int,		--SQA12298
			@psRequestType		nvarchar(50),	--SQA12298
			@pnDataSourceType	int,		--SQA12298
			@pnDataSourceNameNo	int,		--SQA12298
			@pnRenewalStatus	smallint,	--SQA12298
			@pnStatusCode		smallint,	--SQA12298
			@pbExactMatch		bit,
			@pnProfileKey		int = null,
			@pbUserDefinedRule	bit,		--SQA21419
			@psNewSubType		nvarchar(2) 	--SQA21395	
			)

Returns @tbCriteria TABLE
   (      
	CRITERIANO		int		primary key,
	PURPOSECODE		nchar(1)	collate database_default,
	CASETYPE		nchar(1)	collate database_default,
	[ACTION]		nvarchar(2)	collate database_default,
	CHECKLISTTYPE		smallint,
	PROGRAMID		nvarchar(8)	collate database_default,
	PROPERTYTYPE		nchar(1)	collate database_default,
	PROPERTYUNKNOWN		decimal(1,0),
	COUNTRYCODE		nvarchar(3)	collate database_default,
	COUNTRYUNKNOWN		decimal(1),
	CASECATEGORY		nvarchar(2)	collate database_default,
	CATEGORYUNKNOWN		decimal(1,0),
	SUBTYPE			nvarchar(2)	collate database_default,
	SUBTYPEUNKNOWN		decimal(1),
	BASIS			nvarchar(2)	collate database_default,
	REGISTEREDUSERS		nchar(1)	collate database_default,
	LOCALCLIENTFLAG		decimal(1,0),
	TABLECODE		int,
	RATENO			int,
	DATEOFACT		datetime,
	USERDEFINEDRULE		decimal(1,0),
	RULEINUSE		decimal(1,0),
	STARTDETAILENTRY	decimal(1,0),
	PARENTCRITERIA		int,
	BELONGSTOGROUP		decimal(1,0),
	[DESCRIPTION]		nvarchar(254)	collate database_default,
	TYPEOFMARK		int,
	RENEWALTYPE		int,
	DESCRIPTION_TID		int,
	CASEOFFICEID		int,
	LINKTITLE		nvarchar(100)	collate database_default,
	LINKTITLE_TID		int,
	LINKDESCRIPTION		nvarchar(254)	collate database_default,
	LINKDESCRIPTION_TID	int,
	DOCITEMID		int,
	URL			nvarchar(254)	collate database_default,
	ISPUBLIC		bit,
	GROUPID			int,
	PRODUCTCODE		int,
	NEWCASETYPE 		nchar(1) 	collate database_default,
	NEWCOUNTRYCODE 		nvarchar(3) 	collate database_default,
	NEWPROPERTYTYPE 	nchar(1) 	collate database_default,
	NEWCASECATEGORY 	nvarchar(2) 	collate database_default,
	PROFILENAME 		nvarchar(50) 	collate database_default,
	SYSTEMID		smallint,					--SQA12298
	DATAEXTRACTID		smallint,
	RULETYPE		int,						--SQA12298
	REQUESTTYPE		nvarchar(50) 	collate database_default,	--SQA12298
	DATASOURCETYPE		int,						--SQA12298
	DATASOURCENAMENO	int,						--SQA12298
	RENEWALSTATUS		smallint,					--SQA12298
	STATUSCODE		smallint,					--SQA12298
	BESTFIT			nvarchar(20)	collate database_default,
	PROFILEID		int,
	CPARENEWALTYPE		nvarchar(100)   collate database_default,	--SQA19144	
	NEWSUBTYPE		nvarchar(2)	collate database_default	--SQA21395	
   )

as
-- FUNCTION :	fn_GetCriteriaRowsForControl
-- VERSION  :	5
-- COPYRIGHT:	Copyright CPA Software Solutions (Australia) Pty Limited
-- DESCRIPTION:	A Copy of fn_GetCriteriaRows with additional filter parameters for use by the Control program.
--		This function returns CRITERIA row details that match either exactly the 
--		non NULL input parameters or match based on the Best Fit search algorithm.
--		If an exact match is not required then the Best Fit search will determine
--		a BESTFIT value that indicates how well each returned row matches.
--		PurposeCode	Type of Control
--		===========     ===============
--		    A		CPA Renewal Type
--		    C		Checklist
--		    D		USPTO/PAIR
--		    E		Events & Entries
--		    F		Fees & Charges
--		    R		IRN Generation
--		    S		Screen Control
--		    L		Case Links
--		    P		Copy Profile
--		    W		Workbench Windows
--		    U		Update Rules
--		    X		Import Law Blocking
 

-- MODIFICATIONS :
-- Date		Who	Change	Version	Description
-- -----------	-------	------	-------	----------------------------------------------- 
-- 17 Jul 2013	DL	S21419	1	Allow a "Modifiable" filter to only show Criteria that the user is allowed to edit
-- 19 Jul 2013	DL	S21395	2	Include SubType in the determination of the defaul Copy Profile to use
-- 01 Jun 2016	MF	62311	3	When performing a best fit search for Events & Entries , also consider Criteria where RULEINUSE is not set to 1 so that
--					these will be available to the Tree Display.  If there are no Criteria found where RULEINUSE=1 then
--					no result will be returned.  
-- 02 Jun 2016	MF	62311	4	The best fit query for Events & Entries should consider both user defined rules and CPA supplied rules. 
-- 07 Jul 2016	MF	63861	5	A null LOCALCLIENTFLAG should default to 0.

Begin
	If @pnLocalClientFlag is null
	and ISNULL(@pbExactMatch,0)=0
		set @pnLocalClientFlag=0
		
	If @pbExactMatch=1
	begin
		Insert into @tbCriteria(
			CRITERIANO,  PURPOSECODE,  CASETYPE,  ACTION,  CHECKLISTTYPE,  PROGRAMID,  PROPERTYTYPE,
			PROPERTYUNKNOWN,  COUNTRYCODE,  COUNTRYUNKNOWN,  CASECATEGORY,  CATEGORYUNKNOWN,
			SUBTYPE,  SUBTYPEUNKNOWN,  BASIS,  REGISTEREDUSERS,  LOCALCLIENTFLAG,  TABLECODE,  RATENO,
			DATEOFACT,  USERDEFINEDRULE,  RULEINUSE,  STARTDETAILENTRY,  PARENTCRITERIA,
			BELONGSTOGROUP,  DESCRIPTION,  TYPEOFMARK,  RENEWALTYPE,  DESCRIPTION_TID,  CASEOFFICEID,
			LINKTITLE, LINKTITLE_TID, LINKDESCRIPTION, LINKDESCRIPTION_TID, DOCITEMID, URL, ISPUBLIC,		
			GROUPID,PRODUCTCODE, NEWCASETYPE, NEWPROPERTYTYPE, NEWCOUNTRYCODE, NEWCASECATEGORY,
			PROFILENAME, RULETYPE, REQUESTTYPE, DATASOURCETYPE, DATASOURCENAMENO, RENEWALSTATUS,STATUSCODE,PROFILEID, CPARENEWALTYPE, NEWSUBTYPE)
		SELECT	C.CRITERIANO,C.PURPOSECODE,C.CASETYPE,C.ACTION,C.CHECKLISTTYPE,C.PROGRAMID,C.PROPERTYTYPE,
			C.PROPERTYUNKNOWN,C.COUNTRYCODE,C.COUNTRYUNKNOWN,C.CASECATEGORY,C.CATEGORYUNKNOWN,
			C.SUBTYPE,C.SUBTYPEUNKNOWN,C.BASIS,C.REGISTEREDUSERS,C.LOCALCLIENTFLAG,C.TABLECODE,C.RATENO,
			C.DATEOFACT,C.USERDEFINEDRULE,C.RULEINUSE,C.STARTDETAILENTRY,C.PARENTCRITERIA,
			C.BELONGSTOGROUP,C.DESCRIPTION,C.TYPEOFMARK,C.RENEWALTYPE,C.DESCRIPTION_TID,C.CASEOFFICEID,
			LINKTITLE, LINKTITLE_TID, LINKDESCRIPTION, LINKDESCRIPTION_TID, DOCITEMID, URL, ISPUBLIC,		
			GROUPID, C.PRODUCTCODE, C.NEWCASETYPE, C.NEWPROPERTYTYPE, C.NEWCOUNTRYCODE, C.NEWCASECATEGORY,
			C.PROFILENAME,C.RULETYPE,C.REQUESTTYPE,C.DATASOURCETYPE,C.DATASOURCENAMENO,C.RENEWALSTATUS,C.STATUSCODE,C.PROFILEID, T.USERCODE, C.NEWSUBTYPE
		FROM CRITERIA C
		LEFT JOIN TABLECODES T ON T.TABLECODE = C.RENEWALTYPE 
		WHERE 	(C.PURPOSECODE     =@psPurposeCode)
		and	(C.CASETYPE        =@psCaseType		OR @psCaseType         is null)
		and	(C.ACTION	   =@psAction		OR @psAction           is null)
		and	(C.CHECKLISTTYPE   =@pnCheckListType	OR @pnCheckListType    is null)
		and	(C.PROGRAMID	   =@psProgramID	OR @psProgramID        is null)
		and	(C.PROPERTYTYPE	   =@psPropertyType	OR @psPropertyType     is null)
		and	(C.PROPERTYUNKNOWN =@pnPropertyUnknown	OR @pnPropertyUnknown  is null)
		and	(C.COUNTRYCODE	   =@psCountryCode	OR @psCountryCode      is null)
		and	(C.COUNTRYUNKNOWN  =@pnCountryUnknown	OR @pnCountryUnknown   is null)
		and	(C.CASECATEGORY    =@psCaseCategory	OR @psCaseCategory     is null)
		and	(C.CATEGORYUNKNOWN =@pnCategoryUnknown	OR @pnCategoryUnknown  is null)
		and	(C.SUBTYPE         =@psSubType		OR @psSubType          is null)
		and	(C.SUBTYPEUNKNOWN  =@pnSubTypeUnknown	OR @pnSubTypeUnknown   is null)
		and	(C.BASIS           =@psBasis		OR @psBasis            is null)
		and	(C.REGISTEREDUSERS =@psRegisteredUsers	OR @psRegisteredUsers  is null)
		and	(C.LOCALCLIENTFLAG =@pnLocalClientFlag	OR @pnLocalClientFlag  is null)
		and	(C.TABLECODE       =@pnTableCode	OR @pnTableCode        is null)
		and	(C.RATENO          =@pnRateNo		OR @pnRateNo           is null)
		and	(C.DATEOFACT       =@pdtDateOfAct	OR @pdtDateOfAct       is null)
		and	(C.RULEINUSE       =@pnRuleInUse	OR @pnRuleInUse        is null)
		and	(C.TYPEOFMARK      =@pnTypeOfMark	OR @pnTypeOfMark       is null)
		and	(C.CASEOFFICEID	   =@pnCaseOfficeID	OR @pnCaseOfficeID     is null)
		and	(C.NEWCASETYPE	   =@psNewCaseType	OR @psNewCaseType      is null)
		and	(C.NEWPROPERTYTYPE =@psNewPropertyType	OR @psNewPropertyType  is null) 
		and	(C.NEWCOUNTRYCODE  =@psNewCountryCode	OR @psNewCountryCode   is null) 
		and	(C.NEWCASECATEGORY =@psNewCaseCategory	OR @psNewCaseCategory  is null)
		and	(C.RULETYPE	   =@pnRuleType		OR @pnRuleType         is null)
		and	(C.REQUESTTYPE	   =@psRequestType	OR @psRequestType      is null)
		and	(C.DATASOURCETYPE  =@pnDataSourceType	OR @pnDataSourceType   is null) 
		and	(C.DATASOURCENAMENO=@pnDataSourceNameNo OR @pnDataSourceNameNo is null)
		and	(C.RENEWALSTATUS   =@pnRenewalStatus	OR @pnRenewalStatus    is null)
		and	(C.STATUSCODE	   =@pnStatusCode	OR @pnStatusCode       is null) 
		and	(C.PROFILEID	   =@pnProfileKey	OR @pnProfileKey       is null)
		and	(C.USERDEFINEDRULE =@pbUserDefinedRule  OR @pbUserDefinedRule  is null)
		and	(C.NEWSUBTYPE	   =@psNewSubType	OR @psNewSubType       is null)
	End
	-- CPA RENEWAL TYPE
	Else If @psPurposeCode = 'A'
	begin
		Insert into @tbCriteria(
			CRITERIANO,  PURPOSECODE,  CASETYPE,  ACTION,  CHECKLISTTYPE,  PROGRAMID,  PROPERTYTYPE,
			PROPERTYUNKNOWN,  COUNTRYCODE,  COUNTRYUNKNOWN,  CASECATEGORY,  CATEGORYUNKNOWN,
			SUBTYPE,  SUBTYPEUNKNOWN,  BASIS,  REGISTEREDUSERS,  LOCALCLIENTFLAG,  TABLECODE,  RATENO,
			DATEOFACT,  USERDEFINEDRULE,  RULEINUSE,  STARTDETAILENTRY,  PARENTCRITERIA,
			BELONGSTOGROUP,  DESCRIPTION,  TYPEOFMARK,  RENEWALTYPE,  DESCRIPTION_TID,  CASEOFFICEID,
			BESTFIT, CPARENEWALTYPE)
		SELECT	C.CRITERIANO,C.PURPOSECODE,C.CASETYPE,C.ACTION,C.CHECKLISTTYPE,C.PROGRAMID,C.PROPERTYTYPE,
			C.PROPERTYUNKNOWN,C.COUNTRYCODE,C.COUNTRYUNKNOWN,C.CASECATEGORY,C.CATEGORYUNKNOWN,
			C.SUBTYPE,C.SUBTYPEUNKNOWN,C.BASIS,C.REGISTEREDUSERS,C.LOCALCLIENTFLAG,C.TABLECODE,C.RATENO,
			C.DATEOFACT,C.USERDEFINEDRULE,C.RULEINUSE,C.STARTDETAILENTRY,C.PARENTCRITERIA,
			C.BELONGSTOGROUP,C.DESCRIPTION,C.TYPEOFMARK,C.RENEWALTYPE,C.DESCRIPTION_TID,C.CASEOFFICEID,
		
			CASE WHEN (C.PROPERTYTYPE IS NULL)	THEN '0' ELSE '1' END +    			
			CASE WHEN (C.COUNTRYCODE IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.CASECATEGORY IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.SUBTYPE IS NULL)		THEN '0' ELSE '1' END +
			CASE WHEN (C.TABLECODE is NULL)		THEN '0' ELSE '1' END +
			CASE WHEN (C.USERDEFINEDRULE is NULL
				OR C.USERDEFINEDRULE = 0)	THEN '0' ELSE '1' END,
			T.USERCODE				
		FROM CRITERIA C 
		LEFT JOIN TABLECODES T ON T.TABLECODE = C.RENEWALTYPE 
		WHERE	C.RULEINUSE		= 1  	
		AND	C.PURPOSECODE		= 'A' 
		AND (	C.PROPERTYTYPE 		= @psPropertyType 	OR C.PROPERTYTYPE 	IS NULL ) 
		AND (	C.COUNTRYCODE 		= @psCountryCode 	OR C.COUNTRYCODE 	IS NULL ) 
		AND (	C.CASECATEGORY 		= @psCaseCategory 	OR C.CASECATEGORY 	IS NULL ) 
		AND (	C.SUBTYPE 		= @psSubType 		OR C.SUBTYPE 		IS NULL )
		AND (	C.TABLECODE 		= @pnTableCode          OR C.TABLECODE IS NULL )
		AND (	C.USERDEFINEDRULE	= @pbUserDefinedRule	OR @pbUserDefinedRule	IS NULL )
	end

	-- CHECKLISTS
	Else If @psPurposeCode = 'C'
	begin
		Insert into @tbCriteria(
			CRITERIANO,  PURPOSECODE,  CASETYPE,  ACTION,  CHECKLISTTYPE,  PROGRAMID,  PROPERTYTYPE,
			PROPERTYUNKNOWN,  COUNTRYCODE,  COUNTRYUNKNOWN,  CASECATEGORY,  CATEGORYUNKNOWN,
			SUBTYPE,  SUBTYPEUNKNOWN,  BASIS,  REGISTEREDUSERS,  LOCALCLIENTFLAG,  TABLECODE,  RATENO,
			DATEOFACT,  USERDEFINEDRULE,  RULEINUSE,  STARTDETAILENTRY,  PARENTCRITERIA,
			BELONGSTOGROUP,  DESCRIPTION,  TYPEOFMARK,  RENEWALTYPE,  DESCRIPTION_TID,  CASEOFFICEID,
			PRODUCTCODE, BESTFIT)
		SELECT	C.CRITERIANO,C.PURPOSECODE,C.CASETYPE,C.ACTION,C.CHECKLISTTYPE,C.PROGRAMID,C.PROPERTYTYPE,
			C.PROPERTYUNKNOWN,C.COUNTRYCODE,C.COUNTRYUNKNOWN,C.CASECATEGORY,C.CATEGORYUNKNOWN,
			C.SUBTYPE,C.SUBTYPEUNKNOWN,C.BASIS,C.REGISTEREDUSERS,C.LOCALCLIENTFLAG,C.TABLECODE,C.RATENO,
			C.DATEOFACT,C.USERDEFINEDRULE,C.RULEINUSE,C.STARTDETAILENTRY,C.PARENTCRITERIA,
			C.BELONGSTOGROUP,C.DESCRIPTION,C.TYPEOFMARK,C.RENEWALTYPE,C.DESCRIPTION_TID,C.CASEOFFICEID,
			C.PRODUCTCODE,
		
			CASE WHEN (C.CASEOFFICEID IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.CASETYPE IS NULL)		THEN '0' 
				ELSE CASE WHEN(C.CASETYPE=CT.CASETYPE) 	 THEN '2' ELSE '1' END 
			END +  
			CASE WHEN (C.PROPERTYTYPE IS NULL)	THEN '0' ELSE '1' END +    			
			CASE WHEN (C.COUNTRYCODE IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.CASECATEGORY IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.SUBTYPE IS NULL)		THEN '0' ELSE '1' END +
			CASE WHEN (C.BASIS IS NULL)		THEN '0' ELSE '1' END +
			CASE WHEN (C.LOCALCLIENTFLAG IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.REGISTEREDUSERS IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.USERDEFINEDRULE is NULL
				OR C.USERDEFINEDRULE = 0)	THEN '0' ELSE '1' END
		FROM CRITERIA C
		left join CASETYPE CT	on (CT.CASETYPE=@psCaseType)
		WHERE	C.RULEINUSE		= 1  	
		AND	C.PURPOSECODE		= 'C' 
		AND 	C.CHECKLISTTYPE		= @pnCheckListType
		AND (	C.CASEOFFICEID 		= @pnCaseOfficeID 	OR C.CASEOFFICEID 	IS NULL )
		AND (	C.CASETYPE	      in (CT.CASETYPE,CT.ACTUALCASETYPE) or C.CASETYPE	is NULL )
		AND (	C.PROPERTYTYPE 		= @psPropertyType 	OR C.PROPERTYTYPE 	IS NULL ) 
		AND (	C.COUNTRYCODE 		= @psCountryCode 	OR C.COUNTRYCODE 	IS NULL ) 
		AND (	C.CASECATEGORY 		= @psCaseCategory 	OR C.CASECATEGORY 	IS NULL ) 
		AND (	C.SUBTYPE 		= @psSubType 		OR C.SUBTYPE 		IS NULL ) 
		AND (	C.BASIS 		= @psBasis 		OR C.BASIS 		IS NULL ) 	
		AND (	C.REGISTEREDUSERS 	= @psRegisteredUsers	OR C.REGISTEREDUSERS	IS NULL )
		AND (	C.LOCALCLIENTFLAG 	= @pnLocalClientFlag 	OR C.LOCALCLIENTFLAG	IS NULL ) 
		AND (	C.USERDEFINEDRULE	= @pbUserDefinedRule	OR @pbUserDefinedRule	IS NULL )
	end

	-- EVENTS & ENTRIES
	Else If @psPurposeCode = 'E'
	begin

		-- Now get the CriteriaNo for "Events & Entries"

		
		Insert into @tbCriteria(
			CRITERIANO,  PURPOSECODE,  CASETYPE,  ACTION,  CHECKLISTTYPE,  PROGRAMID,  PROPERTYTYPE,
			PROPERTYUNKNOWN,  COUNTRYCODE,  COUNTRYUNKNOWN,  CASECATEGORY,  CATEGORYUNKNOWN,
			SUBTYPE,  SUBTYPEUNKNOWN,  BASIS,  REGISTEREDUSERS,  LOCALCLIENTFLAG,  TABLECODE,  RATENO,
			DATEOFACT,  USERDEFINEDRULE,  RULEINUSE,  STARTDETAILENTRY,  PARENTCRITERIA,
			BELONGSTOGROUP,  DESCRIPTION,  TYPEOFMARK,  RENEWALTYPE,  DESCRIPTION_TID,  CASEOFFICEID,
			BESTFIT)
		SELECT	C.CRITERIANO,C.PURPOSECODE,C.CASETYPE,C.ACTION,C.CHECKLISTTYPE,C.PROGRAMID,C.PROPERTYTYPE,
			C.PROPERTYUNKNOWN,C.COUNTRYCODE,C.COUNTRYUNKNOWN,C.CASECATEGORY,C.CATEGORYUNKNOWN,
			C.SUBTYPE,C.SUBTYPEUNKNOWN,C.BASIS,C.REGISTEREDUSERS,C.LOCALCLIENTFLAG,C.TABLECODE,C.RATENO,
			C.DATEOFACT,C.USERDEFINEDRULE,C.RULEINUSE,C.STARTDETAILENTRY,C.PARENTCRITERIA,
			C.BELONGSTOGROUP,C.DESCRIPTION,C.TYPEOFMARK,C.RENEWALTYPE,C.DESCRIPTION_TID,C.CASEOFFICEID,
			
			CASE WHEN (isnull(C.RULEINUSE,0)=0)     THEN '0' ELSE '1' END +
			CASE WHEN (C.CASEOFFICEID IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.CASETYPE IS NULL)		THEN '0' 
				ELSE CASE WHEN(C.CASETYPE=CT.CASETYPE) 	 THEN '2' ELSE '1' END 
			END + 
			CASE WHEN (C.PROPERTYTYPE IS NULL)	THEN '0' ELSE '1' END +    			
			CASE WHEN (C.COUNTRYCODE IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.CASECATEGORY IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.SUBTYPE IS NULL)		THEN '0' ELSE '1' END +
			CASE WHEN (C.BASIS IS NULL)		THEN '0' ELSE '1' END +
			CASE WHEN (C.TABLECODE is NULL)		THEN '0' ELSE '1' END +
			CASE WHEN (C.LOCALCLIENTFLAG IS NULL)	THEN '0' ELSE '1' END+
			CASE WHEN (C.DATEOFACT IS NULL)		THEN '0' ELSE '1' END +
			isnull(convert(varchar, DATEOFACT, 112),'00000000') +
			CASE WHEN (C.USERDEFINEDRULE is NULL
				OR C.USERDEFINEDRULE = 0)	THEN '0' ELSE '1' END 
		FROM CRITERIA C 
		left join CASETYPE CT	on (CT.CASETYPE=@psCaseType)
		WHERE	C.PURPOSECODE		= 'E' 
		AND (	C.CASETYPE	      in (CT.CASETYPE,CT.ACTUALCASETYPE))
		AND 	C.ACTION		= @psAction
		AND (	C.CASEOFFICEID 		= @pnCaseOfficeID 	OR C.CASEOFFICEID 	IS NULL )
		AND (	C.PROPERTYTYPE 		= @psPropertyType 	OR C.PROPERTYTYPE 	IS NULL ) 
		AND (	C.COUNTRYCODE 		= @psCountryCode 	OR C.COUNTRYCODE 	IS NULL ) 
		AND (	C.CASECATEGORY 		= @psCaseCategory 	OR C.CASECATEGORY 	IS NULL ) 
		AND (	C.SUBTYPE 		= @psSubType 		OR C.SUBTYPE 		IS NULL ) 
		AND (	C.BASIS 		= @psBasis 		OR C.BASIS 		IS NULL ) 	
		AND (	C.REGISTEREDUSERS 	= @psRegisteredUsers	OR C.REGISTEREDUSERS	IS NULL )
		AND (	C.LOCALCLIENTFLAG 	= @pnLocalClientFlag 	OR C.LOCALCLIENTFLAG	IS NULL ) 
		AND (	C.DATEOFACT 	       <= @pdtDateOfAct         OR C.DATEOFACT IS NULL )
		AND (	C.TABLECODE 		= @pnTableCode          OR C.TABLECODE IS NULL )
		--AND (	C.USERDEFINEDRULE	= @pbUserDefinedRule	OR @pbUserDefinedRule	IS NULL )
		
		-- If there are no Criteria found where RULEINUSE=1 then all of the 
		-- Criteria are to be rejected.  
		If not exists(select 1 from @tbCriteria where RULEINUSE=1)
			delete @tbCriteria
	end

	-- FEES & CHARGES
	Else If @psPurposeCode = 'F'
	begin
		Insert into @tbCriteria(
			CRITERIANO,  PURPOSECODE,  CASETYPE,  ACTION,  CHECKLISTTYPE,  PROGRAMID,  PROPERTYTYPE,
			PROPERTYUNKNOWN,  COUNTRYCODE,  COUNTRYUNKNOWN,  CASECATEGORY,  CATEGORYUNKNOWN,
			SUBTYPE,  SUBTYPEUNKNOWN,  BASIS,  REGISTEREDUSERS,  LOCALCLIENTFLAG,  TABLECODE,  RATENO,
			DATEOFACT,  USERDEFINEDRULE,  RULEINUSE,  STARTDETAILENTRY,  PARENTCRITERIA,
			BELONGSTOGROUP,  DESCRIPTION,  TYPEOFMARK,  RENEWALTYPE,  DESCRIPTION_TID,  CASEOFFICEID,
			BESTFIT)
		SELECT	C.CRITERIANO,C.PURPOSECODE,C.CASETYPE,C.ACTION,C.CHECKLISTTYPE,C.PROGRAMID,C.PROPERTYTYPE,
			C.PROPERTYUNKNOWN,C.COUNTRYCODE,C.COUNTRYUNKNOWN,C.CASECATEGORY,C.CATEGORYUNKNOWN,
			C.SUBTYPE,C.SUBTYPEUNKNOWN,C.BASIS,C.REGISTEREDUSERS,C.LOCALCLIENTFLAG,C.TABLECODE,C.RATENO,
			C.DATEOFACT,C.USERDEFINEDRULE,C.RULEINUSE,C.STARTDETAILENTRY,C.PARENTCRITERIA,
			C.BELONGSTOGROUP,C.DESCRIPTION,C.TYPEOFMARK,C.RENEWALTYPE,C.DESCRIPTION_TID,C.CASEOFFICEID,
		
			CASE WHEN (C.CASEOFFICEID IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.CASETYPE IS NULL)		THEN '0' 
				ELSE CASE WHEN(C.CASETYPE=CT.CASETYPE) 	 THEN '2' ELSE '1' END 
			END +  
			CASE WHEN (C.PROPERTYTYPE IS NULL)	THEN '0' ELSE '1' END +    			
			CASE WHEN (C.COUNTRYCODE IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.CASECATEGORY IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.SUBTYPE IS NULL)		THEN '0' ELSE '1' END +
			CASE WHEN (C.LOCALCLIENTFLAG IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.TYPEOFMARK      IS NULL)   THEN '0' ELSE '1' END +
			CASE WHEN (C.TABLECODE	    IS NULL)    THEN '0' ELSE '1' END +
			CASE WHEN (C.USERDEFINEDRULE is NULL
				OR C.USERDEFINEDRULE = 0)	THEN '0' ELSE '1' END
		FROM CRITERIA C
		left join CASETYPE CT on (CT.CASETYPE=@psCaseType)
		WHERE	C.RULEINUSE		= 1  	
		AND	C.PURPOSECODE		= 'F' 
		AND 	C.RATENO		= @pnRateNo
		AND (	C.CASEOFFICEID 		= @pnCaseOfficeID	OR C.CASEOFFICEID 	IS NULL )
		AND (	C.CASETYPE	      in (CT.CASETYPE,CT.ACTUALCASETYPE) or C.CASETYPE	is NULL )
		AND (	C.PROPERTYTYPE 		= @psPropertyType 	OR C.PROPERTYTYPE 	IS NULL ) 
		AND (	C.COUNTRYCODE 		= @psCountryCode 	OR C.COUNTRYCODE 	IS NULL ) 
		AND (	C.CASECATEGORY 		= @psCaseCategory 	OR C.CASECATEGORY 	IS NULL ) 
		AND (	C.SUBTYPE 		= @psSubType 		OR C.SUBTYPE 		IS NULL ) 
		AND (	C.TYPEOFMARK 		= @pnTypeOfMark		OR C.TYPEOFMARK		IS NULL ) 	
		AND (	C.TABLECODE	 	= @pnTableCode		OR C.TABLECODE		IS NULL )
		AND (	C.LOCALCLIENTFLAG 	= @pnLocalClientFlag 	OR C.LOCALCLIENTFLAG	IS NULL ) 
		AND (	C.USERDEFINEDRULE	= @pbUserDefinedRule	OR @pbUserDefinedRule	IS NULL )
	end

	-- INTERNAL REFERENCE FORMAT
	Else If @psPurposeCode = 'R'
	begin
		Insert into @tbCriteria(
			CRITERIANO,  PURPOSECODE,  CASETYPE,  ACTION,  CHECKLISTTYPE,  PROGRAMID,  PROPERTYTYPE,
			PROPERTYUNKNOWN,  COUNTRYCODE,  COUNTRYUNKNOWN,  CASECATEGORY,  CATEGORYUNKNOWN,
			SUBTYPE,  SUBTYPEUNKNOWN,  BASIS,  REGISTEREDUSERS,  LOCALCLIENTFLAG,  TABLECODE,  RATENO,
			DATEOFACT,  USERDEFINEDRULE,  RULEINUSE,  STARTDETAILENTRY,  PARENTCRITERIA,
			BELONGSTOGROUP,  DESCRIPTION,  TYPEOFMARK,  RENEWALTYPE,  DESCRIPTION_TID,  CASEOFFICEID,
			BESTFIT)
		SELECT	C.CRITERIANO,C.PURPOSECODE,C.CASETYPE,C.ACTION,C.CHECKLISTTYPE,C.PROGRAMID,C.PROPERTYTYPE,
			C.PROPERTYUNKNOWN,C.COUNTRYCODE,C.COUNTRYUNKNOWN,C.CASECATEGORY,C.CATEGORYUNKNOWN,
			C.SUBTYPE,C.SUBTYPEUNKNOWN,C.BASIS,C.REGISTEREDUSERS,C.LOCALCLIENTFLAG,C.TABLECODE,C.RATENO,
			C.DATEOFACT,C.USERDEFINEDRULE,C.RULEINUSE,C.STARTDETAILENTRY,C.PARENTCRITERIA,
			C.BELONGSTOGROUP,C.DESCRIPTION,C.TYPEOFMARK,C.RENEWALTYPE,C.DESCRIPTION_TID,C.CASEOFFICEID,
		
			CASE WHEN (C.CASEOFFICEID IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.CASETYPE IS NULL)		THEN '0' 
				ELSE CASE WHEN(C.CASETYPE=CT.CASETYPE) 	 THEN '2' ELSE '1' END 
			END +  
			CASE WHEN (C.PROPERTYTYPE IS NULL)	THEN '0' ELSE '1' END +    			
			CASE WHEN (C.COUNTRYCODE IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.CASECATEGORY IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.SUBTYPE IS NULL)		THEN '0' ELSE '1' END +
			CASE WHEN (C.BASIS IS NULL)		THEN '0' ELSE '1' END +
			CASE WHEN (C.USERDEFINEDRULE is NULL
				OR C.USERDEFINEDRULE = 0)	THEN '0' ELSE '1' END 
		FROM CRITERIA C
		left join CASETYPE CT on (CT.CASETYPE=@psCaseType)
		WHERE	C.RULEINUSE		= 1  	
		AND	C.PURPOSECODE		= 'R'
		AND (	C.CASEOFFICEID 		= @pnCaseOfficeID 	OR C.CASEOFFICEID 	IS NULL )
		AND (	C.CASETYPE	      in (CT.CASETYPE,CT.ACTUALCASETYPE) or C.CASETYPE	is NULL )
		AND (	C.PROPERTYTYPE 		= @psPropertyType 	OR C.PROPERTYTYPE 	IS NULL ) 
		AND (	C.COUNTRYCODE 		= @psCountryCode 	OR C.COUNTRYCODE 	IS NULL ) 
		AND (	C.CASECATEGORY 		= @psCaseCategory 	OR C.CASECATEGORY 	IS NULL )
		AND (	C.SUBTYPE 		= @psSubType 		OR C.SUBTYPE 		IS NULL ) 
		AND (	C.BASIS 		= @psBasis	 	OR C.BASIS	 	IS NULL ) 
		AND (	C.USERDEFINEDRULE	= @pbUserDefinedRule	OR @pbUserDefinedRule	IS NULL )
	end

	-- CASE SCREEN CONTROL
	Else If @psPurposeCode in ('S','W')
	begin
		Insert into @tbCriteria(
			CRITERIANO,  PURPOSECODE,  CASETYPE,  ACTION,  CHECKLISTTYPE,  PROGRAMID,  PROPERTYTYPE,
			PROPERTYUNKNOWN,  COUNTRYCODE,  COUNTRYUNKNOWN,  CASECATEGORY,  CATEGORYUNKNOWN,
			SUBTYPE,  SUBTYPEUNKNOWN,  BASIS,  REGISTEREDUSERS,  LOCALCLIENTFLAG,  TABLECODE,  RATENO,
			DATEOFACT,  USERDEFINEDRULE,  RULEINUSE,  STARTDETAILENTRY,  PARENTCRITERIA,
			BELONGSTOGROUP,  DESCRIPTION,  TYPEOFMARK,  RENEWALTYPE,  DESCRIPTION_TID,  CASEOFFICEID,PROFILEID,
			BESTFIT)
		SELECT	C.CRITERIANO,C.PURPOSECODE,C.CASETYPE,C.ACTION,C.CHECKLISTTYPE,C.PROGRAMID,C.PROPERTYTYPE,
			C.PROPERTYUNKNOWN,C.COUNTRYCODE,C.COUNTRYUNKNOWN,C.CASECATEGORY,C.CATEGORYUNKNOWN,
			C.SUBTYPE,C.SUBTYPEUNKNOWN,C.BASIS,C.REGISTEREDUSERS,C.LOCALCLIENTFLAG,C.TABLECODE,C.RATENO,
			C.DATEOFACT,C.USERDEFINEDRULE,C.RULEINUSE,C.STARTDETAILENTRY,C.PARENTCRITERIA,
			C.BELONGSTOGROUP,C.DESCRIPTION,C.TYPEOFMARK,C.RENEWALTYPE,C.DESCRIPTION_TID,C.CASEOFFICEID,C.PROFILEID,		
			CASE WHEN (C.PROFILEID IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.CASEOFFICEID IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.CASETYPE IS NULL)		THEN '0' 
				ELSE CASE WHEN(C.CASETYPE=CT.CASETYPE) 	 THEN '2' ELSE '1' END 
			END + 
			CASE WHEN (C.PROPERTYTYPE IS NULL)	THEN '0' ELSE '1' END +    			
			CASE WHEN (C.COUNTRYCODE IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.CASECATEGORY IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.SUBTYPE IS NULL)		THEN '0' ELSE '1' END +
			CASE WHEN (C.BASIS   IS NULL)		THEN '0' ELSE '1' END +
			CASE WHEN (C.USERDEFINEDRULE is NULL
				OR C.USERDEFINEDRULE = 0)	THEN '0' ELSE '1' END
		FROM CRITERIA C
		left join CASETYPE CT on (CT.CASETYPE=@psCaseType)
		WHERE	C.RULEINUSE		= 1  	
		AND	C.PURPOSECODE		= @psPurposeCode
		AND 	C.PROGRAMID		= @psProgramID
		AND (	C.CASEOFFICEID 		= @pnCaseOfficeID 		OR C.CASEOFFICEID 	IS NULL )
		AND (	C.CASETYPE	      in (CT.CASETYPE,CT.ACTUALCASETYPE) or C.CASETYPE	is NULL )
		AND (	C.PROPERTYTYPE 		= @psPropertyType 		OR C.PROPERTYTYPE 	IS NULL ) 
		AND (	C.COUNTRYCODE 		= @psCountryCode 		OR C.COUNTRYCODE 	IS NULL ) 
		AND (	C.CASECATEGORY 		= @psCaseCategory 		OR C.CASECATEGORY 	IS NULL ) 
		AND (	C.SUBTYPE 		= @psSubType 			OR C.SUBTYPE 		IS NULL ) 
		AND (	C.BASIS 		= @psBasis 			OR C.BASIS 		IS NULL )
		AND (	C.PROPERTYUNKNOWN	= isnull(@pnPropertyUnknown,0) 	OR C.PROPERTYUNKNOWN IS NULL )
		AND (	C.COUNTRYUNKNOWN	= isnull(@pnCountryUnknown ,0) 	OR C.COUNTRYUNKNOWN IS NULL )
		AND (	C.CATEGORYUNKNOWN	= isnull(@pnCategoryUnknown,0) 	OR C.CATEGORYUNKNOWN IS NULL )
		AND (	C.SUBTYPEUNKNOWN	= isnull(@pnSubTypeUnknown ,0) 	OR C.SUBTYPEUNKNOWN IS NULL )
		and (	C.PROFILEID		=@pnProfileKey			OR @pnProfileKey	is null)
		AND (	C.USERDEFINEDRULE	= @pbUserDefinedRule		OR @pbUserDefinedRule	IS NULL )
	End

	-- CASE LINKS
	Else If @psPurposeCode = 'L'
	begin
		Insert into @tbCriteria(
			CRITERIANO,  PURPOSECODE,  CASETYPE,  ACTION,  CHECKLISTTYPE,  PROGRAMID,  PROPERTYTYPE,
			PROPERTYUNKNOWN,  COUNTRYCODE,  COUNTRYUNKNOWN,  CASECATEGORY,  CATEGORYUNKNOWN,
			SUBTYPE,  SUBTYPEUNKNOWN,  BASIS,  REGISTEREDUSERS,  LOCALCLIENTFLAG,  TABLECODE,  RATENO,
			DATEOFACT,  USERDEFINEDRULE,  RULEINUSE,  STARTDETAILENTRY,  PARENTCRITERIA,
			BELONGSTOGROUP,  DESCRIPTION,  TYPEOFMARK,  RENEWALTYPE,  DESCRIPTION_TID,  CASEOFFICEID,
			LINKTITLE, LINKTITLE_TID, LINKDESCRIPTION, LINKDESCRIPTION_TID, DOCITEMID, URL, ISPUBLIC,
			GROUPID, BESTFIT)
		SELECT	C.CRITERIANO,C.PURPOSECODE,C.CASETYPE,C.ACTION,C.CHECKLISTTYPE,C.PROGRAMID,C.PROPERTYTYPE,
			C.PROPERTYUNKNOWN,C.COUNTRYCODE,C.COUNTRYUNKNOWN,C.CASECATEGORY,C.CATEGORYUNKNOWN,
			C.SUBTYPE,C.SUBTYPEUNKNOWN,C.BASIS,C.REGISTEREDUSERS,C.LOCALCLIENTFLAG,C.TABLECODE,C.RATENO,
			C.DATEOFACT,C.USERDEFINEDRULE,C.RULEINUSE,C.STARTDETAILENTRY,C.PARENTCRITERIA,
			C.BELONGSTOGROUP,C.DESCRIPTION,C.TYPEOFMARK,C.RENEWALTYPE,C.DESCRIPTION_TID,C.CASEOFFICEID,
			C.LINKTITLE, C.LINKTITLE_TID, LINKDESCRIPTION, LINKDESCRIPTION_TID, DOCITEMID,URL, ISPUBLIC,
			GROUPID,
		
			CASE WHEN (C.CASEOFFICEID 	IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.CASETYPE 		IS NULL)	THEN '0' ELSE '1' END +  
			CASE WHEN (C.PROPERTYTYPE 	IS NULL)	THEN '0' ELSE '1' END +    			
			CASE WHEN (C.COUNTRYCODE 	IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.CASECATEGORY	IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.SUBTYPE		IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.BASIS		IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.TABLECODE  	IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.USERDEFINEDRULE is NULL OR
				   C.USERDEFINEDRULE = 0)		THEN '0' ELSE '1' END 	
		FROM CRITERIA C	
		WHERE	C.RULEINUSE		= 1  	
		AND	C.PURPOSECODE		= 'L' 
		AND (	C.CASEOFFICEID 		= @pnCaseOfficeID 	OR C.CASEOFFICEID 	IS NULL )
		AND (	C.CASETYPE		= @psCaseType		OR C.CASETYPE		is NULL )
		AND (	C.PROPERTYTYPE 		= @psPropertyType 	OR C.PROPERTYTYPE 	IS NULL ) 
		AND (	C.COUNTRYCODE 		= @psCountryCode 	OR C.COUNTRYCODE 	IS NULL ) 
		AND (	C.CASECATEGORY 		= @psCaseCategory 	OR C.CASECATEGORY 	IS NULL ) 
		AND (	C.SUBTYPE 		= @psSubType 		OR C.SUBTYPE 		IS NULL ) 
		AND (	C.BASIS 		= @psBasis 		OR C.BASIS 		IS NULL )
		AND (	C.TABLECODE 		= @pnTableCode 		OR C.TABLECODE	 	IS NULL ) 
		AND (	C.USERDEFINEDRULE	= @pbUserDefinedRule	OR @pbUserDefinedRule	IS NULL )
	End
	-- CASE COPY PROFILE
		Else If @psPurposeCode = 'P'
	begin
		Insert into @tbCriteria(
			CRITERIANO,  PURPOSECODE,  CASETYPE,  ACTION,  CHECKLISTTYPE,  PROGRAMID,  PROPERTYTYPE,
			PROPERTYUNKNOWN,  COUNTRYCODE,  COUNTRYUNKNOWN,  CASECATEGORY,  CATEGORYUNKNOWN,
			SUBTYPE,  SUBTYPEUNKNOWN,  BASIS,  REGISTEREDUSERS,  LOCALCLIENTFLAG,  TABLECODE,  RATENO,
			DATEOFACT,  USERDEFINEDRULE,  RULEINUSE,  STARTDETAILENTRY,  PARENTCRITERIA,
			BELONGSTOGROUP,  DESCRIPTION,  TYPEOFMARK,  RENEWALTYPE,  DESCRIPTION_TID,  CASEOFFICEID,
			GROUPID, 
			NEWCASETYPE,NEWPROPERTYTYPE,NEWCOUNTRYCODE,NEWCASECATEGORY,NEWSUBTYPE, PROFILENAME,
			BESTFIT)
		SELECT	C.CRITERIANO,C.PURPOSECODE,C.CASETYPE,C.ACTION,C.CHECKLISTTYPE,C.PROGRAMID,C.PROPERTYTYPE,
			C.PROPERTYUNKNOWN,C.COUNTRYCODE,C.COUNTRYUNKNOWN,C.CASECATEGORY,C.CATEGORYUNKNOWN,
			C.SUBTYPE,C.SUBTYPEUNKNOWN,C.BASIS,C.REGISTEREDUSERS,C.LOCALCLIENTFLAG,C.TABLECODE,C.RATENO,
			C.DATEOFACT,C.USERDEFINEDRULE,C.RULEINUSE,C.STARTDETAILENTRY,C.PARENTCRITERIA,
			C.BELONGSTOGROUP,C.DESCRIPTION,C.TYPEOFMARK,C.RENEWALTYPE,C.DESCRIPTION_TID,C.CASEOFFICEID,
			GROUPID,
			C.NEWCASETYPE,C.NEWPROPERTYTYPE,C.NEWCOUNTRYCODE,C.NEWCASECATEGORY,C.NEWSUBTYPE, C.PROFILENAME,
		
			CASE WHEN (C.CASETYPE IS NULL)		THEN '0' 
				ELSE CASE WHEN(C.CASETYPE=CT.CASETYPE) 	 THEN '2' ELSE '1' END 
			END + 
			CASE WHEN (C.NEWCASETYPE IS NULL)	THEN '0' 
				ELSE CASE WHEN(C.NEWCASETYPE=CN.CASETYPE)THEN '2' ELSE '1' END 
			END +  
			CASE WHEN (C.PROPERTYTYPE IS NULL)	THEN '0' ELSE '1' END +    			
			CASE WHEN (C.NEWPROPERTYTYPE IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.COUNTRYCODE IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.NEWCOUNTRYCODE IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.CASECATEGORY IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.NEWCASECATEGORY IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.SUBTYPE IS NULL)		THEN '0' ELSE '1' END +
			CASE WHEN (C.NEWSUBTYPE IS NULL)	THEN '0' ELSE '1' END 

		FROM CRITERIA C
		left join CASETYPE CT on (CT.CASETYPE=@psCaseType)
		left join CASETYPE CN on (CN.CASETYPE=@psNewCaseType)
		WHERE	C.RULEINUSE		= 1  	
		AND	C.PURPOSECODE		= 'P' 
		AND (	C.CASETYPE	      in (CT.CASETYPE,CT.ACTUALCASETYPE) or C.CASETYPE	is NULL )
		AND (	C.PROPERTYTYPE 		= @psPropertyType 	OR C.PROPERTYTYPE 	IS NULL ) 
		AND (	C.COUNTRYCODE 		= @psCountryCode 	OR C.COUNTRYCODE 	IS NULL ) 
		AND (	C.CASECATEGORY		= @psCaseCategory 	OR C.CASECATEGORY 	IS NULL )
		AND (	C.NEWCASETYPE	      in (CN.CASETYPE,CN.ACTUALCASETYPE) or C.NEWCASETYPE is NULL )
		AND (	C.NEWPROPERTYTYPE 	= @psNewPropertyType 	OR C.NEWPROPERTYTYPE 	IS NULL ) 
		AND (	C.NEWCOUNTRYCODE 	= @psNewCountryCode 	OR C.NEWCOUNTRYCODE 	IS NULL ) 
		AND (	C.NEWCASECATEGORY	= @psNewCaseCategory 	OR C.NEWCASECATEGORY 	IS NULL ) 
		AND (	C.USERDEFINEDRULE	= @pbUserDefinedRule	OR @pbUserDefinedRule	IS NULL )
		AND (   C.NEWSUBTYPE		= @psNewSubType		OR C.NEWSUBTYPE		IS NULL)

	End

	-- USPTO/PAIR
	Else If @psPurposeCode = 'D'
	begin
		Insert into @tbCriteria(
			CRITERIANO,  PURPOSECODE,  CASETYPE,  ACTION,  CHECKLISTTYPE,  PROGRAMID,  PROPERTYTYPE,
			PROPERTYUNKNOWN,  COUNTRYCODE,  COUNTRYUNKNOWN,  CASECATEGORY,  CATEGORYUNKNOWN,
			SUBTYPE,  SUBTYPEUNKNOWN,  BASIS,  REGISTEREDUSERS,  LOCALCLIENTFLAG,  TABLECODE,  RATENO,
			DATEOFACT,  USERDEFINEDRULE,  RULEINUSE,  STARTDETAILENTRY,  PARENTCRITERIA,
			BELONGSTOGROUP,  DESCRIPTION,  TYPEOFMARK,  RENEWALTYPE,  DESCRIPTION_TID,  CASEOFFICEID,
			LINKTITLE, LINKTITLE_TID, LINKDESCRIPTION, LINKDESCRIPTION_TID, DOCITEMID, URL, ISPUBLIC,
			GROUPID, 
			C.NEWCASETYPE,C.NEWPROPERTYTYPE,C.NEWCOUNTRYCODE,C.NEWCASECATEGORY,NEWSUBTYPE, C.PROFILENAME, DATAEXTRACTID,
			BESTFIT)
		SELECT	C.CRITERIANO,C.PURPOSECODE,C.CASETYPE,C.ACTION,C.CHECKLISTTYPE,C.PROGRAMID,C.PROPERTYTYPE,
			C.PROPERTYUNKNOWN,C.COUNTRYCODE,C.COUNTRYUNKNOWN,C.CASECATEGORY,C.CATEGORYUNKNOWN,
			C.SUBTYPE,C.SUBTYPEUNKNOWN,C.BASIS,C.REGISTEREDUSERS,C.LOCALCLIENTFLAG,C.TABLECODE,C.RATENO,
			C.DATEOFACT,C.USERDEFINEDRULE,C.RULEINUSE,C.STARTDETAILENTRY,C.PARENTCRITERIA,
			C.BELONGSTOGROUP,C.DESCRIPTION,C.TYPEOFMARK,C.RENEWALTYPE,C.DESCRIPTION_TID,C.CASEOFFICEID,
			C.LINKTITLE, C.LINKTITLE_TID, C.LINKDESCRIPTION, C.LINKDESCRIPTION_TID, C.DOCITEMID,C.URL, C.ISPUBLIC,
			C.GROUPID,		
			C.NEWCASETYPE,C.NEWPROPERTYTYPE,C.NEWCOUNTRYCODE,C.NEWCASECATEGORY, C.NEWSUBTYPE, C.PROFILENAME, C.DATAEXTRACTID,

			CASE WHEN (C.CASEOFFICEID 	IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.CASETYPE 		IS NULL)	THEN '0' ELSE '1' END +  
			CASE WHEN (C.PROPERTYTYPE 	IS NULL)	THEN '0' ELSE '1' END +    			
			CASE WHEN (C.COUNTRYCODE 	IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.TABLECODE  	IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.USERDEFINEDRULE is NULL OR
				   C.USERDEFINEDRULE = 0)		THEN '0' ELSE '1' END 	
		FROM CRITERIA C	
		WHERE	C.RULEINUSE		= 1  	
		AND	C.PURPOSECODE		= 'D' 
		AND (	C.CASEOFFICEID 		= @pnCaseOfficeID 	OR C.CASEOFFICEID 	IS NULL )
		AND (	C.CASETYPE		= @psCaseType		OR C.CASETYPE		is NULL )
		AND (	C.PROPERTYTYPE 		= @psPropertyType 	OR C.PROPERTYTYPE 	IS NULL ) 
		AND (	C.COUNTRYCODE 		= @psCountryCode 	OR C.COUNTRYCODE 	IS NULL ) 
		AND (	C.TABLECODE 		= @pnTableCode 		OR C.TABLECODE	 	IS NULL ) 
		AND (	C.USERDEFINEDRULE	= @pbUserDefinedRule	OR @pbUserDefinedRule	IS NULL )
	End

	-- CASE UPDATE RULES
	Else If @psPurposeCode = 'U'
	begin
		Insert into @tbCriteria(
			CRITERIANO,  PURPOSECODE,  CASETYPE,  ACTION,  CHECKLISTTYPE,  PROGRAMID,  PROPERTYTYPE,
			PROPERTYUNKNOWN,  COUNTRYCODE,  COUNTRYUNKNOWN,  CASECATEGORY,  CATEGORYUNKNOWN,
			SUBTYPE,  SUBTYPEUNKNOWN,  BASIS,  REGISTEREDUSERS,  LOCALCLIENTFLAG,  TABLECODE,  RATENO,
			DATEOFACT,  USERDEFINEDRULE,  RULEINUSE,  STARTDETAILENTRY,  PARENTCRITERIA,
			BELONGSTOGROUP,  DESCRIPTION,  TYPEOFMARK,  RENEWALTYPE,  DESCRIPTION_TID,  CASEOFFICEID,
			RULETYPE, REQUESTTYPE, DATASOURCETYPE, DATASOURCENAMENO, RENEWALSTATUS,STATUSCODE,
			BESTFIT)
		SELECT	C.CRITERIANO,C.PURPOSECODE,C.CASETYPE,C.ACTION,C.CHECKLISTTYPE,C.PROGRAMID,C.PROPERTYTYPE,
			C.PROPERTYUNKNOWN,C.COUNTRYCODE,C.COUNTRYUNKNOWN,C.CASECATEGORY,C.CATEGORYUNKNOWN,
			C.SUBTYPE,C.SUBTYPEUNKNOWN,C.BASIS,C.REGISTEREDUSERS,C.LOCALCLIENTFLAG,C.TABLECODE,C.RATENO,
			C.DATEOFACT,C.USERDEFINEDRULE,C.RULEINUSE,C.STARTDETAILENTRY,C.PARENTCRITERIA,
			C.BELONGSTOGROUP,C.DESCRIPTION,C.TYPEOFMARK,C.RENEWALTYPE,C.DESCRIPTION_TID,C.CASEOFFICEID,
			C.RULETYPE,C.REQUESTTYPE,C.DATASOURCETYPE,C.DATASOURCENAMENO,C.RENEWALSTATUS,C.STATUSCODE,
		
			CASE WHEN (C.CASEOFFICEID IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.REQUESTTYPE IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.DATASOURCETYPE IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.DATASOURCENAMENO IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.CASETYPE IS NULL)		THEN '0' 
				ELSE CASE WHEN(C.CASETYPE=CT.CASETYPE) 	 THEN '2' ELSE '1' END 
			END +  
			CASE WHEN (C.PROPERTYTYPE IS NULL)	THEN '0' ELSE '1' END +    			
			CASE WHEN (C.COUNTRYCODE IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.CASECATEGORY IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.SUBTYPE IS NULL)		THEN '0' ELSE '1' END +
			CASE WHEN (C.RENEWALSTATUS IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.STATUSCODE IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.USERDEFINEDRULE is NULL
				OR C.USERDEFINEDRULE = 0)	THEN '0' ELSE '1' END
		FROM CRITERIA C
		left join CASETYPE CT on (CT.CASETYPE=@psCaseType)
		WHERE	C.RULEINUSE		= 1  	
		AND	C.PURPOSECODE		= 'U' 
		AND 	C.RULETYPE		= @pnRuleType
		AND (	C.CASEOFFICEID 		= @pnCaseOfficeID 	OR C.CASEOFFICEID 	IS NULL )
		AND (	C.REQUESTTYPE 		= @psRequestType 	OR C.REQUESTTYPE 	IS NULL )
		AND (	C.DATASOURCETYPE	= @pnDataSourceType 	OR C.DATASOURCETYPE 	IS NULL )
		AND (	C.DATASOURCENAMENO	= @pnDataSourceNameNo	OR C.DATASOURCENAMENO 	IS NULL )
		AND (	C.CASETYPE	      in (CT.CASETYPE,CT.ACTUALCASETYPE) 
									OR C.CASETYPE		is NULL )
		AND (	C.PROPERTYTYPE 		= @psPropertyType 	OR C.PROPERTYTYPE 	IS NULL ) 
		AND (	C.COUNTRYCODE 		= @psCountryCode 	OR C.COUNTRYCODE 	IS NULL ) 
		AND (	C.CASECATEGORY 		= @psCaseCategory 	OR C.CASECATEGORY 	IS NULL ) 
		AND (	C.SUBTYPE 		= @psSubType 		OR C.SUBTYPE 		IS NULL )
		AND (	C.RENEWALSTATUS		= @pnRenewalStatus	OR C.RENEWALSTATUS	IS NULL ) 
		AND (	C.STATUSCODE		= @pnStatusCode		OR C.STATUSCODE		IS NULL )
		AND (	C.USERDEFINEDRULE	= @pbUserDefinedRule	OR @pbUserDefinedRule	IS NULL )
	End

	-- LAW UPDATE BLOCKING
	Else If @psPurposeCode = 'X'
	begin

		-- Now get the CriteriaNo for "Law Update Blocking"

		
		Insert into @tbCriteria(
			CRITERIANO,  PURPOSECODE,  CASETYPE,  ACTION,  CHECKLISTTYPE,  PROGRAMID,  PROPERTYTYPE,
			PROPERTYUNKNOWN,  COUNTRYCODE,  COUNTRYUNKNOWN,  CASECATEGORY,  CATEGORYUNKNOWN,
			SUBTYPE,  SUBTYPEUNKNOWN,  BASIS,  REGISTEREDUSERS,  LOCALCLIENTFLAG,  TABLECODE,  RATENO,
			DATEOFACT,  USERDEFINEDRULE,  RULEINUSE,  STARTDETAILENTRY,  PARENTCRITERIA,
			BELONGSTOGROUP,  DESCRIPTION,  TYPEOFMARK,  RENEWALTYPE,  DESCRIPTION_TID,  CASEOFFICEID,
			BESTFIT)
		SELECT	C.CRITERIANO,C.PURPOSECODE,C.CASETYPE,C.ACTION,C.CHECKLISTTYPE,C.PROGRAMID,C.PROPERTYTYPE,
			C.PROPERTYUNKNOWN,C.COUNTRYCODE,C.COUNTRYUNKNOWN,C.CASECATEGORY,C.CATEGORYUNKNOWN,
			C.SUBTYPE,C.SUBTYPEUNKNOWN,C.BASIS,C.REGISTEREDUSERS,C.LOCALCLIENTFLAG,C.TABLECODE,C.RATENO,
			C.DATEOFACT,C.USERDEFINEDRULE,C.RULEINUSE,C.STARTDETAILENTRY,C.PARENTCRITERIA,
			C.BELONGSTOGROUP,C.DESCRIPTION,C.TYPEOFMARK,C.RENEWALTYPE,C.DESCRIPTION_TID,C.CASEOFFICEID,
		
			CASE WHEN (C.CASETYPE IS NULL)		THEN '0' 
				ELSE CASE WHEN(C.CASETYPE=CT.CASETYPE) 	 THEN '2' ELSE '1' END 
			END + 
			CASE WHEN (C.PROPERTYTYPE IS NULL)	THEN '0' ELSE '1' END +    			
			CASE WHEN (C.COUNTRYCODE IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.CASECATEGORY IS NULL)	THEN '0' ELSE '1' END +
			CASE WHEN (C.SUBTYPE IS NULL)		THEN '0' ELSE '1' END +
			CASE WHEN (C.BASIS IS NULL)		THEN '0' ELSE '1' END +
			CASE WHEN (C.DATEOFACT IS NULL)		THEN '0' ELSE '1' END +
			isnull(convert(varchar, DATEOFACT, 112),'00000000')
			
		FROM CRITERIA C 
		left join CASETYPE CT	on (CT.CASETYPE=@psCaseType)
		WHERE	C.PURPOSECODE		= 'X' 
		AND (	C.CASETYPE		in (CT.CASETYPE,CT.ACTUALCASETYPE) OR @psCaseType IS NULL)	
		AND (	C.ACTION		= @psAction or @psAction IS NULL)
		AND (	C.PROPERTYTYPE 		= @psPropertyType 	OR C.PROPERTYTYPE 	IS NULL ) 
		AND (	C.COUNTRYCODE 		= @psCountryCode 	OR C.COUNTRYCODE 	IS NULL ) 
		AND (	C.CASECATEGORY 		= @psCaseCategory 	OR C.CASECATEGORY 	IS NULL ) 
		AND (	C.SUBTYPE 		= @psSubType 		OR C.SUBTYPE 		IS NULL ) 
		AND (	C.BASIS 		= @psBasis 		OR C.BASIS 		IS NULL ) 
		AND (	C.DATEOFACT 	       <= @pdtDateOfAct         OR C.DATEOFACT IS NULL )
		AND (	C.USERDEFINEDRULE	= @pbUserDefinedRule	OR @pbUserDefinedRule	IS NULL )
			
	end
	
	Return
End
go

grant REFERENCES, SELECT on dbo.fn_GetCriteriaRowsForControl to public
GO
