/**********************************************************************************************************/
/*** Add all applications to the launchpad								***/
/**********************************************************************************************************/

If not exists (Select * from MENU where MENUNAME='EDE')
BEGIN
	 PRINT '**** Inserting EDE menu'

	 INSERT INTO MENU (MENUNAME, MENUSEQUENCE)
	 VALUES ('EDE',22)

	 PRINT '**** Menu for EDE has been successfully inserted.'
	 PRINT ''
	END
ELSE
	PRINT '**** EDE menu already exists.'
	PRINT ''
go

If not exists (Select * from MENU where MENUNAME='Other')
BEGIN
	 PRINT '**** Inserting Other menu'

	 INSERT INTO MENU (MENUNAME, MENUSEQUENCE)
	 VALUES ('Other',50)

	 PRINT '**** Menu for Other has been successfully inserted.'
	 PRINT ''
	END
ELSE
	PRINT '**** Other menu already exists.'
	PRINT ''
go

-- Add applications to EDE menu

UPDATE APPLICATIONS SET MENUNAME='EDE'
WHERE MENUNAME IS NULL
AND upper(PROGRAMNAME) IN ('BATCHPROCESSING','NAMEMAPPING','NAMESPROCESSING','CASEREVIEW')
go

-- Add applications to Accounting menu
UPDATE APPLICATIONS SET MENUNAME='Accounting'
WHERE MENUNAME IS NULL
AND upper(PROGRAMNAME) IN ('MARGINPROFILE','CASHBOOK','GENERALLEDGER','JOURNALGENERATION','STAFFPERFORMANCE','TRUSTACCT')
and exists (select 1 FROM MENU WHERE MENUNAME='Accounting')
go

-- Add any other applications to the Other menu
UPDATE APPLICATIONS SET MENUNAME='Other'
where MENUNAME IS NULL
go

-- Add any missing applications to SYSADM

INSERT INTO USERAPPLICATIONS (USERID,APPLICATIONNAME,DISPLAYSEQUENCE)
select 'SYSADM', A.APPLICATIONNAME, A.DISPLAYSEQUENCE
from APPLICATIONS A
-- Exclude duplicate application names that end in .
LEFT join APPLICATIONS A1 ON (UPPER(A1.APPLICATIONNAME)+'.'=UPPER(A.APPLICATIONNAME))
WHERE A1.APPLICATIONNAME IS NULL
-- Exclude anything already present
AND NOT EXISTS
	(SELECT *
	FROM USERAPPLICATIONS U
	WHERE U.USERID='SYSADM'
	AND UPPER(U.APPLICATIONNAME)=UPPER(A.APPLICATIONNAME))
-- App doesn't exist any more???
and A.PROGRAMNAME <> 'PTMAIN'
go

/**********************************************************************************************************/
/*** Configure basic test data for Case Review								***/
/**********************************************************************************************************/
-- Create a name group
If NOT exists (select * from NAMEGROUPS where GROUPDESCRIPTION='EDE NAME GROUP')
	Begin
	 PRINT '**** Inserting Name group for EDE names'
	 DECLARE @nNextKey	int
	 UPDATE LASTINTERNALCODE 
	 SET 	INTERNALSEQUENCE = INTERNALSEQUENCE + 1,
	    	@nNextKey = INTERNALSEQUENCE + 1
	 WHERE  TABLENAME = 'NAMEGROUPS'
	 INSERT INTO NAMEGROUPS (NAMEGROUP,GROUPDESCRIPTION)
	 VALUES (@nNextKey, 'EDE NAME GROUP')
 	 PRINT '**** Name group for EDE names has been inserted'
	 PRINT ''
	 insert into GROUPMEMBERS (NAMEGROUP,NAMETYPE)
	 SELECT @nNextKey, NAMETYPE
	 FROM NAMETYPE WHERE NAMETYPE IN ('I','D','O')
 	 PRINT '**** Name types attached to Name group for EDE names'
	 PRINT ''
	 -- Attach EDE name group to template screen control rules
	 UPDATE SCREENCONTROL SET NAMEGROUP=@nNextKey
	 WHERE CRITERIANO = -3001362 AND SCREENNAME = 'frmEDECaseResolutionNames' AND NAMEGROUP IS NULL
 	 PRINT '**** Name group attached to template screen control'
	END
ELSE
 	PRINT '**** Name group for EDE names already exists'
	PRINT ''
GO


-- Create a logical action
If not exists (Select * from ACTIONS where ACTION='ED')
BEGIN
	 PRINT '**** Inserting EDE Action'

	 INSERT INTO ACTIONS (ACTION,ACTIONNAME,NUMCYCLESALLOWED,ACTIONTYPEFLAG)
	 VALUES ('ED','EDE Action',1, 0)

	 PRINT '**** EDE Action has been successfully inserted.'
	 PRINT ''
	END
ELSE
	PRINT '**** EDE Action already exists.'
	PRINT ''
go

-- Attach some events to the logical action
If NOT exists (select * from CRITERIA where ACTION='ED')
	Begin
	 PRINT '**** Inserting Criteria for EDE Action'
	 DECLARE @nNextKey	int
	 UPDATE LASTINTERNALCODE 
	 SET 	INTERNALSEQUENCE = INTERNALSEQUENCE + 1,
	    	@nNextKey = INTERNALSEQUENCE + 1
	 WHERE  TABLENAME = 'CRITERIA'
	 INSERT INTO CRITERIA(CRITERIANO, PURPOSECODE, CASETYPE, ACTION, PROPERTYUNKNOWN, COUNTRYUNKNOWN, CATEGORYUNKNOWN, SUBTYPEUNKNOWN, 
		USERDEFINEDRULE, RULEINUSE, DESCRIPTION)
	 VALUES (@nNextKey, 'E', 'A','ED',0,0,0,0,
		1,1,'EDE Events')
 	 PRINT '**** Criteria for EDE Action has been inserted'
	 PRINT ''

	If NOT exists(SELECT * FROM EVENTCONTROL WHERE CRITERIANO = @nNextKey AND EVENTNO = -1)
	and exists (SELECT * FROM EVENTS WHERE EVENTNO = -1)
        	BEGIN
         	 PRINT '****  Adding EventControl Event = -1'
		 INSERT EVENTCONTROL (CRITERIANO, EVENTNO, EVENTDESCRIPTION, DISPLAYSEQUENCE,
		 PARENTCRITERIANO, PARENTEVENTNO, NUMCYCLESALLOWED, IMPORTANCELEVEL, WHICHDUEDATE, COMPAREBOOLEAN, CHECKCOUNTRYFLAG, SAVEDUEDATE,
		 FROMANCESTOR, UPDATEMANUALLY, INHERITED, SETTHIRDPARTYON, RECALCEVENTDATE)
		 VALUES (@nNextKey,-1,'Earliest Priority Date', 0,null,null, 1,'9','E', null,null,0,
		0,0,0,0,0)
        	 PRINT '****  Data successfully added to EVENTCONTROL table.'
		 PRINT ''
         	END

	If NOT exists(SELECT * FROM EVENTCONTROL WHERE CRITERIANO = @nNextKey AND EVENTNO = -106)
	and exists (SELECT * FROM EVENTS WHERE EVENTNO = -106)
        	BEGIN
         	 PRINT '****  Adding EventControl Event = -106'
		 INSERT EVENTCONTROL (CRITERIANO, EVENTNO, EVENTDESCRIPTION, DISPLAYSEQUENCE,
		 PARENTCRITERIANO, PARENTEVENTNO, NUMCYCLESALLOWED, IMPORTANCELEVEL, WHICHDUEDATE, COMPAREBOOLEAN, CHECKCOUNTRYFLAG, SAVEDUEDATE,
		 FROMANCESTOR, UPDATEMANUALLY, INHERITED, SETTHIRDPARTYON, RECALCEVENTDATE)
		 VALUES (@nNextKey,-106,'Parent Renewal Start Date', 1,null,null, 1,'7','E', null,null,0,
		0,0,0,0,0)
        	 PRINT '****  Data successfully added to EVENTCONTROL table.'
		 PRINT ''
         	END

	If NOT exists(SELECT * FROM EVENTCONTROL WHERE CRITERIANO = @nNextKey AND EVENTNO = -4)
	and exists (SELECT * FROM EVENTS WHERE EVENTNO = -4)
        	BEGIN
         	 PRINT '****  Adding EventControl Event = -4'
		 INSERT EVENTCONTROL (CRITERIANO, EVENTNO, EVENTDESCRIPTION, DISPLAYSEQUENCE,
		 PARENTCRITERIANO, PARENTEVENTNO, NUMCYCLESALLOWED, IMPORTANCELEVEL, WHICHDUEDATE, COMPAREBOOLEAN, CHECKCOUNTRYFLAG, SAVEDUEDATE,
		 FROMANCESTOR, UPDATEMANUALLY, INHERITED, SETTHIRDPARTYON, RECALCEVENTDATE)
		 VALUES (@nNextKey,-4,'Application/Filing Date', 2,null,null, 1,'9','E', null,null,0,
		0,0,0,0,0)
        	 PRINT '****  Data successfully added to EVENTCONTROL table.'
		 PRINT ''
         	END

	If NOT exists(SELECT * FROM EVENTCONTROL WHERE CRITERIANO = @nNextKey AND EVENTNO = -36)
	and exists (SELECT * FROM EVENTS WHERE EVENTNO = -36)
        	BEGIN
         	 PRINT '****  Adding EventControl Event = -36'
		 INSERT EVENTCONTROL (CRITERIANO, EVENTNO, EVENTDESCRIPTION, DISPLAYSEQUENCE,
		 PARENTCRITERIANO, PARENTEVENTNO, NUMCYCLESALLOWED, IMPORTANCELEVEL, WHICHDUEDATE, COMPAREBOOLEAN, CHECKCOUNTRYFLAG, SAVEDUEDATE,
		 FROMANCESTOR, UPDATEMANUALLY, INHERITED, SETTHIRDPARTYON, RECALCEVENTDATE)
		 VALUES (@nNextKey,-36,'Publication Date', 3,null,null, 1,'5','E', null,null,0,
		0,0,0,0,0)
        	 PRINT '****  Data successfully added to EVENTCONTROL table.'
		 PRINT ''
         	END

	If NOT exists(SELECT * FROM EVENTCONTROL WHERE CRITERIANO = @nNextKey AND EVENTNO = -8)
	and exists (SELECT * FROM EVENTS WHERE EVENTNO = -8)
        	BEGIN
         	 PRINT '****  Adding EventControl Event = -8'
		 INSERT EVENTCONTROL (CRITERIANO, EVENTNO, EVENTDESCRIPTION, DISPLAYSEQUENCE,
		 PARENTCRITERIANO, PARENTEVENTNO, NUMCYCLESALLOWED, IMPORTANCELEVEL, WHICHDUEDATE, COMPAREBOOLEAN, CHECKCOUNTRYFLAG, SAVEDUEDATE,
		 FROMANCESTOR, UPDATEMANUALLY, INHERITED, SETTHIRDPARTYON, RECALCEVENTDATE)
		 VALUES (@nNextKey,-8,'Registration/Grant Date', 4,null,null, 1,'9','E', null,null,0,
		0,0,0,0,0)
        	 PRINT '****  Data successfully added to EVENTCONTROL table.'
		 PRINT ''
         	END

	If NOT exists(SELECT * FROM EVENTCONTROL WHERE CRITERIANO = @nNextKey AND EVENTNO = -11858)
	and exists (SELECT * FROM EVENTS WHERE EVENTNO = -11858)
        	BEGIN
         	 PRINT '****  Adding EventControl Event = -11858'
		 INSERT EVENTCONTROL (CRITERIANO, EVENTNO, EVENTDESCRIPTION, DISPLAYSEQUENCE,
		 PARENTCRITERIANO, PARENTEVENTNO, NUMCYCLESALLOWED, IMPORTANCELEVEL, WHICHDUEDATE, COMPAREBOOLEAN, CHECKCOUNTRYFLAG, SAVEDUEDATE,
		 FROMANCESTOR, UPDATEMANUALLY, INHERITED, SETTHIRDPARTYON, RECALCEVENTDATE)
		 VALUES (@nNextKey,-11858,'CPA Start Pay Date', 5,null,null, 1,'5','E', null,null,0,
		0,0,0,0,0)
        	 PRINT '****  Data successfully added to EVENTCONTROL table.'
		 PRINT ''
         	END

	If NOT exists(SELECT * FROM EVENTCONTROL WHERE CRITERIANO = @nNextKey AND EVENTNO = -11859)
	and exists (SELECT * FROM EVENTS WHERE EVENTNO = -11859)
        	BEGIN
         	 PRINT '****  Adding EventControl Event = -11859'
		 INSERT EVENTCONTROL (CRITERIANO, EVENTNO, EVENTDESCRIPTION, DISPLAYSEQUENCE,
		 PARENTCRITERIANO, PARENTEVENTNO, NUMCYCLESALLOWED, IMPORTANCELEVEL, WHICHDUEDATE, COMPAREBOOLEAN, CHECKCOUNTRYFLAG, SAVEDUEDATE,
		 FROMANCESTOR, UPDATEMANUALLY, INHERITED, SETTHIRDPARTYON, RECALCEVENTDATE)
		 VALUES (@nNextKey,-11859,'CPA Stop Pay Date', 6,null,null, 1,'5','E', null,null,0,
		0,0,0,0,0)
        	 PRINT '****  Data successfully added to EVENTCONTROL table.'
		 PRINT ''
         	END

	If NOT exists(SELECT * FROM EVENTCONTROL WHERE CRITERIANO = @nNextKey AND EVENTNO = -11)
	and exists (SELECT * FROM EVENTS WHERE EVENTNO = -11)
        	BEGIN
         	 PRINT '****  Adding EventControl Event = -11'
		 INSERT EVENTCONTROL (CRITERIANO, EVENTNO, EVENTDESCRIPTION, DISPLAYSEQUENCE,
		 PARENTCRITERIANO, PARENTEVENTNO, NUMCYCLESALLOWED, IMPORTANCELEVEL, WHICHDUEDATE, COMPAREBOOLEAN, CHECKCOUNTRYFLAG, SAVEDUEDATE,
		 FROMANCESTOR, UPDATEMANUALLY, INHERITED, SETTHIRDPARTYON, RECALCEVENTDATE)
		 VALUES (@nNextKey,-11,'Next renewal date', 7,null,null, 9999,'9','E', null,null,0,
		0,0,0,0,0)
        	 PRINT '****  Data successfully added to EVENTCONTROL table.'
		 PRINT ''
         	END

	 PRINT ''
	END
ELSE
 	PRINT '**** Criteria for EDE Action already exists'
	PRINT ''
GO

-- Attach EDE action to template screen control rules
PRINT '****  Add EDE action to template screen control.'
UPDATE SCREENCONTROL SET CREATEACTION='ED'
WHERE CRITERIANO = -3001362 AND SCREENNAME = 'frmEDECaseResolutionMain' AND CREATEACTION IS NULL
GO

-- SQA12361 Set up Lapse Event site control
If exists (SELECT * FROM SITECONTROL WHERE UPPER(CONTROLID) = N'LAPSE EVENT' AND COLINTEGER is null)
BEGIN
	 PRINT '**** Updating data in the SITECONTROL table for Lapse Event.'
	 UPDATE SITECONTROL
	 SET COLINTEGER = -108
	 WHERE UPPER(CONTROLID) = N'LAPSE EVENT'
	 PRINT '**** SITECONTROL table for Lapse Event has been updated successfully.'
	 PRINT ''
	END
ELSE
	PRINT '**** SITECONTROL table for Lapse Event has already been updated.'
	PRINT ''
go

-- SQA10105 Set up Control Accounts
-- Trust      
/*SELECT * FROM LEDGERACCOUNT   
order by ACCOUNTTYPE, ACCOUNTCODE
*/
If NOT exists(SELECT * FROM LEDGERACCOUNT WHERE ACCOUNTCODE = '201')
	BEGIN
 	 PRINT '****  Adding LEDGERACCOUNT.ACCOUNTCODE = ''201'''
	 Declare @nAccountId int

	 update  LASTINTERNALCODE
	 Set	INTERNALSEQUENCE=INTERNALSEQUENCE+1,
		@nAccountId       =INTERNALSEQUENCE+1
	 where   TABLENAME='LEDGERACCOUNT'

	 INSERT LEDGERACCOUNT (ACCOUNTID, ACCOUNTCODE, DESCRIPTION, ACCOUNTTYPE, ISACTIVE, 
		PARENTACCOUNTID, DISBURSETOWIP, BUDGETMOVEMENT)
	 VALUES (@nAccountId, '201', 'Trust Owed', 8102, 1, NULL, 0, 1 )
	 PRINT '****  Data successfully added to LEDGERACCOUNT table.'
	 PRINT ''
 	END
ELSE
 	PRINT '**** LEDGERACCOUNT.ACCOUNTCODE = ''201'' already exists'
	PRINT ''

GO

--select * from DEFAULTACCOUNT
If NOT exists(SELECT * FROM DEFAULTACCOUNT WHERE CONTROLACCTYPEID = 8710 AND ENTITYNO = 80)
	BEGIN
	 PRINT '****  Adding DEFAULTACCOUNT.CONTROLACCTYPEID = 8710 AND DEFAULTACCOUNT.ENTITYNO = 80'

	 Declare @nDefaultAccountId int

	 update  LASTINTERNALCODE
	 Set	INTERNALSEQUENCE=INTERNALSEQUENCE+1,
		@nDefaultAccountId       =INTERNALSEQUENCE+1
	 where   TABLENAME='DEFAULTACCOUNT'

	 INSERT INTO DEFAULTACCOUNT (DEFAULTACCOUNTID, CONTROLACCTYPEID, ENTITYNO, ACCOUNTID, PROFITCENTRECODE)
	 SELECT @nDefaultAccountId, 8710, 80, ACCOUNTID, 'ADMIN'
	 FROM LEDGERACCOUNT
	 WHERE ACCOUNTCODE = '201' 
	 PRINT '****  Data successfully added to DEFAULTACCOUNT table.'
	 PRINT ''
 	END
ELSE
 	PRINT '**** DEFAULTACCOUNT.CONTROLACCTYPEID = 8710 AND DEFAULTACCOUNT.ENTITYNO = 80 already exists'
	PRINT ''

GO 

If NOT exists(SELECT * FROM DEFAULTACCOUNT WHERE CONTROLACCTYPEID = 8710 AND ENTITYNO = -283575757)
	BEGIN
 	 PRINT '****  Adding DEFAULTACCOUNT.CONTROLACCTYPEID = 8710 AND DEFAULTACCOUNT.ENTITYNO = -283575757'

	 Declare @nDefaultAccountId int

	 update  LASTINTERNALCODE
	 Set	INTERNALSEQUENCE=INTERNALSEQUENCE+1,
		@nDefaultAccountId       =INTERNALSEQUENCE+1
	 where   TABLENAME='DEFAULTACCOUNT'

	 INSERT INTO DEFAULTACCOUNT (DEFAULTACCOUNTID, CONTROLACCTYPEID, ENTITYNO, ACCOUNTID, PROFITCENTRECODE)
	 SELECT @nDefaultAccountId, 8710, -283575757, LEDGERACCOUNT.ACCOUNTID, 'PTCHM'
	 FROM LEDGERACCOUNT
	 WHERE ACCOUNTCODE = '201' 
	 PRINT '****  Data successfully added to DEFAULTACCOUNT table.'
	 PRINT ''
 	END
ELSE
 	PRINT '**** DEFAULTACCOUNT.CONTROLACCTYPEID = 8710 AND DEFAULTACCOUNT.ENTITYNO = -283575757 already exists'
	PRINT ''
GO

-- Added to enable IPDEMO UPGRADE TO 6
If NOT exists(SELECT * FROM SPECIALNAME WHERE NAMENO = -483)
	BEGIN
		PRINT '****  Adding SPECIALNAME for NAMENO = -483'
		INSERT INTO SPECIALNAME (NAMENO,ENTITYFLAG, IPOFFICEFLAG, BANKFLAG, LASTOPENITEMNO, LASTDRAFTNO, LASTARNO)
		VALUES (-483,1,	0,0,0,0,0)
		PRINT '****  Data successfully added to DEFAULTACCOUNT table.'
		PRINT ''
 	END
ELSE
 	PRINT '**** SPECIALNAME NAMENO = -483 already exists'
	PRINT ''
GO

-- Added to enable IPDEMO UPGRADE TO 6
If NOT exists(SELECT * FROM PROFITCENTRE WHERE PROFITCENTRECODE = 'A-CORP')
	BEGIN
		PRINT '****  Adding PROFITCENTRE A-CORP'
		INSERT INTO PROFITCENTRE(PROFITCENTRECODE, ENTITYNO, DESCRIPTION)
		VALUES ('A-CORP', -483, 'APA Corporate')
		PRINT '****  Data successfully added to DEFAULTACCOUNT table.'
		PRINT ''
 	END
ELSE
 	PRINT '**** PROFITCENTRE PROFITCENTRECODE = A-CORP already exists'
	PRINT ''
GO



If NOT exists(SELECT * FROM DEFAULTACCOUNT WHERE CONTROLACCTYPEID = 8710 AND ENTITYNO = -483)
	BEGIN
 	 PRINT '****  Adding DEFAULTACCOUNT for CONTROLACCTYPEID = 8710 AND ENTITYNO = -483'

	 Declare @nDefaultAccountId int

	 update  LASTINTERNALCODE
	 Set	INTERNALSEQUENCE=INTERNALSEQUENCE+1,
		@nDefaultAccountId       =INTERNALSEQUENCE+1
	 where   TABLENAME='DEFAULTACCOUNT'

	 INSERT INTO DEFAULTACCOUNT (DEFAULTACCOUNTID, CONTROLACCTYPEID, ENTITYNO, ACCOUNTID, PROFITCENTRECODE)
	 SELECT @nDefaultAccountId, 8710, -483, LEDGERACCOUNT.ACCOUNTID, 'A-CORP'
	 FROM LEDGERACCOUNT
	 WHERE ACCOUNTCODE = '201' 
	 PRINT '****  Data successfully added to DEFAULTACCOUNT table.'
	 PRINT ''
 	END
ELSE
 	PRINT '**** DEFAULTACCOUNT.CONTROLACCTYPEID = 8710 AND DEFAULTACCOUNT.ENTITYNO = -483 already exists'
	PRINT ''

GO

-- Added to enable IPDEMO UPGRADE TO 6
If NOT exists(SELECT * FROM PROFITCENTRE WHERE PROFITCENTRECODE = 'G-CORP')
	BEGIN
		PRINT '****  Adding PROFITCENTRE G-CORP'
		INSERT INTO PROFITCENTRE(PROFITCENTRECODE, ENTITYNO, DESCRIPTION)
		VALUES ('G-CORP', 24, 'GBH Corporate')
		PRINT '****  Data successfully added to DEFAULTACCOUNT table.'
		PRINT ''
 	END
ELSE
 	PRINT '**** PROFITCENTRE PROFITCENTRECODE = G-CORP already exists'
	PRINT ''
GO


If NOT exists(SELECT * FROM DEFAULTACCOUNT WHERE CONTROLACCTYPEID = 8710 AND ENTITYNO = 24)
	BEGIN
 	 PRINT '****  Adding DEFAULTACCOUNT for CONTROLACCTYPEID = 8710 AND ENTITYNO = 24'

	 Declare @nDefaultAccountId int

	 update  LASTINTERNALCODE
	 Set	INTERNALSEQUENCE=INTERNALSEQUENCE+1,
		@nDefaultAccountId       =INTERNALSEQUENCE+1
	 where   TABLENAME='DEFAULTACCOUNT'


	 INSERT INTO DEFAULTACCOUNT (DEFAULTACCOUNTID, CONTROLACCTYPEID, ENTITYNO, ACCOUNTID, PROFITCENTRECODE)
	 SELECT @nDefaultAccountId, 8710, 24, LEDGERACCOUNT.ACCOUNTID, 'G-CORP'
	 FROM LEDGERACCOUNT
	 WHERE ACCOUNTCODE = '201' 
	 PRINT '****  Data successfully added to DEFAULTACCOUNT table.'
	 PRINT ''
 	END
ELSE
 	PRINT '**** DEFAULTACCOUNT.CONTROLACCTYPEID = 8710 AND DEFAULTACCOUNT.ENTITYNO = 24 already exists'
	PRINT ''
GO


-- Prepayment  
--select * from LEDGERACCOUNT       
If NOT exists(SELECT * FROM LEDGERACCOUNT WHERE ACCOUNTCODE = '100')
	BEGIN
 	 PRINT '****  Adding LEDGERACCOUNT.ACCOUNTCODE = ''100'''
	 Declare @nAccountId int

	 update  LASTINTERNALCODE
	 Set	INTERNALSEQUENCE=INTERNALSEQUENCE+1,
		@nAccountId       =INTERNALSEQUENCE+1
	 where   TABLENAME='LEDGERACCOUNT'

	 INSERT LEDGERACCOUNT (ACCOUNTID, ACCOUNTCODE, DESCRIPTION, ACCOUNTTYPE, ISACTIVE, 
		PARENTACCOUNTID, DISBURSETOWIP, BUDGETMOVEMENT)
	 VALUES (@nAccountId, '100', 'Prepayment', 8101, 1, NULL, 0, 1 )
	 PRINT '****  Data successfully added to LEDGERACCOUNT table.'
	 PRINT ''
 	END
ELSE
 	PRINT '**** LEDGERACCOUNT.ACCOUNTCODE = ''100'' already exists'
	PRINT ''

GO

--select * from DEFAULTACCOUNT
If NOT exists(SELECT * FROM DEFAULTACCOUNT WHERE CONTROLACCTYPEID = 8711 AND ENTITYNO = 80)
	BEGIN
 	 PRINT '****  Adding DEFAULTACCOUNT.CONTROLACCTYPEID = 8710 AND DEFAULTACCOUNT.ENTITYNO = 80'

	 Declare @nDefaultAccountId int

	 update  LASTINTERNALCODE
	 Set	INTERNALSEQUENCE=INTERNALSEQUENCE+1,
		@nDefaultAccountId       =INTERNALSEQUENCE+1
	 where   TABLENAME='DEFAULTACCOUNT'


	 INSERT INTO DEFAULTACCOUNT (DEFAULTACCOUNTID, CONTROLACCTYPEID, ENTITYNO, ACCOUNTID, PROFITCENTRECODE)
	 SELECT @nDefaultAccountId, 8711, 80, LEDGERACCOUNT.ACCOUNTID, 'ADMIN'
	 FROM LEDGERACCOUNT
	 WHERE ACCOUNTCODE = '100' 
	 PRINT '****  Data successfully added to DEFAULTACCOUNT table.'
	 PRINT ''
 	END
ELSE
 	PRINT '**** DEFAULTACCOUNT.CONTROLACCTYPEID = 8711 AND DEFAULTACCOUNT.ENTITYNO = 80 already exists'
	PRINT ''

GO

If NOT exists(SELECT * FROM DEFAULTACCOUNT WHERE CONTROLACCTYPEID = 8711 AND ENTITYNO = -283575757)
	BEGIN
 	 PRINT '****  Adding DEFAULTACCOUNT.CONTROLACCTYPEID = 8711 AND DEFAULTACCOUNT.ENTITYNO = -283575757'

	 Declare @nDefaultAccountId int

	 update  LASTINTERNALCODE
	 Set	INTERNALSEQUENCE=INTERNALSEQUENCE+1,
		@nDefaultAccountId       =INTERNALSEQUENCE+1
	 where   TABLENAME='DEFAULTACCOUNT'

	 INSERT INTO DEFAULTACCOUNT (DEFAULTACCOUNTID, CONTROLACCTYPEID, ENTITYNO, ACCOUNTID, PROFITCENTRECODE)
	 SELECT @nDefaultAccountId, 8711, -283575757, LEDGERACCOUNT.ACCOUNTID, 'PTCHM'
	 FROM LEDGERACCOUNT
	 WHERE ACCOUNTCODE = '100' 
	 PRINT '****  Data successfully added to DEFAULTACCOUNT table.'
	 PRINT ''
 	END
ELSE
 	PRINT '**** DEFAULTACCOUNT.CONTROLACCTYPEID = 8711 AND DEFAULTACCOUNT.ENTITYNO = -283575757 already exists'
	PRINT ''

GO

If NOT exists(SELECT * FROM DEFAULTACCOUNT WHERE CONTROLACCTYPEID = 8711 AND ENTITYNO = -483)
	BEGIN
 	 PRINT '****  Adding DEFAULTACCOUNT for CONTROLACCTYPEID = 8711 AND ENTITYNO = -483'

	 Declare @nDefaultAccountId int

	 update  LASTINTERNALCODE
	 Set	INTERNALSEQUENCE=INTERNALSEQUENCE+1,
		@nDefaultAccountId       =INTERNALSEQUENCE+1
	 where   TABLENAME='DEFAULTACCOUNT'


	 INSERT INTO DEFAULTACCOUNT (DEFAULTACCOUNTID, CONTROLACCTYPEID, ENTITYNO, ACCOUNTID, PROFITCENTRECODE)
	 SELECT @nDefaultAccountId, 8711, -483, LEDGERACCOUNT.ACCOUNTID, 'A-CORP'
	 FROM LEDGERACCOUNT
	 WHERE ACCOUNTCODE = '100' 
	 PRINT '****  Data successfully added to DEFAULTACCOUNT table.'
	 PRINT ''
 	END
ELSE
 	PRINT '**** DEFAULTACCOUNT.CONTROLACCTYPEID = 8711 AND DEFAULTACCOUNT.ENTITYNO = -483 already exists'
	PRINT ''

GO

If NOT exists(SELECT * FROM DEFAULTACCOUNT WHERE CONTROLACCTYPEID = 8711 AND ENTITYNO = 24)
	BEGIN
 	 PRINT '****  Adding DEFAULTACCOUNT for CONTROLACCTYPEID = 8711 AND ENTITYNO = 24'

	 Declare @nDefaultAccountId int

	 update  LASTINTERNALCODE
	 Set	INTERNALSEQUENCE=INTERNALSEQUENCE+1,
		@nDefaultAccountId       =INTERNALSEQUENCE+1
	 where   TABLENAME='DEFAULTACCOUNT'


	 INSERT INTO DEFAULTACCOUNT (DEFAULTACCOUNTID, CONTROLACCTYPEID, ENTITYNO, ACCOUNTID, PROFITCENTRECODE)
	 SELECT @nDefaultAccountId, 8711, 24, LEDGERACCOUNT.ACCOUNTID, 'G-CORP'
	 FROM LEDGERACCOUNT
	 WHERE ACCOUNTCODE = '100' 
	 PRINT '****  Data successfully added to DEFAULTACCOUNT table.'
	 PRINT ''
 	END
ELSE
 	PRINT '**** DEFAULTACCOUNT.CONTROLACCTYPEID = 8711 AND DEFAULTACCOUNT.ENTITYNO = 24 already exists'
	PRINT ''
GO	           

-- Cash
If NOT exists(SELECT * FROM DEFAULTACCOUNT WHERE CONTROLACCTYPEID = 8712 AND ENTITYNO = 80)
	BEGIN
 	 PRINT '****  Adding DEFAULTACCOUNT.CONTROLACCTYPEID = 8712 AND DEFAULTACCOUNT.ENTITYNO = 80'

	 Declare @nDefaultAccountId int

	 update  LASTINTERNALCODE
	 Set	INTERNALSEQUENCE=INTERNALSEQUENCE+1,
		@nDefaultAccountId       =INTERNALSEQUENCE+1
	 where   TABLENAME='DEFAULTACCOUNT'

	 INSERT DEFAULTACCOUNT (DEFAULTACCOUNTID, CONTROLACCTYPEID, ENTITYNO, ACCOUNTID, PROFITCENTRECODE)
	 VALUES(@nDefaultAccountId, 8712, 80, 1, 'ADMIN')
	 PRINT '****  Data successfully added to DEFAULTACCOUNT table.'
	 PRINT ''
 	END
ELSE
 	PRINT '**** DEFAULTACCOUNT.CONTROLACCTYPEID = 8712 AND DEFAULTACCOUNT.ENTITYNO = 80 already exists'
	PRINT ''
GO

If NOT exists(SELECT * FROM DEFAULTACCOUNT WHERE CONTROLACCTYPEID = 8712 AND ENTITYNO = -283575757)
	BEGIN
 	 PRINT '****  Adding DEFAULTACCOUNT.CONTROLACCTYPEID = 8712 AND DEFAULTACCOUNT.ENTITYNO = -283575757'
	 
	 Declare @nDefaultAccountId int

	 update  LASTINTERNALCODE
	 Set	INTERNALSEQUENCE=INTERNALSEQUENCE+1,
		@nDefaultAccountId       =INTERNALSEQUENCE+1
	 where   TABLENAME='DEFAULTACCOUNT'

	 INSERT DEFAULTACCOUNT (DEFAULTACCOUNTID, CONTROLACCTYPEID, ENTITYNO, ACCOUNTID, PROFITCENTRECODE)
	 VALUES(@nDefaultAccountId, 8712, -283575757, 1, 'PTCHM')
	 PRINT '****  Data successfully added to DEFAULTACCOUNT table.'
	 PRINT ''
 	END
ELSE
 	PRINT '**** DEFAULTACCOUNT.CONTROLACCTYPEID = 8712 AND DEFAULTACCOUNT.ENTITYNO = -283575757 already exists'
	PRINT ''
GO

If NOT exists(SELECT * FROM DEFAULTACCOUNT WHERE CONTROLACCTYPEID = 8712 AND ENTITYNO = -483)
	BEGIN
 	 PRINT '****  Adding DEFAULTACCOUNT for CONTROLACCTYPEID = 8712 AND ENTITYNO = -483'
	 
	 Declare @nDefaultAccountId int

	 update  LASTINTERNALCODE
	 Set	INTERNALSEQUENCE=INTERNALSEQUENCE+1,
		@nDefaultAccountId       =INTERNALSEQUENCE+1
	 where   TABLENAME='DEFAULTACCOUNT'

	 INSERT DEFAULTACCOUNT (DEFAULTACCOUNTID, CONTROLACCTYPEID, ENTITYNO, ACCOUNTID, PROFITCENTRECODE)
	 VALUES(@nDefaultAccountId, 8712, -483, 1, 'A-CORP')
	 PRINT '****  Data successfully added to DEFAULTACCOUNT table.'
	 PRINT ''
 	END
ELSE
 	PRINT '**** DEFAULTACCOUNT.CONTROLACCTYPEID = 8712 AND DEFAULTACCOUNT.ENTITYNO = -483 already exists'
	PRINT ''
GO

If NOT exists(SELECT * FROM DEFAULTACCOUNT WHERE CONTROLACCTYPEID = 8712 AND ENTITYNO = 24)
	BEGIN
 	 PRINT '****  Adding DEFAULTACCOUNT for CONTROLACCTYPEID = 8712 AND ENTITYNO = 24'
	 
	 Declare @nDefaultAccountId int

	 update  LASTINTERNALCODE
	 Set	INTERNALSEQUENCE=INTERNALSEQUENCE+1,
		@nDefaultAccountId       =INTERNALSEQUENCE+1
	 where   TABLENAME='DEFAULTACCOUNT'

	 INSERT DEFAULTACCOUNT (DEFAULTACCOUNTID, CONTROLACCTYPEID, ENTITYNO, ACCOUNTID, PROFITCENTRECODE)
	 VALUES(@nDefaultAccountId, 8712, 24, 1, 'G-CORP')
	 PRINT '****  Data successfully added to DEFAULTACCOUNT table.'
	 PRINT ''
 	END
ELSE
 	PRINT '**** DEFAULTACCOUNT.CONTROLACCTYPEID = 8712 AND DEFAULTACCOUNT.ENTITYNO = 24 already exists'
	PRINT ''
GO	     

-- Trust bank Accounts
If NOT exists(SELECT * FROM LEDGERACCOUNT WHERE ACCOUNTCODE = '1001-1')
	BEGIN
 	 PRINT '****  Adding LEDGERACCOUNT.ACCOUNTCODE = ''1001-1'''
	 Declare @nAccountId int

	 update  LASTINTERNALCODE
	 Set	INTERNALSEQUENCE=INTERNALSEQUENCE+1,
		@nAccountId=INTERNALSEQUENCE+1
	 where   TABLENAME='LEDGERACCOUNT'

	 INSERT LEDGERACCOUNT (ACCOUNTID, ACCOUNTCODE, DESCRIPTION, ACCOUNTTYPE, ISACTIVE, 
		PARENTACCOUNTID, DISBURSETOWIP, BUDGETMOVEMENT)
	 VALUES (@nAccountId, '1001-1', 'Trust Bank',8101,1,NULL,0,1 )
	 PRINT '****  Data successfully added to LEDGERACCOUNT table.'
	 PRINT ''
 	END
ELSE
 	PRINT '**** LEDGERACCOUNT.ACCOUNTCODE = ''1001-1'' already exists'
	PRINT ''

GO

-- ADD CURRENCY 
If NOT exists(SELECT * FROM CURRENCY WHERE CURRENCY = 'AUD' )
	BEGIN
 		PRINT '****  Adding CURRENCY AUD'
		INSERT INTO CURRENCY ( CURRENCY, DESCRIPTION, BUYFACTOR, SELLFACTOR, BANKRATE, BUYRATE, SELLRATE)
		VALUES ('AUD', 'Australian Dollar', 1, 1, 1, 1, 1)
		PRINT '****  Data successfully added to CURRENCY table.'
		PRINT ''
 	END
ELSE
 	PRINT '**** CURRENCY AUD already exists'
	PRINT ''

GO
If NOT exists(SELECT * FROM CURRENCY WHERE CURRENCY = 'USD' )
	BEGIN
 		PRINT '****  Adding CURRENCY USD'
		INSERT INTO CURRENCY ( CURRENCY, DESCRIPTION, BUYFACTOR, SELLFACTOR, BANKRATE, BUYRATE, SELLRATE, ROUNDBILLEDVALUES)
		VALUES (N'USD',	N'U.S. Dollar', 1, 1,	0.5599,	0.5599,	0.5599,	1)
		PRINT '****  Data successfully added to CURRENCY table.'
		PRINT ''
 	END
ELSE
 	PRINT '**** CURRENCY USD already exists'
	PRINT ''

GO
If NOT exists(SELECT * FROM CURRENCY WHERE CURRENCY = 'GBP' )
	BEGIN
 		PRINT '****  Adding CURRENCY GBP'
		INSERT INTO CURRENCY ( CURRENCY, DESCRIPTION, BUYFACTOR, SELLFACTOR, BANKRATE, BUYRATE, SELLRATE)
		VALUES (N'GBP', N'Pound Sterling', 1.0000, 1.0000, 0.3806, 0.3806, 0.3806)
		PRINT '****  Data successfully added to CURRENCY table.'
		PRINT ''
 	END
ELSE
 	PRINT '**** CURRENCY GBP already exists'
	PRINT ''

GO

If NOT exists(SELECT * FROM TABLECODES WHERE TABLECODE = '6001' )
	BEGIN
 		PRINT '****  Adding TABLECODES 6001 for Cheque Account'
		INSERT INTO TABLECODES ( TABLECODE, TABLETYPE, DESCRIPTION)
		VALUES (6001, 60, N'Cheque Account')
		PRINT '****  Data successfully added to TABLECODES table.'
		PRINT ''
 	END
ELSE
 	PRINT '**** TABLECODE 6001 - Cheque Account already exists'
	PRINT ''

GO



-- select * from LEDGERACCOUNT

-- Remove DESCRIPTION from the checking to enable IPDEMO UPGRADE TO 6
-- If NOT exists(SELECT * FROM BANKACCOUNT WHERE DESCRIPTION = 'MY&C US$ Trust Account' AND ACCOUNTOWNER = -283575757 AND BANKNAMENO = 10038 AND SEQUENCENO = 3)
If NOT exists(SELECT * FROM BANKACCOUNT WHERE ACCOUNTOWNER = -283575757 AND BANKNAMENO = 10038 AND SEQUENCENO = 3)
	BEGIN
 	 PRINT '****  Adding BANKACCOUNT.DESCRIPTION = ''MY&C US$ Trust Account'' AND BANKACCOUNT.ACCOUNTOWNER = -283575757 AND BANKACCOUNT.BANKNAMENO = 10038 AND SEQUENCENO = 3'
	    INSERT [BANKACCOUNT]([ACCOUNTOWNER],[BANKNAMENO],[SEQUENCENO],[ISOPERATIONAL],[BANKBRANCHNO],[BRANCHNAMENO],[ACCOUNTNO],[ACCOUNTNAME],[CURRENCY],[DESCRIPTION],[ACCOUNTTYPE],[DRAWCHEQUESFLAG],[LASTMANUALCHEQUE],[LASTAUTOCHEQUE],[ACCOUNTBALANCE],[LOCALBALANCE],[DATECEASED],[BICBANKCODE],[BICCOUNTRYCODE],[BICLOCATIONCODE],[BICBRANCHCODE],[IBAN],[BANKOPERATIONCODE],[DETAILSOFCHARGES],[EFTFILEFORMATUSED],[CABPROFITCENTRE],[CABACCOUNTID],[CABCPROFITCENTRE],[CABCACCOUNTID],[PROCAMOUNTTOWORDS],[TRUSTACCTFLAG])
	    SELECT -283575757,10038,3,1,21,NULL,'435663454','Maxim Yarrow and Colman','USD','MY&C US$ Trust Account',6001,1,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,'344-566',NULL,NULL,NULL,'TM',LEDGERACCOUNT.ACCOUNTID,NULL,NULL,'ap_ConvertNumberToDollarWords', 1
	    FROM LEDGERACCOUNT
	    WHERE ACCOUNTCODE = '1001-1'
	 PRINT '****  Data successfully added to BANKACCOUNT table.'
	 PRINT ''
 	END
ELSE
 	PRINT '**** BANKACCOUNT.DESCRIPTION = ''MY&C US$ Trust Account'' AND BANKACCOUNT.ACCOUNTOWNER = -283575757 AND BANKACCOUNT.BANKNAMENO = 10038 AND SEQUENCENO = 3 already exists'
	PRINT ''

GO
 

If NOT exists(SELECT * FROM BANKACCOUNT WHERE DESCRIPTION = 'MY&C AU$ Trust Account' AND ACCOUNTOWNER = -283575757 AND BANKNAMENO = 10038 AND SEQUENCENO = 4)
	BEGIN
 	 PRINT '****  Adding BANKACCOUNT.DESCRIPTION = ''MY&C AU$ Trust Account'' AND BANKACCOUNT.ACCOUNTOWNER = -283575757 AND BANKACCOUNT.BANKNAMENO = 10038 AND SEQUENCENO = 4'
	INSERT [BANKACCOUNT]([ACCOUNTOWNER],[BANKNAMENO],[SEQUENCENO],[ISOPERATIONAL],[BANKBRANCHNO],[BRANCHNAMENO],[ACCOUNTNO],[ACCOUNTNAME],[CURRENCY],[DESCRIPTION],[ACCOUNTTYPE],[DRAWCHEQUESFLAG],[LASTMANUALCHEQUE],[LASTAUTOCHEQUE],[ACCOUNTBALANCE],[LOCALBALANCE],[DATECEASED],[BICBANKCODE],[BICCOUNTRYCODE],[BICLOCATIONCODE],[BICBRANCHCODE],[IBAN],[BANKOPERATIONCODE],[DETAILSOFCHARGES],[EFTFILEFORMATUSED],[CABPROFITCENTRE],[CABACCOUNTID],[CABCPROFITCENTRE],[CABCACCOUNTID],[PROCAMOUNTTOWORDS],[TRUSTACCTFLAG])
	SELECT -283575757,10038,4,1,34,NULL,'456623556','Maxim Yarrow and Colman','AUD','MY&C AU$ Trust Account',6001,1,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,'345-651',NULL,NULL,NULL,'TM',LEDGERACCOUNT.ACCOUNTID,NULL,NULL,'ap_ConvertNumberToDollarWords', 1
	FROM LEDGERACCOUNT
	WHERE ACCOUNTCODE = '1001-1'
	PRINT '****  Data successfully added to BANKACCOUNT table.'
	 PRINT ''
 	END
ELSE
 	PRINT '**** BANKACCOUNT.DESCRIPTION = ''MY&C AU$ Trust Account'' AND BANKACCOUNT.ACCOUNTOWNER = -283575757 AND BANKACCOUNT.BANKNAMENO = 10038 AND SEQUENCENO = 4 already exists'
	PRINT ''

GO
-- SELECT * FROM BANKACCOUNT

If NOT exists(SELECT * FROM EFTDETAIL WHERE ACCOUNTOWNER = -283575757 AND BANKNAMENO = 10038 AND SEQUENCENO = 3)
	BEGIN
 	 PRINT '****  Adding EFTDETAIL.ACCOUNTOWNER = -283575757 AND EFTDETAIL.BANKNAMENO = 10038 AND SEQUENCENO = 3' 
	    INSERT INTO [dbo].[EFTDETAIL]([ACCOUNTOWNER],[BANKNAMENO],[SEQUENCENO],[BANKCODE],[COUNTRYCODE],[LOCATIONCODE],[BRANCHCODE],[BANKOPERATIONCODE],[DETAILSOFCHARGES],[FILEFORMATUSED],[ALIAS],[USERREFNO],[APPLICATIONID],[FORMATFILE],[SQLTEMPLATE],[PAYMENTREFPREFIX],[LASTPAYMENTREFNO],[SELFBALANCING],[LOGUSERID],[LOGIDENTITYID],[LOGTRANSACTIONNO], [LOGDATETIMESTAMP], [LOGAPPLICATION] ,[LOGOFFICEID])
	    VALUES(-283575757,10038,3,'MYC','AU','BR','BRI',9601,9701,3,'MYCUSTA',123,'MYCUSTA','xslt_eftpaymenttxt.xsl','SQLT_EFTPayment.xml',0,NULL,1,'SYSADM',15,NULL,GETDATE(),'Trust Accounting System',NULL)
	PRINT '****  Data successfully added to EFTDETAIL table.'
	 PRINT ''
 	END
ELSE
 	PRINT '**** EFTDETAIL.ACCOUNTOWNER = -283575757 AND EFTDETAIL.BANKNAMENO = 10038 AND SEQUENCENO = 3 already exists'
	PRINT ''

GO

If NOT exists(SELECT * FROM EFTDETAIL WHERE ACCOUNTOWNER = -283575757 AND BANKNAMENO = 10038 AND SEQUENCENO = 4)
	BEGIN
 	 PRINT '****  Adding EFTDETAIL.ACCOUNTOWNER = -283575757 AND EFTDETAIL.BANKNAMENO = 10038 AND SEQUENCENO = 4' 
	    INSERT INTO [dbo].[EFTDETAIL]([ACCOUNTOWNER],[BANKNAMENO],[SEQUENCENO],[BANKCODE],[COUNTRYCODE],[LOCATIONCODE],[BRANCHCODE],[BANKOPERATIONCODE],[DETAILSOFCHARGES],[FILEFORMATUSED],[ALIAS],[USERREFNO],[APPLICATIONID],[FORMATFILE],[SQLTEMPLATE],[PAYMENTREFPREFIX],[LASTPAYMENTREFNO],[SELFBALANCING],[LOGUSERID],[LOGIDENTITYID],[LOGTRANSACTIONNO], [LOGDATETIMESTAMP], [LOGAPPLICATION] ,[LOGOFFICEID])
	    VALUES(-283575757,10038,4,'CWA','AU','SY','SYD',9601,9701,3,'MYCATA',456,'MYCATA','xslt_eftpaymenttxt.xsl','SQLT_EFTPayment.xml',0,NULL,1,'SYSADM',15,NULL,GETDATE(),'Trust Accounting System',NULL)
	PRINT '****  Data successfully added to EFTDETAIL table.'
	 PRINT ''
 	END
ELSE
 	PRINT '**** EFTDETAIL.ACCOUNTOWNER = -283575757 AND EFTDETAIL.BANKNAMENO = 10038 AND SEQUENCENO = 4 already exists'
	PRINT ''

GO
-- SELECT * FROM EFTDETAIL  

	/**********************************************************************************************************/
	/*** 10105 Add data PAYMENTMETHODS.PAYMENTMETHOD = -5							***/
	/**********************************************************************************************************/
	If NOT exists (select * from PAYMENTMETHODS where PAYMENTMETHOD = -5)
        	BEGIN
         	 PRINT '**** 10105 Adding data PAYMENTMETHODS.PAYMENTMETHOD = -5'
		INSERT INTO PAYMENTMETHODS (PAYMENTMETHOD, PAYMENTDESCRIPTION, PRESENTPHYSICALLY, USEDBY)
		VALUES(-5,'Electronic Receipts',0,80)
        	 PRINT '**** 10105 Data successfully added to PAYMENTMETHODS table.'
		 PRINT ''
         	END
    	ELSE
         	PRINT '**** 10105 PAYMENTMETHODS.PAYMENTMETHOD = -5 already exists'
         	PRINT ''
    	go


	/**********************************************************************************************************/
	/*** 10105 Add data PAYMENTMETHODS.PAYMENTMETHOD = -4							***/
	/**********************************************************************************************************/
	If NOT exists (select * from PAYMENTMETHODS where PAYMENTMETHOD = -4)
        	BEGIN
         	 PRINT '**** 10105 Adding data PAYMENTMETHODS.PAYMENTMETHOD = -4'
		INSERT INTO PAYMENTMETHODS (PAYMENTMETHOD, PAYMENTDESCRIPTION, PRESENTPHYSICALLY, USEDBY)
		VALUES(-4,'Cash',1,80)
        	 PRINT '**** 10105 Data successfully added to PAYMENTMETHODS table.'
		 PRINT ''
         	END
    	ELSE
         	PRINT '**** 10105 PAYMENTMETHODS.PAYMENTMETHOD = -4 already exists'
         	PRINT ''
    	go


	/**********************************************************************************************************/
	/*** 10105 Add data PAYMENTMETHODS.PAYMENTMETHOD = -3							***/
	/**********************************************************************************************************/
	If NOT exists (select * from PAYMENTMETHODS where PAYMENTMETHOD = -3)
        	BEGIN
         	 PRINT '**** 10105 Adding data PAYMENTMETHODS.PAYMENTMETHOD = -3'
		INSERT INTO PAYMENTMETHODS (PAYMENTMETHOD, PAYMENTDESCRIPTION, PRESENTPHYSICALLY, USEDBY)
		VALUES(-3,'Credit Card',0,80)
        	 PRINT '**** 10105 Data successfully added to PAYMENTMETHODS table.'
		 PRINT ''
         	END
    	ELSE
         	PRINT '**** 10105 PAYMENTMETHODS.PAYMENTMETHOD = -3 already exists'
         	PRINT ''
    	go


	/**********************************************************************************************************/
	/*** 10105 Add data PAYMENTMETHODS.PAYMENTMETHOD = -2							***/
	/**********************************************************************************************************/
	If NOT exists (select * from PAYMENTMETHODS where PAYMENTMETHOD = -2)
        	BEGIN
         	 PRINT '**** 10105 Adding data PAYMENTMETHODS.PAYMENTMETHOD = -2'
		INSERT INTO PAYMENTMETHODS (PAYMENTMETHOD, PAYMENTDESCRIPTION, PRESENTPHYSICALLY, USEDBY)
		VALUES(-2,'Bank Draft',0,80)
        	 PRINT '**** 10105 Data successfully added to PAYMENTMETHODS table.'
		 PRINT ''
         	END
    	ELSE
         	PRINT '**** 10105 PAYMENTMETHODS.PAYMENTMETHOD = -2 already exists'
         	PRINT ''
    	go
    
    
	-- remove corrupted data as requested from KR
    	delete from CASETEXT where  CASEID = -487 and CLASS = '42' and TEXTTYPE = 'R'
    	go