//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inprotech.Integration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Alerts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Alerts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inprotech.Integration.Properties.Alerts", typeof(Alerts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulk update could not be completed. Contact your system administrator for details..
        /// </summary>
        internal static string BulkUpdate_Fails {
            get {
                return ResourceManager.GetString("BulkUpdate_Fails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected class {0} is not applicable for some of the cases. .
        /// </summary>
        internal static string InvalidCasesForGoodsAndServicesWithClass {
            get {
                return ResourceManager.GetString("InvalidCasesForGoodsAndServicesWithClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note that after the expiry date, you may be BLOCKED from using the specific module..
        /// </summary>
        internal static string LicenseExpiry_Explanation {
            get {
                return ResourceManager.GetString("LicenseExpiry_Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact Inprotech Support immediately for a licence extension..
        /// </summary>
        internal static string LicenseExpiry_Extension {
            get {
                return ResourceManager.GetString("LicenseExpiry_Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} will expire on {1}..
        /// </summary>
        internal static string LicenseExpiry_ModuleItem {
            get {
                return ResourceManager.GetString("LicenseExpiry_ModuleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The licences for the following modules are about to expire..
        /// </summary>
        internal static string LicenseExpiry_ModuleList {
            get {
                return ResourceManager.GetString("LicenseExpiry_ModuleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inprotech licence approaching expiry.
        /// </summary>
        internal static string LicenseExpiry_Title {
            get {
                return ResourceManager.GetString("LicenseExpiry_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of the user administrators in the system has an email address.  Unable to notify user administrators of errors..
        /// </summary>
        internal static string LicenseExpiry_UnableToNotify {
            get {
                return ResourceManager.GetString("LicenseExpiry_UnableToNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cases .
        /// </summary>
        internal static string MultipleCaseRef {
            get {
                return ResourceManager.GetString("MultipleCaseRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important: Password Expiration.
        /// </summary>
        internal static string PasswordExpiry_Title {
            get {
                return ResourceManager.GetString("PasswordExpiry_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user does not has email address.  Unable to notify user for password expiration..
        /// </summary>
        internal static string PasswordExpiry_UnableToNotify {
            get {
                return ResourceManager.GetString("PasswordExpiry_UnableToNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to case .
        /// </summary>
        internal static string SingleCaseRef {
            get {
                return ResourceManager.GetString("SingleCaseRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reports server returns unexpected content type please verify Reporting service configuration settings..
        /// </summary>
        internal static string SsrsReturnsUnExpectedContentType {
            get {
                return ResourceManager.GetString("SsrsReturnsUnExpectedContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnAuthorizedCases: .
        /// </summary>
        internal static string UnAuthorisedCases {
            get {
                return ResourceManager.GetString("UnAuthorisedCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of the user administrators in the system has an email address.  Unable to notify user administrators of locked accounts..
        /// </summary>
        internal static string UserAccountLocked_UnableToNotify {
            get {
                return ResourceManager.GetString("UserAccountLocked_UnableToNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following Inprotech user has exceeded the maximum number of attempts to login to the application:.
        /// </summary>
        internal static string UserAccountLockedExplanation {
            get {
                return ResourceManager.GetString("UserAccountLockedExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user account &apos;{0}&apos; has been locked..
        /// </summary>
        internal static string UserAccountLockedTitle {
            get {
                return ResourceManager.GetString("UserAccountLockedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inprotech Verification Code.
        /// </summary>
        internal static string UserAccountRequiresTwoFactorEmailTitle {
            get {
                return ResourceManager.GetString("UserAccountRequiresTwoFactorEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Use this code for Inprotech verification:.
        /// </summary>
        internal static string UserAccountRequiresTwoFactorExplanation {
            get {
                return ResourceManager.GetString("UserAccountRequiresTwoFactorExplanation", resourceCulture);
            }
        }
    }
}
