//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inprotech.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConfigurationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigurationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inprotech.Web.Properties.ConfigurationResources", typeof(ConfigurationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Characteristics.
        /// </summary>
        public static string AllCharacteristics {
            get {
                return ResourceManager.GetString("AllCharacteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting this default item will also delete the associated language items for this combination..
        /// </summary>
        public static string ClassItemDeleteValidation {
            get {
                return ResourceManager.GetString("ClassItemDeleteValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to copy the valid combinations that do not exist?.
        /// </summary>
        public static string ConfirmCopyValidCombination {
            get {
                return ResourceManager.GetString("ConfirmCopyValidCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save this as a valid combination only for:.
        /// </summary>
        public static string ConfirmSaveForValidCombination {
            get {
                return ResourceManager.GetString("ConfirmSaveForValidCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected items have been deleted sucessfully..
        /// </summary>
        public static string DeleteSuccessMessage {
            get {
                return ResourceManager.GetString("DeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display error.
        /// </summary>
        public static string DisplayError {
            get {
                return ResourceManager.GetString("DisplayError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display warning dialog.
        /// </summary>
        public static string DisplayWarning {
            get {
                return ResourceManager.GetString("DisplayWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display warning dialog &amp; prompt for password.
        /// </summary>
        public static string DisplayWarningPromptPassword {
            get {
                return ResourceManager.GetString("DisplayWarningPromptPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Combination.
        /// </summary>
        public static string DuplicateCombination {
            get {
                return ResourceManager.GetString("DuplicateCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This attribute already exists for the selected jurisdiction..
        /// </summary>
        public static string DuplicateJurisdictionAttribute {
            get {
                return ResourceManager.GetString("DuplicateJurisdictionAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Text Type and Property Type combination already exists for the selected Jurisdiction..
        /// </summary>
        public static string DuplicateJurisdictionTexts {
            get {
                return ResourceManager.GetString("DuplicateJurisdictionTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The valid combination already exists for:.
        /// </summary>
        public static string DuplicateValidCombination {
            get {
                return ResourceManager.GetString("DuplicateValidCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text type can not be blank..
        /// </summary>
        public static string EmpltyJurisdictionTexts {
            get {
                return ResourceManager.GetString("EmpltyJurisdictionTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jurisdiction Code &apos;{0}&apos; already exists. Please use another code that is unique..
        /// </summary>
        public static string ErrorDuplicateJurisdictionCode {
            get {
                return ResourceManager.GetString("ErrorDuplicateJurisdictionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locality Code &apos;{0}&apos; already exists. Please use another locality code that is unique..
        /// </summary>
        public static string ErrorDuplicateLocalityCode {
            get {
                return ResourceManager.GetString("ErrorDuplicateLocalityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locality &apos;{0}&apos; already exists. Please use another description that is unique..
        /// </summary>
        public static string ErrorDuplicateLocalityDescription {
            get {
                return ResourceManager.GetString("ErrorDuplicateLocalityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Relationship Code &apos;{0}&apos; already exists. Please use another name relationship code that is unique..
        /// </summary>
        public static string ErrorDuplicateNameRelationshipCode {
            get {
                return ResourceManager.GetString("ErrorDuplicateNameRelationshipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Relationship &apos;{0}&apos; already exists. Please use another description that is unique..
        /// </summary>
        public static string ErrorDuplicateNameRelationshipDescription {
            get {
                return ResourceManager.GetString("ErrorDuplicateNameRelationshipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse Relationship &apos;{0}&apos; already exists. Please use another reverse relationship that is unique..
        /// </summary>
        public static string ErrorDuplicateNameRelationshipReverseDescription {
            get {
                return ResourceManager.GetString("ErrorDuplicateNameRelationshipReverseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This valid combination already exists for the selected Jurisdiction. Modify the combination and try again..
        /// </summary>
        public static string ErrorDuplicateValidCombination {
            get {
                return ResourceManager.GetString("ErrorDuplicateValidCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Case Category is not available for the selected combination. Modify the combination and try again..
        /// </summary>
        public static string ErrorInvalidCaseCategories {
            get {
                return ResourceManager.GetString("ErrorInvalidCaseCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Property Type is not available for the selected Jurisdiction. Modify either characteristic and try again..
        /// </summary>
        public static string ErrorInvalidPropertyTypes {
            get {
                return ResourceManager.GetString("ErrorInvalidPropertyTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string EventNoteTypeDescription {
            get {
                return ResourceManager.GetString("EventNoteTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string EventNoteTypeExternal {
            get {
                return ResourceManager.GetString("EventNoteTypeExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items highlighted in red cannot be deleted as they are in use..
        /// </summary>
        public static string InUseErrorMessage {
            get {
                return ResourceManager.GetString("InUseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected Case Category is not available for:.
        /// </summary>
        public static string InvalidCaseCategory {
            get {
                return ResourceManager.GetString("InvalidCaseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected Property Type is not available for:.
        /// </summary>
        public static string InValidPorpertyTypes {
            get {
                return ResourceManager.GetString("InValidPorpertyTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string LocalityCity {
            get {
                return ResourceManager.GetString("LocalityCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string LocalityCode {
            get {
                return ResourceManager.GetString("LocalityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string LocalityCountry {
            get {
                return ResourceManager.GetString("LocalityCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LocalityName {
            get {
                return ResourceManager.GetString("LocalityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string LocalityState {
            get {
                return ResourceManager.GetString("LocalityState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of attributes for ‘{0}’ exceeded..
        /// </summary>
        public static string MaxAttributesError {
            get {
                return ResourceManager.GetString("MaxAttributesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum number of attributes required for ‘{0}’ is {1}. Add more attributes for the type..
        /// </summary>
        public static string MinAttributesError {
            get {
                return ResourceManager.GetString("MinAttributesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string NameAliasType {
            get {
                return ResourceManager.GetString("NameAliasType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string NameAliasTypeDescription {
            get {
                return ResourceManager.GetString("NameAliasTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique.
        /// </summary>
        public static string NameAliasTypeUnique {
            get {
                return ResourceManager.GetString("NameAliasTypeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory to select one of these options..
        /// </summary>
        public static string NameRelationAtleastOneOptionRequired {
            get {
                return ResourceManager.GetString("NameRelationAtleastOneOptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Action.
        /// </summary>
        public static string NoAction {
            get {
                return ResourceManager.GetString("NoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Unable to retrieve class item for update.&quot;.
        /// </summary>
        public static string RecordNotFoundForUpdate {
            get {
                return ResourceManager.GetString("RecordNotFoundForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable Combination.
        /// </summary>
        public static string UnavailableCombination {
            get {
                return ResourceManager.GetString("UnavailableCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string ValidAction {
            get {
                return ResourceManager.GetString("ValidAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basis.
        /// </summary>
        public static string ValidBasis {
            get {
                return ResourceManager.GetString("ValidBasis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string ValidCategory {
            get {
                return ResourceManager.GetString("ValidCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checklist.
        /// </summary>
        public static string ValidChecklist {
            get {
                return ResourceManager.GetString("ValidChecklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the valid combinations already exist for:.
        /// </summary>
        public static string ValidCombinationExistForCopy {
            get {
                return ResourceManager.GetString("ValidCombinationExistForCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Law.
        /// </summary>
        public static string ValidDateOfLaw {
            get {
                return ResourceManager.GetString("ValidDateOfLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Type.
        /// </summary>
        public static string ValidPropertyType {
            get {
                return ResourceManager.GetString("ValidPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Relationship.
        /// </summary>
        public static string ValidRelationship {
            get {
                return ResourceManager.GetString("ValidRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string ValidStatus {
            get {
                return ResourceManager.GetString("ValidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Type.
        /// </summary>
        public static string ValidSubType {
            get {
                return ResourceManager.GetString("ValidSubType", resourceCulture);
            }
        }
    }
}
