//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inprotech.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inprotech.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Became Full Member cannot exist for an Associate member..
        /// </summary>
        public static string AssociateMemberErrorMessage {
            get {
                return ResourceManager.GetString("AssociateMemberErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while saving following Characteristics:.
        /// </summary>
        public static string CharacteristicsErrorTitle {
            get {
                return ResourceManager.GetString("CharacteristicsErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code &apos;{0}&apos; already exists. Please use another code that is unique..
        /// </summary>
        public static string CodeNotUnique {
            get {
                return ResourceManager.GetString("CodeNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is a required field..
        /// </summary>
        public static string DataMappingDescriptionMandatory {
            get {
                return ResourceManager.GetString("DataMappingDescriptionMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data mapping &apos;{0}&apos; already exists. Please use another description that is unique..
        /// </summary>
        public static string DataMappingDescriptionNotUnique {
            get {
                return ResourceManager.GetString("DataMappingDescriptionNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event &apos;{0}&apos; already exists. Please use another code that is unique..
        /// </summary>
        public static string DataMappingOutput {
            get {
                return ResourceManager.GetString("DataMappingOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Became Associate Member cannot be less than Date Joined Group..
        /// </summary>
        public static string DateAssociateMemberErrorMessage {
            get {
                return ResourceManager.GetString("DateAssociateMemberErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Left Group cannot be less than Date Joined Group..
        /// </summary>
        public static string DateCeasedErrorMessage {
            get {
                return ResourceManager.GetString("DateCeasedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Became Full Member cannot be less than Date Joined Group..
        /// </summary>
        public static string DateFullMembershipErrorMessage {
            get {
                return ResourceManager.GetString("DateFullMembershipErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Left Group cannot be less than Date Became Associate Member..
        /// </summary>
        public static string DateLeftAssoicateMemberErrorMessage {
            get {
                return ResourceManager.GetString("DateLeftAssoicateMemberErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Left Group cannot be less than Date Became Full Member..
        /// </summary>
        public static string DateLeftErrorMessage {
            get {
                return ResourceManager.GetString("DateLeftErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Delete.
        /// </summary>
        public static string DeleteErrorTitle {
            get {
                return ResourceManager.GetString("DeleteErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This event is being used by the following criteria: .
        /// </summary>
        public static string DeleteEventErrorCritieria {
            get {
                return ResourceManager.GetString("DeleteEventErrorCritieria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This event exists as an &apos;orphaned event&apos; on one or more cases..
        /// </summary>
        public static string DeleteEventErrorOrphan {
            get {
                return ResourceManager.GetString("DeleteEventErrorOrphan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not unique..
        /// </summary>
        public static string DescriptionNotUnique {
            get {
                return ResourceManager.GetString("DescriptionNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Jurisdiction is already a member of the selected Group..
        /// </summary>
        public static string DuplicateGroupCodeMessage {
            get {
                return ResourceManager.GetString("DuplicateGroupCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Texts and Property combination already exists..
        /// </summary>
        public static string DuplicateTextsPropertyMessage {
            get {
                return ResourceManager.GetString("DuplicateTextsPropertyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The batch with batch identifier, &apos;{0}&apos; has already been processed and cannot be resubmitted..
        /// </summary>
        public static string ErrorBatchAlreadyProcessed {
            get {
                return ResourceManager.GetString("ErrorBatchAlreadyProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The batch with batch identifier, &apos;{0}&apos; is already in progress. Please refresh the window..
        /// </summary>
        public static string ErrorBatchInProgress {
            get {
                return ResourceManager.GetString("ErrorBatchInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case not found..
        /// </summary>
        public static string ErrorCasesCaseNotFound {
            get {
                return ResourceManager.GetString("ErrorCasesCaseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find any of specified cases. If they exist, you may not have update permission to them..
        /// </summary>
        public static string ErrorCasesOneOrMoreSpecifiedCasesNotFoundOrNotUpdatable {
            get {
                return ResourceManager.GetString("ErrorCasesOneOrMoreSpecifiedCasesNotFoundOrNotUpdatable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data entry task not found..
        /// </summary>
        public static string ErrorDataEntryTaskDataEntryTaskNotFound {
            get {
                return ResourceManager.GetString("ErrorDataEntryTaskDataEntryTaskNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Item &apos;{0}&apos; already exists. Please use another data item name that is unique..
        /// </summary>
        public static string ErrorDuplicateDataItemName {
            get {
                return ResourceManager.GetString("ErrorDuplicateDataItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Note Type &apos;{0}&apos; already exists. Please use another description that is unique..
        /// </summary>
        public static string ErrorDuplicateEventNoteTypeCode {
            get {
                return ResourceManager.GetString("ErrorDuplicateEventNoteTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Alias with the same description &apos;{0}&apos; already exists. Please enter a unique description..
        /// </summary>
        public static string ErrorDuplicateNameAliasDesc {
            get {
                return ResourceManager.GetString("ErrorDuplicateNameAliasDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Alias with the same type &apos;{0}&apos; already exists. Please enter a unique type..
        /// </summary>
        public static string ErrorDuplicateNameAliasType {
            get {
                return ResourceManager.GetString("ErrorDuplicateNameAliasType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Restriction &apos;{0}&apos; already exists. Please use another description that is unique..
        /// </summary>
        public static string ErrorDuplicateNameRestrictionDescription {
            get {
                return ResourceManager.GetString("ErrorDuplicateNameRestrictionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Type Code &apos;{0}&apos; already exists. Please use another name type code that is unique..
        /// </summary>
        public static string ErrorDuplicateNameTypeCode {
            get {
                return ResourceManager.GetString("ErrorDuplicateNameTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Type Code &apos;{0}&apos; already exists. Please use another number type code that is unique..
        /// </summary>
        public static string ErrorDuplicateNumberTypeCode {
            get {
                return ResourceManager.GetString("ErrorDuplicateNumberTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A CSV file with the file name of &apos;{1}&apos;, or CPA XML file with the sender identifier of &apos;{1}&apos; has already been imported to Inprotech for {0}. Try importing it with a different file name or sender identifier..
        /// </summary>
        public static string ErrorDuplicateSenderRequest {
            get {
                return ResourceManager.GetString("ErrorDuplicateSenderRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status &apos;{0}&apos; already exists. Please use another internal description that is unique..
        /// </summary>
        public static string ErrorDuplicateStatusDescription {
            get {
                return ResourceManager.GetString("ErrorDuplicateStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Type Code &apos;{0}&apos; already exists. Please use another text type code that is unique..
        /// </summary>
        public static string ErrorDuplicateTextTypeCode {
            get {
                return ResourceManager.GetString("ErrorDuplicateTextTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the file you have added is not the same as the value of the SenderFilename value in the CPA XML. Change the file name..
        /// </summary>
        public static string ErrorFileNameMustMatchSenderFilename {
            get {
                return ResourceManager.GetString("ErrorFileNameMustMatchSenderFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified resource not found..
        /// </summary>
        public static string ErrorHttpResourceNotFound {
            get {
                return ResourceManager.GetString("ErrorHttpResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another staff member is currently using Import Cases. Only one set of data can be imported at a time. Try again soon..
        /// </summary>
        public static string ErrorOtherExportInProgress {
            get {
                return ResourceManager.GetString("ErrorOtherExportInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough information to perform an exact find..
        /// </summary>
        public static string ErrorPriorArtNotEnoughInfoForExactFind {
            get {
                return ResourceManager.GetString("ErrorPriorArtNotEnoughInfoForExactFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have sufficient privileges to perform this action..
        /// </summary>
        public static string ErrorSecurityTaskAccessCheckFailure {
            get {
                return ResourceManager.GetString("ErrorSecurityTaskAccessCheckFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no SenderFilename element in the CPA XML. Add the SenderFilename element to the file..
        /// </summary>
        public static string ErrorSenderFilenameMustExist {
            get {
                return ResourceManager.GetString("ErrorSenderFilenameMustExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SenderRequestIdentifier is not found in the CPA XML. Add the SenderRequestIdentifier to the file..
        /// </summary>
        public static string ErrorSenderIdentifierMustExist {
            get {
                return ResourceManager.GetString("ErrorSenderIdentifierMustExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are multiple EDE Identifier alias matches in Inprotech on the Sender &apos;{0}&apos;. Ensure only a single name is mapped to the Sender in Inprotech..
        /// </summary>
        public static string ErrorSenderMappedToMoreThanOneNameAliases {
            get {
                return ResourceManager.GetString("ErrorSenderMappedToMoreThanOneNameAliases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no EDE Identifier aliases for any name in Inprotech that match the Sender &apos;{0}&apos;. Ensure a name is mapped to the Sender in Inprotech..
        /// </summary>
        public static string ErrorSenderNotMappedOrNotProvided {
            get {
                return ResourceManager.GetString("ErrorSenderNotMappedOrNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be one SenderDetails element included in the CPA XML. Update the CPA XML..
        /// </summary>
        public static string ErrorTooManySenderDetailsOrNotFound {
            get {
                return ResourceManager.GetString("ErrorTooManySenderDetailsOrNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SenderRequest type of &apos;{0}&apos; is not valid. Enter &apos;Case Import&apos; in the SenderRequest element..
        /// </summary>
        public static string ErrorUnknownSenderRequestType {
            get {
                return ResourceManager.GetString("ErrorUnknownSenderRequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethical Wall.
        /// </summary>
        public static string EthicalWall {
            get {
                return ResourceManager.GetString("EthicalWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate mappings present for column &apos;{0}&apos;. Rectify mapping and try again..
        /// </summary>
        public static string ImportCasesDuplicateMapping {
            get {
                return ResourceManager.GetString("ImportCasesDuplicateMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid sender request type used - &apos;{0}&apos;. Rectify and try again..
        /// </summary>
        public static string ImportCasesInvalidSenderRequestType {
            get {
                return ResourceManager.GetString("ImportCasesInvalidSenderRequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cases found in the file &apos;{0}&apos;.
        /// </summary>
        public static string ImportCasesNoCasesFound {
            get {
                return ResourceManager.GetString("ImportCasesNoCasesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Id needs to be provided as part of filename for sender request type - &apos;{0}&apos;. Rectify and try again..
        /// </summary>
        public static string ImportCasesSenderIdNotProvided {
            get {
                return ResourceManager.GetString("ImportCasesSenderIdNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following Characteristics were not found in the system. Please refresh the window to reload the latest available Characteristics..
        /// </summary>
        public static string InstructionCharacteristicsNotFound {
            get {
                return ResourceManager.GetString("InstructionCharacteristicsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Instruction was not found in the system..
        /// </summary>
        public static string InstructionNotFound {
            get {
                return ResourceManager.GetString("InstructionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while saving following Instructions:.
        /// </summary>
        public static string InstructionsErrorTitle {
            get {
                return ResourceManager.GetString("InstructionsErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following Characteristics are in use and cannot be deleted:.
        /// </summary>
        public static string InstructionTypeCharacteristicsInUse {
            get {
                return ResourceManager.GetString("InstructionTypeCharacteristicsInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is used by the following {1}.
        /// </summary>
        public static string InstructionTypeCharacteristicsInUseErrorMessage {
            get {
                return ResourceManager.GetString("InstructionTypeCharacteristicsInUseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following Instructions are in use and cannot be deleted:.
        /// </summary>
        public static string InstructionTypeInstructionsInUse {
            get {
                return ResourceManager.GetString("InstructionTypeInstructionsInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is used by one or more Names or Cases.
        /// </summary>
        public static string InstructionTypeInstructionsInUseErrorMessage {
            get {
                return ResourceManager.GetString("InstructionTypeInstructionsInUseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Instruction Type was not found in the system..
        /// </summary>
        public static string InstructionTypeNotFound {
            get {
                return ResourceManager.GetString("InstructionTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Sanity Check Data Item entry point. The SQL Statement for a Data Item that belongs to the Data Validation group must contain the entry point formatted as &apos;=:CaseId&apos;..
        /// </summary>
        public static string InvalidCaseIdForCaseValidationSql {
            get {
                return ResourceManager.GetString("InvalidCaseIdForCaseValidationSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is more than one column selected in the SQL statement which is potentially an image. Please change the SELECT statement to only return one (long) column or de-select the Image option..
        /// </summary>
        public static string MultipleImageColumn {
            get {
                return ResourceManager.GetString("MultipleImageColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested Name Relation cannot be deleted as it is essential to other existing information..
        /// </summary>
        public static string NameRelationAlreadyInUse {
            get {
                return ResourceManager.GetString("NameRelationAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicable to CRM.
        /// </summary>
        public static string NameRelationCrm {
            get {
                return ResourceManager.GetString("NameRelationCrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string NameRelationEmployee {
            get {
                return ResourceManager.GetString("NameRelationEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual.
        /// </summary>
        public static string NameRelationIndividual {
            get {
                return ResourceManager.GetString("NameRelationIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation.
        /// </summary>
        public static string NameRelationOrganisation {
            get {
                return ResourceManager.GetString("NameRelationOrganisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship Code.
        /// </summary>
        public static string NameRelationRelationship {
            get {
                return ResourceManager.GetString("NameRelationRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship Description.
        /// </summary>
        public static string NameRelationRelationshipDesc {
            get {
                return ResourceManager.GetString("NameRelationRelationshipDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse Relationship.
        /// </summary>
        public static string NameRelationReverseDescription {
            get {
                return ResourceManager.GetString("NameRelationReverseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse the SQL statement to derive values for the columns SQL_DESCRIBE and SQL_INTO in the ITEM table. This is probably because the SQL statement contains comments, or a subquery or complex expression. Please simplify the SQL statement or use a stored procedure instead..
        /// </summary>
        public static string NoColumnSql {
            get {
                return ResourceManager.GetString("NoColumnSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no return value from the stored procedure used by the data item. The stored procedure must use SELECT to return values instead of using the RETURN or OUTPUT parameters..
        /// </summary>
        public static string NoColumnStoredProcedure {
            get {
                return ResourceManager.GetString("NoColumnStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no columns selected in the SQL statement which could potentially contain an image. Please change the SELECT statement or untick the &apos;Returns an image&apos; option..
        /// </summary>
        public static string NoImageColumn {
            get {
                return ResourceManager.GetString("NoImageColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group and Country cannot be same..
        /// </summary>
        public static string SameMemberAndGroupCodeMessage {
            get {
                return ResourceManager.GetString("SameMemberAndGroupCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one case id must be specified..
        /// </summary>
        public static string ValidationAtLeastOneCaseIdMustBeSpecified {
            get {
                return ResourceManager.GetString("ValidationAtLeastOneCaseIdMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must not be greater than {0} characters..
        /// </summary>
        public static string ValidationErrorMaxLengthExceeded {
            get {
                return ResourceManager.GetString("ValidationErrorMaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit limit exceeded..
        /// </summary>
        public static string WarningCreditLimitExceeded {
            get {
                return ResourceManager.GetString("WarningCreditLimitExceeded", resourceCulture);
            }
        }
    }
}
