IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CLIENTLICENSE')
	BEGIN
	 PRINT '**** Creating CLIENTLICENSE table'
 	 CREATE TABLE dbo.CLIENTLICENSE (
	        NAMENO			int NOT NULL,
	        MODULEID		int NOT NULL,
		MAXUSERS		int NULL,
		PRICINGMODEL		int NULL,
		MAXCASES		int NULL,
		EXPIRYDATE		datetime NULL,
		EXPIRYACTION		int NULL,
		EXPIRYWARNINGDAYS	int NULL,
		LICENSETYPE		int NULL
	 	)
	 print '**** CLIENTLICENSE table succesfully created'
	END
ELSE
	BEGIN
	 If NOT exists (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CLIENTLICENSE' AND COLUMN_NAME = 'EXPIRYDATE')
		BEGIN
		 PRINT '**** Adding new column CLIENTLICENSE.EXPIRYDATE'
		 ALTER TABLE CLIENTLICENSE ADD EXPIRYDATE DATETIME NULL
		END
	 If NOT exists (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CLIENTLICENSE' AND COLUMN_NAME = 'EXPIRYACTION')
		BEGIN
		 PRINT '**** Adding new column CLIENTLICENSE.EXPIRYWARNINGDAYS'
		 ALTER TABLE CLIENTLICENSE ADD EXPIRYACTION INT NULL
		END
	 If NOT exists (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CLIENTLICENSE' AND COLUMN_NAME = 'EXPIRYWARNINGDAYS')
		BEGIN
		 PRINT '**** Adding new column CLIENTLICENSE.EXPIRYWARNINGDAYS'
		 ALTER TABLE CLIENTLICENSE ADD EXPIRYWARNINGDAYS INT NULL
	 	END
	 If NOT exists (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CLIENTLICENSE' AND COLUMN_NAME = 'LICENSETYPE')
		BEGIN
		 PRINT '**** Adding new column CLIENTLICENSE.LICENSETYPE'
		 ALTER TABLE CLIENTLICENSE ADD LICENSETYPE INT NULL
	 	END
	END
go
