using Inprotech.Tests.Integration.DbHelpers;
using InprotechKaizen.Model.Queries;

namespace Inprotech.Tests.Integration.EndToEnd.SavedSearch.Case
{
    class CaseSavedSearchDbSetup : DbSetup
    {
        public dynamic Setup(int? userIdentityId = null, bool isExternal = false)
        {
            var contextId = isExternal ? 1 : 2;
            var group1 = Insert(new QueryGroup { ContextId = contextId, GroupName = "Trademark Cases", DisplaySequence = 10 });
            var group2 = Insert(new QueryGroup { ContextId = contextId, GroupName = "General Cases", DisplaySequence = 11 });

            const string xmlFilterCriteria1 = @"<Search><Report><ReportTitle>UK Trademark</ReportTitle></Report><Filtering><csw_ListCase>
                                     <FilterCriteriaGroup>
                                        <FilterCriteria ID='1'>
                                            <AccessMode>1</AccessMode>
                                            <IsAdvancedFilter>true</IsAdvancedFilter>
                                            <CaseTypeKeys Operator='0' IncludeCRMCases='0'>A</CaseTypeKeys>
                                            <PropertyTypeKeys Operator='0'><PropertyTypeKey>T</PropertyTypeKey><PropertyTypeKey>P</PropertyTypeKey></PropertyTypeKeys>
                                            <SubTypeKey Operator='1'>N</SubTypeKey>
                                            <BasisKey Operator='0'>N</BasisKey>
                                            <FamilyKey Operator='0'>BALLOON,FLOAT</FamilyKey>
                                            <CategoryKey Operator='0'>N</CategoryKey>
                                            <OfficeKeys Operator='0'>10175,10272</OfficeKeys>
                                            <IncludeDraftCase>1</IncludeDraftCase>
                                            <Classes Operator='2' IsLocal='1' IsInternational='1'>12,24,48</Classes>
                                            <CountryCodes Operator='0' IncludeDesignations='1'>AU,US</CountryCodes>
                                        </FilterCriteria>
                                        <FilterCriteria BooleanOperator='OR' ID='2'>
                                            <AccessMode>1</AccessMode>
                                            <IsAdvancedFilter>false</IsAdvancedFilter>
                                            <CaseReference Operator='2'>1234</CaseReference>
                                        </FilterCriteria>
                                    </FilterCriteriaGroup>
                                    </csw_ListCase></Filtering></Search>";

            var filter1 = Insert(new QueryFilter {ProcedureName = "csw_ListCase", XmlFilterCriteria = xmlFilterCriteria1});
            var filter2 = Insert(new QueryFilter { ProcedureName = "csw_ListCase", XmlFilterCriteria = "<Search><Report><ReportTitle>US Trademark1</ReportTitle></Report><Filtering><csw_ListCase><FilterCriteriaGroup><FilterCriteria ID='1'><IsAdvancedFilter>true</IsAdvancedFilter><CaseTypeKey Operator='0' IncludeCRMCases='0'>A</CaseTypeKey><PropertyTypeKey Operator='0'>T</PropertyTypeKey><PropertyTypeKeys Operator='0'><PropertyTypeKey>T</PropertyTypeKey></PropertyTypeKeys><StandingInstructions IncludeInherited='0' /><StatusFlags CheckDeadCaseRestriction='1' /><CountryCodes Operator='0'>US</CountryCodes><InheritedName /><CaseNameGroup /><AttributeGroup BooleanOr='0' /><Event Operator='' IsRenewalsOnly='0' IsNonRenewalsOnly='0'><Period><Type>D</Type><Quantity></Quantity></Period></Event><Actions /></FilterCriteria></FilterCriteriaGroup><ColumnFilterCriteria><DueDates UseEventDates='1' UseAdHocDates='1'><Dates UseDueDate='0' UseReminderDate='0' /><Actions IncludeClosed='0' IsRenewalsOnly='0' IsNonRenewalsOnly='0' /><DueDateResponsibilityOf IsAnyName='0' IsStaff='0' IsSignatory='0' /></DueDates></ColumnFilterCriteria></csw_ListCase></Filtering></Search>" });
            var filter3 = Insert(new QueryFilter { ProcedureName = "csw_ListCase", XmlFilterCriteria = "<Search><Report><ReportTitle>India</ReportTitle></Report><Filtering><csw_ListCase><FilterCriteriaGroup><FilterCriteria ID='1'><AccessMode>1</AccessMode><IsAdvancedFilter>false</IsAdvancedFilter><StandingInstructions IncludeInherited='0' /><StatusFlags CheckDeadCaseRestriction='1' /><CountryCodes Operator='0'>IN</CountryCodes><InheritedName /><CaseNameGroup /><AttributeGroup BooleanOr='0' /><Event Operator='' IsRenewalsOnly='0' IsNonRenewalsOnly='0' ByEventDate='1' /><Actions /></FilterCriteria></FilterCriteriaGroup><ColumnFilterCriteria><DueDates UseEventDates='1' UseAdHocDates='0'><Dates UseDueDate='0' UseReminderDate='0' /><Actions IncludeClosed='0' IsRenewalsOnly='1' IsNonRenewalsOnly='1' /><DueDateResponsibilityOf IsAnyName='0' IsStaff='0' IsSignatory='0' /></DueDates></ColumnFilterCriteria></csw_ListCase></Filtering></Search>" });
            var filter4 = Insert(new QueryFilter { ProcedureName = "csw_ListCase", XmlFilterCriteria = "<Search><Report><ReportTitle>T1</ReportTitle></Report><Filtering><csw_ListCase><FilterCriteriaGroup><FilterCriteria ID=\'1\'><AccessMode>1</AccessMode><IsAdvancedFilter>false</IsAdvancedFilter><PropertyTypeKeys Operator=\'0\'><PropertyTypeKey>T</PropertyTypeKey></PropertyTypeKeys><StandingInstructions IncludeInherited=\'0\' /><StatusFlags CheckDeadCaseRestriction=\'1\' /><InheritedName /><CaseNameGroup /><AttributeGroup BooleanOr=\'0\' /><Event Operator=\'\' IsRenewalsOnly=\'0\' IsNonRenewalsOnly=\'0\' ByEventDate=\'1\' /><Actions /></FilterCriteria></FilterCriteriaGroup><ColumnFilterCriteria><DueDates UseEventDates=\'1\' UseAdHocDates=\'0\'><Dates UseDueDate=\'0\' UseReminderDate=\'0\' /><Actions IncludeClosed=\'0\' IsRenewalsOnly=\'1\' IsNonRenewalsOnly=\'1\' /><DueDateResponsibilityOf IsAnyName=\'0\' IsStaff=\'0\' IsSignatory=\'0\' /></DueDates></ColumnFilterCriteria></csw_ListCase></Filtering></Search>" });
            var filter5 = Insert(new QueryFilter { ProcedureName = "csw_ListCase", XmlFilterCriteria = "<Search><Report><ReportTitle>P1</ReportTitle></Report><Filtering><csw_ListCase><FilterCriteriaGroup><FilterCriteria ID='1'><AccessMode>1</AccessMode><IsAdvancedFilter>false</IsAdvancedFilter><PropertyTypeKeys Operator='0'><PropertyTypeKey>P</PropertyTypeKey></PropertyTypeKeys><StandingInstructions IncludeInherited='0' /><StatusFlags CheckDeadCaseRestriction='1' /><InheritedName /><CaseNameGroup /><AttributeGroup BooleanOr='0' /><Event Operator='' IsRenewalsOnly='0' IsNonRenewalsOnly='0' ByEventDate='1' /><Actions /></FilterCriteria></FilterCriteriaGroup><ColumnFilterCriteria><DueDates UseEventDates='1' UseAdHocDates='0'><Dates UseDueDate='0' UseReminderDate='0' /><Actions IncludeClosed='0' IsRenewalsOnly='1' IsNonRenewalsOnly='1' /><DueDateResponsibilityOf IsAnyName='0' IsStaff='0' IsSignatory='0' /></DueDates></ColumnFilterCriteria></csw_ListCase></Filtering></Search>" });
            var textFilter = Insert(new QueryFilter { ProcedureName = "csw_ListCase", XmlFilterCriteria = "<Search><Report><ReportTitle>Text</ReportTitle></Report><Filtering><csw_ListCase><FilterCriteriaGroup><FilterCriteria ID='1'><AccessMode>1</AccessMode><IsAdvancedFilter>true</IsAdvancedFilter><TypeOfMarkKey Operator='1'>5106</TypeOfMarkKey><Title Operator='4'>The</Title><KeyWord Operator='1'>RONDON</KeyWord><StandingInstructions IncludeInherited='0' /><StatusFlags CheckDeadCaseRestriction='1' /><InheritedName /><CaseNameGroup /><AttributeGroup BooleanOr='0' /><CaseTextGroup><CaseText Operator='3'><TypeKey>_B</TypeKey><Text>xyz</Text></CaseText></CaseTextGroup><Event Operator='' IsRenewalsOnly='0' IsNonRenewalsOnly='0' ByEventDate='1'><Period><Type>D</Type><Quantity /></Period></Event><Actions /></FilterCriteria></FilterCriteriaGroup></csw_ListCase></Filtering></Search>" });
            var referenceFilter = Insert(new QueryFilter { ProcedureName = "csw_ListCase", XmlFilterCriteria = "<Search><Report><ReportTitle>References</ReportTitle></Report><Filtering><csw_ListCase><FilterCriteriaGroup><FilterCriteria ID='1'><AccessMode>1</AccessMode><IsAdvancedFilter>true</IsAdvancedFilter><CaseKeys Operator='0'>-487,-494,-486</CaseKeys><OfficialNumber Operator='2' UseCurrent='0' UseRelatedCase='0'><TypeKey /><Number UseNumericSearch='0'>1234</Number></OfficialNumber><FamilyKey Operator='0'>BALLOON,BWU</FamilyKey><CaseList IsPrimeCasesOnly='1'><CaseListKey Operator='1'>2</CaseListKey></CaseList><StandingInstructions IncludeInherited='0' /><StatusFlags CheckDeadCaseRestriction='1' /><CaseNameReference Operator='3'><TypeKey>I</TypeKey><ReferenceNo>xyz</ReferenceNo></CaseNameReference><InheritedName /><CaseNameGroup /><AttributeGroup BooleanOr='0' /><Event Operator='' IsRenewalsOnly='0' IsNonRenewalsOnly='0' ByEventDate='1'><Period><Type>D</Type><Quantity /></Period></Event><Actions /></FilterCriteria></FilterCriteriaGroup><ColumnFilterCriteria><DueDates UseEventDates='1' UseAdHocDates='0'><Dates UseDueDate='0' UseReminderDate='0' /><Actions IncludeClosed='0' IsRenewalsOnly='1' IsNonRenewalsOnly='1' /><DueDateResponsibilityOf IsAnyName='0' IsStaff='0' IsSignatory='0' /></DueDates></ColumnFilterCriteria></csw_ListCase></Filtering></Search>" });
            var detailTopicFilter = Insert(new QueryFilter { ProcedureName = "csw_ListCase", XmlFilterCriteria = "<Search><Report><ReportTitle>Details</ReportTitle></Report><Filtering><csw_ListCase><FilterCriteriaGroup><FilterCriteria ID='1'><AccessMode>1</AccessMode><IsAdvancedFilter>true</IsAdvancedFilter><CaseReference Operator='2'>123</CaseReference><CaseTypeKeys Operator='0' IncludeCRMCases='0'>A</CaseTypeKeys><PropertyTypeKeys Operator='0'><PropertyTypeKey>T</PropertyTypeKey><PropertyTypeKey>P</PropertyTypeKey></PropertyTypeKeys><SubTypeKey Operator='1'>N</SubTypeKey><BasisKey Operator='0'>N</BasisKey><FamilyKey Operator='0'>BALLOON,FLOAT</FamilyKey><CategoryKey Operator='0'>N,5</CategoryKey><OfficeKeys Operator='0'>10175,10272</OfficeKeys><IncludeDraftCase>1</IncludeDraftCase><Classes Operator='2' IsLocal='1' IsInternational='1'>12,24,48</Classes><CountryCodes Operator='0' IncludeDesignations='1'>AU,US</CountryCodes></FilterCriteria></FilterCriteriaGroup><ColumnFilterCriteria><DueDates UseEventDates='1' UseAdHocDates='0'><Dates UseDueDate='0' UseReminderDate='0' /><Actions IncludeClosed='0' IsRenewalsOnly='1' IsNonRenewalsOnly='1' /><DueDateResponsibilityOf IsAnyName='0' IsStaff='0' IsSignatory='0' /></DueDates></ColumnFilterCriteria></csw_ListCase></Filtering></Search>" });
            var statusTopicFilter = Insert(new QueryFilter { ProcedureName = "csw_ListCase", XmlFilterCriteria = "<Search><Report><ReportTitle>Status</ReportTitle></Report><Filtering><csw_ListCase><FilterCriteriaGroup><FilterCriteria ID='1'><AccessMode>1</AccessMode><IsAdvancedFilter>true</IsAdvancedFilter><StatusKey Operator='0'>-200,-301</StatusKey><RenewalStatusKey Operator='0'>-224,-223</RenewalStatusKey><StandingInstructions IncludeInherited='0' /><StatusFlags CheckDeadCaseRestriction='1'><IsPending>1</IsPending><IsRegistered>1</IsRegistered><IsDead>0</IsDead></StatusFlags><InheritedName /><CaseNameGroup /><AttributeGroup BooleanOr='0' /><Event Operator='' IsRenewalsOnly='0' IsNonRenewalsOnly='0' ByEventDate='1' /><Actions /></FilterCriteria></FilterCriteriaGroup><ColumnFilterCriteria><DueDates UseEventDates='1' UseAdHocDates='0'><Dates UseDueDate='0' UseReminderDate='0' /><Actions IncludeClosed='0' IsRenewalsOnly='1' IsNonRenewalsOnly='1' /><DueDateResponsibilityOf IsAnyName='0' IsStaff='0' IsSignatory='0' /></DueDates></ColumnFilterCriteria></csw_ListCase></Filtering></Search>" });
            var namesTopicFilter = Insert(new QueryFilter { ProcedureName = "csw_ListCase", XmlFilterCriteria = "<Search><Report><ReportTitle>namestopic</ReportTitle></Report><Filtering><csw_ListCase><FilterCriteriaGroup><FilterCriteria ID='1'><AccessMode>1</AccessMode><IsAdvancedFilter>true</IsAdvancedFilter><StandingInstructions IncludeInherited='0' /><StatusFlags CheckDeadCaseRestriction='1' /><NameRelationships Operator='0'><NameTypes>&amp;</NameTypes><Relationships>AGT</Relationships></NameRelationships><InheritedName><ParentNameKey Operator='0'>10050</ParentNameKey><NameTypeKey Operator='0'>O</NameTypeKey><DefaultRelationshipKey Operator='0'>BIL</DefaultRelationshipKey></InheritedName><CaseNameFromCase><CaseKey>-486</CaseKey></CaseNameFromCase><CaseNameGroup><CaseName Operator='0'><TypeKey>I</TypeKey><NameKeys>7,10054</NameKeys></CaseName><CaseName Operator='0'><TypeKey>O</TypeKey><NameKeys>7,10054</NameKeys></CaseName><CaseName Operator='0'><TypeKey>A</TypeKey><NameKeys>-6325100,-5001000</NameKeys></CaseName><CaseName Operator='0'><TypeKey>EMP</TypeKey><NameKeys IsCurrentUser='1'>-283677770,-487</NameKeys></CaseName><CaseName Operator='1'><TypeKey>SIG</TypeKey><NameKeys IsCurrentUser='0'>-487</NameKeys></CaseName><CaseName is-other-name-type='true' Operator='0'><TypeKey>D</TypeKey><NameKeys UseAttentionName='1'>-493</NameKeys><NameVariantKeys></NameVariantKeys></CaseName></CaseNameGroup><AttributeGroup BooleanOr='0' /><Event Operator='' IsRenewalsOnly='0' IsNonRenewalsOnly='0' ByEventDate='1'><Period><Type>D</Type><Quantity></Quantity></Period></Event><Actions /></FilterCriteria></FilterCriteriaGroup><ColumnFilterCriteria><DueDates UseEventDates='1' UseAdHocDates='0'><Dates UseDueDate='0' UseReminderDate='0' /><Actions IncludeClosed='0' IsRenewalsOnly='1' IsNonRenewalsOnly='1' /><DueDateResponsibilityOf IsAnyName='0' IsStaff='0' IsSignatory='0' /></DueDates></ColumnFilterCriteria></csw_ListCase></Filtering></Search>" });
            var attributesTopicFilter = Insert(new QueryFilter { ProcedureName = "csw_ListCase", XmlFilterCriteria = "<Search><Report><ReportTitle>attributes</ReportTitle></Report><Filtering><csw_ListCase><FilterCriteriaGroup><FilterCriteria ID='1'><AccessMode>1</AccessMode><IsAdvancedFilter>true</IsAdvancedFilter><StandingInstructions IncludeInherited='0' /><StatusFlags CheckDeadCaseRestriction='1' /><InheritedName /><CaseNameGroup /><AttributeGroup BooleanOr='0'><Attribute Operator='0'><TypeKey>44</TypeKey><AttributeKey>10272</AttributeKey></Attribute><Attribute Operator='1'><TypeKey>151</TypeKey><AttributeKey>10285</AttributeKey></Attribute><Attribute Operator='0'><TypeKey>143</TypeKey><AttributeKey>-14307</AttributeKey></Attribute></AttributeGroup><Event Operator='' IsRenewalsOnly='0' IsNonRenewalsOnly='0' ByEventDate='1' /><Actions /></FilterCriteria></FilterCriteriaGroup><ColumnFilterCriteria><DueDates UseEventDates='1' UseAdHocDates='0'><Dates UseDueDate='0' UseReminderDate='0' /><Actions IncludeClosed='0' IsRenewalsOnly='1' IsNonRenewalsOnly='1' /><DueDateResponsibilityOf IsAnyName='0' IsStaff='0' IsSignatory='0' /></DueDates></ColumnFilterCriteria></csw_ListCase></Filtering></Search>" });
            var otherDetailsTopicFilter = Insert(new QueryFilter { ProcedureName = "csw_ListCase", XmlFilterCriteria = "<Search><Report><ReportTitle>otherDetails</ReportTitle></Report><Filtering><csw_ListCase><FilterCriteriaGroup><FilterCriteria ID='1'><AccessMode>1</AccessMode><IsAdvancedFilter>true</IsAdvancedFilter><FileLocationKeys Operator='0'>10203,10200</FileLocationKeys><FileLocationBayNo Operator='2'>11234</FileLocationBayNo><StandingInstructions IncludeInherited='0'><CharacteristicFlag Operator='0'>6</CharacteristicFlag></StandingInstructions><StatusFlags CheckDeadCaseRestriction='1' /><QueueFlags><HasLettersOnQueue>1</HasLettersOnQueue><HasChargesOnQueue>1</HasChargesOnQueue></QueueFlags><HasIncompletePolicing>1</HasIncompletePolicing><HasIncompleteNameChange>1</HasIncompleteNameChange><InheritedName /><PurchaseOrderNo Operator='2'>121</PurchaseOrderNo><CaseNameGroup /><AttributeGroup BooleanOr='0' /><Event Operator='' IsRenewalsOnly='0' IsNonRenewalsOnly='0' ByEventDate='1' /><Actions /></FilterCriteria></FilterCriteriaGroup><ColumnFilterCriteria><DueDates UseEventDates='1' UseAdHocDates='0'><Dates UseDueDate='0' UseReminderDate='0' /><Actions IncludeClosed='0' IsRenewalsOnly='1' IsNonRenewalsOnly='1' /><DueDateResponsibilityOf IsAnyName='0' IsStaff='0' IsSignatory='0' /></DueDates></ColumnFilterCriteria></csw_ListCase></Filtering></Search>" });
            var ptaTopicFilter = Insert(new QueryFilter { ProcedureName = "csw_ListCase", XmlFilterCriteria = "<Search><Report><ReportTitle>PTA</ReportTitle></Report><Filtering><csw_ListCase><FilterCriteriaGroup><FilterCriteria ID='1'><AccessMode>1</AccessMode><IsAdvancedFilter>true</IsAdvancedFilter><StandingInstructions IncludeInherited='0' /><StatusFlags CheckDeadCaseRestriction='1' /><InheritedName /><PatentTermAdjustments><IPOfficeAdjustment Operator='7'><FromDays>1</FromDays><ToDays>10</ToDays></IPOfficeAdjustment><CalculatedAdjustment Operator='8'><FromDays>0</FromDays><ToDays>20</ToDays></CalculatedAdjustment><IPOfficeDelay Operator='7'><FromDays>1</FromDays><ToDays>100</ToDays></IPOfficeDelay><ApplicantDelay Operator='8'><FromDays>1</FromDays><ToDays>10</ToDays></ApplicantDelay><HasDiscrepancy>1</HasDiscrepancy></PatentTermAdjustments><CaseNameGroup /><AttributeGroup BooleanOr='0' /><Event Operator='' IsRenewalsOnly='0' IsNonRenewalsOnly='0' ByEventDate='1' /><Actions /></FilterCriteria></FilterCriteriaGroup><ColumnFilterCriteria><DueDates UseEventDates='1' UseAdHocDates='0'><Dates UseDueDate='0' UseReminderDate='0' /><Actions IncludeClosed='0' IsRenewalsOnly='1' IsNonRenewalsOnly='1' /><DueDateResponsibilityOf IsAnyName='0' IsStaff='0' IsSignatory='0' /></DueDates></ColumnFilterCriteria></csw_ListCase></Filtering></Search>" });
            var dmTopicFilter = Insert(new QueryFilter { ProcedureName = "csw_ListCase", XmlFilterCriteria = "<Search><Report><ReportTitle>DataManagement</ReportTitle></Report><Filtering><csw_ListCase><FilterCriteriaGroup><FilterCriteria ID='1'><AccessMode>1</AccessMode><IsAdvancedFilter>true</IsAdvancedFilter><StandingInstructions IncludeInherited='0' /><StatusFlags CheckDeadCaseRestriction='1' /><InheritedName /><CaseNameGroup /><AttributeGroup BooleanOr='0' /><EDEBatchIdentifier>112</EDEBatchIdentifier><EDEDataSourceNameNo>-283575757</EDEDataSourceNameNo><CPASentBatchNo>501</CPASentBatchNo><Event Operator='' IsRenewalsOnly='0' IsNonRenewalsOnly='0' ByEventDate='1'><Period><Type>D</Type><Quantity></Quantity></Period></Event><Actions /></FilterCriteria></FilterCriteriaGroup><ColumnFilterCriteria><DueDates UseEventDates='1' UseAdHocDates='0'><Dates UseDueDate='0' UseReminderDate='0' /><Actions IncludeClosed='0' IsRenewalsOnly='1' IsNonRenewalsOnly='1' /><DueDateResponsibilityOf IsAnyName='0' IsStaff='0' IsSignatory='0' /></DueDates></ColumnFilterCriteria></csw_ListCase></Filtering></Search>" }); 
            var eventActionsFilter = Insert(new QueryFilter { ProcedureName = "csw_ListCase", XmlFilterCriteria = "<Search><Report><ReportTitle>Events and Actions</ReportTitle></Report><Filtering><csw_ListCase><FilterCriteriaGroup><FilterCriteria ID='1'><AccessMode>1</AccessMode><IsAdvancedFilter>true</IsAdvancedFilter><StandingInstructions IncludeInherited='0' /><StatusFlags CheckDeadCaseRestriction='1' /><InheritedName /><ActionKey Operator='1' IsOpen='1'>AL</ActionKey><CaseNameGroup /><AttributeGroup BooleanOr='0' /><Event Operator='' IsRenewalsOnly='1' IsNonRenewalsOnly='1' ByDueDate='1' ByEventDate='1' IncludeClosedActions='1'><EventKey>-1011351,-1011785</EventKey><Period><Type>D</Type><Quantity /></Period><ImportanceLevel Operator='8'><From>7</From><To>5</To></ImportanceLevel><EventNoteText Operator='4'>xyz</EventNoteText></Event><Actions /></FilterCriteria></FilterCriteriaGroup><ColumnFilterCriteria><DueDates UseEventDates='1' UseAdHocDates='0'><Dates UseDueDate='0' UseReminderDate='0' /><Actions IncludeClosed='0' IsRenewalsOnly='1' IsNonRenewalsOnly='1' /><DueDateResponsibilityOf IsAnyName='0' IsStaff='0' IsSignatory='0' /></DueDates></ColumnFilterCriteria></csw_ListCase></Filtering></Search>" });
            var dueDateFilter = Insert(new QueryFilter { ProcedureName = "csw_ListCase", XmlFilterCriteria = "<Search><Report><ReportTitle>DueDate3</ReportTitle></Report><Filtering><csw_ListCase><FilterCriteriaGroup><FilterCriteria ID='1'><AccessMode>1</AccessMode><IsAdvancedFilter>false</IsAdvancedFilter><StandingInstructions IncludeInherited='0' /><StatusFlags CheckDeadCaseRestriction='1' /><InheritedName /><CaseNameGroup /><AttributeGroup BooleanOr='0' /><Event Operator='' IsRenewalsOnly='0' IsNonRenewalsOnly='0' ByEventDate='1' /><Actions /></FilterCriteria></FilterCriteriaGroup><ColumnFilterCriteria><DueDates UseEventDates='1' UseAdHocDates='1'><Dates UseDueDate='1' UseReminderDate='1'><DateRange Operator='7'><From>2019-10-01</From><To>2019-10-31</To></DateRange></Dates><Actions IncludeClosed='1' IsRenewalsOnly='1' IsNonRenewalsOnly='1'><ActionKey Operator='0'></ActionKey></Actions><ImportanceLevel Operator='7'><From></From><To></To></ImportanceLevel><EventKey Operator='0'></EventKey><EventCategoryKey Operator='0'></EventCategoryKey><DueDateResponsibilityOf IsAnyName='1' IsStaff='1' IsSignatory='1'><NameType Operator='1'>SIG</NameType><NameKey Operator='0'></NameKey><NameGroupKey Operator='0'></NameGroupKey><StaffClassificationKey Operator='0'></StaffClassificationKey></DueDateResponsibilityOf></DueDates></ColumnFilterCriteria></csw_ListCase></Filtering></Search>" });

            var query1 = Insert(new Query {ContextId = contextId, Filter = filter1, Name = "UK Trademark", IdentityId = userIdentityId ?? 45 });
            var query2 = Insert(new Query { ContextId = contextId, Filter = filter2, Name = "US Trademark1" });
            var query3 = Insert(new Query { ContextId = contextId, Filter = filter3, Name = "India", Group = group1});
            var query4 = Insert(new Query { ContextId = contextId, Filter = filter4, Name = "T1", Group = group1, IdentityId = userIdentityId ?? 45 });
            var query5 = Insert(new Query { ContextId = contextId, Filter = filter5, Name = "P1", Group = group2 });
            var textTopic = Insert(new Query { ContextId = contextId, Filter = textFilter, Name = "TextTopic", IdentityId = userIdentityId ?? 45});
            var referenceTopic = Insert(new Query { ContextId = contextId, Filter = referenceFilter, Name = "References", IdentityId = userIdentityId ?? 45});
            var detailTopic = Insert(new Query { ContextId = contextId, Filter = detailTopicFilter, Name = "Details", IdentityId = userIdentityId ?? 45});
            var statusTopic = Insert(new Query { ContextId = contextId, Filter = statusTopicFilter, Name = "Status", IdentityId = userIdentityId ?? 45});
            var namesTopic = Insert(new Query { ContextId = contextId, Filter = namesTopicFilter, Name = "Names", IdentityId = userIdentityId ?? 45});
            var attributesTopic = Insert(new Query {ContextId = contextId, Filter = attributesTopicFilter, Name = "Attributes", IdentityId = userIdentityId ?? 45});
            var otherDetailsTopic = Insert(new Query {ContextId = contextId, Filter = otherDetailsTopicFilter, Name = "OtherDetails", IdentityId = userIdentityId ?? 45});
            var ptaTopic = Insert(new Query {ContextId = contextId, Filter = ptaTopicFilter, Name = "PatentTermAdjustments", IdentityId = userIdentityId ?? 45});
            var eventActionsTopic = Insert(new Query {ContextId = contextId, Filter = eventActionsFilter, Name = "Events and Actions", IdentityId = userIdentityId ?? 45});
            var dmTopic = Insert(new Query {ContextId = contextId, Filter = dmTopicFilter, Name = "DataManagement", IdentityId = userIdentityId ?? 45});
            var dueDateModal = Insert(new Query { ContextId = contextId, Filter = dueDateFilter, Name = "DueDate", IdentityId = userIdentityId ?? 45 });

            return new
            {
                query1,
                query2,
                query3,
                query4,
                query5,
                textTopic,
                referenceTopic,
                detailTopic,
                statusTopic,
                namesTopic,
                attributesTopic,
                otherDetailsTopic,
                ptaTopic,
                eventActionsTopic,
                dmTopic,
                dueDateModal
            };
        }

    }
}
